// computational — the tool theorems whose objects are NOT in Lean (the FNV address, the gate, SHA-256, ChaCha,
// merkle, imprint, harness, render). Per the discipline "only algebra in Lean", these carry lean: null — HONESTLY:
// a Lean proof would be `native_decide` over a full port of the function, which is real but pending; it is NOT
// claimed here. Each still PROVES ITSELF in code: a self-proving test that holds AND rejects a false variant
// (falsifiable), recomputable by anyone. Integrity, not truth. 0/7.
import { toUuid, strictUuidna } from '../../address.js'
import { computes } from '../../gate.js'
import { merkleRoot, merkleProof, verifyProof } from '../../merkle.js'
import { merkleGravity, doubleTorusField, seats } from '../../gravity.js'
import { involute, involutionFixed } from '../../diamond.js'
import { imprintTextChain, readImprintTextChain } from '../../imprint.js'
import { adjudicate, proveVerdict, verifyUuidna } from '../../adjudicate.js'
import { harness, harness7, reeducate } from '../../harness.js'
import { billUuidna, coins } from '../../billing.js'
import { renderTheorem } from '../../render.js'
import { sha256, hmacSha256 } from '../../sha256.js'
import { aeadEncrypt, aeadDecrypt } from '../../chacha.js'

const te = new TextEncoder(), td = new TextDecoder()
const utf8 = (s: string) => te.encode(s)
const hex = (u: Uint8Array) => Array.from(u, (b) => b.toString(16).padStart(2, '0')).join('')

export interface Entry { key: string; formula: string; statement: string; lean: string | null; prove: () => boolean }

export const COMPUTATIONAL: readonly Entry[] = [
  { key: 'seats_pigeonhole', formula: 'seats(b) = 2^b;  2^8=256, 2^0=1, 2^10=1024', statement: 'a b-bit digest has two-to-the-b seats — the pigeonhole capacity that forces a collision', lean: 'theorem seats_pigeonhole : (2:Nat)^8 = 256 ∧ (2:Nat)^0 = 1 ∧ (2:Nat)^10 = 1024 := by decide', prove: () => seats(8) === 256 && seats(0) === 1 && seats(10) === 1024 },
  { key: 'content_address_deterministic', formula: 'toUuid(x) = toUuid(x) ∧ toUuid(a) ≠ toUuid(b)  (FNV-1a, native_decide pending a Lean port)', statement: 'the content-address is deterministic and context-free — the same value always mints the same', lean: null, prove: () => toUuid('uuidna') === 'fc511532-6e8a-8418-a522-a51b1d46a70c' && toUuid('a') !== toUuid('b') },
  { key: 'strict_address_converges', formula: 'strict(" 3 ") = strict("3") ∧ strict("3") ≠ strict("4")', statement: 'the strict address normalises equivalent inputs to one uuid, and distinct values stay distinct', lean: null, prove: () => strictUuidna(' 3 ') === strictUuidna('3') && strictUuidna('3') !== strictUuidna('4') },
  { key: 'involute_centre', formula: 'a reflection i↔(n−1−i): |fixed| = n mod 2 (1 if odd, 0 if even)', statement: 'the list involution has exactly one centre when the set is odd and none when even', lean: 'theorem involute_centre : (List.range 12).all (fun n => ((List.range n).filter (fun i => 2*i + 1 == n)).length = n % 2) := by decide', prove: () => involutionFixed(['a', 'b', 'c', 'd', 'e']).length === 1 && involutionFixed(['a', 'b', 'c', 'd']).length === 0 && involute(['a', 'b', 'c']).length === 3 },
  { key: 'merkle_gravity_order_invariant', formula: 'merkleGravity(S) = merkleGravity(reverse S) ≠ merkleGravity(other)', statement: 'the merkle gravity of a set is order-invariant — every observer order falls to the same root', lean: null, prove: () => { const g = ['a', 'b', 'c'].map(toUuid); return merkleGravity(g) === merkleGravity([...g].reverse()) && merkleGravity(g) !== merkleGravity([toUuid('x')]) } },
  { key: 'double_torus_field', formula: 'doubleTorusField(S).dims has length 7 ∧ root is a uuid', statement: 'the double-torus field folds a set through seven dimensions to one content-address', lean: null, prove: () => { const f = doubleTorusField(['a', 'b', 'c'].map(toUuid)); return f.dims.length === 7 && /^[0-9a-f-]{36}$/.test(f.root) } },
  { key: 'merkle_proof_sound', formula: 'verifyProof(leaf, proof, root) = true ∧ verifyProof(forge, proof, root) = false', statement: 'the merkle proof is sound — the true leaf verifies against the root and a forgery fails', lean: null, prove: () => { const leaves = Array.from({ length: 8 }, (_, i) => toUuid('leaf' + i)); const root = merkleRoot(leaves); const proof = merkleProof(leaves, 3); return verifyProof(leaves[3], proof, root) === true && verifyProof(toUuid('forge'), proof, root) === false } },
  { key: 'imprint_roundtrip', formula: 'read(imprint(s)) = s  for all s (reversible codec)', statement: 'the imprint codec round-trips arbitrary text through a uuid chain — reversible, not encryption', lean: null, prove: () => ['', 'Hi', 'the units of Z/9', '你好 · Riemann'].every((s) => readImprintTextChain(imprintTextChain(s)) === s) },
  { key: 'honesty_gate_drains_overreach', formula: 'computes("we prove <X>").binary = 0 ∧ computes(honest).binary = 1', statement: 'the honesty gate drains a named overclaim to zero and signs the honest floor at one', lean: null, prove: () => computes('we prove the Riemann hypothesis').binary === 0 && computes('a content-address proves integrity, not truth; 0/7').binary === 1 },
  { key: 'adjudicate_three_way', formula: 'REFUTED (gate drains) · UNVERIFIED (no test) · SEALED (gate-clean ∧ test holds)', statement: 'the trial returns a recomputable three-way verdict — refuted, unverified, or sealed', lean: null, prove: () => adjudicate('we prove all seven').verdict === 'REFUTED' && adjudicate('a plain unbacked claim').verdict === 'UNVERIFIED' && adjudicate('two units multiply to a unit', () => (2 * 5) % 9 === 1).verdict === 'SEALED' },
  { key: 'verdict_receipt_order_invariant', formula: 'proveVerdict(s, F).proofRoot = proveVerdict(s, reverse F).proofRoot', statement: 'the proof-of-verdict root is order-invariant — the formulas fold to one root in any order', lean: null, prove: () => { const f = [toUuid('f1'), toUuid('f2')]; return proveVerdict('we prove all seven', f).proofRoot === proveVerdict('we prove all seven', [...f].reverse()).proofRoot } },
  { key: 'verify_uuidna_recomputes', formula: 'verifyUuidna(seed).recomputes = true', statement: 'the self-verdict recomputes the address from its seed — verification re-mints the same value', lean: null, prove: () => verifyUuidna('1011').recomputes === true },
  { key: 'harness_auditable', formula: 'harness(x).auditable = true ∧ harness7(x).auditableInAll = true', statement: 'the harness makes any output auditable, in one dimension and in all seven at once', lean: null, prove: () => harness('anything').auditable === true && harness7('x').auditableInAll === true },
  { key: 'reeducate_bounds_overreach', formula: 'reeducate(overclaim).passed = true', statement: 'reeducate bounds an overclaiming output to the honest floor until it holds', lean: null, prove: () => reeducate('we prove the Riemann hypothesis and it is faster than light, unbreakable').passed === true },
  { key: 'render_by_reference', formula: 'render(t) contains a uuidna-card + a content-address ∧ no <script>', statement: 'render presents a statement by reference — a framework-free card carrying its content-address, no script', lean: null, prove: () => { const h = renderTheorem({ name: 'a decidable theorem' }); return /uuidna-card/.test(h) && /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/.test(h) && !/<script/i.test(h) } },
  { key: 'billing_two_coins', formula: 'bitsSaved = recompute − verify (1024−1 = 1023) ∧ coins = 2', statement: 'billing measures the bits saved and conserves the two coins; public interest is free', lean: 'theorem billing_arith : (1024 - 1 = 1023) ∧ (1000000 - 1 = 999999) ∧ (2 = 1 + 1) := by decide', prove: () => coins() === 2 && billUuidna({ commercial: true, recomputeOps: 1024, verifyOps: 1 }).bitsSaved === 1023 && billUuidna({ commercial: false, recomputeOps: 1e6, verifyOps: 1 }).free === true },
  { key: 'sha256_kat', formula: 'sha256("abc") = ba7816bf…20015ad  (NIST vector; native_decide pending a Lean port)', statement: 'the cryptographic hash matches the NIST vector — sha256 of abc is the known digest', lean: null, prove: () => hex(sha256(utf8('abc'))) === 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad' },
  { key: 'hmac_keyed', formula: 'HMAC(k,m) deterministic ∧ ≠ sha256(m) ∧ 32 bytes', statement: 'keyed authentication is deterministic and distinct from the bare hash — HMAC-SHA256', lean: null, prove: () => { const a = hex(hmacSha256(utf8('k'), utf8('m'))), b = hex(hmacSha256(utf8('k'), utf8('m'))); return a === b && a !== hex(sha256(utf8('m'))) && a.length === 64 } },
  { key: 'aead_roundtrip', formula: 'open(seal(m)) = m ∧ a tampered tag fails authentication  (ChaCha20-Poly1305)', statement: 'the AEAD seal round-trips and a tampered tag fails authentication — ChaCha20-Poly1305', lean: null, prove: () => { const key = new Uint8Array(32).fill(7), nonce = new Uint8Array(12).fill(3); const { ct, tag } = aeadEncrypt(key, nonce, utf8('beat to windward'), new Uint8Array()); const opened = td.decode(aeadDecrypt(key, nonce, ct, tag, new Uint8Array())); const bad = new Uint8Array(tag); bad[0] ^= 1; let tamperFails = false; try { aeadDecrypt(key, nonce, ct, bad, new Uint8Array()) } catch { tamperFails = true } return opened === 'beat to windward' && tamperFails } },
]
