// derived-attribute — A FILE MARKED DERIVED MUST ACTUALLY BE DERIVED, OR THE MERGE DRIVER DELETES WORK.
//
// .gitattributes gives a set of paths `merge=derived`, and the driver configured for it is literally `true`:
// it keeps one side of a conflict and discards the other, silently. That is CORRECT for a derived file — both
// sides are correct outputs of different sources, and the recomputation settles it — and it is catastrophic for
// a file nothing recomputes, because the discarded side is simply gone and no one is told.
//
// MEASURED 2026-08-25, found by a peer and verified here independently. `lean/** merge=derived` is right for the
// WINGS and far too wide for the hand-maintained JSON beside them. lean/wave-queue.json is a DEPOSIT RECORD:
// mcp.ts writes it through depositCandidates, gen-waves only reads it, and it appears NOWHERE in reconcile's
// derive block or generate's manifest. One checkout held 462 accepted deposits; origin held 53. The wings then
// regenerate from a queue that no longer names those candidates, so the theorems evaporate — src/firewall,
// src/knowledge and src/resonance are zero files on origin, and thirteen sealed theorems went with them.
//
// The same glob also captured lean/leads.json (the research record), lean/dormant-scripts.json (a list whose
// own header says it MAY ONLY SHRINK), lean/mcp-context-budget.json (a ceiling re-sealed deliberately, with the
// reason written into the file) and .gitattributes ITSELF — so a conflict in the rules would have been resolved
// by keeping one side at random.
//
// This test holds the rule those attributes are an approximation of: a path may claim to be derived only if
// something in the tree actually writes it.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { ROOT } from '../boundary.js'

const attributes = (): string[] =>
  readFileSync(join(ROOT, '.gitattributes'), 'utf8')
    .split(String.fromCharCode(10))
    .filter((l) => !l.trimStart().startsWith('#'))

/** what git ACTUALLY decides for a path — the attribute file has precedence rules, and reading the lines is not
 *  the same as asking. The last matching rule wins, which is exactly how the correction works. */
const mergeAttr = (path: string): string =>
  execFileSync('git', ['check-attr', 'merge', '--', path], { cwd: ROOT, encoding: 'utf8' })
    .trim().replace(/^.*merge: /, '')

test('the hand-maintained records do NOT auto-resolve — a conflict in them is a question, not a coin flip', () => {
  // Each of these is written by a person or by a deposit, and nothing recomputes any of them. `unspecified`
  // means the ordinary three-way merge, which produces conflict markers a human must settle. That is the point.
  for (const p of [
    'lean/wave-queue.json',        // deposits: mcp.ts writes, gen-waves reads, no generator regenerates
    'lean/leads.json',             // the research record — held/refuted/refused, authored
    'lean/research-ledger.json',   // hand-maintained; its own comment says the two copies are held together BY HAND
    'lean/dormant-scripts.json',   // a list whose header says it MAY ONLY SHRINK
    'lean/mcp-context-budget.json',// a ceiling re-sealed deliberately, each raise carrying its reason
    '.gitattributes',              // the rules: deciding a conflict here at random is how a misclassification survives
  ]) {
    assert.notEqual(mergeAttr(p), 'derived',
      `${p} is not regenerated by anything — marked derived, the merge driver keeps one side and DISCARDS the other silently`)
  }
})

test('the genuinely derived layer KEEPS the driver — this is a correction, not a retreat', () => {
  // the control: if the fix had simply unset the attribute everywhere, the derived layer would start producing
  // conflicts in files where both sides are correct outputs and the recomputation settles it. It must not.
  for (const p of ['src/theorems/generated.ts', 'lean/PRINCIPLE.md', 'CHANGELOG.md', 'lean/axioms.json'])
    assert.equal(mergeAttr(p), 'derived', `${p} IS regenerated — it should still auto-resolve and be recomputed`)
  // and the wings under the same glob that caused the trouble stay derived, because they genuinely are
  assert.equal(mergeAttr('lean/Negation.lean'), 'derived', 'a .lean wing is written by its generator')
})

test('every path still claiming DERIVED is written by something in the tree', () => {
  // THE RULE THE ATTRIBUTES APPROXIMATE. A path may claim to be derived only if a writer exists for it. Read
  // from the derive chain and the generator manifest rather than from a second list, so this cannot drift from
  // what actually runs.
  const rec = readFileSync(join(ROOT, 'src', 'scripts', 'reconcile.ts'), 'utf8')
  const derive = rec.slice(0, rec.indexOf('// THE SPLIT.'))
  const gen = readFileSync(join(ROOT, 'src', 'scripts', 'generate.ts'), 'utf8')
  const api = readFileSync(join(ROOT, 'src', 'scripts', 'api.ts'), 'utf8')
  const corpus = derive + gen + api

  const unwritten: string[] = []
  for (const line of attributes()) {
    if (!/merge=derived/.test(line)) continue
    const path = line.split(' ')[0]!
    if (path.includes('*')) continue                       // globs are checked by the two tests above, by sample
    if (mergeAttr(path) !== 'derived') continue            // a later rule already corrected it
    if (!existsSync(join(ROOT, path))) continue            // a path that does not exist cannot lose work
    const base = path.split('/').pop()!
    if (!corpus.includes(base)) unwritten.push(path)
  }
  assert.deepEqual(unwritten, [],
    'a path marked merge=derived that no generator writes will have one side of every conflict silently discarded, '
    + 'and nothing will ever recompute what was lost. Either give it a writer, or unset the attribute with !merge.')
})
