// derived-attribute — A FILE MARKED DERIVED MUST ACTUALLY BE DERIVED, OR THE MERGE DRIVER DELETES WORK.
//
// .gitattributes gives a set of paths `merge=derived`, and the driver configured for it is literally `true`:
// it keeps one side of a conflict and discards the other, silently. That is CORRECT for a derived file — both
// sides are correct outputs of different sources, and the recomputation settles it — and it is catastrophic for
// a file nothing recomputes, because the discarded side is simply gone and no one is told.
//
// MEASURED 2026-08-25, found by a peer and verified here independently. `lean/** merge=derived` is right for the
// WINGS and far too wide for the hand-maintained JSON beside them. lean/wave-queue.json is a DEPOSIT RECORD:
// mcp.ts writes it through depositCandidates, gen-waves only reads it, and it appears NOWHERE in reconcile's
// derive block or generate's manifest. One checkout held 462 accepted deposits; origin held 53. The wings then
// regenerate from a queue that no longer names those candidates, so the theorems evaporate — src/firewall,
// src/knowledge and src/resonance are zero files on origin, and thirteen sealed theorems went with them.
//
// The same glob also captured lean/leads.json (the research record), lean/dormant-scripts.json (a list whose
// own header says it MAY ONLY SHRINK), lean/mcp-context-budget.json (a ceiling re-sealed deliberately, with the
// reason written into the file) and .gitattributes ITSELF — so a conflict in the rules would have been resolved
// by keeping one side at random.
//
// This test holds the rule those attributes are an approximation of: a path may claim to be derived only if
// something in the tree actually writes it.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { ROOT } from '../boundary.js'

const attributes = (): string[] =>
  readFileSync(join(ROOT, '.gitattributes'), 'utf8')
    .split(String.fromCharCode(10))
    .filter((l) => !l.trimStart().startsWith('#'))

/** what git ACTUALLY decides for a path — the attribute file has precedence rules, and reading the lines is not
 *  the same as asking. The last matching rule wins, which is exactly how the correction works. */
const mergeAttr = (path: string): string =>
  execFileSync('git', ['check-attr', 'merge', '--', path], { cwd: ROOT, encoding: 'utf8' })
    .trim().replace(/^.*merge: /, '')

test('the hand-maintained records do NOT auto-resolve — a conflict in them is a question, not a coin flip', () => {
  // Each of these is written by a person or by a deposit, and nothing recomputes any of them. `unspecified`
  // means the ordinary three-way merge, which produces conflict markers a human must settle. That is the point.
  for (const p of [
    'lean/wave-queue.json',        // deposits: mcp.ts writes, gen-waves reads, no generator regenerates
    'lean/leads.json',             // the research record — held/refuted/refused, authored
    'lean/research-ledger.json',   // hand-maintained; its own comment says the two copies are held together BY HAND
    'lean/dormant-scripts.json',   // a list whose header says it MAY ONLY SHRINK
    'lean/mcp-context-budget.json',// a ceiling re-sealed deliberately, each raise carrying its reason
    '.gitattributes',              // the rules: deciding a conflict here at random is how a misclassification survives
  ]) {
    assert.notEqual(mergeAttr(p), 'derived',
      `${p} is not regenerated by anything — marked derived, the merge driver keeps one side and DISCARDS the other silently`)
  }
})

test('the genuinely derived layer KEEPS the driver — this is a correction, not a retreat', () => {
  // the control: if the fix had simply unset the attribute everywhere, the derived layer would start producing
  // conflicts in files where both sides are correct outputs and the recomputation settles it. It must not.
  for (const p of ['src/theorems/generated.ts', 'lean/PRINCIPLE.md', 'CHANGELOG.md', 'lean/axioms.json'])
    assert.equal(mergeAttr(p), 'derived', `${p} IS regenerated — it should still auto-resolve and be recomputed`)
  // and the wings under the same glob that caused the trouble stay derived, because they genuinely are
  assert.equal(mergeAttr('lean/Negation.lean'), 'derived', 'a .lean wing is written by its generator')
})

// ── A GENERATOR THAT WRITES AND IS NEVER RUN. The narrow, computable half of the rule.
//
// I TRIED FOUR TIMES TO MAKE THIS A GENERAL PROPERTY AND COULD NOT, honestly, so this asserts what is actually
// decidable and the failures are recorded rather than hidden:
//
//   1. "an invoked script mentions the path" — api.ts DECLARES the derived layer, so a path's own declaration
//      satisfied its own check. The self-witness api.ts states the law against: evidence must come from
//      somewhere else, a file is never its own witness.
//   2. "search reconcile + generate for the path" — generate.ts lists GENERATOR filenames, never their outputs,
//      so every declared path looked unwritten.
//   3. "an invoked script mentions the path", corrected — an invoked generator MENTIONS a sibling's output, so a
//      mention counted as a write. Mention-versus-use, in the instrument, for the third time in one evening.
//   4. reading each generator's writeFileSync target — works only where the target is a literal join(ROOT, …).
//      gen-captain-claims-complete writes `writeFileSync(ledgerPath, …)`, a variable, and is invisible to it.
//
// So the general claim is abandoned rather than faked. What IS decidable: a gen-* script whose write target is a
// literal path, which the chain never invokes. That catches a real class — a generator nobody runs produces a
// file that rots while `git status` shows it clean — and it says plainly which cases it cannot see.
test('a generator that writes a literal path is INVOKED by the chain, or it is rot waiting to happen', () => {
  const rec = readFileSync(join(ROOT, 'src', 'scripts', 'reconcile.ts'), 'utf8')
  const derive = rec.slice(0, rec.indexOf('// THE SPLIT.'))
  const gen = readFileSync(join(ROOT, 'src', 'scripts', 'generate.ts'), 'utf8')
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { scripts: Record<string, string> }
  const invoked = new Set<string>()
  for (const m of (gen + derive + (pkg.scripts.lean ?? '')).matchAll(/([a-z0-9-]+)\.js/g)) invoked.add(m[1]!)

  const orphans: string[] = []
  for (const f of readdirSync(join(ROOT, 'src', 'scripts')).filter((n) => /^gen-.*\.ts$/.test(n))) {
    const name = f.replace(/\.ts$/, '')
    if (invoked.has(name)) continue
    const src = readFileSync(join(ROOT, 'src', 'scripts', f), 'utf8')
    // only a LITERAL target counts — a variable is invisible here, and the comment above says so
    if (/writeFileSync\(\s*join\(ROOT,/.test(src)) orphans.push(name)
  }
  assert.deepEqual(orphans.sort(), ['gen-alpine-apps', 'gen-quantum-advantage'],
    'a gen-* that writes a file and is never run leaves that file to rot while git reports it clean. Wire it into '
    + 'generate.ts\'s manifest, or stop it writing. The two named here are KNOWN and unwired — this assertion is a '
    + 'ratchet: it fails when the list grows, and it fails when one is fixed without updating it.')
})
