// api — THE SCRIPTS' QUANTUM API, declared once. 125 scripts each re-declared the same boilerplate (ROOT
// resolution, file reads, the 16-hex fold, the GAP+FIX reporter); this module is the singularity they all import
// from — standardisation and DRY use of one api, so a script is only its own logic. The `one-receipt dry` finder
// objects (GAP + exact FIX) to any script that re-declares what lives here — the duplication class cannot regrow.
import { createHash } from 'node:crypto'
import { execSync } from 'node:child_process'
import { readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

/** the scripts directory (dist/scripts at runtime) — every script lives here, so one HERE serves all */
export const HERE = dirname(fileURLToPath(import.meta.url))
/** the repo root */
export const ROOT = join(HERE, '..', '..')
/** read a repo-relative file as utf8 */
export const rd = (p: string): string => readFileSync(join(ROOT, p), 'utf8')
/** does a repo-relative path exist */
export const has = (p: string): boolean => existsSync(join(ROOT, p))
/** the 16-hex component fold */
export const h16 = (data: string): string => createHash('sha256').update(data).digest('hex').slice(0, 16)
/** the 32-hex order-invariant fold over named components */
export const foldOf = (entries: Record<string, string>): string =>
  createHash('sha256').update(Object.entries(entries).map(([k, v]) => `${k}:${v}`).sort().join('|')).digest('hex').slice(0, 32)
/** the ℤ/7 ray of a string — the same partition as /rosetta */
export const ray = (s: string): number => parseInt(createHash('sha256').update(s).digest('hex').slice(0, 8), 16) % 7

/** The result of a teed child step: whether it passed, and the tail of what it said. */
export type StepResult = { ok: boolean; out: string; tail: string }
/** the last n lines of output — what a retry or a cure must quote to be worth printing */
export const lastLines = (s: string, n = 20): string => s.trimEnd().split('\n').slice(-n).join('\n')
/** Run a child step with its output TEED: stderr merged, passed through to this process's stdout so the caller's own
 *  log holds the child's words, and kept so a failure can be matched against a cure and quoted. Declared HERE because
 *  both the seal and the develop pass need it, and a retry loop that discards its child's output costs more than the
 *  failure it retries (learned 2026-08-17: six seal rounds produced a seven-line log while throwing away the real
 *  objection each time). */
export function teeStep(label: string, cmd: string, cwd: string = ROOT): StepResult {
  process.stdout.write(`\n── ${label} ──\n`)
  try {
    const out = execSync(`${cmd} 2>&1`, { cwd, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
    process.stdout.write(out)
    return { ok: true, out, tail: lastLines(out) }
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string; message?: string }
    const out = `${err.stdout ?? ''}${err.stderr ?? ''}`.trim() || String(err.message ?? e)
    process.stdout.write(out + '\n')
    return { ok: false, out, tail: lastLines(out) }
  }
}

/** THE DRAIN'S OWN PATHS — every artifact the unattended drain REGENERATES, and nothing else. The seal and reconcile
 *  used `git add -A`, which on a shared tree sweeps a sibling session's in-flight SOURCE edits into a commit whose
 *  message describes something else: four times in one day work landed under a title about unrelated work, and in this
 *  repo a commit message is a signed artifact that must cite a sealed theorem, so the record has to mean what it says.
 *  Staging explicit paths keeps the drain to what it computed. Anything else left dirty is somebody's work: the drain
 *  NAMES it and leaves it alone (see stageDerived). Add a path here only if a generator writes it. */
export const DRAIN_PATHS: readonly string[] = [
  // the declared derived layer (mirrors src/spin.ts DERIVED_FILES — spin seals exactly these)
  'src/theorems/generated.ts', 'lean/PRINCIPLE.md', 'CHANGELOG.md', 'lean/axioms.json',
  'docs/mcp.md', 'audit-citations.json', 'support-audit.json', 'research-leads.json',
  // the other computed artifacts the drain writes: the fold, the seal manifest, the measured costs, the page seeds
  'quantum-fold.json', 'spin-manifest.json', 'lean/heartbeats.json', 'lean/proof-cache.json',
  'prose-trials.json', 'docs/captain-claims.json', 'src/lean',
  // regenerated by the reconcile chain and, until 2026-08-17, staged by nothing — so every run rewrote them and
  // then committed with nothing added. Named by `one-receipt drain`, which holds this list against
  // RECONCILE_OUTPUTS from both sides.
  'README.md', 'llm.txt', 'docs/analytics.md',
]

/** What each generator in the reconcile chain WRITES — declared, because the write targets are computed through
 *  variables (`readmePath`, `leanPath`, `CACHE_PATH`), so no honest static scan can recover them. The drain stages
 *  DRAIN_PATHS and nothing else, so a generator whose output is absent from that list is regenerated on every
 *  reconcile and staged by none of them: the run then commits with nothing added and dies on git's own error.
 *  Measured 2026-08-17 — README.md, docs/analytics.md, docs/captain-claims.md, lean/cipher-manifest.json and
 *  llm.txt all rewrote and none were staged. `one-receipt drain` holds this map against reconcile.ts and
 *  against DRAIN_PATHS, so adding a generator to the chain without declaring its output fails at guard speed. */
export const RECONCILE_OUTPUTS: Readonly<Record<string, readonly string[]>> = {
  'lean-axioms': ['lean/axioms.json'],
  'gen-mcp': ['docs/mcp.md'],
  'gen-readme': ['README.md'],
  'gen-llm': ['llm.txt'],
  'gen-analytics': ['docs/analytics.md'],
  'lean-heartbeats': ['lean/heartbeats.json'],
  'support': ['support-audit.json', 'research-leads.json'],
  'audit-citations': ['audit-citations.json'],
  'sync-changelog': ['CHANGELOG.md'],
  'spin': ['spin-manifest.json'],
  'account': [],       // reports only — aborts the run when the ledger does not reconcile, writes nothing
  'one-receipt': [],   // invoked as the `coherent` probe here; the finders report, they do not write
}

/** Stage ONLY the drain's own paths, then report what was left for a human. Returns the untouched paths so a caller
 *  can print them: a sibling's edit is neither swept into the drain's commit nor silently ignored — it is named. */
export function stageDerived(cwd: string = ROOT): { staged: number; leftForHumans: string[] } {
  const existing = DRAIN_PATHS.filter((p) => existsSync(join(cwd, p)))
  if (existing.length) execSync(`git add -- ${existing.map((p) => JSON.stringify(p)).join(' ')}`, { cwd })
  const staged = execSync('git diff --cached --name-only', { cwd, encoding: 'utf8' }).trim().split('\n').filter(Boolean).length
  const leftForHumans = execSync('git status --porcelain', { cwd, encoding: 'utf8' })
    .split('\n').filter(Boolean)
    .filter((l) => !l.startsWith('M  ') && !l.startsWith('A  ') && !l.startsWith('D  '))   // not already staged
    .map((l) => l.slice(3).trim())
  return { staged, leftForHumans }
}

export type Gap = { what: string; fix: string }
/** the GAP+FIX reporter — every audit finding is an exact computational prompt; exits 1 on any gap */
export function report(name: string, gaps: Gap[], okMessage: string): void {
  if (gaps.length) {
    console.error(`✗ ${name} — ${gaps.length} gap(s), each with its exact fix:`)
    for (const g of gaps) { console.error(`    GAP ${g.what}`); console.error(`    FIX ${g.fix}`) }
    process.exit(1)
  }
  console.log(`✓ ${name} — ${okMessage}`)
}
