#!/usr/bin/env node
// audit-prose-anchors — THE LAST MANUAL ACT, FOLDED. Every wave of the 2026-08-15 vortex had the same shape: a
// human (or an agent) READ pages to find the ones that drift — prose with no sealed anchor, path claims that went
// stale when the tree moved. Minutes of grepping, every time. This folds that reading into the guard, forever:
//   1. EVERY hand-written docs page must anchor to the ledger — at least one /theorem/<key> or /publications/<slug>
//      link. A page that cannot walk to a sealed proof is a dead node ("revealing theorems on the path" is the law).
//   2. EVERY repo-path claim in docs prose must exist — docs/.vitepress/dist, lean/, worker.js…: a moved tree that
//      leaves a doc teaching the old path is caught at guard time, not by a reader (deploy.md taught ./site for
//      two builds — that class of drift can no longer ship).
// Generated pages are exempt (their generators are the checked source); each finding is an exact computational
// prompt (GAP + FIX). Milliseconds, no network. Honest scope: anchoring, not accuracy — the gate and the trials
// judge the claims themselves.
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const rd = (p: string) => readFileSync(join(ROOT, p), 'utf8')

// Exported PURE — fold-quantum imports this so the prose surface is a dimension of the ONE guard receipt.
// Execution happens only when run directly (below).
export function proseGaps(): { gaps: { what: string; fix: string }[]; facts: string; pages: number } {
  const gaps: { what: string; fix: string }[] = []

// generated by scripts (the generator is the checked source), data-index pages (the ledger IS their anchor), or
// pure includes — exempt from the hand-prose anchor rule.
const EXEMPT = new Set(['mcp.md', 'captain-claims.md', 'analytics.md', 'prose-evidence.md', 'changelog.md', 'search.md', 'theorems.md', 'topics.md', 'rosetta.md', 'trials.md', 'publications.md'])

const pages = readdirSync(join(ROOT, 'docs')).filter((f) => f.endsWith('.md'))
for (const f of pages) {
  const prose = rd(`docs/${f}`).replace(/```[\s\S]*?```/g, '')
  // 1) the sealed anchor — a page must walk to a proof.
  if (!EXEMPT.has(f) && !/\]\(\/(theorem|publications)\//.test(prose))
    gaps.push({
      what: `docs/${f}: no sealed anchor — the page cannot walk to a theorem or cluster`,
      fix: `edit docs/${f}: link the page's subject to its cluster ([the <name> cluster](/publications/<slug>)) or a sealed theorem ([\`<key>\`](/theorem/<key>)) — pick from the ledger, cite nothing unsealed`,
    })
  // 2) path claims — any repo path a doc teaches must exist right now.
  for (const m of prose.matchAll(/(?:^|[\s(`])(\.?\/?(?:docs\/\.vitepress|src|lean|packages|hooks)\/[A-Za-z0-9_./-]+|worker\.js|wrangler\.toml|CONTRIBUTING\.md|LICENSE)(?=[\s)`.,:]|$)/gm)) {
    const p = m[1].replace(/^\.\//, '').replace(/[.,:]+$/, '')
    if (p.includes('*') || p.endsWith('/')) continue
    if (!existsSync(join(ROOT, p)))
      gaps.push({ what: `docs/${f}: teaches the path "${p}" which does not exist`, fix: `edit docs/${f}: replace "${p}" with the current path (verify with \`ls\`), or delete the claim` })
  }
}

  // the FACTS the audit stood on — the prose dimension of the one guard receipt.
  const facts = [...pages.map((f) => `${f}:${EXEMPT.has(f) ? 'exempt' : 'anchored'}`), `gaps:${gaps.length}`].sort().join('\n')
  return { gaps, facts, pages: pages.length }
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const { gaps, pages } = proseGaps()
  if (gaps.length) {
    console.error(`✗ audit-prose-anchors — ${gaps.length} unanchored/stale page claim(s), each with its exact fix:`)
    for (const g of gaps) { console.error(`    GAP ${g.what}`); console.error(`    FIX ${g.fix}`) }
    process.exit(1)
  }
  console.log(`✓ audit-prose-anchors — all ${pages} pages walk to the ledger and teach only paths that exist. The reading is folded; the guard reads now.`)
}
