#!/usr/bin/env node
// @non-harmonic: reads npm registry over the network — the os/overlay boundary, where live tarball shasum is honest.
//
// gen-alpine-overlay — npm/curl apps in catalogue shape (repo=overlay). NOT Alpine Linux distro packages.
// Merged at catalogue read time for uuidna_exec + hexbit; excluded from manDrivenPortCoverage (APKINDEX only).
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { OVERLAY_APPS, npmShasumToQ1, overlayDocChecksum } from '../os/overlay/index.js'
import {
  CATALOGUE_COLUMNS, CATALOGUE_FILE, CATALOGUE_TESTING_FILE, OVERLAY_REPO,
  mergeCatalogueLayers, catalogueTsvBody, parseCatalogue, type CataloguePackage,
} from '../quantum/os/catalogue.js'

export const OVERLAY_FILE = 'mirror/alpine-overlay.tsv'

async function npmMeta(spec: typeof OVERLAY_APPS[number]): Promise<{ shasum: string; desc: string }> {
  const url = `https://registry.npmjs.org/${encodeURIComponent(spec.npm)}/${spec.npmVersion}`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`npm ${spec.npm}@${spec.npmVersion}: HTTP ${res.status}`)
  const j = await res.json() as { dist?: { shasum?: string }; description?: string }
  const shasum = j.dist?.shasum
  if (!shasum || !/^[a-f0-9]{40}$/.test(shasum)) {
    throw new Error(`npm ${spec.npm}@${spec.npmVersion}: missing shasum`)
  }
  return { shasum, desc: j.description ?? spec.desc }
}

function row(p: CataloguePackage): string {
  return [p.repo, p.name, p.version, p.checksum, p.desc, p.deps.join(' '), p.provides.join(' ')].join('\t')
}

async function main(): Promise<void> {
  const rows: CataloguePackage[] = []
  for (const spec of OVERLAY_APPS) {
    const meta = await npmMeta(spec)
    const checksum = npmShasumToQ1(meta.shasum)
    rows.push({
      repo: OVERLAY_REPO, name: spec.name, version: spec.version, checksum,
      desc: spec.desc || meta.desc, deps: [...spec.deps], provides: [...spec.provides],
    })
    rows.push({
      repo: OVERLAY_REPO, name: `${spec.name}-doc`, version: spec.version,
      checksum: overlayDocChecksum(spec.name, spec.version),
      desc: `${spec.desc || meta.desc} (documentation)`, deps: [], provides: [],
    })
    console.log(`  ${spec.name.padEnd(14)} ${spec.version}  npm shasum ${meta.shasum.slice(0, 12)}… → ${checksum.slice(0, 14)}…`)
  }

  const header = `# uuidna alpine overlay — GENERATED by scripts/gen-alpine-overlay. DO NOT EDIT.\n`
    + `# npm-ported apps outside APKINDEX; merged into catalogue at read time\n`
    + `# packages=${rows.length}\n`
    + `# ${CATALOGUE_COLUMNS.join('\t')}\n`
  const out = join(ROOT, OVERLAY_FILE)
  mkdirSync(join(ROOT, 'mirror'), { recursive: true })
  writeFileSync(out, header + rows.map(row).join('\n') + '\n')
  console.log(`✓ gen-alpine-overlay — ${rows.length} rows → ${OVERLAY_FILE}`)

  const basePath = join(ROOT, CATALOGUE_FILE)
  if (existsSync(basePath)) {
    const baseText = readFileSync(basePath, 'utf8')
    const testingPath = join(ROOT, CATALOGUE_TESTING_FILE)
    const testing = existsSync(testingPath) ? parseCatalogue(readFileSync(testingPath, 'utf8')) : []
    const merged = mergeCatalogueLayers(parseCatalogue(baseText), testing, rows)
    const servedHeader = baseText.split('\n').filter((l) => l.charCodeAt(0) === 35).join('\n') + '\n'
    const served = join(ROOT, 'docs/public/alpine-catalogue.tsv')
    mkdirSync(join(ROOT, 'docs/public'), { recursive: true })
    writeFileSync(served, servedHeader + catalogueTsvBody(merged) + '\n')
    console.log(`  → docs/public/alpine-catalogue.tsv merged (${merged.length} packages)`)
  }
}

main().catch((e) => { console.error(e); process.exit(1) })
