#!/usr/bin/env node
// @non-harmonic: reads Alpine edge/testing APKINDEX over the network — the os/ boundary, where a live
// "latest" read is honest, and nowhere else.
//
// gen-alpine-testing-leads — CLOSE named latest-stable closure gaps from published testing, do not keep them open.
//
// latest-stable community sometimes depends on a package Alpine only publishes on edge/testing. Naming that
// miss and allowing it is a known gap left open. This mill pulls the published testing rows those names
// resolve to (and their testing-only package-name deps) so packageSelfTestCoverage().failed is 0.
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { untarGzipMember } from '../os/packages/index.js'
import {
  CATALOGUE_COLUMNS, CATALOGUE_FILE, CATALOGUE_OVERLAY_FILE, CATALOGUE_TESTING_FILE,
  TESTING_REPO, parseCatalogue, parseApkIndex, mergeCatalogueLayers, catalogueTsvBody,
  missingPackageNameDeps, type CataloguePackage,
} from '../quantum/os/catalogue/index.js'

const CDN = 'https://dl-cdn.alpinelinux.org/alpine'
const TESTING_BRANCH = 'edge'
const TESTING_INDEX_REPO = 'testing'

// THE READ IS SLOW BEFORE IT IS BROKEN, and undici does not know the difference. On 2026-09-05 this generator
// killed the whole reconcile with UND_ERR_CONNECT_TIMEOUT while the mirror was answering perfectly well — in
// 25.0s, against undici's undeclared 10s connect default. A chain that regenerates the derived layer must not
// be stopped by someone else's latency, and the cure is not a bigger silence: the timeout is DECLARED here, the
// read is retried, and a mirror that still will not answer is reported unread rather than fatal (see main()).
const MIRROR_TIMEOUT_MS = 60_000
const MIRROR_ATTEMPTS = 3

async function fetchTestingIndex(arch: string): Promise<CataloguePackage[]> {
  const url = `${CDN}/${TESTING_BRANCH}/${TESTING_INDEX_REPO}/${arch}/APKINDEX.tar.gz`
  let res: Response | null = null
  let last = ''
  for (let attempt = 1; attempt <= MIRROR_ATTEMPTS; attempt++) {
    try {
      res = await fetch(url, { signal: AbortSignal.timeout(MIRROR_TIMEOUT_MS) })
      break
    } catch (e) {
      last = e instanceof Error ? e.message : String(e)
      // the message reports WHAT HAPPENED, not what was assumed: a refused connection fails in milliseconds
      // and a timeout takes the full budget, and printing "did not answer within 60s" over the first would be
      // this session's own recurring fault — a plausible reason written where the actual one was available.
      console.log(`  mirror attempt ${attempt}/${MIRROR_ATTEMPTS} failed (budget ${MIRROR_TIMEOUT_MS / 1000}s): ${last}`)
    }
  }
  if (!res) throw new Error(`mirror unread after ${MIRROR_ATTEMPTS} attempts: ${last}`)
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`)
  const gz = new Uint8Array(await res.arrayBuffer())
  const body = await untarGzipMember(gz, 'APKINDEX')
  if (!body) throw new Error('edge/testing APKINDEX member missing')
  const recs = parseApkIndex(body, TESTING_REPO)
  if (!recs.length) throw new Error('edge/testing parsed to zero packages')
  return recs
}

function closeFromTesting(base: CataloguePackage[], testingIndex: CataloguePackage[]): CataloguePackage[] {
  const byName = new Map(testingIndex.map((p) => [p.name, p]))
  const leads: CataloguePackage[] = []
  const taken = new Set<string>()
  for (let round = 0; round < 32; round++) {
    const world = mergeCatalogueLayers(base, leads)
    const missing = missingPackageNameDeps(world)
    const add = missing.filter((n) => byName.has(n) && !taken.has(n))
    if (!add.length) {
      const still = missing.filter((n) => !byName.has(n))
      if (still.length) {
        throw new Error(`testing index does not close: ${still.join(', ')}`)
      }
      return leads.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)
    }
    for (const n of add) {
      taken.add(n)
      leads.push(byName.get(n)!)
    }
  }
  throw new Error('testing-lead closure did not finish in 32 rounds')
}

async function main(): Promise<void> {
  const arch = process.env.UUIDNA_ALPINE_ARCH ?? 'x86_64'
  const basePath = join(ROOT, CATALOGUE_FILE)
  if (!existsSync(basePath)) {
    console.error(`✗ gen-alpine-testing-leads — ${CATALOGUE_FILE} missing`)
    process.exit(1)
  }
  const base = parseCatalogue(readFileSync(basePath, 'utf8'))
  const overlayPath = join(ROOT, CATALOGUE_OVERLAY_FILE)
  const overlay = existsSync(overlayPath) ? parseCatalogue(readFileSync(overlayPath, 'utf8')) : []
  const withoutTesting = mergeCatalogueLayers(base, overlay)
  const missingBefore = missingPackageNameDeps(withoutTesting)
  if (!missingBefore.length) {
    const header = `# uuidna alpine testing leads — GENERATED by scripts/gen-alpine-testing-leads. DO NOT EDIT.\n`
      + `# branch=${TESTING_BRANCH} arch=${arch} repo=${TESTING_REPO} packages=0\n`
      + `# latest-stable closure already complete; no testing leads\n`
      + `# ${CATALOGUE_COLUMNS.join('\t')}\n`
    mkdirSync(join(ROOT, 'mirror'), { recursive: true })
    writeFileSync(join(ROOT, CATALOGUE_TESTING_FILE), header)
    console.log('✓ gen-alpine-testing-leads — 0 leads (latest-stable already closed)')
    return
  }

  console.log(`  latest-stable missing ${missingBefore.length}: ${missingBefore.join(', ')}`)
  // AN UNREAD MIRROR IS NOT A BROKEN TREE, and it is not a licence to ship nothing either. If the index cannot
  // be read, the leads sealed on the last successful read still stand — but only if they STILL CLOSE the gap,
  // which is checked here rather than assumed. A stale seal that closes is the best available answer and the
  // chain continues; a stale seal that does not close, or none at all, is a real failure and still aborts.
  let testingIndex: CataloguePackage[]
  try {
    testingIndex = await fetchTestingIndex(arch)
  } catch (e) {
    const why = e instanceof Error ? e.message : String(e)
    const sealedPath = join(ROOT, CATALOGUE_TESTING_FILE)
    const sealed = existsSync(sealedPath) ? parseCatalogue(readFileSync(sealedPath, 'utf8')) : []
    const stillOpen = missingPackageNameDeps(mergeCatalogueLayers(base, sealed, overlay))
    if (sealed.length && !stillOpen.length) {
      console.log(`· gen-alpine-testing-leads — MIRROR UNREAD (${why})`)
      console.log(`  the ${sealed.length} leads sealed on the last successful read still close latest-stable, so they stand unchanged.`)
      console.log(`  NOTHING WAS REGENERATED from the network this run — rerun when the mirror answers to refresh them.`)
      return
    }
    console.error(`✗ gen-alpine-testing-leads — mirror unread (${why}) and the sealed leads do not close the gap`)
    console.error(`  ${sealed.length} sealed lead(s); still open: ${stillOpen.join(', ') || '(no seal on disk at all)'}`)
    process.exit(1)
  }
  console.log(`  ${TESTING_BRANCH}/${TESTING_INDEX_REPO} ${testingIndex.length} packages`)
  const leads = closeFromTesting(withoutTesting, testingIndex)
  const header = `# uuidna alpine testing leads — GENERATED by scripts/gen-alpine-testing-leads. DO NOT EDIT.\n`
    + `# branch=${TESTING_BRANCH} arch=${arch} repo=${TESTING_REPO} packages=${leads.length}\n`
    + `# edge/testing packages latest-stable community depends on; merged at catalogue read time\n`
    + `# ${CATALOGUE_COLUMNS.join('\t')}\n`
  mkdirSync(join(ROOT, 'mirror'), { recursive: true })
  writeFileSync(join(ROOT, CATALOGUE_TESTING_FILE), header + catalogueTsvBody(leads) + '\n')
  console.log(`✓ gen-alpine-testing-leads — ${leads.length} leads → ${CATALOGUE_TESTING_FILE}`)
  for (const p of leads) console.log(`  ${p.name.padEnd(22)} ${p.version}`)

  const merged = mergeCatalogueLayers(base, leads, overlay)
  const still = missingPackageNameDeps(merged)
  if (still.length) {
    console.error(`✗ gen-alpine-testing-leads — still open after fill: ${still.join(', ')}`)
    process.exit(1)
  }
  const servedHeader = readFileSync(basePath, 'utf8').split('\n').filter((l) => l.charCodeAt(0) === 35).join('\n') + '\n'
  mkdirSync(join(ROOT, 'docs/public'), { recursive: true })
  writeFileSync(join(ROOT, 'docs/public/alpine-catalogue.tsv'), servedHeader + catalogueTsvBody(merged) + '\n')
  console.log(`  → docs/public/alpine-catalogue.tsv merged (${merged.length} packages)`)
}

main().catch((e) => { console.error(e); process.exit(1) })
