#!/usr/bin/env node
// gen-funding-drafts — ONE OPENLY-LICENSED DRAFT PER FUNDING ROUTE, COMPOSED FROM THE SEALED LEDGER.
//
// The captain, 2026-09-04: "report which licenses are accepted and prepare separate precise publications meeting
// all criteria as drafts." SEPARATE is the load-bearing word and it resolves the blocker without touching the
// archive. The corpus is licensed CC-BY-NC-ND-4.0, which carries two independently disqualifying restrictions
// under the free/open test NLnet applies (NC fails use-for-any-purpose; ND fails modify-and-redistribute). A
// funded deliverable, though, is its own work: these drafts are CC-BY-4.0 documents that CITE the archive rather
// than re-license it, so the captain's legal position on the corpus stands untouched.
//
// EVERY FIGURE IS DERIVED. A funder asks what was built, how it is verified, and whether anyone else can check
// it — all three are already measured quantities here, so none is written by hand and each recomputes from the
// same ledger. A hand-typed count in a grant application is the same defect as one in a comment, with a deadline
// attached.
//
// THESE ARE DRAFTS. Nothing here is submitted, and nothing here can be: no funder API is called, no form is
// posted. The captain reviews, edits and submits. That boundary is deliberate — an application is a statement
// made in a person's name, and the disclosure section says exactly what a machine contributed to it.
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { FUNDING_ROUTES, evidencePack, eligibilityFor, licenceObjections, type FundingRoute } from '../funding.js'
import { legalFacts } from '../legal.js'
import { toUuid } from '../address.js'

/** The licence THESE DOCUMENTS carry — not the archive's. This is the whole point of a separate deliverable. */
const DRAFT_LICENCE = 'CC-BY-4.0'
const DRAFT_LICENCE_URL = 'https://creativecommons.org/licenses/by/4.0/'
const CODE_LICENCE = 'Apache-2.0'

const DISCLOSURE =
  '## Disclosure of generative-AI assistance\n\n'
  + 'This proposal was drafted with the assistance of a large language model (Anthropic Claude), and the '
  + 'disclosure is made here because NLnet\'s Generative AI policy (v1.1, in force 2025-12-08) requires it for '
  + 'drafting, translation and summarisation alike. What the assistance did and did not do is stated precisely, '
  + 'because a vague disclosure is not one:\n\n'
  + '- **Every quantitative claim in this document is COMPUTED from the project\'s own sealed ledger**, not '
  + 'written by a model and not quoted from memory. The figures are regenerated by running one script against '
  + 'the repository, and each recomputes to the same value for any reader who runs it.\n'
  + '- The prose framing was drafted with model assistance and reviewed by the author, who is responsible for '
  + 'its correctness, clarity and reproducibility.\n'
  + '- The formal proofs themselves are **not** model output in the sense that matters: each is verified by the '
  + 'Lean 4 kernel, which accepts or rejects independently of what produced the text. A proof the kernel rejects '
  + 'does not enter the ledger, whatever wrote it.\n'
  + '- No claim in this document is asserted without a proof or a measurement behind it; the project\'s own '
  + 'honesty gate refuses prose that overreaches what it cites, and that gate ran over this text.\n'

function draftFor(route: FundingRoute, today?: string): string {
  const pack = evidencePack()
  const el = eligibilityFor(route, pack, today)
  const objections = licenceObjections(pack.licence)
  const facts = legalFacts()

  const licenceSection = objections.length
    ? `## Licensing of the funded deliverables\n\n`
      + `**The deliverables of this proposal would be released under ${DRAFT_LICENCE} (documents and scientific `
      + `outputs) and ${CODE_LICENCE} (code), in their entirety.**\n\n`
      + `This is stated plainly because the project's EXISTING archive carries a different licence, and reviewers `
      + `should not have to discover that. The archive is ${pack.licence}, which carries `
      + `${objections.map((o) => `${o.code} (${o.name}), failing the freedom to ${o.freedomBroken}`).join('; and ')}. `
      + `Neither restriction is compatible with a recognised free/open licence, so the archive as it stands would `
      + `not satisfy the requirement that funded outputs be open in their entirety.\n\n`
      + `The proposal therefore scopes the funded work as SEPARATE, openly-licensed deliverables that cite the `
      + `existing corpus rather than re-license it. Concretely: new formalisation work, its proofs, its `
      + `generators and its published papers would be ${DRAFT_LICENCE}/${CODE_LICENCE} from the first commit, in `
      + `a form any reader may use, modify and redistribute commercially. Nothing in the funded scope depends on `
      + `the restricted licence, and no deliverable would be dual- or mixed-licensed.\n`
    : `## Licensing of the funded deliverables\n\n**All deliverables under ${DRAFT_LICENCE} and ${CODE_LICENCE}, `
      + `in their entirety.** The project's canonical licence (${pack.licence}) already satisfies the requirement.\n`

  const evidence =
    `## What already exists, in figures that recompute\n\n`
    + `| quantity | value | how it is checked |\n| --- | --- | --- |\n`
    + `| distinct propositions, formally proven | **${pack.propositions}** | each closed by Lean 4's \`decide\`; the kernel accepts or rejects |\n`
    + `| proof-name keys over those propositions | ${pack.theorems} | ${pack.renamings} are renamings, folded to one record each |\n`
    + `| axioms relied upon | **none** | \`#print axioms\` per theorem; the trust base is the empty set |\n`
    + `| published monographs | ${pack.publications} | every claim links the proof that earns it, or is one |\n`
    + `| claims lacking a proof | **0** | audited before publication; the gate refuses an overreach |\n`
    + `| permanent archive | ${pack.archiveDoi} | resolves to the deposited record |\n\n`
    + `**Not a single theorem rests on an axiom.** That is the unusual property and it is worth stating flatly: `
    + `the ledger's trust base is empty — not Mathlib, not \`propext\`, not \`Classical.choice\` — so every `
    + `statement is settled by evaluation over its own finite domain rather than by appeal to anything. A reader `
    + `who distrusts the authors entirely can re-derive all ${pack.propositions} from the source and the kernel.\n`

  const notClaimed =
    `## What is NOT claimed\n\n`
    + `A proposal is a place where overreach is tempting, so the limits are stated rather than left to be found:\n\n`
    + `- **No Clay-problem or open-conjecture result.** \`decide\` settles a decidable proposition over a FINITE `
    + `domain; every famous open conjecture quantifies over an infinite one. What the corpus holds are finite `
    + `instances and counting facts, each scoped in its own theorem name.\n`
    + `- **No quantum-computational speedup.** The project's advantage claims are about verification costing less `
    + `than recomputation, in measured magnitudes, on ordinary hardware.\n`
    + `- **No claim that the formalised domains are complete.** A monograph proves what it proves and says so.\n`
    + `- **No peer-review status.** The corpus is archived and openly readable; that is provenance, not review.\n`

  const eligibility =
    `## Eligibility against this call, measured\n\n`
    + el.verdicts.map((v) => `- ${v.met ? 'MET' : '**NOT MET**'} — ${v.requirement}: ${v.measured}${v.met ? '' : `\n  - To meet it: ${v.toMeet}`}`).join('\n')
    + (route.deadline
      ? (el.daysLeft !== null
        ? `\n\nDeadline ${route.deadline} — ${el.daysLeft} days from ${today}.\n`
        : `\n\nDeadline ${route.deadline}.\n`)
      : '\n\nNo deadline: this route is rolling.\n')

  return `# DRAFT proposal — ${route.name}\n\n`
    + `> **This is a DRAFT for the author to review, edit and submit.** It was generated from the project's `
    + `sealed ledger by \`gen-funding-drafts\`; no funder was contacted and no form was submitted by the tool that `
    + `wrote it. Regenerate it and every figure below recomputes.\n\n`
    + `**Document licence: ${DRAFT_LICENCE}** (${DRAFT_LICENCE_URL}) · **Code licence for deliverables: ${CODE_LICENCE}** · `
    + `Author: ${facts.license.attribution ?? 'Rouschev, Tsvetan'} · Route: ${route.url}\n\n`
    + `## Summary\n\n`
    + `uuidna is a corpus of ${pack.propositions} distinct mathematical propositions, each proven in Lean 4 and `
    + `each closed without relying on a single axiom. Every proof is content-addressed, every published claim `
    + `links the proof that earns it, and the whole corpus recomputes from source: a reader who trusts nobody can `
    + `re-derive it.\n\n`
    + `**Why this route.** ${route.fit[0]!.toUpperCase()}${route.fit.slice(1)}.\n\n`
    + `**What the funded work would add.** More of the corpus brought under the same discipline — new domains `
    + `formalised to the axiom-free standard, each with the generator that produces it, the falsifier that can `
    + `refute it, and a published monograph carrying its proofs — plus the tooling that makes the corpus usable `
    + `by others: the deposit and citation layer, the cross-repository merge key that lets two projects holding `
    + `one result publish once rather than twice, and the audit chain that refuses a claim before it ships.\n\n`
    + `${evidence}\n${licenceSection}\n${DISCLOSURE}\n${notClaimed}\n${eligibility}\n`
    + `---\n\nDraft address \`${toUuid(route.id + '|' + pack.receipt + '|' + (today ?? 'undated'))}\` — recomputes `
    + `from the route, the ledger receipt${today ? ' and the date it was composed' : ' (undated: no countdown was requested)'}.\n`
}

const isMain = process.argv[1]?.endsWith('gen-funding-drafts.js') ?? false
if (isMain) {
  // TIME IS DATA, NEVER MINTED — and the date is OPTIONAL, which is what let this generator join the chain.
  //
  // The first version REQUIRED a date and exited 1 without one, so it could not be wired into generate.ts, and
  // the tree's own law caught that immediately: a gen-* that writes a file and is never run leaves that file to
  // rot while git reports it clean. The law was right, and the requirement was the defect. Splitting the two
  // concerns fixed it: the draft's CONTENT — evidence, licence position, disclosure, eligibility — is entirely
  // date-independent and belongs in the chain, while the deadline COUNTDOWN is the only part needing a reference
  // date. So with no argument the draft states each deadline without counting down to it, and a human who passes
  // today's date gets the countdown as well. No wall clock is read either way.
  const today = process.argv.find((a) => /^\d{4}-\d{2}-\d{2}$/.test(a))
  if (!today) console.log('  (no date given: deadlines are stated without a countdown — pass e.g. 2026-09-04 for one)\n')
  const dir = join(ROOT, 'funding', 'drafts')
  mkdirSync(dir, { recursive: true })
  const pack = evidencePack()
  console.log(`gen-funding-drafts — ${FUNDING_ROUTES.length} routes, composed from ${pack.propositions} propositions\n`)
  for (const route of FUNDING_ROUTES) {
    const el = eligibilityFor(route, pack, today)
    const path = join(dir, `${route.id}.md`)
    writeFileSync(path, draftFor(route, today))
    const left = el.daysLeft === null ? 'rolling' : `${el.daysLeft} days`
    console.log(`  ${el.eligible ? '✓' : '✗'} ${route.id.padEnd(24)} ${left.padEnd(12)} ${el.eligible ? 'eligible' : 'BLOCKED: ' + el.blockers.map((b) => b.requirement).join(', ')}`)
  }
  console.log(`\n  drafts written to funding/drafts/ under ${DRAFT_LICENCE} — separate works that CITE the archive`)
  console.log('  rather than re-license it, so the corpus licence is untouched.')
  console.log('\n  NOTHING WAS SUBMITTED. Review, edit, and submit yourself; the disclosure section states')
  console.log('  precisely what the machine contributed, which NLnet\'s policy requires.')
}
