#!/usr/bin/env node
// gen-falsifiers — EMIT THE FALSIFIER TEST FOR EVERY SEALED STATEMENT A SECOND IMPLEMENTATION CAN DECIDE.
//
// THE BACKLOG. A theorem stands on five legs — symbol, proof, witness, falsifier, address. The ledger mints
// three; the other two are authored, and almost every sealed theorem owes at least one.
//
// HISTORY, 2026-08-25, the measurement that motivated this file and deliberately written in the past tense so
// its numbers are a record rather than a claim about now: the ledger held two thousand one hundred and one
// sealed theorems; two thousand and ninety-one witness legs and one thousand nine hundred and seventy-seven
// falsifier legs were owed; one hundred and twenty-four theorems carried a falsifier; ten carried an external
// witness; and exactly two stood on all five. Run `node dist/scripts/rosetta.js` for what is true today — a
// count in a comment is wrong on the next landing, which is the rule that caught this header.
//
// THE TWO HALVES ARE NOT THE SAME KIND OF WORK, and conflating them is how a backlog gets "finished" dishonestly.
// A WITNESS must be "something outside this repository that a stranger could consult — a published standard, a
// named author, a measured artefact" (rosetta), and "the project's own prose is not a witness to itself". No
// generator can produce one: it is research, one theorem at a time, and inventing one would be a second name for
// the same claim. Those 2,091 are not touched here and must not be.
//
// A FALSIFIER is different in kind: it is the mutation that must break the theorem, and for a DECIDABLE statement
// a second independent implementation IS one. If the sealed proposition stops being true, an evaluator that
// recomputes it says false and the test goes red. That is not a restatement of the claim — the Lean kernel and a
// TypeScript evaluator are two different machines agreeing, which is exactly the independence the leg asks for.
//
// WHAT IT WILL NOT DO. It emits a test ONLY for statements src/involution's `evaluable` accepts and `holds`
// decides — 805 of 2,101 — and it emits nothing for the other 1,296. A theorem whose statement needs a grammar
// the evaluator lacks gets no leg from this, and is left in the backlog where a human can see it, rather than
// being handed a test that asserts something weaker than the theorem. A generated leg that half-checks its
// theorem is worse than the missing leg it replaces.
//
// AND IT REFUSES ON FALSE. If any sealed statement evaluates FALSE, that is not a test to emit — it is a ledger
// and an evaluator disagreeing about a proposition, which is a finding, and the run stops and names it.
//
// GENERATED, NOT HAND-TYPED, because the list must not lag: rosetta grants the leg by grepping test files for the
// literal key, so the keys have to appear in a test — and a hand-typed list of eight hundred keys is the defect
// this repository names in six other places. Regenerate and the set follows the ledger.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { THEOREMS } from '../theorems/index.js'
import { evaluable, holds } from '../involution/index.js'

const OUT = join(ROOT, 'src', 'falsifiers.test.ts')

interface Decidable { key: string; statement: string }

const decidable: Decidable[] = []
const disagreed: Decidable[] = []
const unreached: string[] = []

for (const t of THEOREMS) {
  if (!evaluable(t.statement)) { unreached.push(t.key); continue }
  const h = holds(t.statement)
  if (h === true) decidable.push({ key: t.key, statement: t.statement })
  else if (h === false) disagreed.push({ key: t.key, statement: t.statement })
  else unreached.push(t.key)          // evaluable in shape, undecided in fact — no leg claimed
}

if (disagreed.length) {
  console.error(`✗ gen-falsifiers — ${disagreed.length} SEALED statement(s) evaluate FALSE under an independent evaluator.`)
  console.error('  That is the ledger and the evaluator disagreeing about a proposition. It is a finding, not a test to emit.')
  for (const d of disagreed.slice(0, 5)) console.error(`    ${d.key}: ${d.statement.slice(0, 90)}`)
  process.exit(1)
}

// the statement rides in the emitted file as a STRING the test re-evaluates, so the assertion is over the sealed
// text rather than over a copy of the arithmetic — mutate the theorem and this recomputes the mutation
const lines = decidable.map((d) => `  [${JSON.stringify(d.key)}, ${JSON.stringify(d.statement)}],`)

const file = `// GENERATED by src/scripts/gen-falsifiers.ts — DO NOT EDIT. Regenerate: npm run x -- gen-falsifiers
//
// THE FALSIFIER LEG, FOR EVERY SEALED STATEMENT A SECOND IMPLEMENTATION CAN DECIDE.
//
// rosetta grants the falsifier leg when "a test names it, which is where a mutation that must fail would live".
// Each theorem below is named with its SEALED STATEMENT, and the test re-decides that statement with an
// evaluator written independently of the Lean kernel that proved it. Mutate a proposition so it stops being
// true and this file goes red; that is the mutation the leg is asking about.
//
// WHAT THIS IS NOT: a witness. A witness is something outside this repository a stranger could consult, and the
// project's own arithmetic is not a witness to itself. Every theorem here still owes that leg.
//
// WHAT IS ABSENT AND WHY: the sealed theorems NOT listed here are absent because the evaluator's grammar cannot
// reach their statements. They keep their missing falsifier rather than receiving a test that checks something
// weaker than the theorem — a generated leg that half-checks is worse than the gap it hides. The count is
// deliberately not written down: run the generator, which prints it, or read it off the census — a number in a
// comment is wrong on the next landing even when a generator would have refreshed it, and the rule that catches
// that caught this file.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { holds } from './involution/index.js'
import { theoremByKey } from './index.js'

/** [key, the exact sealed statement] — regenerated from the ledger, never hand-edited. */
const DECIDED: readonly (readonly [string, string])[] = [
${lines.join('\n')}
]

test('every sealed statement here re-decides TRUE under an independent evaluator', () => {
  const wrong: string[] = []
  for (const [key, statement] of DECIDED) if (holds(statement) !== true) wrong.push(key)
  assert.deepEqual(wrong, [],
    'a sealed proposition that a second implementation does not confirm is the ledger and the evaluator disagreeing')
})

test('every statement named here is the one the ledger currently seals — no stale copies', () => {
  const drifted: string[] = []
  for (const [key, statement] of DECIDED) {
    const t = theoremByKey().get(key)
    if (!t) { drifted.push(key + ' (no longer sealed)'); continue }
    if (t.statement !== statement) drifted.push(key + ' (statement moved)')
  }
  assert.deepEqual(drifted, [],
    'regenerate with npm run x -- gen-falsifiers — a falsifier over a stale statement falsifies nothing')
})

test('THE CHECK BITES — a mutated statement is refused', () => {
  // if this passed, every assertion above would be decoration: an evaluator that accepts anything confirms nothing
  assert.notEqual(holds('2 + 2 = 5'), true)
  assert.equal(holds('2 + 2 = 4'), true)
})
`

writeFileSync(OUT, file)
console.log(`✓ gen-falsifiers — ${decidable.length} sealed statement(s) re-decided TRUE by an independent evaluator`)
console.log(`    emitted   src/falsifiers.test.ts`)
console.log(`    unreached ${unreached.length} — the evaluator's grammar cannot decide these; they keep their missing leg`)
console.log(`    disagreed ${disagreed.length}`)
