#!/usr/bin/env node
// gen-cloudflare-templates — EMBED THE TEMPLATE MIRROR AS A MODULE, so nothing reads a file at run time.
//
// WHY THIS EXISTS, and it is a regression I caused. src/cloudflare-templates.ts read mirror/cloudflare-templates.tsv
// with node:fs. That is fine in a script and wrong in a module the site imports: vitepress pulled it into the
// browser bundle, externalised node:fs and node:path, and the docs build failed — which blocked the release gate.
// It also contradicted the thing I had just measured and published, that all 13 subpaths of @uuidna/uuidna reach
// ZERO Node builtins. A module that claims to run in a Worker may not read the disk.
//
// So the mirror is compiled to a TypeScript module, the way this tree already compiles the Lean ledger into
// src/theorems/generated.ts. The harvest still writes the TSV (it is the committed, human-readable fact); this
// turns that fact into something a browser, a Worker and Node can all import with no host behind it.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'

const MIRROR = 'mirror/cloudflare-templates.tsv'
const OUT = 'src/cloudflare-templates-data.ts'

const path = join(ROOT, MIRROR)
if (!existsSync(path)) {
  console.error(`✗ gen-cloudflare-templates — ${MIRROR} missing; run the harvest first`)
  process.exit(1)
}
const rows = readFileSync(path, 'utf8').split('\n')
  .filter((l) => l && !l.startsWith('#'))
  .map((l) => {
    const [template, config, workerName, bindings, main, compat] = l.split('\t')
    return {
      template: template ?? '',
      config: config === 'e2e' ? 'e2e' : 'primary',
      workerName: workerName ?? '-',
      bindings: (bindings ?? '-') === '-' ? [] : (bindings ?? '').split(','),
      main: main ?? '-',
      compatibilityDate: compat ?? '-',
    }
  })

const body = `// GENERATED by scripts/gen-cloudflare-templates from ${MIRROR}. DO NOT EDIT.
//
// The mirror is the committed fact, harvested from each Cloudflare template's own wrangler config. This module
// is that fact compiled, so every surface — browser, Worker, Node — imports it with no filesystem behind it.
// The module that reads a file cannot run where uuidna claims to run, and the claim is measured: 13 of 13
// published subpaths reach zero Node builtins.
import type { CloudflareTemplate } from './cloudflare-templates.js'

export const TEMPLATE_ROWS: readonly CloudflareTemplate[] = ${JSON.stringify(rows, null, 1)} as const
`
writeFileSync(join(ROOT, OUT), body)
const primary = rows.filter((r) => r.config === 'primary').length
console.log(`✓ gen-cloudflare-templates — ${rows.length} configs (${primary} templates, ${rows.length - primary} e2e) → ${OUT}`)
