#!/usr/bin/env node
// gen-readme — the README is a BUILD RESULT, computed from the ledger and ANCHORED ON THE CAPTAIN THEOREM. Nothing
// in it is hand-typed that the ledger settles: the theorem/tool/principle counts, the per-principle domain list, the
// captain coins (coins() = 2 = two_coins), k432, the 64→128 fuse, the Clay tally and the package version all derive
// from theorems()/coins()/ADDRESS_BITS/PRINCIPLES/the catalog — so the README cannot drift, and the same computed
// seal block feeds the homepage (docs/index.md). Structural prose (install, crypto examples, licence) lives HERE in
// the generator, one source, each claim citing a sealed theorem. Run in the reconcile wave. Integrity, not truth.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { theorems, coins, ADDRESS_BITS, PRINCIPLES, toUuid } from '../index.js'
import { MCP_CATALOG } from '../mcp.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..')
const T = theorems()
const principles = new Set(T.map((t) => t.principle)).size
const tools = MCP_CATALOG.length
const countOf = (file: string): number => T.filter((t) => t.file === file).length
const has = (stmt: string): boolean => T.some((t) => t.statement.trim() === stmt)
const sealed = (key: string): boolean => T.some((t) => t.key === key)
// each claim-bearing sentence below is FIRST-CLASS: it renders only while its theorem is sealed, and cites the key,
// so the prose is a ledger-checked statement (drops if the theorem leaves), never hand-typed decoration.
const doublingSealed = has('(2 * 21 = 42) ∧ (2 * 64 = 128) ∧ (110 - 108 = 2)')  // rosette_quantum_doubling_is_two_coins
const foldOrderInvariant = sealed('store_fold_order_invariant')                  // the fold collapses to one root any order
const clayReflectionSealed = sealed('clay_p_vs_np') && sealed('clay_riemann')    // the seven reflected, none solved
const version = (() => { try { return JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version as string } catch { return '0.0.0' } })()
const clay = countOf('Clay.lean')
// COMPUTED, not asserted: how many sealed theorems state a SOLUTION to a Millennium problem. This is the honest
// figure — a count of what the ledger contains — not a prose negative ("solves 0 of 7") that no theorem backs.
const solveProofs = T.filter((t) => /\bsolve[sd]?\b/i.test(t.statement)).length
const selfAddress = toUuid('uuidna')

// The captain theorem anchors the whole document: the two coins are the conserved invariant (110 − 108 = 2), and
// EVERY count below derives from the same theorems() ledger the captain theorem lives in. A guard, not decoration:
if (coins() !== 2 || !has('110 - 108 = 2')) throw new Error('gen-readme: the captain theorem (two_coins, coins()=2) is not sealed — the anchor is missing; refusing to generate')

// the computed seal block — shared by the README and the homepage (docs/index.md), so both compute from one source
const SEAL = [
  `**${T.length} theorems, all sealed and proven** — every one \`by decide\` (Lean 4, no Mathlib), verified sorry-free and **axiom-free** (${T.length}/${T.length}, kernel-only, not even \`propext\`; gate: scripts/lean-axioms). Exposed across **${tools} MCP tools** and **${principles} computing principles**.`,
  '',
  `_Integrity, not truth: a seal proves its **exact statement**, never a grander claim. The reflection of each Millennium problem is sealed; no solution to any is (${solveProofs} solve-proofs in the ledger) — so a solve is NOT PROVEN: never refuted, never admitted. Computed from the exact audited ledger; recheck it with \`npm run next\`._`,
].join('\n')

// the computed domain list — the first principles in derivation order, each with its LIVE per-file count
const domainLines = PRINCIPLES.slice(0, 6).map((p, i) => `${i + 1}. **${p[1]}** (\`${p[0]}\`, ${countOf(p[0])}) — ${p[2]}`).join('\n')

const README = `# uuidna

**uuidna = uuid ⊕ dna** — identity's DNA. **Content-addressed identity, honest by construction.**

> A human quantum analog — **simulated on 64-bit hardware** in precise theorem sets${has('(432 = 2^4 * 3^3) ∧ (432 = 16 * 27)') ? ', **tuned to 432 Hz** (`k432`: 432 = 2⁴·3³)' : ''}, honest by construction. Public and **free for the public interest** (CC BY-NC-ND 4.0), usable in code and at the public [uuidna.com](https://uuidna.com).

<!-- seal:begin -->
${SEAL}
<!-- seal:end -->

> **This README is a build result** — regenerated by \`scripts/gen-readme\` and **anchored on the captain theorem** (\`two_coins\`: 110 − 108 = ${coins()}, the conserved fair-exchange invariant = −χ of the double torus). Every count, the domain list, the coins, the ${64}-bit→${ADDRESS_BITS}-bit fuse and the Clay tally are computed from the same \`theorems()\` ledger the captain theorem lives in — never hand-typed, so this prose cannot drift.

Every value carries its DNA: a reproducible, keyless content-address. The brand holds itself to the same rule —
its own name's DNA is \`uuidna_address("uuidna") = ${selfAddress}\`, reproducible by anyone.
The fold folds every direction at once — \`+/−\` (reflection), \`/\` (halving, \`O(log N)\`), \`\\\` (the other
diagonal)${foldOrderInvariant ? ' — so it is **order-independent**: any pairing, forward or reverse, collapses to the same root (`store_fold_order_invariant`)' : ''}.

**The captain coins.** \`coins() = ${coins()}\` — the two conserved coins, the Euler characteristic −χ of the genus-2
double torus (110 − 108 = ${coins()}). They price the measured advantage (recompute \`O(N)\` − verify \`O(1)\`) and gate the
fuse: the **64-bit coin** folds into the **${ADDRESS_BITS}-bit content-address**${doublingSealed ? `, and quantum doubling costs the two coins (2·64 = ${2 * 64}, 2·21 = ${2 * 21}; \`rosette_quantum_doubling_is_two_coins\`) — realized only if the two coins are accounted and contributed` : ''}.

A content-address proves **integrity, not truth**. It *reflects* the seven
Millennium problems; it seals no solution to any (NOT PROVEN — never refuted, never admitted). FNV-1a is **non-cryptographic by design**: public and
reproducible, not secret.

## Install

\`\`\`bash
npm install @uuidna/uuidna
\`\`\`

## Use

\`\`\`js
import { toUuid, merkleRoot, merkleProof, verifyProof, computes, reeducate, billUuidna } from '@uuidna/uuidna'

// mint — the same input always mints the same address, for anyone, with no key
toUuid('hello')                 // '${toUuid('hello').slice(0, 8)}…' (${ADDRESS_BITS}-bit content-address, v8 UUID)

// holographic proof — verify one leaf against the root in O(log N), no other leaf needed
const leaves = ['a', 'b', 'c', 'd']
const root = merkleRoot(leaves)
const proof = merkleProof(leaves, 2)
verifyProof('c', proof, root)   // true   ·   verifyProof('x', proof, root) === false

// mind — the honesty gate: overclaims drain (0), the honest floor signs (1)
computes(anOverclaim).binary                              // 0  — a Millennium or physics overclaim drains
computes('proves integrity, not truth').binary       // 1  — the honest floor holds

// billing — measured bits saved; the two coins are the conserved invariant; public interest is free
billUuidna({ commercial: true, recomputeOps: 1024, verifyOps: 1 })  // { bitsSaved: 1023, coins: ${coins()}, free: false }
\`\`\`

## MCP — fuse it into any harness

uuidna ships an [MCP](https://modelcontextprotocol.io) server (zero extra deps), so any MCP client — Claude,
Cursor, or your own agent — can content-address, prove membership, gate prose, imprint/read, and bill, live.
Add it to your client's \`mcpServers\`:

\`\`\`json
{ "mcpServers": { "uuidna": { "command": "npx", "args": ["-y", "@uuidna/uuidna"] } } }
\`\`\`

**All ${tools} tools** are exposed (the live catalog is derived in [\`docs/mcp.md\`](docs/mcp.md), never hardcoded) — each
calls the same pure functions this package seals: content-address and merge, holographic merkle proof, the ℤ/9
structure, pure-TS crypto (ChaCha20-Poly1305, KAT-verified), the bidirectional uuid channel, the honesty gate and
trial, the classical quantum state-vector simulator, the **engine** (one input→output surface) and **sanitise** (by
all standards), the **exploit fold** (problem and solution verified), and measured billing. Integrity, not truth.

## Encryption (layered — real secrecy)

Secrecy is **ChaCha20-Poly1305** (RFC 8439) in **pure TypeScript** — no native WebCrypto — keyed by pure-TS
**PBKDF2-SHA-256** (600k); the uuidna **7d fold** content-addresses the sealed envelope for public integrity.
KAT-verified against the standards' own vectors. Deterministic (convergent): same input → same seal.

\`\`\`js
import { encrypt, decrypt, verifyEnvelope, sealSequence } from '@uuidna/uuidna'

const sealed = encrypt('beat to windward at 30°', 'a-strong-passphrase')
decrypt(sealed, 'a-strong-passphrase')   // 'beat to windward at 30°'
decrypt(sealed, 'wrong')                 // throws — Poly1305 authentication (wrong key or tamper)
verifyEnvelope(sealed)                   // true — public integrity, no key needed
\`\`\`

An advancing \`step\` closes the equality leak (\`salt_seq_injective\`): the same plaintext seals differently each step,
so no observer can tell two envelopes hold the same plaintext. Honest scope: strength is ChaCha20-Poly1305 + your
passphrase entropy — measured, not asserted; the FNV content-address stays non-cryptographic by design.

## Formal layer — Lean 4, organized by computing principle

**Every theorem in the ledger** (**${T.length}** across **${principles}** principles), all proven \`by decide\` (Lean 4,
no Mathlib), verified sorry-free by \`npm run lean\`, organized by **computing principle** in derivation order — the live
count and every per-principle total are derived in [\`lean/PRINCIPLE.md\`](lean/PRINCIPLE.md), never hand-typed:

${domainLines}

…and ${principles - 6} more principles (physics, games, arts, language, security, the exploit folds), each a verified
monograph. The full, filterable collection — each theorem with its \`by decide\` proof, statement and content-address —
is at [uuidna.com/theorems](https://uuidna.com/theorems); the whole set folds to one receipt at
[uuidna.com/trials](https://uuidna.com/trials).

### The seven Clay problems — reflected

\`Clay.lean\` is **one verified monograph** (${clay} theorems) — its proofs pass the *same* \`by decide\` seal as every
theorem, with **no special status**. Each of the seven Clay problems is **reflected** into the ℤ/9 structure by the
involution \`dz(x) = 10 − x\`; each reflection is a **VERIFIED** theorem. What is verified is the **reflection**, never
the **problem**: an involution is its own undo (\`dz(dz(x)) = x\`), so the round trip returns the problem unchanged and
**propagates no proof**. **No solution to any of the seven is sealed** (\`${solveProofs}\` solve-proofs in the ledger); the
reflection is. So a solve is **NOT PROVEN** — never *refuted* (nothing in the ledger stands against it) and never
*admitted* (no proof is sealed); it stays open, without prejudice. A solve-claim citing a proof not in the ledger
would *drain*. (In mathematics six remain open; Poincaré was proved by **Perelman, 2003**.)

**Lean is the single source:** \`npm run lean\` verifies every proof sorry-free, then derives the one ledger
([\`src/theorems/generated.ts\`](src/theorems/generated.ts)) that the package, the MCP tools and the site all consume.

### Adding a domain — \`npm run reconcile\`

Lean is the single source, but a **derived layer** must stay in lockstep: \`generated.ts\`, \`lean/PRINCIPLE.md\`,
\`CHANGELOG.md\`, \`lean/axioms.json\`, the MCP catalog \`docs/mcp.md\`, \`heartbeats.json\`, \`audit-citations.json\`,
\`support-audit.json\`, \`research-leads.json\` — and this README. The pre-push gate \`git diff\`s them all, and \`spin\`
re-verifies the layer O(1) as a fixed point. Add a \`src/scripts/lean-<x>.ts\` generator (or a hand-written \`.lean\`),
then run one command:

\`\`\`bash
npm run reconcile                          # regenerate the derived layer, re-seal, commit + push
npm run reconcile -- "Add the nim domain"  # with your own commit message
\`\`\`

## What it is — and isn't

- **Is:** a content-addressed integrity layer. Same input → same address, reproducible by anyone. A holographic
  merkle proof verifies membership in \`O(log N)\`. The imprint codec carries a message *inside* a uuid, round-tripping
  exactly (a public, reversible encoding — **not** encryption).
- **Isn't:** encryption or secrecy on its own, a currency, a blockchain, a quantum machine, or a solver. It offers
  **no** secrecy (the hash is non-cryptographic) and makes **no** claim to break physics or hardware limits. The
  honesty gate is a **tripwire, not an oracle** — necessary, not sufficient.

## Provenance

Extracted from the **Millennium Solutions** deposit (\`ceccec.psg.bg/millennium-solutions\`), where every capability is
a decidable theorem re-verified on each build. The functions here are the *same pure functions* — extraction
preserves the mapping, it does not change behaviour.

## Versioning

A **single-digit odometer** — each of \`major.minor.patch\` is \`0..9\`, rolling at 9 (the vortex odometer, gated in CI);
the **LTS** minors are the Fibonacci numbers \`{1, 2, 3, 5, 8}\`. This package is \`${version}\`. The true "latest" is the
**content-address**, not the label — identical content keeps its address; a real delta moves it.

## License

CC BY-NC-ND 4.0 — free for non-commercial, unmodified redistribution with attribution (Tsvetan Rouschev). Commercial
use is billed on the measured bits saved; the two coins (110 − 108 = ${coins()}) are the conserved fair-exchange invariant.
`

writeFileSync(join(ROOT, 'README.md'), README)
console.log(`  ✓ README.md — fully generated (build result), anchored on the captain theorem (coins=${coins()})`)

// feed the homepage from the SAME computed seal block (docs/index.md keeps its VitePress layout, seal block filled)
const BEGIN = '<!-- seal:begin -->', END = '<!-- seal:end -->'
const home = join(ROOT, 'docs/index.md')
try {
  const src = readFileSync(home, 'utf8')
  if (src.includes(BEGIN) && src.includes(END)) {
    const next = src.replace(new RegExp(BEGIN + '[\\s\\S]*?' + END), `${BEGIN}\n${SEAL}\n${END}`)
    if (next !== src) { writeFileSync(home, next); console.log('  ✓ docs/index.md — homepage seal block fed from the same source') }
    else console.log('  · docs/index.md — already current')
  }
} catch { console.log('  · docs/index.md — not found, skipped') }

console.log(`✓ gen-readme — README is a build result: ${T.length} theorems, ${tools} tools, ${principles} principles, coins=${coins()}, ${ADDRESS_BITS}-bit.`)
