#!/usr/bin/env node
// gen-statement-fixture — EMIT EVERY SEALED STATEMENT WITH ITS ADDRESS, IN ONE PASS, AS AN ARTEFACT.
//
// WHY AN ARTEFACT AND NOT A DESCRIPTION. A peer repository asked uuidna to join a cross-repository statement
// address, and led with the lesson that cost it a day: it sent two peers a rule in prose plus a pinned vector,
// and both were wrong — the pin's halves did not correspond, and "remove a space only where it is not doing
// lexical work" is an intent, not an algorithm. Two repositories then burned fifteen framings between them
// hunting a divergence that did not exist. So nothing here is described. Every value below is computed by
// src/proposition-address.ts in one pass, from the sealed ledger, and anyone may recompute it.
//
// THE FIELD THAT SETTLES A DISAGREEMENT IS `normalisedLength`. Two implementations that disagree on an address
// have either hashed DIFFERENT BYTES or hashed the same bytes DIFFERENTLY, and only the first is visible in the
// length. That fork is the one worth checking before any hash framing is tried: the peer's own divergence
// turned out to be one character, a space after a semicolon, and one number found it after three rounds of
// prose did not.
//
// WHAT UUIDNA'S RULE DOES AND DOES NOT DO, stated as the code and not as a summary — read
// src/proposition-address.ts. Two properties worth naming because they are join-relevant: it does NOT
// lowercase (a Lean corpus is case-load-bearing: `Nat` and `nat` are different identifiers), and it folds `==`
// to `=` and `!=` to `≠` so the two spellings of one proposition land on one address.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { THEOREMS } from '../theorems/index.js'
import { normaliseProposition, propositionAddress, propositionCensus } from '../proposition-address.js'
import { sha256 } from '../sha256.js'

const hex = (b: Uint8Array): string => [...b].map((x) => x.toString(16).padStart(2, '0')).join('')
const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s)

const rows = THEOREMS.map((t) => {
  const normalised = normaliseProposition(t.statement)
  return {
    key: t.key,
    statement: t.statement,
    normalised,
    rawLength: [...t.statement].length,
    normalisedLength: [...normalised].length,
    rawBytes: utf8(t.statement).length,
    normalisedBytes: utf8(normalised).length,
    // the join key, both ways: uuidna's own uuid form, and a plain sha256 of the normalised bytes so a peer
    // whose framing differs can still join on something neither side had to agree about first
    address: propositionAddress(normalised),
    sha256: hex(sha256(utf8(normalised))),
  }
})

const census = propositionCensus(THEOREMS.map((t) => t.statement))
const out = {
  note: 'GENERATED by scripts/gen-statement-fixture from the sealed ledger, in one pass. Nothing here was typed. '
    + 'Compare normalisedLength FIRST: it separates "we hashed different bytes" from "we hashed the same bytes '
    + 'differently", and only the first is a normalisation disagreement.',
  rule: 'src/proposition-address.ts — normaliseProposition. NFC, collapse whitespace, trim, drop a space unless '
    + 'BOTH sides are identifier characters, fold == to = and != to ≠. It does NOT lowercase: a Lean corpus is '
    + 'case-load-bearing, so Nat and nat must not merge.',
  addressForm: 'address = toUuid("proposition:" + normalised); sha256 = sha256(utf8(normalised)) — both emitted '
    + 'so a peer can join on whichever framing it already computes, without either side adopting the other\'s untested.',
  theorems: rows.length,
  distinctStatements: census.statements,
  distinctPropositions: census.propositions,
  mergedGroups: census.merged.length,
  rows,
}

const PATH = 'docs/public/statement-addresses.json'
writeFileSync(join(ROOT, PATH), JSON.stringify(out, null, 1) + '\n')
console.log(`✓ gen-statement-fixture — ${rows.length} statements → ${PATH} (${census.propositions} distinct propositions, ${census.merged.length} merge groups)`)
