#!/usr/bin/env node
// src/scripts/gen-matrix-css.ts — docs/.vitepress/theme/computed.css: THE ONE DESIGN MATRIX, as a stylesheet the
// site loads rather than a script it runs.
//
// WHY THIS FILE EXISTS. The matrix was already computed (src/css.ts) and already reached the browser — palette.ts
// called matrixVars() and matrixEffects() from enhanceApp and wrote 31 custom properties onto the root element plus
// a <style id="uuidna-matrix"> of 3,060 bytes. Measured on the live site 2026-09-20 it was all there, and all of it
// arrived AFTER JavaScript: zero occurrences of --seq-1 in the served HTML, zero in the served stylesheet. So the
// first paint, a reader with JavaScript off, and any server-rendered element using var(--seq-N) without a fallback
// got none of it. A design matrix that only exists after hydration is not the site's design matrix; it is a
// decoration applied to one.
//
// AND IT HID A DRIFT. The same measurement found the browser painting --seq-1: hsl(320 66% 55%) while this tree's
// dist and the hosted uuidna_css door both computed hsl(336 66% 55%) — the deployed bundle was older than the
// source, and nothing compared them, although css.ts states the contract in its own words: two surfaces rendering
// the same matrix compute the same receipt. Generated into the tree, the file is diff-gated by the chain like every
// other derived surface, so the same staleness becomes a failing reconcile instead of a colour nobody checked.
//
// ONE WRITER. These custom properties now have exactly one author — this file. palette.ts no longer sets them, so
// there is no second hand to drift from.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { matrixCss } from '../css.js'

const m = matrixCss()
const head = [
  '/* GENERATED by src/scripts/gen-matrix-css.ts from src/css.ts — do not edit.',
  ' *',
  ' * ' + m.honest,
  ' *',
  ' * vars ' + m.vars + ' · receipt ' + m.receipt,
  ' *',
  ' * The receipt folds this exact text. A surface serving a different receipt is serving a different matrix, which',
  ' * is the whole point of computing it: uuidna_css answers the same bytes to any client that asks.',
  ' */',
  '',
].join('\n')

writeFileSync(join(ROOT, 'docs/.vitepress/theme/computed.css'), head + m.css)
console.log(`✓ gen-matrix-css — ${m.vars} vars + effects → docs/.vitepress/theme/computed.css, receipt ${m.receipt}`)
