#!/usr/bin/env node
// Generate the handle → route map the edge worker resolves ON THE SPOT — the FIRST PART (first 8 hex) of each
// freeze-map subject's content-address mapped to its editorial route. So /<handle> redirects to /theorem/<key>,
// /publications/<slug>, or any static page (incl. homepage) with ZERO static handle pages and almost no memory.
//
// Covers ALL seo-freeze kinds (theorem | publication | page) — not theorems-only — so homepage/pub handles do not 404.
// The first 8 hex are UNIQUE across the freeze map; this asserts it and throws on any collision.
// Regenerated on every build (wrangler's [build] step), so it never drifts.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { buildSeoUrlMap } from '../seo-freeze.js'
import { ROOT } from './api.js'

const map = buildSeoUrlMap()
const routes: Record<string, string> = {}
for (const e of map.entries) {
  const prev = routes[e.handle]
  if (prev !== undefined && prev !== e.route) {
    throw new Error(
      `gen-handles: handle COLLISION on ${e.handle}: ${prev} vs ${e.route} — worker cannot route uniquely`,
    )
  }
  routes[e.handle] = e.route
}
const n = Object.keys(routes).length
if (n !== map.entries.length) {
  throw new Error(
    `gen-handles: first-8 handle COLLISION — ${map.entries.length} freeze entries but only ${n} distinct handles`,
  )
}
const byKind = { theorem: 0, publication: 0, page: 0 }
for (const e of map.entries) byKind[e.kind]++

writeFileSync(
  join(ROOT, 'handles.js'),
  '// GENERATED by scripts/gen-handles — first 8 hex of each freeze-map content-address → editorial route.\n' +
    '// worker.js resolves /<handle> → route on the spot (theorem | publication | page). First-8 uniqueness verified.\n' +
    'export default ' + JSON.stringify(routes) + '\n',
)
console.log(
  `wrote handles.js — ${n} handle→route entries ` +
    `(theorem ${byKind.theorem}, publication ${byKind.publication}, page ${byKind.page}; first-8 unique)`,
)
// sibling runner — seo-freeze-audit must be exercised (use-versus-mention); handles and freeze are one door
const audit = spawnSync(process.execPath, [join(ROOT, 'dist/scripts/seo-freeze-audit.js')], { stdio: 'inherit' })
if (audit.status !== 0) process.exit(audit.status ?? 1)
