#!/usr/bin/env node
// gen-missions — THE MISSION BOARD, derived (lead 224): docs/missions.md and the slice the hosted edge serves it from.
//
// One source, two shapes, no hand-kept copy. The page and uuidna_missions both call missionsOf() over the same
// three records — the shipped rosetta mirror (rows), the sealed bound census (lean/bound-census.json, baked here
// into src/school/missions/generated.ts because a Worker has no filesystem), and the findings already carried in
// source (research-ledger.ts). The captain is read from docs/captain-claims.json, never typed.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { mirrorRows } from '../rosetta-legs.js'
import { FINDINGS } from '../research-ledger.js'
import { missionsOf, innovationPathOf, MISSION_KINDS, type BoundSlice, type BoundRow, type MissionKind } from '../school/missions/index.js'
import { theorems, ledgerFacts } from '../theorems/index.js'
import { pageSafe } from '../quantum/advantage/page/safe/index.js'

const census = JSON.parse(readFileSync(join(ROOT, 'lean', 'bound-census.json'), 'utf8')) as { digest: string; rows: (BoundRow & { statement?: string })[] }
const claims = JSON.parse(readFileSync(join(ROOT, 'docs', 'captain-claims.json'), 'utf8')) as { captain_authority: string }
const slice: BoundSlice = { digest: census.digest, rows: census.rows.map(({ key, wing, verdict }) => ({ key, wing, verdict })) }

writeFileSync(join(ROOT, 'src', 'school', 'missions', 'generated.ts'), `// src/school/missions/generated.ts — GENERATED by scripts/gen-missions from lean/bound-census.json and
// docs/captain-claims.json. Do not edit. Regenerate with \`npm run x -- gen-missions\`; the reconcile chain runs it.
import type { BoundSlice } from './index.js'

export const BOUND_SLICE: BoundSlice = ${JSON.stringify(slice, null, 1)}
export const MISSION_CAPTAIN = ${JSON.stringify(claims.captain_authority)}
`)

const board = missionsOf({ rows: mirrorRows(), bounds: slice, findings: FINDINGS, captain: claims.captain_authority, forged: ledgerFacts().forged })
// NO LEAD REMAINS UNTAGGED — the type already refuses a row without a tag; this is the same law at the one place the
// board is written, so a generated slice can never carry a row the compiler did not see.
{
  const untagged = board.missions.filter((m) => !['crossed', 'uncrossed', 'open'].includes(m.tag))
  if (untagged.length) throw new Error(`gen-missions: ${untagged.length} lead(s) carry no tag — nothing written`)
  const sum = board.byTag.crossed + board.byTag.uncrossed + board.byTag.open
  if (sum !== board.total) throw new Error(`gen-missions: the tag census (${sum}) and the board (${board.total}) disagree — nothing written`)
  console.log(`  leads tagged: ${board.byTag.crossed} crossed · ${board.byTag.uncrossed} uncrossed · ${board.byTag.open} open — of ${board.total}`)
}
const clean = (s: string): string => pageSafe(s.replace(/`/g, ''))
const HEAD: Record<MissionKind, [string, string]> = {
  'seal-finding': ['Seal a finding', 'a read primary source whose value no theorem seals yet — the theorem is the deliverable'],
  'decide-bound': ['Decide a bound', 'a finite domain that survived one widening step — a person decides whether it is the real domain (name it) or decorative (drop it); the instrument cannot'],
  'symbol-leg': ['Give a theorem its symbol leg', 'a sealed Lean line with no TypeScript mirror in the wing emitter — the computation the proof is checked against'],
}
const links = (keys: readonly string[]): string => {
  const shown = keys.slice(0, 12).map((k) => `[\`${k}\`](/theorem/${k})`).join(' · ')
  return keys.length > 12 ? `${shown} · +${keys.length - 12} more in the wing` : shown
}
const sections = MISSION_KINDS.map((kind) => {
  const rows = board.missions.filter((m) => m.kind === kind)
  const [h, why] = HEAD[kind]
  // THE TAG, ON THE ROW, where a reader meets it — the slice carries it and the page must too, or an uncrossed
  // lead reads on this page exactly like a crossed one, which is the invisibility the captain's law forbids
  const tagOf = (m: typeof rows[number]): string =>
    `${m.tag === 'crossed' ? '✓' : m.tag === 'uncrossed' ? '✗' : '○'} ${m.tag} — ${m.cross.legs.map((l) => `${l.holds ? '✓' : '✗'} ${l.leg}`).join(' · ')} · fused \`${m.cross.receipt.slice(0, 13)}…\``
  const body = rows.map((m) =>
    `- **\`${m.handle}\`** ${clean(m.title)}\n  <br><small>${tagOf(m)}</small>\n  <br><small>deliverable: ${clean(m.deliverable)}</small>` +
    (m.keys.length ? `\n  <br><small>covers: ${links(m.keys)}</small>` : '') +
    `\n  <br><small>door: ${clean(m.door)}</small>`).join('\n')
  return `## ${h} — ${rows.length} open\n\n_${why}._\n\n${body || '_none open — every record of this kind is closed_'}`
}).join('\n\n')

// FROM SKILL TO OPEN WORK: the school's curriculum (the ledger by skill) meets this board at the wing, both derived
const path = innovationPathOf(board.missions, theorems())
const routes = path.skills.filter((s) => s.missions > 0)
const pathSection = `## From skill to open work — ${routes.length} skills lead to a mission

_Practise a skill at [the school](/school), then take a mission in a wing that skill lives in: that is how a learner
becomes a contributor. Each row is derived from the ledger by skill and from this board, meeting at the wing. The
${path.unrouted.length} unrouted missions are research findings, named above: their theorem is the deliverable itself.
Ask for one skill's missions with [\`uuidna_missions\`](/mcp#uuidna-missions) and \`{skill}\`._

| Skill | Theorems | Wings | Open missions | Start with |
| --- | ---: | ---: | ---: | --- |
${routes.map((s) => `| ${clean(s.skill)} | ${s.theorems} | ${s.wings} | ${s.missions} | \`${s.first}\` |`).join('\n')}`

const page = `---
title: Missions
description: The mission board, derived — open work with an exact deliverable, one row per record a person can close, claimed through the served doors.
---

# Missions <Badge type="tip" :text="'${board.total} open'" />

> **Silence never refutes** ([\`silence_never_refutes\`](/theorem/silence_never_refutes)): an open record is a
> notice, not a defeat. Each row below is one — a finding nothing seals, a bound one step short of a verdict, a
> theorem without its symbol leg — with the deliverable that closes it and the door the deposit goes through
> ([\`denial_drains_to_the_last_coin\`](/theorem/denial_drains_to_the_last_coin)).

**${board.total} missions** — ${MISSION_KINDS.map((k) => `${board.byKind[k]} ${k}`).join(' · ')} — derived from the
rosetta mirror, the sealed bound census (\`${slice.digest}\`) and the research ledger. The captain of every mission
is the paying handle \`${board.captain}\`: a mission is claimed by DEPOSITING, never by a form — run
[\`uuidna_trial\`](/mcp#uuidna-trial) on your statement, contribute the seal through
[\`uuidna_agent_contribute\`](/mcp#uuidna-agent-contribute), and the board regrows without the row on the next pass.
The same board is served live as [\`uuidna_missions\`](/mcp#uuidna-missions).

**No lead remains untagged** — ${board.byTag.crossed} crossed · ${board.byTag.uncrossed} uncrossed · ${board.byTag.open} open.
Each row carries the verdict of its own cross formula, decided by the doors this tree serves and fused to one receipt:
_crossed_ reads the same from the other side; _uncrossed_ failed a leg after the effort the record shows (a primary
source that could not be read, a forensic violation, an address that does not recompute) — the class to distrust, kept
and marked rather than deleted; _open_ owes its second leg, and that leg is the mission.

${pathSection}

${sections}

## Honest scope

${board.honest}
`
writeFileSync(join(ROOT, 'docs', 'missions.md'), page)
console.log(`✓ gen-missions — docs/missions.md: ${board.total} missions (${MISSION_KINDS.map((k) => `${k} ${board.byKind[k]}`).join(', ')}); slice ${slice.digest} → src/school/missions/generated.ts`)
