#!/usr/bin/env node
// Generate the handle → key map the edge worker resolves ON THE SPOT — the FIRST PART (first 8 hex) of each
// theorem's content-address mapped to its key. So /<handle> redirects to /theorem/<key> with ZERO static pages and
// almost no memory (a ~30 KB string map, not 888 HTML files) — the "compute at spot / optimise the bill" shape.
// The first 8 hex are UNIQUE across the ledger; this asserts it and throws on any collision, so the map can never
// silently point two proofs at one door. Regenerated on every build (wrangler's [build] step), so it never drifts.
// The full uuid is never emitted here — only its first part is the key; the rest recomputes from the proof.
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { theorems } from '../index.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..')
const T = theorems()
const map: Record<string, string> = {}
for (const t of T) map[t.address.slice(0, 8)] = t.key
const n = Object.keys(map).length
if (n !== T.length) throw new Error(`gen-handles: first-8 handle COLLISION — ${T.length} theorems but only ${n} distinct handles; the worker cannot route them uniquely.`)
writeFileSync(
  join(ROOT, 'handles.js'),
  '// GENERATED by scripts/gen-handles — the first 8 hex of each theorem content-address → its key. The edge worker\n' +
  '// (worker.js) resolves /<handle> → /theorem/<key> on the spot; no static pages. First-8 uniqueness is verified.\n' +
  'export default ' + JSON.stringify(map) + '\n',
)
console.log(`wrote handles.js — ${n} handle→key entries (first-8 unique, ${T.length} theorems)`)
