#!/usr/bin/env node
// gen-edge-slices — bake what the hosted edge cannot read (package.json, wrangler.toml, packages/, the minted receipts)
// into src/edge-slices/generated.ts from the live files. Runs after gen-receipts, whose receipts it carries; a bake
// that lags its source fails src/edge-slices/index.test.ts with this command.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { workspacePackages } from '../npm-pack.js'
import { edgeSlicesOf } from '../edge-slices/index.js'

const read = (rel: string): string => readFileSync(join(ROOT, rel), 'utf8')
const slices = edgeSlicesOf({
  pkg: JSON.parse(read('package.json')),
  wrangler: read('wrangler.toml'),
  workspaces: workspacePackages(),
  receipt: (name) => JSON.parse(read(`lean/${name}-receipt.json`)),
})

const body = `// src/edge-slices/generated.ts — GENERATED by scripts/gen-edge-slices from package.json, wrangler.toml, packages/ and
// the minted receipts. Do not edit. Regenerate with \`npm run x -- gen-edge-slices\`; the generate chain runs it after gen-receipts.
import type { EdgeSlices } from './index.js'

export const EDGE_SLICES: EdgeSlices = ${JSON.stringify(slices, null, 1)}
`
writeFileSync(join(ROOT, 'src', 'edge-slices', 'generated.ts'), body)
console.log(`✓ gen-edge-slices — ${slices.package.dependencies.length} runtime · ${slices.package.devDependencies.length} dev deps · ` +
  `${slices.workspaces.length} workspaces · receipts ${Object.keys(slices.receipts).join(', ')} → src/edge-slices/generated.ts`)
