#!/usr/bin/env node
// gen-packages — THE SPLIT IS COMPUTED, NEVER AUTHORED: uuidna/uuidna splits to uuidna/<package> as quantum
// automation. The ONE export surface (src/index.ts) is the single source; a PARTITION maps each root module to its
// package (crypto / ledger / research / quantum / mcp / edge — a module absent from the partition stays root-only);
// this script derives every packages/<name>/src/index.ts from that surface IN ORDER, re-pointed at '@uuidna/uuidna'
// (one implementation, one owner, no fork of the bytes). Each generated surface folds to its content-address and all
// of them fold ORDER-INVARIANTLY (merkleGravity) to ONE packages receipt — the same receipt for every observer.
// `--verify` recomputes and hard-rejects drift (the any-manual-fails law applied to the split): a hand edit to a
// package surface fails the guard exactly like a hand edit to the ledger. Add an export to src/index.ts and the
// owning package gains it on the next `npm run gen:packages` — the split tracks the surface, not the author.
// Deterministic and offline: no clock, no RNG, nothing but the bytes of index.ts. Integrity, not truth.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toUuid, merkleGravity } from '../index.js'
import { ROOT } from './api.js'

const VERIFY = process.argv.includes('--verify')

// the PARTITION — root module specifier → owning package. A module not named here stays root-only (the umbrella
// exports everything; a package is a domain-scoped view). One specifier, one owner: the partition is a function.
const PARTITION: Record<string, string> = {
  // crypto — primitives, envelope, streams, contracts, provenance-by-hash, the exploit fold, the cube challenge
  './sha256.js': 'crypto', './chacha.js': 'crypto', './crypt.js': 'crypto', './stream.js': 'crypto',
  './contract.js': 'crypto', './provenance.js': 'crypto', './exploit-fold.js': 'crypto', './cube.js': 'crypto',
  // ledger — the sealed theorems and every gate standing on them
  './address.js': 'ledger', './merkle.js': 'ledger', './gate.js': 'ledger', './prose-gate.js': 'ledger',
  './slimgate.js': 'ledger', './adjudicate.js': 'ledger', './sign.js': 'ledger', './due-process.js': 'ledger',
  './verify-statement.js': 'ledger', './fingerprint.js': 'ledger', './laws.js': 'ledger', './captain/credits/index.js': 'ledger',
  './conformance.js': 'ledger', './treason.js': 'ledger', './axiom-witness.js': 'ledger', './anti-fraud.js': 'ledger',
  './forensics.js': 'ledger', './evidence.js': 'ledger', './captain/trial/deposit/index.js': 'ledger', './security-audit.js': 'ledger',
  './captain/billing/index.js': 'ledger', './theorems/index.js': 'ledger',
  // research — recomputable research, corroboration, publications, external anchors
  './research.js': 'research', './corroborate.js': 'research', './books.js': 'research', './publish.js': 'research',
  './reporter.js': 'research', './priorart.js': 'research', './anchor.js': 'research', './constants.js': 'research',
  './cve.js': 'research', './vocab.js': 'research', './transform.js': 'research', './reason.js': 'research',
  './reflects.js': 'research',
  // quantum — the exact simulator, messages/voting, the sailing fleet, the folds, the provenance boundary
  './quantum/index.js': 'quantum', './gravity.js': 'quantum', './diamond.js': 'quantum', './holofractal.js': 'quantum',
  './pentagram-stream.js': 'quantum', './pentagram-monographs.js': 'quantum', './cycles.js': 'quantum',
  './aura.js': 'quantum', './domain-wave.js': 'quantum', './quantum/message/index.js': 'quantum',
  './quantum/voting/index.js': 'quantum', './desk/sailing/library/index.js': 'quantum', './desk/news/portal/index.js': 'quantum',
  './desk/news/domains/index.js': 'quantum', './desk/sailing/weather/index.js': 'quantum', './desk/sailing/cross/book/index.js': 'quantum',
  './desk/sailing/complete/index.js': 'quantum', './analytics.js': 'quantum', './os/alpine/index.js': 'quantum',
  './drivers/driver/index.js': 'quantum',
  // mcp — the server's I/O boundary (the bin re-serves the root server)
  './sanitize.js': 'mcp', './harness.js': 'mcp',
  // edge — the deployment surface
  './cloudflare.js': 'edge', './site.js': 'edge', './seo.js': 'edge', './oeapi.js': 'edge', './render.js': 'edge',
  './school-apis.js': 'research',
  './editor.js': 'edge', './payload-seed.js': 'edge', './profile.js': 'edge', './social.js': 'edge',
}

// each package's header — the domain, its honest scope, and the generated banner (the author is this script)
const BANNER = '// GENERATED by src/scripts/gen-packages.ts — DO NOT EDIT: the split is computed from src/index.ts\n// (the one export surface). Regenerate with `npm run gen:packages`; the guard hard-rejects drift.\n'
const HEADERS: Record<string, string> = {
  crypto: '// @uuidna/crypto — the CRYPTO SURFACE of uuidna: pure-TS SHA-256 / HMAC / PBKDF2, ChaCha20-Poly1305\n// (RFC 8439, KAT-verified), the 7d-fold envelope, onion-sealed uuid streams, contract seals, byte-level\n// provenance, the exploit fold, and the quantum-cube challenge. Integrity, not truth.\n',
  ledger: '// @uuidna/ledger — the SEALED THEOREM LEDGER and every gate that stands on it: the content-address core,\n// merkle proofs, the honesty gates (slimGate / computes / overreachOf), the trial, commit signing, anti-fraud,\n// forensics, conformance, treason, the ledger fingerprint, laws, credits, and the billing coins. A claim is\n// judged solely by whether the theorems it cites are sealed here. Integrity, not truth.\n',
  research: '// @uuidna/research — RECOMPUTABLE RESEARCH: deep research through the imprint codec, corroboration and\n// publication scans, book/movie/record/standard audits, gated publications, the reporter’s method, prior art,\n// the NIST beacon anchor, CODATA constants, CVE fingerprints, the vocabulary, transform-until-verified, the\n// reasoner, and reflections. Provenance and structure, never meaning. Integrity, not truth.\n',
  quantum: '// @uuidna/quantum — the CLASSICAL, EXACT quantum surface: the Gaussian-integer state-vector simulator\n// (honestly bounded — the exact classical 2^n of theorem n_qubit_dimension), quantum messages / voting / receipts, the sailing fleet, the news\n// portals, gravity contractions, the diamond involution, holofractal and pentagram folds, the A432 aura,\n// quantum analytics, and the uuidnaOS provenance boundary (provenance and integrity, NEVER an OS port or\n// execution). Integrity, not truth.\n',
  mcp: '// @uuidna/mcp — the MCP SERVER package: the `uuidna-mcp` stdio bin (re-served from the root dist) plus the\n// I/O boundary the server stands on — the sanitizers and the reeducating harness. Integrity, not truth.\n',
  edge: '// @uuidna/edge — the DEPLOYMENT SURFACE: the Cloudflare bindings audit (committed config, not the live\n// edge), the one navigable site graph, quantum SEO, the theorem renderers, the content-addressed document\n// serializer, and the profile / social cards. Integrity, not truth.\n',
}
const PACKAGES = ['crypto', 'ledger', 'research', 'quantum', 'mcp', 'edge'] as const

// parse the ONE export surface in order; each clause keeps its exact text, re-pointed at the umbrella package
const INDEX = readFileSync(join(ROOT, 'src', 'index.ts'), 'utf8')
const CLAUSE = /export \{[\s\S]*?\} from '(\.\/[^']+)'/g
const lines: Record<string, string[]> = Object.fromEntries(PACKAGES.map((p) => [p, []]))
const rootOnly: string[] = []
for (const m of INDEX.matchAll(CLAUSE)) {
  const [clause, spec] = m
  const pkg = PARTITION[spec]
  if (!pkg) { rootOnly.push(spec); continue }
  lines[pkg].push(clause.replace(`from '${spec}'`, "from '@uuidna/uuidna'"))
}

const generated = PACKAGES.map((pkg) => {
  const content = BANNER + HEADERS[pkg] + lines[pkg].join('\n') + '\n'
  return { pkg, content, address: toUuid(content), path: join(ROOT, 'packages', pkg, 'src', 'index.ts') }
})
const receipt = merkleGravity(generated.map((g) => g.address))

let drift = 0
for (const g of generated) {
  const disk = existsSync(g.path) ? readFileSync(g.path, 'utf8') : null
  const fresh = disk === g.content
  if (VERIFY) {
    if (fresh) console.log(`✓ gen-packages — @uuidna/${g.pkg} matches the computed split (${lines[g.pkg].length} clauses; ${g.address})`)
    else { drift++; console.error(`✗ gen-packages — @uuidna/${g.pkg} DRIFTS from the computed split${disk === null ? ' (missing)' : ''} — run \`npm run gen:packages\``) }
  } else if (!fresh) {
    mkdirSync(dirname(g.path), { recursive: true })
    writeFileSync(g.path, g.content)
    console.log(`✎ gen-packages — @uuidna/${g.pkg} regenerated (${lines[g.pkg].length} clauses; ${g.address})`)
  } else {
    console.log(`✓ gen-packages — @uuidna/${g.pkg} already fresh (${lines[g.pkg].length} clauses; ${g.address})`)
  }
}
console.log(`gen-packages — ${generated.length} packages computed from the one surface; ${rootOnly.length} modules stay root-only; packages receipt ${receipt}`)
if (VERIFY && drift) { console.error(`✗ gen-packages — ${drift} package surface(s) drift; the split is computed, never authored.`); process.exit(1) }
