#!/usr/bin/env node
// Generate the handle → route map the edge worker resolves ON THE SPOT — the FIRST PART (first 8 hex) of each
// freeze-map subject's content-address mapped to its editorial route. So /<handle> redirects to /theorem/<key>,
// /publications/<slug>, or any static page (incl. homepage) with ZERO static handle pages and almost no memory.
//
// Covers ALL seo-freeze kinds (theorem | publication | page) — not theorems-only — so homepage/pub handles do not 404.
// A first-8 that binds two editorial routes is OMITTED: unknown → 404, never a wrong page (worker.js). Past the
// birthday point that omission is the capacity speaking (theorem message_carries_address), not a generator failure.
// Regenerated on every build (wrangler's [build] step), so it never drifts.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { buildSeoUrlMap } from '../seo-freeze.js'
import { handleBirthdayPoint, uniqueHandleRouteMap } from '../handle.js'
import { ROOT } from './api.js'

const map = buildSeoUrlMap()
const { routes, collisions } = uniqueHandleRouteMap(map.entries)
if (collisions.length) {
  const bound = handleBirthdayPoint()
  console.log(
    `gen-handles — ${collisions.length} first-8 collision(s); ${map.entries.length} freeze entries against birthday ${bound}. ` +
      `Omitting from the unique worker map (never a wrong page):`,
  )
  for (const c of collisions) console.log(`  ${c.handle}: ${c.routes.join(' vs ')}`)
}
const n = Object.keys(routes).length
const byKind = { theorem: 0, publication: 0, page: 0 }
for (const e of map.entries) byKind[e.kind]++

writeFileSync(
  join(ROOT, 'handles.js'),
  '// GENERATED by scripts/gen-handles — first 8 hex of each freeze-map content-address → editorial route.\n' +
    '// worker.js resolves /<handle> → route on the spot (theorem | publication | page). Colliding first-8 doors are omitted.\n' +
    'export default ' + JSON.stringify(routes) + '\n',
)
console.log(
  `wrote handles.js — ${n} unique handle→route entries ` +
    `(theorem ${byKind.theorem}, publication ${byKind.publication}, page ${byKind.page}; ` +
    `${collisions.length} colliding door(s) omitted)`,
)
// sibling runner — seo-freeze-audit must be exercised (use-versus-mention); handles and freeze are one door
const audit = spawnSync(process.execPath, [join(ROOT, 'dist/scripts/seo-freeze-audit.js')], { stdio: 'inherit' })
if (audit.status !== 0) process.exit(audit.status ?? 1)
