#!/usr/bin/env node
// gen-missions — THE MISSION BOARD, derived (lead 224): docs/missions.md and the slice the hosted edge serves it from.
//
// One source, two shapes, no hand-kept copy. The page and uuidna_missions both call missionsOf() over the same
// three records — the shipped rosetta mirror (rows), the sealed bound census (lean/bound-census.json, baked here
// into src/school/missions/generated.ts because a Worker has no filesystem), and the findings already carried in
// source (research-ledger.ts). The captain is read from docs/captain-claims.json, never typed.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { mirrorRows } from '../rosetta-legs.js'
import { FINDINGS } from '../research-ledger.js'
import { missionsOf, MISSION_KINDS, type BoundSlice, type BoundRow, type MissionKind } from '../school/missions/index.js'
import { pageSafe } from '../quantum/advantage/page/safe/index.js'

const census = JSON.parse(readFileSync(join(ROOT, 'lean', 'bound-census.json'), 'utf8')) as { digest: string; rows: (BoundRow & { statement?: string })[] }
const claims = JSON.parse(readFileSync(join(ROOT, 'docs', 'captain-claims.json'), 'utf8')) as { captain_authority: string }
const slice: BoundSlice = { digest: census.digest, rows: census.rows.map(({ key, wing, verdict }) => ({ key, wing, verdict })) }

writeFileSync(join(ROOT, 'src', 'school', 'missions', 'generated.ts'), `// src/school/missions/generated.ts — GENERATED by scripts/gen-missions from lean/bound-census.json and
// docs/captain-claims.json. Do not edit. Regenerate with \`npm run x -- gen-missions\`; the reconcile chain runs it.
import type { BoundSlice } from './index.js'

export const BOUND_SLICE: BoundSlice = ${JSON.stringify(slice, null, 1)}
export const MISSION_CAPTAIN = ${JSON.stringify(claims.captain_authority)}
`)

const board = missionsOf({ rows: mirrorRows(), bounds: slice, findings: FINDINGS, captain: claims.captain_authority })
const clean = (s: string): string => pageSafe(s.replace(/`/g, ''))
const HEAD: Record<MissionKind, [string, string]> = {
  'seal-finding': ['Seal a finding', 'a read primary source whose value no theorem seals yet — the theorem is the deliverable'],
  'decide-bound': ['Decide a bound', 'a finite domain that survived one widening step — a person decides whether it is the real domain (name it) or decorative (drop it); the instrument cannot'],
  'symbol-leg': ['Give a theorem its symbol leg', 'a sealed Lean line with no TypeScript mirror in the wing emitter — the computation the proof is checked against'],
}
const links = (keys: readonly string[]): string => {
  const shown = keys.slice(0, 12).map((k) => `[\`${k}\`](/theorem/${k})`).join(' · ')
  return keys.length > 12 ? `${shown} · +${keys.length - 12} more in the wing` : shown
}
const sections = MISSION_KINDS.map((kind) => {
  const rows = board.missions.filter((m) => m.kind === kind)
  const [h, why] = HEAD[kind]
  const body = rows.map((m) =>
    `- **\`${m.handle}\`** ${clean(m.title)}\n  <br><small>deliverable: ${clean(m.deliverable)}</small>` +
    (m.keys.length ? `\n  <br><small>covers: ${links(m.keys)}</small>` : '') +
    `\n  <br><small>door: ${clean(m.door)}</small>`).join('\n')
  return `## ${h} — ${rows.length} open\n\n_${why}._\n\n${body || '_none open — every record of this kind is closed_'}`
}).join('\n\n')

const page = `---
title: Missions
description: The mission board, derived — open work with an exact deliverable, one row per record a person can close, claimed through the served doors.
---

# Missions <Badge type="tip" :text="'${board.total} open'" />

> **Silence never refutes** ([\`silence_never_refutes\`](/theorem/silence_never_refutes)): an open record is a
> notice, not a defeat. Each row below is one — a finding nothing seals, a bound one step short of a verdict, a
> theorem without its symbol leg — with the deliverable that closes it and the door the deposit goes through
> ([\`denial_drains_to_the_last_coin\`](/theorem/denial_drains_to_the_last_coin)).

**${board.total} missions** — ${MISSION_KINDS.map((k) => `${board.byKind[k]} ${k}`).join(' · ')} — derived from the
rosetta mirror, the sealed bound census (\`${slice.digest}\`) and the research ledger. The captain of every mission
is the paying handle \`${board.captain}\`: a mission is claimed by DEPOSITING, never by a form — run
[\`uuidna_trial\`](/mcp#uuidna-trial) on your statement, contribute the seal through
[\`uuidna_agent_contribute\`](/mcp#uuidna-agent-contribute), and the board regrows without the row on the next pass.
The same board is served live as [\`uuidna_missions\`](/mcp#uuidna-missions).

${sections}

## Honest scope

${board.honest}
`
writeFileSync(join(ROOT, 'docs', 'missions.md'), page)
console.log(`✓ gen-missions — docs/missions.md: ${board.total} missions (${MISSION_KINDS.map((k) => `${k} ${board.byKind[k]}`).join(', ')}); slice ${slice.digest} → src/school/missions/generated.ts`)
