#!/usr/bin/env node
// gen-refusals — THE REFUSALS REGISTER AS AN IMPORTABLE MODULE, so the hosted edge can serve it.
//
// uuidna_refusals is served at uuidna.com/mcp, and a Worker has no filesystem: the census read lean/leads.json
// through scripts/api.ts, whose builtins resolve lazily through process.getBuiltinModule, so the tool loaded at the
// edge and threw `process is not defined` on its first call — while every local test passed, because every local
// test runs on Node. This writes the slice the census needs to src/school/refusals/generated.ts, exactly as
// gen-references writes src/references-resolved.ts and gen-cloudflare-templates writes its data module: one
// source, two shapes, no hand-kept copy. src/school/refusals/index.test.ts holds the module to the live record.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { refusalSliceOf, type LeadsRecord } from '../school/refusals/slice.js'

const record = JSON.parse(readFileSync(join(ROOT, 'lean', 'leads.json'), 'utf8')) as LeadsRecord
const slice = refusalSliceOf(record)

const body = `// src/school/refusals/generated.ts — GENERATED by scripts/gen-refusals from lean/leads.json. Do not edit.
// The refusals register as a module, so the hosted edge (no filesystem) serves uuidna_refusals from the same rows
// the stdio server does. Regenerate with \`npm run x -- gen-refusals\`; the reconcile chain runs it on every pass.
import type { RefusalSlice } from './slice.js'

/** the refused leads with their boundaries, and the refusals later withdrawn with what overturned them */
export const REFUSAL_SLICE: RefusalSlice = ${JSON.stringify(slice, null, 1)}
`
writeFileSync(join(ROOT, 'src', 'school', 'refusals', 'generated.ts'), body)
console.log(`✓ gen-refusals — ${slice.refused.length} refused · ${slice.withdrawn.length} withdrawn → src/school/refusals/generated.ts`)
