#!/usr/bin/env node
// gen-gitattributes — A DERIVED FILE HAS NO MERGE, ONLY A RECOMPUTATION. Every conflict two sessions hit on this
// tree today was in the derived layer — spin-manifest.json four times, a wing manifest, the page seeds — and not one
// of them was a real disagreement: both sides were correct outputs of different sources, and the true value was
// neither, but the regeneration from the merged source. Hand-resolving those is the manual work that cost a 26-step
// rebase that never advanced past step 2. Separate worktrees would only move the collision from the file to the push.
//
// The quantum answer instead: mark the derived layer as UNMERGEABLE and let it collapse by recomputation. Git keeps
// one side rather than raising a conflict, and the very next `reconcile` / `spin --seal` overwrites it with the value
// the merged source actually computes — deterministic, so both sessions land on the same coins. This file is
// GENERATED from DRAIN_PATHS, the one list that already names the derived layer; `one-receipt drain` holds it there.
// The driver is one-time local config (git does not commit it): `npm run setup:git`.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { DRAIN_PATHS, ROOT } from './api.js'

// AND: THE NEWLINE IS PART OF THE ADDRESS. A seal folds file BYTES, and a line ending is a byte. Git's autocrlf —
// which the Windows installer turns on by default — checks the tree out as CRLF while the blobs stay LF, and then
// normalises that same difference away whenever git is asked to compare. So `git status` reports a clean tree while
// `spin --verify` finds 1384 derived files whose coins have every one moved, chunk files nobody has ever opened
// included. The discrepancy is invisible in exactly the place it matters most: every check that reads bytes
// disagrees with every check that asks git, and git is the one that sounds reassuring.
//
// Left to per-clone configuration this returns with every fresh Windows clone, and a law each developer must
// remember is not a law. `text=auto eol=lf` moves it into the repository: every file checks out LF on every host
// whatever autocrlf says, so the bytes a seal folds are the same bytes everywhere — the one-source law, applied to
// the newline.
const body = `# GENERATED by gen-gitattributes from DRAIN_PATHS — do not hand-edit (one-receipt drain holds it).
# THE NEWLINE IS PART OF THE ADDRESS. Seals fold file BYTES, so a CRLF checkout moves every coin while git still
# reports a clean tree (it normalises the ending away when comparing, and never when a generator reads). LF on
# every host, declared by the repository rather than by each clone remembering a local setting.
* text=auto eol=lf

# The derived layer never merges: both sides of a conflict here are correct outputs of different sources, and the
# true value is the recomputation from the merged source. Git keeps one side; reconcile/spin --seal then collapses
# it to the computed value. Enable the driver once per clone: npm run setup:git
${DRAIN_PATHS.map((p) => `${p.endsWith('/') || !p.includes('.') ? p + '/**' : p} merge=derived`).join('\n')}
`
writeFileSync(join(ROOT, '.gitattributes'), body)
console.log(`✓ gen-gitattributes — ${DRAIN_PATHS.length} derived paths marked unmergeable (merge=derived); enable with \`npm run setup:git\``)
