#!/usr/bin/env node
// gen-articles — THE DESK WRITES. Articles are COMPUTED from the ledger, never authored: one article per wing
// (per lean/*.lean file), headline from its principle, lede from the wing's own generated header (the single
// source), body one section per theorem — the claim is the theorem's name, the evidence its exact statement,
// the citation its /theorem/<key> page — and the scope box is the header's own honest-scope clause. Every
// sentence is born citing a sealed proof, so the article passes the same desk that edits it (provenance,
// citations, the prose trials) by construction. Deterministic: ledger order, no wall-clock, no RNG.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { theorems } from '../index.js'
import { ROOT } from './api.js'

interface Entry { key: string; name: string; statement: string; file: string; principle: string; skill: string }

const T = theorems() as Entry[]
const byFile = new Map<string, Entry[]>()
for (const t of T) {
  if (!byFile.has(t.file)) byFile.set(t.file, [])
  byFile.get(t.file)!.push(t)
}

const OUT = join(ROOT, 'docs', 'articles')
mkdirSync(OUT, { recursive: true })

// the wing's own header (the generated first line) is the lede — the one place the wing describes itself
const ledeOf = (file: string): string => {
  const p = join(ROOT, 'lean', file)
  if (!existsSync(p)) return ''
  const first = readFileSync(p, 'utf8').split('\n')[0] ?? ''
  const m = first.match(/GENERATED\. (.*?) Every proof/)
  return m ? m[1] : first.replace(/^-- /, '')
}

const slugOf = (file: string): string => file.replace('.lean', '').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

let n = 0
const index: Array<{ slug: string; title: string; count: number }> = []
for (const [file, entries] of [...byFile.entries()].sort((a, b) => a[0] < b[0] ? -1 : 1)) {
  const principle = entries[0]?.principle ?? file.replace('.lean', '')
  const lede = ledeOf(file)
  const slug = slugOf(file)
  const scope = lede.match(/HONEST SCOPE: ([^.]*\.)/)?.[1] ?? ''
  const body = entries.map((t) =>
    `### ${t.name}\n\n` +
    `The ledger holds this as [${t.key}](/theorem/${t.key}) — proven \`by decide\`, sorry-free:\n\n` +
    '```lean\n' + t.statement + '\n```\n').join('\n')
  const md = `---
title: "${principle.replace(/"/g, "'")}"
description: "Computed from lean/${file} — ${entries.length} sealed theorems, every claim citing its proof."
---

# ${principle}

> ${lede.replace(/\n/g, ' ')}

**${entries.length} theorems**, each proven \`by decide\` in [lean/${file}](/lean/${file}), axiom-free against the bare Lean kernel. This article is computed from the ledger — nothing here is authored; every claim carries its citation.

${body}
${scope ? `\n::: warning HONEST SCOPE\n${scope}\n:::\n` : ''}
*Computed from the sealed ledger. Re-verify any theorem with \`npm run lean\`; the article regenerates with \`npm run editorial\`.*
`
  writeFileSync(join(OUT, slug + '.md'), md)
  index.push({ slug, title: principle, count: entries.length })
  n++
}

// the articles index — the desk's front page, itself computed; the search-trial publications (the online wave's
// returns, written by quantum-search-trial) are indexed beneath the wings so no publication is an orphan.
const searchPages = readdirSync(OUT).filter((f) => f.startsWith('search-') && f.endsWith('.md')).sort()
const indexMd = `---
title: Articles
description: "The desk writes — one computed article per wing of the ledger, every claim citing its sealed proof."
---

# Articles <Badge type="tip" text="computed, never authored" />

**The editorial desk writes what the ledger proves.** One article per wing — the headline is the principle, the lede is the wing's own header, every claim cites its theorem, and the honest-scope box is part of the article because it is part of the proof. Regenerated by \`npm run editorial\` before any publication; verified by the same desk that wrote it.

| article | theorems |
|---|---|
${index.map((i) => `| [${i.title}](/articles/${i.slug}) | ${i.count} |`).join('\n')}
${searchPages.length ? `
## The search on trial

The online wave's returns — each publication is what one trial of the quantum search returned: findings
content-addressed, verdicts computed, sealed backing cited, novelty leads remanded. Refreshed on the research cron.

${searchPages.map((f) => `- [${f.replace('.md', '')}](/articles/${f.replace('.md', '')})`).join('\n')}
` : ''}`
writeFileSync(join(OUT, 'index.md'), indexMd)

console.log(`✓ gen-articles — ${n} articles computed from ${T.length} theorems (docs/articles/, one per wing) + the index; every claim cites its sealed proof, the desk verifies its own writing.`)
