#!/usr/bin/env node
// Organise by COMPUTING PRINCIPLE — not arbitrary moduli. The framework has two moduli: the RING ℤ/9 (the vortex)
// and the ROSETTE ℤ/7 (the Pliska group). This generates their full multiplication, addition and power tables,
// one `by decide` Lean theorem per cell, into lean/Ring.lean and lean/Rosette.lean — each a computing principle.
// Every fact is COMPUTED (the right-hand side derived, Lean recomputes it). Emits manifests for the microdata UI,
// and verifies both files compile sorry-free. Integrity, not truth.
import { emit } from './lean-gen.js'

function build(n: number, label: string, sym: string, skill: string) {
  const T = []
  for (let a = 0; a < n; a++) for (let b = 0; b < n; b++) {
    T.push({ key: `${sym}mul_${a}_${b}`, stmt: `(${a} * ${b}) % ${n} = ${(a * b) % n}`, name: `${a}·${b} ≡ ${(a * b) % n} (mod ${n})` })
    T.push({ key: `${sym}add_${a}_${b}`, stmt: `(${a} + ${b}) % ${n} = ${(a + b) % n}`, name: `${a}+${b} ≡ ${(a + b) % n} (mod ${n})` })
  }
  for (let a = 0; a < n; a++) for (let k = 2; k <= n; k++) {
    let r = 1; for (let i = 0; i < k; i++) r = (r * a) % n
    T.push({ key: `${sym}pow_${a}_${k}`, stmt: `(${a} ^ ${k}) % ${n} = ${r}`, name: `${a}^${k} ≡ ${r} (mod ${n})` })
  }
  if (n === 7) { // ── decode the Pliska rosette: ℤ/7, seven rays, the units generated by the primitive root 3 ──
    T.push({ key: 'z7rays_seven', stmt: '(List.range 7).length = 7', name: 'the Pliska rosette has SEVEN rays — ℤ/7 = {0,1,2,3,4,5,6}' })
    T.push({ key: 'z7primitive_root_3', stmt: "(List.range' 1 6).map (fun k => (3 ^ k) % 7) = [3, 2, 6, 4, 5, 1]", name: '3 is a primitive root mod 7 — its powers trace the rosette 3→2→6→4→5→1, covering all six units' })
    T.push({ key: 'z7units_sum_21', stmt: '(1 + 2 + 3 + 4 + 5 + 6) = 21', name: 'the six rosette units {1..6} sum to 21 = 3·7 — the rosette closes on the trinity' })
    T.push({ key: 'z7fermat', stmt: '(List.range 7).all (fun a => a % 7 == 0 || (a ^ 6) % 7 == 1)', name: 'Fermat on the rosette: every non-zero ray to the sixth is 1 (mod 7) — the six-fold closes' })
    T.push({ key: 'z7reflection_center', stmt: '(List.range 7).all (fun d => ((7 - (7 - d) % 7) % 7) == d % 7) ∧ ((List.range 7).filter (fun d => (7 - d) % 7 == d)).length = 1', name: 'the rosette reflection d ↦ 7−d is a self-inverse with a single center (0) — the still point of the seven' })
    T.push({ key: 'rosette_pairs_twentyone', stmt: '(7 * 6) / 2 = 21', name: 'the 21 ROSETTE: C(7,2) = 7·6/2 = 21 — the undirected pairs of the seven rays, the edges of the 7-star (the 21-test two-coins guard)' })
    T.push({ key: 'rosette_quantum_fortytwo', stmt: '7 * 6 = 42', name: 'the 42 QUANTUM rosette: made order-sensitive — each pair a DIRECTED merge edge (a↔b becomes a→b and b→a) — the 21 doubles to 7·6 = 42 directed pairs' })
    T.push({ key: 'rosette_quantum_doubling_is_two_coins', stmt: '(2 * 21 = 42) ∧ (2 * 64 = 128) ∧ (110 - 108 = 2)', name: 'QUANTUM DOUBLING IS THE TWO CAPTAIN COINS contributed: the factor 2 (= 110−108, −χ of the double torus) takes the 21 rosette to the 42 quantum rosette AND the 64-bit coin to the 128-bit address — the doubling holds only if the two coins are accounted and contributed' })
  }
  const header = `The ${label === 'Ring' ? 'RING ℤ/9 (the vortex)' : 'ROSETTE ℤ/7 (the Pliska group)'} — its full multiplication, addition and power tables. Each right-hand side is COMPUTED; Lean recomputes it.`
  return emit({ file: label + '.lean', header, facts: T, skill })
}

const ring = build(9, 'Ring', 'z9', 'z9-ring')
const rosette = build(7, 'Rosette', 'z7', 'z7-rosette')
console.log('organised by computing principle: Ring ℤ/9 (' + ring + ') + Rosette ℤ/7 (' + rosette + ') = ' + (ring + rosette) + ' theorems.')
