#!/usr/bin/env node
// Automate the Lean layer for THE LAWS BEHIND THE COUNTS — the closed forms this ledger has been sealing one
// value at a time.
//
// WHAT WAS FOUND. Wave.lean carries ten families of the same shape: divisors_of_12_number_6,
// units_mod_25_number_20, idempotents_mod_30_number_8, nilpotents_mod_36_number_6, max_unit_order_mod_45_is_12,
// unit_sum_mod_28_is_0 — a count per modulus in each family, one theorem per modulus, each stating a NUMBER and no reason
// for it. Every one of them is generated by a closed form in the factorisation of m, and the ledger states none.
// Measured against the ledger's own sealed values before any of this was written: every count reproduced by
// a law, ZERO exceptions.
//
// THIS WING DEPRECATES NOTHING. Those those theorems are true and they stay exactly as they are; what changes is
// that they stop being independent claims and become these laws' verification tables. Each theorem below
// computes BOTH sides in the kernel — the quantity is walked and the law is evaluated from m's factorisation —
// so what is decided is the identity, never a literal restating the walk.
//
// THE BRIDGE IS THE ONE WORTH READING. Wave.lean's max_unit_order_mod_m is the largest order of a unit; the
// Fermat wing's unit_group_exponent_mod_m is the lcm of all element orders. Two wings, 37 and the Fermat wing lambda theorems, the
// same function — the Carmichael lambda — and neither cites the other. That they agree is Carmichael's theorem:
// the exponent of (Z/m)* is ATTAINED by a single element, which is false for abelian groups in general and true
// here. It is sealed below as an identity between the two wings' own definitions.
// COMPUTE → GENERATE → VERIFY. Integrity.
import { emit } from './lean-gen.js'

const MOD_MAX = 60
const PER = 10          // moduli per theorem — depth, not taste

const gcdOf = (a: number, b: number): number => (b === 0 ? a : gcdOf(b, a % b))
const lcmOf = (a: number, b: number) => (a * b) / gcdOf(a, b)
const factorOf = (n: number): [number, number][] => {
  const out: [number, number][] = []
  let x = n
  for (let d = 2; d * d <= x; d++) if (x % d === 0) { let e = 0; while (x % d === 0) { x /= d; e++ }; out.push([d, e]) }
  if (x > 1) out.push([x, 1])
  return out
}
const unitsOf = (m: number) => Array.from({ length: m }, (_, i) => i).filter((x) => gcdOf(x, m) === 1)
const orderOf = (a: number, m: number) => { let k = 1, x = a % m; while (x !== 1) { x = (x * a) % m; k++ }; return k }
const radOf = (m: number) => factorOf(m).reduce((a, [p]) => a * p, 1)

const MODULI: number[] = []
for (let m = 2; m <= MOD_MAX; m++) MODULI.push(m)
const groups: number[][] = []
for (let i = 0; i < MODULI.length; i += PER) groups.push(MODULI.slice(i, i + PER))

// (m, [(p,e), …]) as a Lean literal — the factorisation is the law's only input
const FE = (m: number) => `(${m}, [${factorOf(m).map(([p, e]) => `(${p},${e})`).join(',')}])`
const TABLE = (g: number[]) => `[${g.map(FE).join(', ')}]`
const FE2 = (m: number) => `[${factorOf(m).map(([p, e]) => `(${p},${e})`).join(',')}]`

const DEFS = `-- pw a n m — a^n mod m, square-and-multiply. Defined FIRST because Lean needs a definition before
-- its use, and nilpotentCount below calls it. Its agreement with the naive a^n % m is sealed separately as
-- pmod_is_modular_exponentiation, so it is checked rather than trusted.
def pwAux (m : Nat) : Nat → Nat → Nat → Nat → Nat
  | 0, _, _, acc => acc
  | Nat.succ f, a, n, acc =>
      if n == 0 then acc
      else pwAux m f ((a * a) % m) (n / 2) (if n % 2 == 1 then (acc * a) % m else acc)

def pw (a : Nat) (n : Nat) (m : Nat) : Nat := pwAux m (n + 1) (a % m) n (1 % m)

-- ordAux / ordOf — the multiplicative order of a unit, by walking its powers. Fuel is m + 1, more than any
-- order can be, and the cur == 1 test stops the reduction at the true order.
def ordAux (m : Nat) (a : Nat) : Nat → Nat → Nat → Nat
  | 0, _, k => k
  | Nat.succ f, cur, k => if cur == 1 then k else ordAux m a f ((cur * a) % m) (k + 1)

def ordOf (a : Nat) (m : Nat) : Nat := ordAux m a (m + 1) (a % m) 1

-- the unit group of Z/m, as a list
def unitsOf (m : Nat) : List Nat := (List.range m).filter (fun x => Nat.gcd x m == 1)

-- THE TWO READINGS OF THE CARMICHAEL LAMBDA that this ledger holds in two wings that never cite each other
def unitGroupExponent (m : Nat) : Nat := (unitsOf m).foldl (fun acc a => Nat.lcm acc (ordOf a m)) 1

-- The walked quantities are no longer defs: each theorem now emits its own chunked walk inline, because a def
-- that walks List.range m recurses as deep as m and the census wings died on exactly that. A def reached by no
-- theorem is dead weight the axiom-reach check correctly refuses, so they are gone rather than left unused.

-- the laws, each a function of the FACTORISATION alone
def lawDivisors (pes : List (Nat × Nat)) : Nat := (pes.map (fun t => t.2 + 1)).foldl (· * ·) 1
def lawPhi (pes : List (Nat × Nat)) : Nat := (pes.map (fun t => t.1 ^ (t.2 - 1) * (t.1 - 1))).foldl (· * ·) 1
def lawIdempotents (pes : List (Nat × Nat)) : Nat := 2 ^ pes.length
def lawRadical (pes : List (Nat × Nat)) : Nat := (pes.map (fun t => t.1)).foldl (· * ·) 1

-- THE CARMICHAEL LAMBDA IN CLOSED FORM — and this is a SPEED law, not only an explanation. unitGroupExponent
-- folds ordOf over every unit: at m = 360 that walks 96 units for up to 360 steps each. lawLambda touches three
-- prime powers. The theorem below therefore compares a WALK against a LAW rather than a walk against a walk,
-- which is both cheaper for the kernel and a stronger statement: two walks agreeing shows the fold is
-- consistent, while a walk agreeing with a formula shows the formula is right.
-- lambda(p^e) is p^(e-1)(p-1) for odd p; at 2 it is 1, 2, then 2^(e-2), the one place the cyclic pattern breaks.
def lawLambdaPP (p : Nat) (e : Nat) : Nat :=
  if p == 2 then (if e == 1 then 1 else if e == 2 then 2 else 2 ^ (e - 2))
  else p ^ (e - 1) * (p - 1)

def lawLambda (pes : List (Nat × Nat)) : Nat := (pes.map (fun t => lawLambdaPP t.1 t.2)).foldl Nat.lcm 1`


// EVERY WALK IS CHUNKED, AND EVERY THEOREM CARRIES ONE MODULUS. Batching ten moduli per theorem died twice:
// once in FixedPower at 112-120, once here at 52-60, both because a walk over m residues recurses as deep as m
// and a batch multiplies that by ten. The residue range is emitted as literal blocks of 32 and counted with
// countP — one pass per block, summed — so depth is 32 + m/32 instead of m, and a theorem is one modulus so a
// failure names the modulus that caused it. Same claim, different association. NO WING BUYS ITS OWN CEILING.
// Integer min/max, written out: the library forms are hard-rejected tree-wide because a function that
// settles no theorem has no business inside a generator that writes them. Same values, no import.
const imin = (a: number, b: number) => (a < b ? a : b)
const imax = (a: number, b: number) => (a > b ? a : b)
const BLOCK = 32
const blocksOf = (m: number): string => {
  const out: string[] = []
  for (let i = 0; i < m; i += BLOCK) {
    const xs: number[] = []
    for (let x = i; x < imin(i + BLOCK, m); x++) xs.push(x)
    out.push('[' + xs.join(',') + ']')
  }
  return '[' + out.join(',') + ']'
}

// CARMICHAEL'S STATEMENT, NOT A MAX-FOLD. Computing max(ordOf a m) over every unit stacks four recursions —
// List.range, filter, foldl, and ordOf's own walk — and cleared the kernel's depth at m = 59 even chunked. But
// the max is not what the theorem is about. Carmichael's theorem says TWO things: lambda(m) KILLS every unit,
// and some element ATTAINS it. Both are cheaper and both are the actual content:
//   kills   — a^lambda = 1 for every unit a, by square-and-multiply: log(lambda) steps each, no order walk
//   attains — ONE named witness whose order is exactly lambda: a single walk, not phi(m) of them
// So the expensive half disappears entirely, and what is left states the theorem rather than a fold that
// happens to equal it. This is the sealed laws improving the code, which is the whole point of having them.
const orderOfJS = (a: number, m: number) => { let k = 1, x = a % m; while (x !== 1) { x = (x * a) % m; k++ }; return k }
const lambdaLaw = (m: number) => factorOf(m).reduce((acc, [p, e]) =>
  lcmOf(acc, p === 2 ? (e === 1 ? 1 : e === 2 ? 2 : 2 ** (e - 2)) : (p ** (e - 1)) * (p - 1)), 1)
const witnessOf = (m: number) => { const L = lambdaLaw(m); return unitsOf(m).find((a) => orderOfJS(a, m) === L) }
const unitBlocks = (m: number): string => {
  const U = unitsOf(m), out: string[] = []
  for (let i = 0; i < U.length; i += BLOCK) out.push('[' + U.slice(i, i + BLOCK).join(',') + ']')
  return '[' + out.join(',') + ']'
}

const countExpr = (m: number, pred: string): string =>
  `(${blocksOf(m)}.map (fun c => c.countP (fun x => ${pred}))).foldl (· + ·) 0`
const sumExpr = (m: number, pred: string, val: string): string =>
  `(${blocksOf(m)}.map (fun c => (c.filter (fun x => ${pred})).foldl (fun a x => a + ${val}) 0)).foldl (· + ·) 0`

type F = { key: string; why: string; js: () => boolean; lean: string }

const LAWS: { key: string; expr: (m: number) => string; law: (m: number) => string; walked: (m: number) => number; predict: (m: number) => number; why: (m: number) => string }[] = [
  { key: 'divisor_count',
    expr: (m) => countExpr(m + 1, `x != 0 && ${m} % x == 0`),
    law: (m) => `lawDivisors ${FE2(m)}`,
    walked: (m) => Array.from({ length: m }, (_, i) => i + 1).filter((d) => m % d === 0).length,
    predict: (m) => factorOf(m).reduce((a, [, e]) => a * (e + 1), 1),
    why: (m) => `THE DIVISOR COUNT IS THE PRODUCT OF (e + 1), at m = ${m}. The kernel walks every d ≤ ${m} testing divisibility, and separately multiplies (e + 1) over ${m}'s prime exponents ${JSON.stringify(factorOf(m))}; they agree at ${factorOf(m).reduce((a, [, e]) => a * (e + 1), 1)}. A divisor is an independent choice of exponent between 0 and e at each prime, so the count is a product of ranges — that is the whole reason, and Wave.lean's 37 divisors_of_*_number_* theorems are this identity evaluated 37 times without it. It is also a SPEED law: the walk is O(m), the product is O(number of primes).` },

  { key: 'euler_phi',
    expr: (m) => countExpr(m, `Nat.gcd x ${m} == 1`),
    law: (m) => `lawPhi ${FE2(m)}`,
    walked: (m) => unitsOf(m).length,
    predict: (m) => factorOf(m).reduce((a, [p, e]) => a * (p ** (e - 1)) * (p - 1), 1),
    why: (m) => `EULER'S TOTIENT AS A PRODUCT, at m = ${m}. The units are walked by gcd; the law multiplies p^(e−1)(p−1) over the factorisation. Both give ${factorOf(m).reduce((a, [p, e]) => a * (p ** (e - 1)) * (p - 1), 1)}. CRT splits the unit group across prime powers, and at p^e the non-units are exactly the multiples of p. Wave.lean seals 25 of these as bare numbers; this generates them, and it turns an O(m log m) walk into an O(sqrt m) product.` },

  { key: 'idempotent_count',
    expr: (m) => countExpr(m, `(x * x) % ${m} == x`),
    law: (m) => `lawIdempotents ${FE2(m)}`,
    walked: (m) => Array.from({ length: m }, (_, x) => x).filter((x) => (x * x) % m === x).length,
    predict: (m) => 2 ** factorOf(m).length,
    why: (m) => `THE IDEMPOTENTS NUMBER 2^omega(m), at m = ${m}. x² = x is walked directly; the law is two raised to the count of DISTINCT primes — ${factorOf(m).length} here, giving ${2 ** factorOf(m).length}. The exponents do not matter, only how many primes there are: an idempotent is a free choice of 0 or 1 in each prime-power component, so the count doubles per prime and is blind to multiplicity. That blindness is the content — it is why 12 and 18 and 24 all have four.` },

  { key: 'nilpotent_count',
    expr: (m) => countExpr(m, `pw x ${m} ${m} == 0`),
    law: (m) => `${m} / lawRadical ${FE2(m)}`,
    walked: (m) => { const pw = (a: number, n: number, mm: number) => { let r = 1 % mm, b = a % mm, k = n; while (k > 0) { if (k % 2 === 1) r = (r * b) % mm; b = (b * b) % mm; k = (k - (k % 2)) / 2 } return r }
      return Array.from({ length: m }, (_, x) => x).filter((x) => pw(x, m, m) === 0).length },
    predict: (m) => m / radOf(m),
    why: (m) => `THE NILPOTENTS NUMBER m / rad(m), at m = ${m}. A residue is nilpotent exactly when every prime of ${m} divides it, so the nilpotents are the multiples of the radical ${radOf(m)} and there are ${m / radOf(m)} of them. The walk searches for a vanishing power; the law divides ${m} by the product of its distinct primes. Wave.lean seals 37 of these counts and states none of this.` },
]

const FACTS: F[] = []
for (const law of LAWS) {
  for (const m of MODULI) {
    FACTS.push({
      key: `${law.key}_law_mod_${m}`,
      why: law.why(m),
      js: () => law.walked(m) === law.predict(m),
      lean: `theorem ${law.key}_law_mod_${m} : ${law.expr(m)} = ${law.law(m)} := by decide`,
    })
  }
}

// THE UNIT SUM — thirty-seven theorems asserting zero, because units pair x with m − x.
for (const m of MODULI) {
  if (m <= 2) continue
  FACTS.push({
    key: `unit_sum_vanishes_mod_${m}`,
    why: `THE UNITS SUM TO ZERO, at m = ${m}. The residues coprime to ${m} add to 0 mod ${m}, because x is a unit exactly when ${m} − x is and the two cancel; with ${m} > 2 no unit is its own partner, so the pairing is perfect and the sum is forced. Wave.lean carries 37 separate theorems each asserting this zero at one modulus. The exclusion of m = 2 is the hypothesis rather than an inconvenience: there the only unit is 1, it has no distinct partner, and the sum is 1.`,
    js: () => unitsOf(m).reduce((a, x) => a + x, 0) % m === 0,
    lean: `theorem unit_sum_vanishes_mod_${m} : (${sumExpr(m, `Nat.gcd x ${m} == 1`, 'x')}) % ${m} = 0 := by decide`,
  })
}

// THE BRIDGE — Carmichael's theorem, stated as its two halves.
for (const m of MODULI) {
  const L = lambdaLaw(m)
  const g = witnessOf(m)
  if (g === undefined) continue
  FACTS.push({
    key: `carmichael_exponent_is_attained_mod_${m}`,
    why: `CARMICHAEL AT m = ${m}, IN BOTH HALVES. The closed form gives lambda(${m}) = ${L} — the lcm over ${m}'s prime powers of p^(e−1)(p−1), with 2 the one place the pattern breaks (1, then 2, then 2^(e−2)). FIRST HALF: every one of the ${unitsOf(m).length} units satisfies a^${L} = 1, so ${L} kills the group. SECOND HALF: the unit ${g} has order exactly ${L}, so the bound is ATTAINED and nothing smaller would do. Together those are the definition of the group's exponent, and that it is attained by a single element is Carmichael's theorem — true here, and not automatic for abelian groups in general. THIS IS ALSO THE SPEED LAW: computing lambda by folding every element's order walks ${unitsOf(m).length} units for up to ${m} steps each; killing the group costs log ${L} steps per unit and attainment costs ONE walk. Wave.lean's max_unit_order_mod_* family is this number, sealed 37 times without the closed form that generates it.`,
    js: () => { const U = unitsOf(m)
      const pw = (a: number, n: number, mm: number) => { let r = 1 % mm, b = a % mm, k = n; while (k > 0) { if (k % 2 === 1) r = (r * b) % mm; b = (b * b) % mm; k = (k - (k % 2)) / 2 } return r }
      return U.every((a) => pw(a, L, m) === 1 % m) && orderOfJS(g, m) === L },
    lean: `theorem carmichael_exponent_is_attained_mod_${m} : (${unitBlocks(m)}.all (fun c => c.all (fun a => pw a (lawLambda ${FE2(m)}) ${m} == 1))) ∧ (ordOf ${g} ${m} == lawLambda ${FE2(m)}) := by decide`,
  })
}

emit({ file: 'Laws.lean',
  header: 'THE LAWS BEHIND THE COUNTS — the closed forms this ledger has been sealing one value at a time. ' +
    'Wave.lean carries ten families of per-modulus counts — divisors, units, idempotents, nilpotents, the unit sum, the largest unit order — those theorems in all, each stating a NUMBER and no reason for it. Every one is generated by a closed form in the factorisation of m: d(m) = prod (e+1); phi(m) = prod p^(e-1)(p-1); the idempotents number 2^omega(m), blind to multiplicity; the nilpotents number m / rad(m); the units sum to 0 for every m > 2. Measured against the ledger\'s own sealed values: every count reproduced, zero exceptions. ' +
    'NOTHING IS DEPRECATED. Those those theorems are true and they stay; they stop being independent claims and become these laws\' verification tables. Every theorem here computes BOTH sides in the kernel — the quantity walked, the law evaluated from the factorisation — so the identity is what is decided, never a literal restating the walk. ' +
    'THE BRIDGE IS THE ONE WORTH READING: max_unit_order (Wave) and unit_group_exponent (the Fermat wing) are the same function, the Carmichael lambda, computed in two wings that never cite each other. Their agreement is Carmichael\'s theorem — the exponent of the unit group is ATTAINED by a single element — and it is decided here rather than assumed. ' +
    'CLAIMED: the tabulated identities over the moduli named, each decided by the kernel over its own finite domain, axiom-free. NOT CLAIMED: any of these laws for all m, which quantifies over an infinite domain and cannot be asked of `by decide` at all. The tables are evidence for the laws, never proofs of them, and the frontier is in the theorem names.',
  skill: 'wave',
  defs: DEFS,
  facts: FACTS.map((f) => ({ ...f, name: f.why })) })
