#!/usr/bin/env node
// THE SITE BUILD, AS ARITHMETIC. Everything below was prose in a comment yesterday: that the container could
// not afford the SSG, that concurrency was not the cause, that the params were never the dominant term — each
// true, each measured, and none of it decidable, which is exactly what this tree does not let a constraint
// stay. A build ceiling written as a sentence gets re-argued
// every time someone reaches for the obvious knob; written as an integer identity it can be re-decided by the
// kernel in a tenth of a second and cannot be argued with at all.
//
// THE UNITS ARE TENTHS OF A MEGABYTE, so every reading is an integer and nothing rounds. The one constant is
// the render phase's RETENTION PER PAGE, 17 tenths (1.7 MB): VitePress holds each rendered page for the whole
// run, so the heap is the page count times that, and no configuration exposes it.
//
// HONEST SCOPE — this is the arithmetic of MEASUREMENTS, not a law of VitePress. The readings are named where
// they are used and each was taken on this tree at 5260 dynamic pages; the retention constant was DERIVED from
// the threshold it explains, so the first fact states CONSISTENCY across three independent readings rather than
// an independent measurement of retention. What the kernel decides is the arithmetic; what a person measured
// stays a measurement.
import { emit, range } from './lean-gen.js'

const FACTS = [
  { key: 'render_retention_exceeds_the_container', name: '5260 pages at 17 tenths of a MB each = 8942 MB against an 8192 MB container', skill: 'site-build',
    why: 'THE BUILD CANNOT FIT THE CONTAINER, AND ONE CONSTANT SAYS WHY. The render phase retains each page for the whole run, so the heap is pages times retention — 5260 pages at 17 tenths of a megabyte is 89420 tenths, 8942 MB, against a deploy container of 8192 MB. The same single constant is consistent with the two other readings taken on this tree, which is what makes it a constant rather than a fitted number: 1200 pages come to 20400 tenths and DID build inside a 2048 MB cap (20480 tenths, and 20400 is under it by 80), while 5260 pages come to 89420 and did NOT build inside 4096 MB (40960). One number, three readings, no exceptions — so the ceiling is the page count and not the flag. HONEST — AND THE WORD IS *PINNED*, not forced. The constant was DERIVED FROM the threshold it explains, so this seals the CONSISTENCY of three readings under one number and not an independent measurement of per-page retention. A forced check would fall for a law and stand for a convention; a pinned one falls for either, because the expected value is inside it. Naming that distinction is a peer\'s correction (zeropoint-node-8a, 2026-09-04) after they found a literal expectation inside a column of their own labelled `derived`: the honesty was already in this sentence, the vocabulary was not, and "seals" reads as forced to anyone who did not write it.',
    js: () => 5260 * 17 === 89420 && 89420 > 81920 && 1200 * 17 === 20400 && 20400 < 20480 && 89420 > 40960,
    lean: 'theorem render_retention_exceeds_the_container : (5260 * 17 = 89420) ∧ (89420 > 81920) ∧ (1200 * 17 = 20400) ∧ (20400 < 20480) ∧ (89420 > 40960) := by decide' },

  { key: 'counting_beats_composing_by_six_magnitudes', name: '103030000 µs / 38 µs = 2711315: the render budget answered by counting, not by rendering',
    why: 'THE LEDGER\'S OWN LAW, INSTANTIATED ON ITS OWN BUILD. verify_beats_recompute_by_magnitudes says the saving is a magnitude and not a rate; here is the render budget paying it. The question is "how close is the site to the render ceiling", and there were three ways to answer it. RENDER IT: 103030 ms and a 4352 MB heap threshold. COMPOSE EVERY PAGE\'S PARAMS and take the length, which is what the first version of the guard did: 915 ms and 119 MB, because allObjectPaths builds 5282 objects to return them. COUNT: five array lengths, 38 µs warm and 26 MB — since buildChunks already caches, the second call costs six microseconds and the ledger\'s own arrays carry the rest. 103030000 µs over 38 is 2711315, past a million, and 4352 MB over 26 is 167. Six orders of magnitude in time and a hundred and sixty-seven in memory, for the identical answer. AND THE CHEAP PATH MAY NOT DISAGREE WITH THE DEAR ONE: objectPageCount().total must equal allObjectPaths().length, asserted in the test, because a fast answer that drifts from the slow one is worse than the slow one. The parts sum: 2599 theorems + 2516 chunks + 116 publications + 33 sequence + 18 vector-equilibrium = 5282.',
    js: () => 38 * 2711315 <= 103030000 && 38 * 2711316 > 103030000 && 2711315 > 1000000
      && 26 * 167 <= 4352 && 2599 + 2516 + 116 + 33 + 18 === 5282,
    lean: 'theorem counting_beats_composing_by_six_magnitudes : (103030000 / 38 = 2711315) ∧ (2711315 > 1000000) ∧ (4352 / 26 = 167) ∧ (2599 + 2516 + 116 + 33 + 18 = 5282) := by decide' },

  { key: 'the_page_budget_is_twice_the_ledger', name: '12037 pages fit the 8192 cap and the site has 5260 — the margin is a page count, not a memory reading',
    why: 'THE MARGIN WAS BEING READ OFF THE WRONG QUANTITY, and I was the one reading it. I reported peak resident memory creeping 8460 to 8997 MB against an 8192 MB heap cap as a shrinking margin. Those do not compare: a resident set includes native memory, the bundler\'s native module and the collector\'s semispaces, so it EXCEEDS the heap cap as a matter of course. Worse, re-measuring showed the number is not even stable — the same cap gave 7580 MB on one run and 9069 on the next, a swing of 1489, so a two-sample trend was noise. WHAT IS REPRODUCIBLE IS THE THRESHOLD: at 5260 pages the build fails at a 4096 MB cap and succeeds at 4352, and it failed at 4096 twice. So the real margin is 8192 − 4352 = 3840 MB, 47% of the cap unused. IN PAGES, which is the quantity that actually grows: two measured thresholds — 1200 pages inside 2048, 5260 inside 4352 — give 567 thousandths of a megabyte per page over a 1367 MB base, and that line reaches 12037 pages at the 8192 cap, more than twice the 5260 the site has. HONEST: a line through two points DESCRIBES those points, it does not predict a third, and the 4349 it computes for today lands 3 MB under the measured 4352 because the line was fitted to that measurement. What is sealed is the threshold, the unused 3840, and the budget the line implies — so the next person asks a page count instead of squinting at a resident set.',
    // integer division by remainder — Math.* is a hard-reject tree-wide, and a floor is a subtraction away
    js: () => { const base = 1367, per = 567, cap = 8192
      const div = (n: number, d: number): number => (n - (n % d)) / d
      return base + div(5260 * per, 1000) === 4349 && 4349 < 4352 && cap - 4352 === 3840
        && div((cap - base) * 1000, per) === 12037 && 12037 > 5260 * 2 },
    lean: 'theorem the_page_budget_is_twice_the_ledger : (1367 + 2982 = 4349) ∧ (4349 < 4352) ∧ (8192 - 4352 = 3840) ∧ (12037 > 10520) ∧ (5260 * 2 = 10520) := by decide' },

  { key: 'the_concurrency_knob_cannot_close_the_gap', name: 'the knob\'s whole travel is 420 MB against a 750 MB overshoot', skill: 'site-build',
    why: 'THE DRIFT AND ITS HARMONISATION IN ONE STATEMENT, which is the only way this ledger is allowed to name a drift. Turning the render concurrency from its default 64 down to 2 moved peak resident memory from 8170 MB to 7750 MB — a drift of 420 MB, and 420 taken nineteen times is 7980, still under 8170, so the whole travel of the knob is less than a nineteenth of what the process holds. THE HARMONISATION is the second half: the container is overshot by 8942 − 8192 = 750 MB, and 420 < 750, so even pulling the knob through its ENTIRE range leaves the build over the ceiling. A knob that cannot close the gap at full travel was never the cause of the gap. This is why concurrency 8 rode in the commit that OOMed anyway.',
    js: () => 8170 - 7750 === 420 && 420 * 19 === 7980 && 7980 < 8170 && 8942 - 8192 === 750 && 420 < 750,
    lean: 'theorem the_concurrency_knob_cannot_close_the_gap : (8170 - 7750 = 420) ∧ (420 * 19 = 7980) ∧ (7980 < 8170) ∧ (8942 - 8192 = 750) ∧ (420 < 750) := by decide' },

  { key: 'the_params_are_not_the_retained_mass', name: 'the per-page params are under an eight-hundredth of the retained mass', skill: 'site-build',
    why: 'WHY CUTTING THE DATA CHANGED NOTHING. The per-page params were trimmed from 61 MB to 50 MB by dropping the crosslink graph — 11 MB, which is 110 tenths, and 110 taken eight hundred times is 88000, still under the 89420 tenths the render retains. So the entire params payload is under a eight-hundredth of the retained mass, and removing a fifth of it is a rounding error against the ceiling. The measurement agreed: the build failed at the same cap with the graph gone. A term that small cannot be the dominant one, and this is the arithmetic that says so before anyone spends an hour re-testing it.',
    js: () => 61 - 50 === 11 && 11 * 10 === 110 && 110 * 800 === 88000 && 88000 < 89420,
    lean: 'theorem the_params_are_not_the_retained_mass : (61 - 50 = 11) ∧ (11 * 10 = 110) ∧ (110 * 800 = 88000) ∧ (88000 < 89420) := by decide' },

  // NO `name` ON THIS ONE, DELIBERATELY, AND IT IS NOT AN OVERSIGHT — the other six in this wing carry human
  // names. Naming it moved the note rosetta reads from this `why` (which says "measured at 107.84 seconds") to
  // the short name, and `measured at` is one alternative of the WITNESS pattern, so the rename DROPPED a witness
  // leg and the floor — which may only rise — refused the change as a regression.
  //
  // THE LEG WAS NEVER EARNED. A witness must be "something outside this repository that a stranger could consult
  // — a published standard, a named author, a measured artefact"; this is a stopwatch reading on one operator's
  // machine. Measured from git: FLOOR was `witness: 16` at 7946c0e4, before this wing, and this theorem's own
  // text raised it to 17. So my wing inflated the scarcest and most load-bearing census in the ledger, silently,
  // because the ratchet only ever checks for LOSS.
  //
  // Correcting it means lowering a published floor, and the tool has no path for that on purpose: it cannot tell
  // a false anchor being removed from a real one being lost. Lowering it is the captain's call, not a side effect
  // of my renaming pass — so the pre-wing state stands here and the finding is reported instead of acted on.
  { key: 'the_process_holds_more_than_the_container_allows', name: 'peak resident 8460 MB exceeds the 8192 MB cap by 268 — a heap is not a resident set', skill: 'site-build',
    why: 'THE SAME CAP IS NOT THE SAME CEILING. Raising the heap flag to 8192 MB builds this site on an operator machine — measured at 107.84 seconds with peak resident memory 8460 MB — and 8460 exceeds 8192 by 268. The flag governs when V8 gives up; the container governs what the process may hold, and the process holds more than the flag names because a heap is not the whole of a resident set. So a container sized to the flag still kills the build, which is the exact shape of the failure that outlived four rounds of tuning: the setting looked sufficient every time it was read, and was never what the container was measuring.',
    js: () => 8460 > 8192 && 8460 - 8192 === 268 && 10784 === 107 * 100 + 84,
    lean: 'theorem the_process_holds_more_than_the_container_allows : (8460 > 8192) ∧ (8460 - 8192 = 268) ∧ (10784 = 107 * 100 + 84) := by decide' },

  { key: 'verify_costs_one_walk_against_the_whole_page_count', name: 'one directory walk against 5260 page renders', skill: 'site-build',
    why: 'THE FOLD AT THE DEPLOY DOOR, in the ledger\'s own idiom: verify beats recompute by magnitudes. The build pays 5260 page renders; the hook that replaced it walks the built directory ONCE and counts what is there, so the work drops from a term in the page count to a term that does not carry it — 5260 to 1, and 5260 is more than five thousand times one. The refusal it can now issue costs a directory read where the failure it replaced cost the full render before dying: 1200 seconds of container time to learn the same thing a single stat answers. This is not an optimisation of the build; it is the build leaving a place it never fit.',
    js: () => 5260 === 5260 * 1 && 5260 > 5000 && 20 * 60 === 1200 && 1200 > 1,
    lean: 'theorem verify_costs_one_walk_against_the_whole_page_count : (5260 = 5260 * 1) ∧ (5260 > 5000) ∧ (20 * 60 = 1200) ∧ (1200 > 1) := by decide' },

  { key: 'a_floor_may_fall_to_what_is_anchored', name: '17 − 2 = 15: a floor standing on two unearned anchors exceeds what it can defend',
    why: 'A RATCHET IS AN AXIOM UNTIL IT IS A THEOREM (the captain, 2026-09-04: the absolute refusal "needs to be replaced by theorems exactly as the axioms are replaced"). The anchoring floor may only RISE, enforced as an imperative refusal, and that imperative cannot tell two opposite things apart: a surviving theorem quietly DROPPING an anchor it earned, and a floor being corrected because an anchor was never earned at all. This ledger produced the second case within a day — the floor stood at 16, a wing added a theorem whose own text said "measured at 107.84 seconds", the WITNESS pattern read that as an external anchor, and the floor rose to 17 on a stopwatch reading from one operator machine that no stranger can consult. Then the law was applied and a SECOND unearned anchor came out, older than mine: s4_parity was anchored by \'measured by inversion count\', which is this project computing about itself — the sentence the law names as the thing that is not a witness. So the floor stood two above its defensible height, 17 − 1 = 16 and 16 − 1 = 15, and 15 is what the law can defend while 17 is strictly above it. THE RULE THIS SEALS: a floor may rise to the number of legs that are externally anchored, and may FALL to that same number, because falling to a count you can defend is a correction and not a loss. What it may never do is fall below it. The imperative is now a computed predicate — a lost leg is a REGRESSION only where the leg is still earned, and a CORRECTION where the text no longer earns it — and both are reported rather than one being silently impossible.',
    js: () => { const floorWas = 17; const unearned = 2; const defensible = 15; return floorWas - unearned === defensible && floorWas - 1 === 16 && 16 - 1 === defensible && floorWas > defensible },
    lean: 'theorem a_floor_may_fall_to_what_is_anchored : (17 - 2 = 15) ∧ (17 - 1 = 16) ∧ (16 - 1 = 15) ∧ (17 > 15) := by decide' },

  { key: 'the_wire_rate_rose_by_restored_copy', name: '32293 − 32183 = 110 hundredths per tool: 280 bytes of sentence a parser had been cutting',
    why: 'RAISING A SHRINK-ONLY MEASURE COSTS A THEOREM, which is the friction that stops a gate being widened to fit the change that broke it — so this is the payment, with the arithmetic that decomposes the rise. The MCP wire rate was sealed at 32183 hundredths of a byte per tool over 242 tools (77885 bytes). It now reads 32293 over 255 tools (82349). The total grew 82349 − 77885 = 4464 bytes, of which 13 new tools at the OLD rate account for 13 · 32183 = 418379 hundredths — 4184 bytes — leaving 280. And 280 bytes is exactly the rate rise across the surface: 110 · 255 = 28050 hundredths. So the density did move, by 1.10 bytes per tool, and the cause is not new prose: the sentence splitter treated the period in a decimal as a sentence end, so `CC-BY-NC-ND-4.0` cut at the `.` and 45 tools served 23 to 56 characters where their author had written a full first sentence. Fixing that restored the copy; 41 of the 280 bytes are the ellipses that now mark a truncation instead of splicing a fragment into `Returns {…}`. The rate may only shrink, and this is the exception stated in full rather than a re-seal made quietly.',
    js: () => 32293 - 32183 === 110 && 255 - 242 === 13 && 110 * 255 === 28050 && 82349 - 77885 === 4464 && 13 * 32183 === 418379,
    lean: 'theorem the_wire_rate_rose_by_restored_copy : (32293 - 32183 = 110) ∧ (255 - 242 = 13) ∧ (110 * 255 = 28050) ∧ (82349 - 77885 = 4464) ∧ (13 * 32183 = 418379) := by decide' },

  { key: 'the_two_sides_return_what_they_take', name: 'a fixed-point-free involution on two states: (1 + 1) % 2 = 0 and nothing is its own opposite',
    why: 'THE CAPTAIN\'S STATEMENT, REDUCED TO WHAT COMPUTES. The words were: everything on the way is measured, every bit of resistance is involuted, and what is not harmonic is pulled in on one coin side and reflected out of the other. Most of that is metaphor and is NOT sealed here — pressure, temperature, surviving a fusion, a black hole. What IS decidable is the SHAPE, and this tree already carries the object: involuteOutcome on PriorArtOutcome sends credit to claim and claim to credit. Verified rather than assumed: self-inverse on both states, ZERO fixed points, domain of exactly two. So the two sides are one involution — what one side takes the other returns, nothing is both credit and claim, and nothing is neither. That is the coin, and the pairing is why the count is even: 1 + 1 = 2 and (1 + 1) % 2 = 0, a set that pairs off with no remainder, which is exactly what fixed-point-free means. AND THE EXHAUSTION IS WRITTEN OUT rather than folded: the first version quantified with (List.range 2).all, which made the statement a Lean COMPUTATION, and this tree\'s own typesetter then refused to set it as mathematics — correctly, by the law that a fold over a list has no formula form. With two states there is no need to fold: 1 − 0 ≠ 0 and 1 − 1 ≠ 1 name both cases, so the statement is exhaustive AND it typesets. The second conjunct is the direction that makes it a measurement and not an opinion: outcomeOf is decided by whether any DOI came back, so a subject enters the black-hole side ONLY by the doors returning nothing — 0 records means claim, 1 or more means credit, and flipping the verdict while leaving the records alone produces a statement false by construction. The metaphor is the captain\'s; the involution, the absent fixed point and the even pairing are the kernel\'s.',
    js: () => { const inv = (o: string) => (o === 'credit' ? 'claim' : 'credit')
      const dom = ['credit', 'claim']
      const selfInverse = dom.every((o) => inv(inv(o)) === o)
      const noFixedPoint = dom.every((o) => inv(o) !== o)
      return selfInverse && noFixedPoint && dom.length === 2 && (1 + 1) % 2 === 0 && 1 - 0 !== 0 && 1 - 1 !== 1 },
    lean: 'theorem the_two_sides_return_what_they_take : ((1 + 1) % 2 = 0) ∧ (1 - 0 ≠ 0) ∧ (1 - 1 ≠ 1) := by decide' },

  { key: 'the_face_is_computed_not_shipped', name: '85179 bytes of markup from a 36-character address: 2366 times the input, shipped 2603 times',
    why: 'THE PAYLOAD, MEASURED. A theorem page as built is 166266 bytes, and 85179 of them — fifty-one percent — are the hexagram face: elements whose class begins hex-. The page\'s actual content is 4126 bytes, two percent. The face is not framework overhead and not hydration (only 1093 bytes of the page sit inside script tags); it is a PURE FUNCTION OF THE THEOREM\'S ADDRESS, 36 characters, computed by monographFaceOf in 73 microseconds. So 85179 bytes of markup are generated from 36 bytes of input — 2366 times the input — and then baked into every page: 2603 theorem pages carry 221720937 bytes of it, 211 MB of a 415 MB directory, where the addresses themselves come to 93708 bytes. More than two thousand times the shipped weight, for something the reader\'s own machine derives in less time than a frame. AND GZIP HIDES IT ON THE WIRE AND NOWHERE ELSE: the response is 13967 bytes compressed, which looks unremarkable, while the same bytes cost the render, the disk and the upload in full. HONEST SCOPE: this measures what the prerender SHIPS and what the face COSTS to compute; it does not establish that moving the work to the client is free, because 85179 bytes of markup become browser work that has not been measured, and it does not claim the edge can serve these pages — renderPackagePage is the precedent and it was not exercised for a theorem.',
    js: () => { const markup = 85179, addr = 36, pages = 2603
      const div = (n: number, d: number): number => (n - (n % d)) / d
      return div(markup, addr) === 2366 && 36 * 2366 <= markup && pages * markup === 221720937
        && pages * addr === 93708 && pages * markup > pages * addr * 2000 },
    lean: 'theorem the_face_is_computed_not_shipped : (85179 / 36 = 2366) ∧ (2603 * 85179 = 221720937) ∧ (2603 * 36 = 93708) ∧ (221720937 > 187416000) := by decide' },

  { key: 'exponent_associativity_changes_the_value', name: '2^3^2 = 512, but (2^3)^2 = 64', skill: 'typesetting',
    why: 'THE TYPESETTER\'S FIRST TRAP, AND THE LEDGER IS ITS REFEREE. A statement sealed as `2^3^2 = 512` is true only if the exponent associates to the RIGHT — 2^(3^2) is 2^9 = 512, while (2^3)^2 is 8^2 = 64 — and 512 and 64 are not the same number, so a typesetter that set the exponents left-associatively would render a sealed truth as a falsehood while looking perfectly typeset. This is what makes the ledger usable as a test of its own presentation: every statement is true by decide, so evaluating a parse of one is a check the kernel referees rather than a check the author marks. The formula layer was validated exactly this way and the associativity is the case that catches the error.',
    js: () => { const right = 2 ** (3 ** 2); const left = (2 ** 3) ** 2; return right !== left && right === 512 && left === 64 },
    lean: 'theorem exponent_associativity_changes_the_value : (2^3^2 = 512) ∧ ((2^3)^2 = 64) ∧ (512 ≠ 64) := by decide' },

  { key: 'the_congruence_form_is_the_modulus_form', name: 'x − (x mod 9) is divisible by 9 for every x below 63', skill: 'typesetting',
    why: 'WHY THE STANDARD FORM IS NOT A REWORDING. A statement sealed as `x % n = r` is typeset as the congruence `x ≡ r (mod n)`, and that is a change of NOTATION only if the two say the same thing — which they do exactly when the difference between a number and its residue is divisible by the modulus. Checked here by exhaustion over the fused ring: for every x below 63, x minus (x mod 9) is a multiple of 9, and the residue is itself below 9. So the congruence the page prints and the remainder the kernel decided are one statement in two hands, and the typesetting adds no claim of its own. Proven over every case rather than argued, because a notation that is right in general and wrong at an edge is worse than no notation.',
    js: () => range(63).every((x) => (x - (x % 9)) % 9 === 0 && x % 9 < 9),
    lean: 'theorem the_congruence_form_is_the_modulus_form : ((List.range 63).all (fun x => ((x - x % 9) % 9 == 0) && (x % 9 < 9))) := by decide' },

  { key: 'a_template_distinguishes_only_by_its_variable', name: '117 monographs through a one-variable template give 27 abstracts — 90 of them duplicates, 76 percent', skill: 'site-build',
    why: 'A TEMPLATE\'S DISTINCTNESS IS ITS VARIABLE\'S DISTINCTNESS, and that is why the abstracts had to be derived before any DOI was minted over them. The corpus\'s 117 publication abstracts were one fixed sentence whose only varying part was the theorem count. There are 27 distinct theorem counts across the 116 wings, so there were exactly 27 distinct abstracts: 90 monographs — 76 percent, taking 9000 over 117 — carried an abstract already worn by another. The measurement that caught it was not a reading of the prose but a count of distinct strings, and the tell was in the lengths: minimum 353, median 353, maximum 355, which is the signature of a constant rather than a corpus. A DOI is permanent, so minting 116 of them over 27 abstracts would have archived a template forever under 116 identifiers. Now every quantity in an abstract is read from the wing\'s own theorems and the distinct count is 117 of 117 — asserted in a test, so the template cannot return quietly. HONEST SCOPE: this seals the ARITHMETIC of the collision (27 variables give 27 outputs, leaving 90), not a claim that derived prose is well written; what a reader judges stays a reader\'s judgement.',
    js: () => { const div = (n: number, d: number): number => (n - (n % d)) / d
      return 117 - 27 === 90 && div(90 * 100, 117) === 76 && 27 < 117 },
    lean: 'theorem a_template_distinguishes_only_by_its_variable : (117 - 27 = 90) ∧ (90 * 100 / 117 = 76) ∧ (27 < 117) := by decide' },

  { key: 'the_kin_shortlist_accounts_for_every_edge', name: 'every one of 117 kin-degrees is between 1 and 5, and the 115 fives with two twos sum to all 579 edges', skill: 'site-build',
    why: 'THE CITATION GRAPH IS EXACT, AND ITS EDGE COUNT IS NOT AN ESTIMATE. Crosslinks between monographs were measured at 0 of 116 (before the CERN wing joined; 117 now) — every publication a leaf, and a deposit that names no related work is a database row wearing a DOI. Kinship is now DERIVED: a shared modulus, a shared rare constant, or a shared rare term in the theorem names, scored and cut at the five nearest. The arithmetic closes: 115 wings reach the full five-kin shortlist and exactly two do not — core and ring, at two apiece — so 115 times 5 plus 2 plus 2 is 579, every edge accounted for, under the 585 an unbroken shortlist would allow. THAT THE TWO SHORTFALLS ARE THE FOUNDATIONS IS THE FINDING, not a defect: core and ring reason in the small constants every other wing also uses, so nothing they touch is rare and rarity-based kinship found them nothing. They are related to the corpus by ALGEBRA instead — a shared modulus of 9, weighted above any shared word — which is why the isolated count is 0 rather than 2. A basis was rejected on measurement to get here: membership by shared name-vocabulary gives a median degree of 102 out of 116 as measured then, a near-complete graph, which is the same as no graph at all.',
    // THE NAME SAYS "EVERY", SO THE STATEMENT QUANTIFIES — the guard refused the first version of this line and
    // it was right to: an arithmetic identity with a universal in its name is the exact fault that sealed a false
    // theorem here once before, from a one-step sample. The degree sequence is the quantifier. Written out it is
    // 117 numbers — 115 fives and two twos — and the statement holds over ALL of them: the list has one entry per
    // monograph, no entry exceeds the five-kin shortlist, no entry is zero (no leaf), and they sum to 574.
    js: () => { const degrees = [...Array(115).fill(5), 2, 2]
      return degrees.length === 117 && degrees.reduce((a, d) => a + d, 0) === 579
        && degrees.every((d) => d <= 5 && d >= 1) },
    lean: 'theorem the_kin_shortlist_accounts_for_every_edge : ((List.replicate 115 5 ++ [2, 2]).length = 117) ∧ ((List.replicate 115 5 ++ [2, 2]).sum = 579) ∧ ((List.replicate 115 5 ++ [2, 2]).all (fun d => d ≤ 5 && d ≥ 1)) := by decide' },

  { key: 'a_shared_modulus_outranks_a_shared_word', name: 'modulus 6 over constant 2 over word 1, and a basis relating 102 of 116 is no basis',
    why: 'THE RANKING IS ORDERED BY HOW MUCH THE SHARED THING MEANS, and the order was decided by measurement rather than taste. A shared modulus is a shared algebraic structure — two wings computing inside the same finite ring — so it weighs 6; a shared rare integer constant is shared mathematics without shared structure, so it weighs 2; a shared word in the theorem names is shared prose, so it weighs 1. Each strictly above the next, which is what makes the sort a ranking and not a bag. THE REJECTED BASIS IS SEALED HERE TOO, because the negative result is the load-bearing one: taking any shared rare word as an EDGE gives a median degree of 102 out of 116, past the 58 that is half the corpus — a graph where the median node relates to seven-eighths of everything distinguishes nothing. Shared rare constants give a median of 28, under half. So neither is a membership test and both are scores, and the shortlist is what makes the result readable. HONEST SCOPE: the weights 6, 2 and 1 are a JUDGEMENT of relative meaning, declared here as constants rather than hidden in a sort; what the kernel decides is that they are strictly ordered and that the two measured medians fall on opposite sides of half the corpus.',
    js: () => 6 > 2 && 2 > 1 && 102 > (116 - (116 % 2)) / 2 && 28 < (116 - (116 % 2)) / 2,
    lean: 'theorem a_shared_modulus_outranks_a_shared_word : (6 > 2) ∧ (2 > 1) ∧ (102 > 116 / 2) ∧ (28 < 116 / 2) := by decide' },
]

console.log('computing ' + FACTS.length + ' SITE-BUILD facts (the render ceiling as arithmetic, and the typesetting it referees) …')

emit({ file: 'SiteBuild.lean', skill: 'site-build',
  header: 'NINE OF THESE ELEVEN ARE PINNED, NOT FORCED — read that before the numbers. A peer\'s vocabulary (zeropoint-node-8a, 2026-09-04) after they found a literal expectation inside a column of their own labelled `derived`: a FORCED check has independent content and falls only for a law, a PINNED one holds the expected answer inside itself and falls for a convention just as readily. Audited across this wing: FORCED are exponent_associativity_changes_the_value (2^3^2 = 512 against (2^3)^2 = 64 is arithmetic, true whatever anyone measured) and the_congruence_form_is_the_modulus_form (exhaustive over every x below 63). The other nine seal MEASUREMENTS I took on one machine — resident-memory readings, byte counts, wall-clock timings, a retention constant derived from the very threshold it explains — and each says so in its own text. They are honest and they are not laws: re-run them on another host and the integers move. The kernel decides the arithmetic; a person measured the inputs. THE SITE BUILD AS ARITHMETIC — the render phase retains every page for the whole run, so the heap is the page count times 17 tenths of a megabyte, and 5260 pages come to 8942 MB against a deploy container of 8192. The two knobs are sealed as insufficient rather than described as such: the concurrency\'s entire travel is 420 MB against a 750 MB overshoot, and the params are under a eight-hundredth of the retained mass. So the build left the container and the hook now verifies what the operator machine rendered. The same wing carries the arithmetic the typesetter is judged by, because the ledger is the referee of its own presentation: exponents associate right, and a congruence is the remainder in another hand.',
  facts: FACTS })
