#!/usr/bin/env node
// lean-ledger — LEAN IS THE SINGLE SOURCE OF THEOREMS. This parses every lean/*.lean theorem (organised by
// computing principle) and writes src/theorems/generated.ts — the one derived ledger the package, the MCP tools,
// the trial and the site all consume. No theorem is authored anywhere else: a theorem computes in Lean, or it is
// not a theorem. Names come from the *-manifest.json emitted alongside each proof. Run by `npm run lean`.
import { writeFileSync, readdirSync, readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { LeanTheorem } from '../theorems/generated.js'
import { ROOT } from './api.js'

const LEAN_DIR = join(ROOT, 'lean')

// the computing-principle order — the derivation order the whole layer is organised by
export const PRINCIPLE = [
  ['Core.lean', 'The 8×8 core', "the multiplication table of ℤ/9's eight non-zero residues — from these 64 the rest computes"],
  ['Ring.lean', 'The ring ℤ/9', 'the vortex ring: its full multiplication, addition and power tables'],
  ['Rosette.lean', 'The rosette ℤ/7', 'the Pliska group: its full multiplication, addition and power tables'],
  ['Uuidna.lean', 'The vortex algebra', 'units, orbit, involution, gravity, division by zero, light — the foundational facts'],
  ['Vortex.lean', 'Ported from millennium-solutions', 'the honest ℤ/9 & ℤ/7 facts, ported to plain Lean (no Mathlib)'],
  ['Sequence.lean', 'The sequence & reflection group', 'the mirror, AGL(1,ℤ/9)=54, one strip, neighbours, the ± polarities, the crypt salt'],
  ['DivByZero.lean', 'Division by zero', 'the reflection dz(x)=10−x — a finite residue, never infinity'],
  ['BioPhysics.lean', 'Applied structure — the science pairs', 'blood, DNA, sound, chemistry, music, acid-base, heredity, colour — the algebra, demarcated'],
  ['Discover.lean', 'Self-discovered', 'facts derived by function: Lagrange, the unit criterion, idempotents'],
  ['Quantum.lean', 'The quantum computer', 'the exact facts the classical state-vector simulator computes — Born rule, no-signaling, GHZ, gate truth-tables, phase algebra; simulation, not hardware'],
  ['Clay.lean', 'The seven reflected', 'the seven Clay problems reflected into the ℤ/9 structure and solved none — a bijection that relabels, it does not propagate proofs; it reflects all seven and solves none. VERIFIED ≠ SOLVED is itself sealed: the kernel verifies the stated proposition, the seal confers no solved status on the named problem — decided by theorems only, the seven casting secure-messaging ballots witnessed by their own sealed proofs. THE COLLISION LAW seals beside it by the same electorate: a claim colliding with the sealed status DNA (subject ∧ self-voice ∧ undemarcated) never verifies, whatever it cites — a real citation is not entailment, and the laundering probes recompute refused at every generation'],
  ['Legal.lean', 'The legal vocabulary', 'the trial\'s legal terms as decidable facts — PROVEN (admitted, stays), REFUTED (a recomputable contradiction), NOT PROVEN (dismissed without prejudice), REMAND (to development trial): only the proven is admitted, every non-proven is remanded (nothing discarded), and the non-justiciable is never refuted (you cannot refute what has no decidable test)'],
  ['Infinity.lean', 'The physics infinities, made finite', 'the nasty divergences of physics — UV catastrophe, self-energy, the Landau pole, 1+2+3+…, the derivative 0/0, δ(0), the horizon, the 1/r singularity — each the finite object physics puts where the naive infinity was, exactly as dz(x)=10−x replaces x/0'],
  ['Cipher.lean', 'The cipher & the strand', 'crypto ∩ DNA, honest by construction — base-pairing is a fixed-key XOR (a one-time-pad step), the pad is self-inverse but key reuse leaks the plaintext XOR (why a step must rotate), a linear fold is malleable (a receipt is integrity, not a seal), the transport leaks message length, translation is lossy (never a cipher), an affine S-box is invertible but linear, and Grover only halves the key (256→128, not a break) — the shared algebra and its honest limits'],
  ['Audit.lean', 'The detectors, proven', 'the provenance gate as decidable logic — flag(h,d,b)=h·(1−d)·(1−b): hollow prose is flagged only when neither demarcated nor backed by a sealed theorem, a demarcation clears it, a backing clears it, and of the eight states exactly one fires — the honesty detector, itself a theorem set'],
  ['AuditGame.lean', 'The audit game', 'why an audit is more ACCURATE framed as a game, sealed by decide — a finding is FLAGGED iff some independent refuter has a winning move (the OR), a claim is CLEAN iff none does (a P-position, the same Nim/Bouton decidability as a zero nim-sum), the verdict is exactly one of the two (survive + flag = 1), and N independent refuters are strictly more accurate: adding a refuter is monotone (never un-flags), a 3-vote panel confirms on a majority (4 of the 8 profiles), and a unanimous acquittal is the product of clears ∏(1−rᵢ); the honesty gate drains only the hollow-and-unbacked citation (1 of 4 states, echoing the detectors); and the game is finite (2ⁿ outcomes) so its value is decidable. HONEST SCOPE: the DECISION is decidable but the COVERAGE is not — the refutation lexicon is incomplete, so an audit raises the cost of a false claim surviving, never zeroing it. A floor, not a wall — the same bound Security proves'],
  ['Coins.lean', 'The two coins & the 64', 'the honest billing/measure algebra — the two coins are the conserved fair-exchange invariant (110−108 = 2 = −χ of the double torus, genus 2), 64 = 2⁶ is the bit measure, contribute 2 to save up to 64 (leverage 32), n qubits give 2ⁿ direct outcomes reaching 64 at n=6, and the measured saving never goes negative — a measured unit of work saved, not a price and not a claim of speed'],
  ['Hardware.lean', 'The hardware-verifiable binary algebra', 'the low-level combinational-logic identities every digital circuit is built from, each a decidable axiom-free `by decide` particle: the four gate truth tables as bit arithmetic (NOT a = 1−a, AND = a·b, OR = a+b−a·b, XOR = the axiom-free lxor), XOR = ℤ/2 parity, Boolean closure on the bit, NAND functional completeness (NAND rebuilds NOT/AND/OR — why chips are one repeated gate), De Morgan, the half- and full-adder (sum + 2·carry = the input sum), and the 2:1 multiplexer. All match the live published digital-logic spec. HONEST SCOPE: integrity, not truth — uuidna SEALS the spec a netlist is verified AGAINST; it does not fabricate a device, synthesise a netlist, or develop silicon. A sealed spec, not a chip'],
  ['Software.lean', 'The software-verifiable algebra', 'the algebraic correctness LAWS a program is verified against, one level up from the hardware layer, each a decidable axiom-free `by decide` particle: losslessness (split-and-recompose is the identity — serialisation loses nothing), structure preservation (map keeps length, filter never grows, append adds), idempotent normalisation, a TOTAL guarded division (no divide-by-zero crash), bounded termination (a shift loop halts), order-invariant reduction (safe to parallelise), the compare-swap that orders (every sort\'s basis), total safe indexing (no over-read), and reversibility (undo of undo is the identity). HONEST SCOPE: integrity, not truth — uuidna SEALS the spec an implementation is verified AGAINST; it does not write, compile, or run your program, nor prove an arbitrary program correct. A sealed spec, not the program'],
  ['Os.lean', 'The OS-integrity algebra', 'the decidable facts a DEPLOYMENT is verified against, completing hardware → software → os, each an axiom-free `by decide` particle: exact-copy verification IS byte-equality, so a single-byte tamper, a truncation, or a REORDERING breaks the match (a provenance is a SEQUENCE, not a set); the SHA-256 digest is a fixed 256 bits, the content-address a fixed 128; and the non-determinism boundary is EXACTLY the two named modules (src/os, src/drivers). The runtime side (Alpine + driver provenance, portAllAlpine over the whole arch matrix) enforces it against real bytes with uuidna\'s own pure-TS SHA-256. HONEST SCOPE: integrity, not truth, and NOT execution — uuidna seals what an exact-copy verification decides; it does not boot, port the runtime, link, or run an operating system. A sealed integrity spec, not a booted OS'],
  ['Exploits.lean', 'The exploit folds', 'known public exploit CLASSES folded through uuidna\'s involution, the CVE/CWE codes kept INLINE IN LEAN so the audit computes itself from the ledger — a FOLDED class (fold_*) encodes its code as a decidable fact and cites a sealed defence (Trojan-Source→strip 9 BIDI points, prototype-pollution→drop 3 poison keys, supply-chain→zero runtime deps, DoS→sanitiser bounds, weak-hash→SHA-256 seats, tampering→content-address+merkle, code-injection→no eval, weak-RNG→determinism hard-reject), and an OUT-OF-SCOPE class (oos_*) folds to the VOID (compromised host, deceived human, physical side-channel, FNV-as-secret misuse, non-decidable correctness). HONEST SCOPE: uuidna does NOT solve all hacks — both problem and solution are verified, and the boundary is named, never falsely marked solved'],
  ['Sanitize.lean', 'The sanitise standards', 'the engine\'s one input→output guard with its rules kept IN THE THEOREMS — MAX_DEPTH = 32 = 2⁵, MAX_STRING = 10⁶, arrays and object keys bounded to 10⁵, the three prototype-pollution poison keys (__proto__, constructor, prototype) dropped, and the nine Trojan-Source BIDI code points (five overrides U+202A..202E + four isolates U+2066..2069) stripped — process any input, sanitise any output by all standards, the rule sent by the theorems themselves so a code constant cannot drift from its sealed value'],
  ['Solids.lean', 'The Platonic solids in every dimension', 'the five regular solids and the regular polytopes of every dimension, sealed to green: Euler V−E+F = 2 for all five (the dodecahedron\'s 2 IS the two captain coins), the dodecahedron is twelve pentagons (the twelve the monographs computed themselves into) dual to the icosahedron\'s twenty triangles, the tetrahedron self-dual, three pentagons closing each vertex by the angle defect 3·108° < 360° < 4·108°, and the per-dimension census [5,6,3,3,3] for dimensions 3..7 — five in 3D, six in 4D, exactly three in every dimension ≥5 including the 7th (simplex, hypercube, orthoplex). Integrity, not truth: each theorem seals its exact decidable arithmetic'],
  ['Neuro.lean', 'The algebra of the neuron', 'neuroscience, demarcated — all-or-none firing as a threshold step, sub-threshold silence, supra-threshold spike, monotone firing, spatial summation (two sub-threshold inputs sum to fire), the excitatory−inhibitory net drive, the −70→+40 mV action potential (rest < threshold < peak), Hebbian coincidence (Δw = pre·post), and the refractory cap — the textbook model as decidable algebra, not clinical and not about any individual'],
  ['Propulsion.lean', 'Propulsion — Newtonian & bounded', 'thrust is conserved momentum (Newton\'s third law), it REQUIRES reaction mass (zero exhaust → zero thrust: no reactionless/free drive), thrust = ṁ·vₑ, the Δv budget adds across stages, and acceleration a = F/m is finite — no infinite g. The algebra of rocketry, demarcated: not a novel drive, not FTL, not infinite g'],
  ['Navigation.lean', 'Navigation — bounded geometry', 'straight-line distance is Pythagorean (3-4-5), the compass rose is ℤ/8 (eight 45° headings), the reciprocal bearing is +4 (an involution), a quarter turn is +2 (order 4), and dead reckoning is the vector sum of the legs — classical navigation as decidable algebra, not GPS-grade guidance and not a positioning claim about anyone'],
  ['Topography.lean', 'The lay of the land', 'topography as decidable arithmetic, the map beneath navigation — a contour joins points of equal height and every fifth line is the heavy index contour (multiples of 50 m at a 10 m interval), so elevation is read by COUNTING rings (5 × 20 = 100 m of ascent); gradient is rise over run (a 1-in-20 slope climbs 5 m in 100), contour spacing is its inverse (a steep 1-in-5 crowds the lines to 50 m, a gentle 1-in-10 spreads them to 100), and the slope distance is Pythagorean (a 400 m run up 300 m walks 500 m, longer than the map\'s flat shadow); scale is a pure ratio (1:25000 → 1 cm is 250 m, 4 cm a kilometre); a grid reference nests by tens (each 100 m square split ten ways to 10 m); a back-bearing is the forward turned 180° about the compass in ℤ/360; relief is the highest spot height less the lowest; Gunter\'s chain measures the mile and the acre whole (80 × 66 = 5280 ft, 22 × 220 = 4840 sq yd); triangulation rests on the 180° triangle; and a cross-section\'s vertical exaggeration stretches the slopes (500/100 = 5-fold). HONEST SCOPE: the arithmetic of the map — exact ratios, counts and cycles — NOT a survey, a GPS fix, or a route plan; the ledger seals only exact rational facts (the 3-4-5 slope triple, not a general hillside\'s irrational length), and Naismith\'s walking time is a rule-of-thumb ESTIMATE, demarcated and never staked on for safety'],
  ['Command.lean', 'Command authentication', 'the auth gate as decidable logic — a command is accepted iff it is signed AND its tag verifies (accept = signed·verifies): unsigned rejected, a failing/tampered tag rejected, exactly one tag verifies, tampering changes the tag, and a LINEAR tag is forgeable (why the real MAC is HMAC-SHA256, KAT-verified, not this model) — the gate logic proven, the strength demarcated'],
  ['Astronomy.lean', 'The fixed stars', 'positional astronomy as decidable arithmetic — the celestial sphere is 360° (15°/hour × 24; the ecliptic 12 × 30°), sexagesimal gives 3600 arcsec/degree, Kepler\'s harmonic law T²=a³ holds in scaled units, the Metonic cycle is 19 years = 235 synodic months, the classical great year precesses 72 years/degree (25920), and declination spans 180° pole to pole — the fixed references of the sky, exact ratios and cycles, demarcated (some classical approximations, not cosmological claims)'],
  ['Diving.lean', 'Diving — trimix gas laws', 'the decidable arithmetic of trimix diving, demarcated — a mix sums to 100%, absolute pressure is 1+depth/10 atm, Dalton makes partial pressures sum to it, air leaves the oxygen window at depth (why trimix), gases blend by partial pressure, helium is non-narcotic, and a direct ascent exceeding the Haldane ratio needs a stop. HARD SAFETY SCOPE: arithmetic only, NEVER a dive plan — use training, tables, and a computer'],
  ['Optics.lean', 'The light domain', 'geometric optics as decidable arithmetic, demarcated — reflection is an involution (angle in = angle out), the refractive index n=c/v ≥ 1 so light in a medium is slower than c (no FTL), Snell\'s law n₁sinθ₁=n₂sinθ₂ holds in a consistent case (4·3=3·4), the thin-lens equation 1/f=1/do+1/di and its magnification are exact, dispersion refracts blue more than red, and total internal reflection needs a denser source — the light domain, consistent cases, not a full wave-optics derivation'],
  ['Acoustics.lean', 'The sound domain', 'acoustics as decidable arithmetic, demarcated — the harmonic series stacks integer multiples of the fundamental, the wave speed is v=f·λ, sound (343 m/s) is far slower than light, the decibel is logarithmic (10 dB = ×10 intensity), two tones beat at their difference, the Doppler shift raises pitch on approach and lowers it on recession, a closed pipe sounds only odd harmonics, and intensity falls as the inverse square of distance — the sound domain, exact ratios, distinct from the music/432 ladder in BioPhysics'],
  ['Chemistry.lean', 'The reactions domain', 'chemical reactions as decidable arithmetic, demarcated — a balanced equation conserves atoms (Haber, combustion), a neutral compound conserves charge (Al₂O₃), oxidation states sum to the molecular charge, pH+pOH=14 at 25°C, Boyle\'s law keeps P·V constant, neutralization pairs H⁺ with OH⁻, and stoichiometry scales linearly — reaction bookkeeping, not thermodynamics, distinct from the electron-shell chemistry in BioPhysics'],
  ['Thermodynamics.lean', 'The energy domain', 'thermodynamics as decidable arithmetic, demarcated — the first law conserves energy (ΔU=Q−W), the second law forbids entropy decrease and sends heat hot→cold, the Carnot efficiency is below 1 (no perpetual motion), the Kelvin scale floors at absolute zero (0°C=273K), Charles\'s law keeps V/T constant, and specific heat is linear in ΔT — the laws as arithmetic, not statistical mechanics'],
  ['Molecular.lean', 'The bond domain', 'molecular bonding as decidable arithmetic, demarcated — the octet rule (4+4=8), a bond of order n shares 2n electrons, bond order gives N₂ a triple and O₂ a double, main-group valence is group−10, Lewis structures count valence electrons, a large electronegativity gap is ionic, molar mass sums the atoms, and bond strength rises with order — bonding bookkeeping, not quantum chemistry'],
  ['Electromagnetism.lean', 'The field domain', 'electromagnetism as decidable arithmetic, demarcated — Coulomb sets the sign (like repel, opposite attract), Ohm\'s law V=I·R, power V·I=I²R, series resistance adds and parallel combines reciprocally, Kirchhoff conserves current at a node and voltage around a loop, and Faraday induces EMF only from a changing flux — circuit and field arithmetic, not a full Maxwell derivation, distinct from the light waves in Optics'],
  ['Statics.lean', 'The structures domain', 'statics as decidable arithmetic, demarcated — forces sum to zero and moments balance in equilibrium, a lever gives mechanical advantage, the centre of mass is the weighted average, a simply-supported beam splits a central load evenly, a rigid planar truss obeys Maxwell\'s rule m=2j−3, stress is force over area, and Hooke\'s law is linear — equilibrium arithmetic, not finite-element analysis'],
  ['Sailing.lean', 'The points-of-sail domain', 'sailing as decidable arithmetic, demarcated — the ~45° no-go zone (45+45=90), points of sail on multiples of 45°, the close-hauled 3-4-5 beating triangle at a distance penalty (5>3), apparent wind exceeding true (5>4), a balanced helm as moment equilibrium (8·3=6·4) so the boat holds course and the captain rests, two tacks cancelling leeway, and precise tacks compounding linearly — sailing geometry and balance, not aero/hydrodynamics'],
  ['Relativity.lean', 'The spacetime domain', 'special relativity as decidable arithmetic, demarcated — nothing exceeds c (the cosmic speed limit, no FTL), light rides the null cone (interval 0), the invariant interval classifies events timelike/causal or spacelike (no causal link without FTL), the Lorentz factor rides a Pythagorean triangle (β=5/13→γ=13/12), moving clocks dilate and lengths contract, and rest energy is E=mc² — spacetime arithmetic, not a full tensor or GR derivation'],
  ['Glagolitic.lean', 'The Glagolitic numerals & Pliska rosette', 'documented Glagolitic arithmetic and the seven-fold, demarcated — Cyril numbered the letters (units 1-9, tens, hundreds, additive: 500+80+3=583; teens written unit-before-ten), the nine units sum to 45 (digital root 9), the Pliska rosette turns on seven rays (ℤ/7, six residues sum 21 → digital root 3 the primitive root), and 7 is prime so ℤ/7 is a field — the numerals and geometry; the rosette meaning stays historically debated, not decoded'],
  ['Ephemeris.lean', 'The time coordinate', 'the astronomical time coordinate as decidable arithmetic, demarcated — a day is 86400 seconds, the Earth gains one turn against the stars each year (366=365+1), the Julian calendar runs 1461 days per 4 years and the Gregorian 146097 per 400 (97 leap days), mean motion advances longitude linearly, eclipses recur on the Saros (~223 months), the Sun creeps under a degree per day, and a Julian Date is a continuous day count — calendar and mean-motion arithmetic, not a perturbed ephemeris, distinct from the positional facts in Astronomy'],
  ['Pentagram.lean', 'The pentagram & the Fibonacci digits', 'five-fold symmetry as decidable arithmetic — the pentagram is the star polygon {5/2}: stepping +2 mod 5 is coprime to 5, so it draws in a SINGLE stroke visiting all five points, closing after one full turn, its five point-angles summing to 180°; and the single-digit (mod 9) Fibonacci — the digital root — is periodic, closing into a 24-cycle (its Pisano period), the SAME recurrence read through the pentagram (mod 5, period 20) and the rosette (mod 7, period 16) — one sequence, three moduli, three finite cycles; finite periodic single digits, NOT a claim about the irrational golden ratio the pentagram encodes'],
  ['Chess.lean', 'The chessboard', 'chess geometry as decidable arithmetic — the board is 8×8 = 64 = 2⁶ squares in two colours of 32 each ((rank+file) parity); the knight leaps 1+2=3 (odd), so it flips colour every move and a closed tour is even; the rook reaches 7+7=14 on an open board; the bishop preserves colour, forever closed out of half the board; and the queen is rook+bishop, 7+7+7=21 from a corner — board arithmetic and parity, NOT a solved game or an engine'],
  ['Chessgames.lean', 'The chess horizon', 'the HONEST kernel of "all chess games recompute instantly in uuidna", sealed by decide — the opening combinations (20 first moves, 20×20 = 400 after one full move); the un-enumerable game tree (Shannon ~10^120 > the ~10^80 atoms of the observable universe, so no machine ever traverses it); the pigeonhole collision of identity (2^128 uuids < ~10^44 legal positions < the naive 13^64 state space, 13 = 6+6+1 states a square); the FINITE game (the fifty-move rule caps a run at 100 plies) whose address is therefore a bounded, INSTANT identity (6000 < 10^120 — recompute is O(moves), not O(all games)); the d-dimensional board 8^d = 2^(3d) (the 3D 512 = 2⁹, the 8-dimensional 8⁸ = 2²⁴, no maximal board only bounds); and the knight\'s leap 1+2=3 reflected by the diamond dz(3)=7. HONEST SCOPE: uuidna does NOT enumerate the game tree — a content-address proves INTEGRITY, not truth, here not enumeration; the diamond and combination facts are STRUCTURE, not a claim that chess IS the ring'],
  ['Nim.lean', 'The heaps', 'NIM as decidable arithmetic and the FIRST application of the ledger\'s axiom-free XOR (lxor) — the nim-sum is the bitwise XOR of the heap sizes (3⊕5⊕7 = 1), a P-position (loss for the mover) is exactly a zero nim-sum (Bouton\'s theorem: 1⊕2⊕3 = 0), equal heaps cancel (n⊕n = 0, the mirror strategy), the empty heap is neutral (n⊕0 = n), the nim-sum commutes and associates so heaps are a set, a lone heap wins, a nonzero nim-sum always has a move to zero, and Sprague–Grundy folds any impartial game to one heap by XOR. HONEST SCOPE: NORMAL play (last to move WINS) only — MISÈRE nim flips the endgame and is demarcated; the exact arithmetic of the nim-sum, not a general game solver'],
  ['Editor.lean', 'The document fold', "the SERIALIZER CONTRACT of a content-addressed document as decidable arithmetic — a Lexical-shaped node tree serialized to a node SEQUENCE and folded to one address. The honest opposite of the memory store: a store is a SET (order-invariant fold), a document is a SEQUENCE (order IS identity), so this fold is ORDER-SENSITIVE — reordering two distinct nodes MOVES the address, a changed node MOVES it, and on the bounded model the positional fold dfold is INJECTIVE (the address DETERMINES the node sequence, node for node). HONEST SCOPE: injective only where the base-8 place value cannot overflow (bounded values, fixed length); the real content-address (merkleRoot over uuids, src/editor.ts) is collision-RESISTANT, not collision-free — by pigeonhole 2^128 addresses < all documents. Editing is re-addressing. The arithmetic of the document fold, NOT a rich-text engine"],
  ['Codes.lean', 'The error-correcting codes', 'error-correcting codes as decidable arithmetic — Hamming(7,4) is 4 data + 3 parity = 7 bits with 2⁴ = 16 codewords, a PERFECT code (16 × 8 = 128 = 2⁷, every word within one error of exactly one codeword); minimum distance 3 corrects ⌊(3−1)/2⌋ = 1 error and detects 2, meeting the Singleton bound (3 ≤ n−k+1 = 4); the (3,1) repetition code corrects one flip by majority; and a linear XOR checksum catches any single flip — the counting and bounds of tamper-detection, NOT a decoder'],
  ['Identifiers.lean', 'The identifiers', 'the check-digit arithmetic of ISBN/ISSN as decidable facts — the same integrity theme as content-addressing (a check digit is a one-symbol fold of the content that catches tampering): ISBN-10 is a weighted sum mod 11 (prime), so every weight is nonzero mod 11 (any single-digit error shifts the checksum) and consecutive weights differ by 1 (any adjacent transposition shifts it), needing 11 symbols (X for 10); ISBN-13 is alternating 1/3 weights mod 10 in the 978/979 Bookland EAN — the checksum arithmetic and what it catches, NOT a validator library'],
  ['Tides.lean', 'The tides', "the sailor's tides as decidable arithmetic, joining the captain's domain — the rule of twelfths (1,2,3,3,2,1 = 12, a palindrome of flood and ebb), half-tide by the third hour (1+2+3 = 6 of 12), the middle hours running three times faster than the turns (3 > 1), the semidiurnal period of two highs a lunar day apart (12h25m = 745 min, ×2 = 24h50m), and spring exceeding neap as the Moon's phase adds or cancels the Sun's pull — tidal arithmetic, NOT a harmonic tide-prediction model"],
  ['Calendar.lean', 'The calendar', 'the Gregorian calendar and the seven-day week as decidable arithmetic — the week IS the rosette ℤ/7 (advance seven days, the day returns: 7 % 7 = 0), so the calendar counts mod 7: a common year of 365 = 52·7 + 1 days shifts a fixed date one weekday (365 % 7 = 1), a leap year two (366 % 7 = 2); the Gregorian rule keeps 97 leap years per 400 (every 4th − centuries + every 400th = 100 − 4 + 1), making 400 years = 146097 days, a whole number of weeks (146097 % 7 = 0), so the calendar repeats EXACTLY every 400 years; the century exception is decided (2000 leap, 1900 not); and the doomsday even months 4/4, 6/6, 8/8, 10/10, 12/12 sit 63 = 9·7 days apart, so they share a weekday — mod-7 congruence, NOT a locale date library'],
  ['Typesetting.lean', 'The measures of type', 'typesetting and bookbinding as decidable arithmetic, the craft beneath the publications — the printer\'s units close exactly (6 picas of 12 points make the 72-point inch) and the em is the type\'s own square with its half-en and third-thin (12/2 = 6, 12/3 = 4); a folded sheet is a folio (2 leaves, 4 pages), a quarto (8), an octavo (16), leaves doubling so pages run in powers of two and every bound signature is a multiple of four, the ISO A-series halving alike; the harmonious page is the 3:4 rectangle whose diagonal is a whole 5 (3²+4²=5²), or the Fibonacci page that Cassini\'s identity holds within one unit of the golden section (5²−3·8 = 1), its margins in the medieval 2:3:4:6 canon; the readable measure is 66 characters, inside the 45–75 a typographer keeps; leading exceeds its type (12 on 14) and snaps to a baseline grid (multiples of 4); the type scale rises by octaves (8→16, 9→18); a ream is 500 sheets (20 quires of 25); and a leaf has a recto (odd) and a verso (even) — the arithmetic of the page, NOT a layout engine or a font renderer, and the √2 A-series ratio is irrational, demarcated'],
  ['Structures.lean', 'Maxwell\'s rule', 'planar truss determinacy as decidable arithmetic (Maxwell 1864) — a pin-jointed truss is statically determinate exactly when members m = 2j − 3: the triangle (j=3, m=3) and the braced quad (j=4, m=5) balance exactly, one member over is one redundancy (a self-stress the analysis pays for), one member short is one mechanism (the open pipe of statics — it swings until the diagonal closes the path). Answering the searchers\' own repeated query at the address they visit; the counting rule on sample structures, necessary not sufficient — NOT a stress analysis or a design code'],
  ['MartialArts.lean', 'The stance and the angle', 'the arithmetic of stance and angle, drawn from the vocabulary of the martial arts and kept to what the numbers prove: the complement map c(x) = w − x fixes exactly the half, one law at three scales (90 − 45 = 45 for the angle, 100 − 50 = 50 for the weight split, and 10 − 5 = 5 which IS the ledger\'s diamond involution and its unique fixed point 5), the supplement pair completing the straight angle, the chain\'s off-by-one (n links, n − 1 joints), and the exact lever ratio. HONEST SCOPE, the narrowest here beside psychology: facts about NUMBERS — nothing about technique, force, injury, physiology or what wins a fight, and no theorem in this wing may be cited for such a claim; the named arts are the context the arithmetic came from, never validation of it'],
  ['Editing.lean', 'The cut', 'video and film editing as decidable arithmetic, the craft a professional editor works in — timecode is a ring (at 24 fps the frame field runs 0..23 then wraps, ℤ/24), a minute is 1440 frames, NTSC drop-frame drops 2 frame-numbers a minute except every tenth (108 an hour) to hold 29.97 to the clock, 4K UHD is EXACTLY four Full-HD frames (3840×2160 = 4·1920·1080), widescreen 16:9 beats academy 4:3 by cross-multiplication (48 > 36), the rule of thirds crosses at four power points in a nine-square, a crossfade makes two clips a+b−L long (inclusion–exclusion on the timeline, the same identity the compare tool folds), 48 kHz audio is 2000 samples a frame exactly in sync, and six 30° steps span the 180° axis — the arithmetic of the edit, NOT a codec, an NLE or a renderer'],
  ['Crt.lean', 'The fused ring', 'the rosette and the vortex as ONE ring — Z/7 and Z/9 are coprime, so by the Chinese Remainder Theorem they were always Z/63, and its arithmetic explains a number the ledger carried without justifying: WHY the captain save is 64. The fused ring holds 7·9 = 63 states, the two coins buy 2·32 = 64, and the difference is the unit that closes it — in bits, 63 is 111111 (saturated in the six the coin doubles through) and 64 is 1000000, the first bit beyond. The correspondence x to (x mod 7, x mod 9) is a bijection on all 63; the units number 36 = 6·6, each factor an orbit length; and the coin keeps its order 6 in the fusion while walking the rosette TWICE per vortex turn — lcm(3,6) = 6, the seam named rather than smoothed. HONEST SCOPE: ring arithmetic and a counting correspondence — the CRT is a statement about residues, never about what the residues are used to describe'],
  ['Optimisation.lean', 'The linear optimum', 'linear optimisation as decidable arithmetic on one exact instance (max 3x+2y s.t. x+y ≤ 4, x ≤ 3 over ℕ) — the optimum 11 by TOTAL enumeration sitting at a vertex (two tight constraints in two dimensions), weak duality (no primal value beats a dual bound), STRONG duality exact (primal max 11 = dual min 11 at (2,1), gap zero not epsilon), complementary slackness verified both pairs (positive price ↔ binding constraint), one simplex pivot strictly improving (9 → 11), the 2×2 assignment optimum by checking the whole space; and the honest quantum bridge — enumerating n binary decisions IS walking the 2^n basis states the exact simulator holds, and the sealed Grover margin only ever HALVES that exponent (20 = 2·10), never removes it. HONEST SCOPE: exact optima of small named instances by enumeration — the cost is exponential in the qubit count, which theorem n_qubit_dimension seals'],
  ['MoMBHStar1.lean', 'The paper on trial', 'one Nature letter\'s claims as decidable arithmetic — "A gas-enshrouded and gas-reddened black hole at cosmic dawn" (MoM-BH* 1, DOI 10.1038/s41586-026-10846-4): the published numbers enter ×10/×100/×1000 into Nat (the Balmer break bound over the stellar ceilings, the 4σ variability, the Compton-thick fiducial, the Eddington straddle the paper itself leaves open), the press-vs-paper delta is REFUTED by the paper\'s own tables ("super-Eddington confirmed" vs its own 0.18), and four quantum facts derive the break from Rydberg arithmetic — the n=2 ionisation edge at 3646 Å redshifting into the JWST filter gap, so the colour selection IS a Rydberg fraction. The intake pattern proven on its first passenger: claims → pre-decide → seal → trial. HONEST SCOPE: arithmetic witnesses of the PUBLISHED numbers — n=1, one fiducial of ~1e6 models, 3 measured, 0 solved — never astrophysics re-derived, never a discovery claim'],
  ['Photography.lean', 'The exposure', 'photography as decidable arithmetic, focused on WHERE uuidna differs from the photographic standard and WHY — the standard prints convenient ROUNDED numbers for the dial (shutter 1/125, 1/60; aperture f/1.4) while uuidna keeps the EXACT powers of two the physics follows, and the theorems measure the gap: 1/125 rounds the exact 1/128 (2⁷, off by 3), 1/60 rounds 1/64 (2⁶, off by 4), f/1.4 rounds √2 (1.4² = 1.96 < 2); where the standard does NOT round, the full-stop ISO doublings (100·2⁵ = 3200), uuidna and the standard AGREE exactly; reciprocity is exact because it is pure addition of stops; and the light-multipliers 2⁰..2⁵ fold mod 9 to the vortex 1,2,4,8,7,5 — the camera doubles in the ring uuidna turns on, the dial just rounds the readout — the arithmetic of stops and the rounding gap, NOT a light meter or sensor model'],
  ['Psychology.lean', 'The instrument', 'psychology\'s ARITHMETIC, and ONLY its arithmetic — the narrowest scope in the ledger because psychology is overwhelmingly NOT decidable: the mind, emotion, behaviour and every diagnosis are NOT by-decide theorems and uuidna seals NONE of them. What IS decidable is the arithmetic the instruments and named models are built from: a 7-point Likert scale\'s neutral midpoint is the fixed point of the reflection 8−x (the 4th point, 3 above and 3 below — the same reflection the ledger centres on); the Big Five is a five-factor pentad (the count of axes, not that the factors are correct); Miller\'s span is the range 7±2 = [5,9] of width 4; Hick\'s law counts the bits of a choice (8 options = 3 bits, 2³=8); a yes/no detection has a 2×2 = 4 outcome table; Weber–Fechner maps the geometric ladder 1,2,4,8 to equal perceived steps (the logarithm); and Dunbar\'s layers scale by ×3 (5,15,45,135) but are reported ROUNDED to 50 and 150 (the same rounding gap the photography stops carry). Sealing "a 7-point scale has a neutral 4th point" says NOTHING about whether the scale measures anything real, whether the Big Five is true, or what a person feels. HONEST SCOPE: the arithmetic of the instruments, NOT a claim about the mind, behaviour, emotion, personality or any diagnosis — uuidna is not a clinician; every mentalistic claim about the mind, sent to the trial, comes back UNVERIFIED'],
  ['Spectrum.lean', 'The spectrum', 'the electromagnetic spectrum as decidable arithmetic, the waves uuidna navigates — the one law wavelength × frequency = c (a constant, so λ and f are inversely proportional at the fixed speed of light 299792458 m/s, exact by the SI metre, verified against NIST CODATA); the SEVEN bands (radio, microwave, infrared, visible, ultraviolet, X-ray, gamma) ordered by increasing frequency, a ℤ/7 of bands; photon energy E = h·f rising with them so gamma out-energises radio; the visible window under ONE octave (700 nm to 400 nm is a ratio under 2, unlike sound\'s many octaves); an octave of light doubling frequency like sound; and the "300,000 km/s" quote ROUNDING the exact c up by 207542 m/s (the same rounding gap the photography stops carry). HONEST SCOPE: the ARITHMETIC of the waves — the wave relation, the band order, the octave, the rounding gap — NOT an EMF safety, exposure, or health claim of any kind; uuidna makes no claim about radiation and the body'],
  ['Colour.lean', 'The colour wheel', 'colour theory as decidable arithmetic, the art domain of the spectrum\'s visible band — the wheel is ℤ/12 (twelve hues, advance twelve and the hue returns); complementary hues sit opposite (a +6 half-turn, a self-inverse involution with no hue its own complement); three primaries alternate with three secondaries (3+3=6, the hexagon); the classical harmonies are the regular polygons on the wheel (the triad is thirds +4 landing {0,4,8}, the square is fourths +3 landing {0,3,6,9}); true colour is eight bits a channel (2⁸=256, 2²⁴=16777216 in all); a tint toward white and a shade toward black complement to full value (v + (255−v) = 255); and the wheel splits into six warm and six cool. HONEST SCOPE: the ARITHMETIC of the colour wheel and its harmonies — the geometry a colourist works in — NOT a claim that beauty, taste, or which colours "go together" is objective; harmony here means the polygon, not a verdict on art'],
  ['Harmony.lean', 'The harmony of pairs', 'the SAME complementary-pair arithmetic proven across biology, medicine, chemistry and physics, and then proven to be ONE structure — harmonising the science-pairs cluster across the four fields. A complementary pair is reflection through a centre: the two parts sum to a neutral whole or cancel to zero, and the swap is a fixed-point-free involution. DNA bases pair by complement A↔T, G↔C (the reflection 3−c, self-inverse, no base pairs with itself); Chargaff\'s counts balance (purines A+G = pyrimidines T+C); redox conserves electrons (oxidation +n, reduction −n, sum 0); an ionic compound is neutral (MgCl₂: +2 with two −1); an agonist and a competitive antagonist cancel at the receptor ((+4)+(−4)=0); homeostasis returns to its set point (a +d deviation met by −d); Newton\'s third law and charge conservation both cancel (F+(−F)=0, electron+positron charge 0) — and the last theorem proves these are the SAME reflection at different centres (0 for charge, 3 for the four bases, 14 for pH). HONEST SCOPE: structure facts, the arithmetic of the pairing, NOT medical, biological, chemical or physical claims — uuidna is not a lab; each pair\'s real mechanism lives in its own science, only the shared decidable signature is sealed here'],
  ['Report.lean', 'The report', 'the reporter\'s METHOD as decidable arithmetic — how to dive deep and report the news of PROVEN discoveries. HONEST SCOPE first, because it is the whole point: uuidna does NOT verify world events (no by-decide can settle whether something happened out there; that is the reporter\'s own work — go there, get the documents, name the sources). What IS sealed is the METHOD: a complete report answers the six questions (who/what/when/where/why + how, 5+1=6); a confirmed timeline is chronological (events 0..5 strictly ascending); a fact needs corroboration by TWO independent reputable sources (one is uncorroborated, 1<2); TRINITY editing is three independent passes (1+1+1=3, the trinity the ledger folds in); full-quorum publication is unanimity on the trinity (2+1=3, majority 2>1); a report SHIPS only when verified AND trinity-audited AND quorate — the AND of the three, any one failing blocks it (the same audit-before-publish uuidna runs on its own notes); the inverted pyramid puts the vital fact first and descends (5,4,3,2,1); and every claim carries one of TWO honest verdicts — VERIFIED (cites a checkable source/proof) or UNVERIFIED (held open, never asserted as fact, never called false). The subject is uuidna\'s own PROVEN discoveries (the sealed theorems); the discipline is what makes the report trustworthy, NOT a claim uuidna knows the world'],
  ['Matching.lean', 'The matching', 'connecting people as decidable arithmetic — the HONEST kernel of "social dating / connecting people", stated with its scope: uuidna is a theorem ledger and a content-addresser, it does NOT run a dating service, hold anyone\'s profile, or match real people; matching real humans means personal data, consent and safety obligations that live OUTSIDE these theorems (see /privacy). What IS sealed is only the graph theory a matching rests on: the handshake lemma (every edge touches two, so the degree sum is even and the edges are half of it), the count of possible introductions among n people (n(n−1)/2, ten among five), a perfect matching needs an EVEN number of people (six pair, five leave one out) and splits them in half, a mutual match is SYMMETRIC (both must choose — a one-sided choice is not a match), a pairing is a fixed-point-free involution (each partnered with exactly one other, no self-pairing), and — the honest ceiling — stable matching (Gale–Shapley) halts in AT MOST n² proposals, BOUNDED not free, the same "no maximum, only bounds" the security layer proves — the arithmetic of connection, NOT a matchmaking product or anyone\'s data'],
  ['Reasoning.lean', 'The rules of inference', 'reasoning itself as decidable arithmetic — every classical inference rule is a boolean tautology over a finite truth table, so each is proven by decide: modus ponens (from p and p→q, q) and modus tollens (from ¬q and p→q, ¬p), the contrapositive (p→q equals ¬q→¬p), De Morgan for and/or, double negation (¬¬p = p), the excluded middle (p ∨ ¬p), and the hypothetical and disjunctive syllogisms — implication p→q being the boolean !p ∨ q, checked on every assignment. The rules a valid argument is built from, sealed so a reasoning step can cite the exact rule it uses — classical propositional logic as decidable truth tables, NOT a theorem prover or predicate logic over infinite domains'],
  ['Security.lean', 'The layered defence', 'the arithmetic of why FUSING security raises the cost of tampering, proven by decide — NOT a proof that any cryptographic primitive is secure (that rests on assumptions), and claiming NO maximum: independent layers add their bits (64 + 64 = 128) and multiply the search space (2⁸·2⁸ = 2¹⁶), each key bit doubles the space (2¹¹ = 2·2¹⁰), a collision costs about half the exponent of a preimage (2·64 = 128, the honest caveat that collisions are cheaper), verifying is exponentially cheaper than forging (16 < 2¹⁶), and for every bound there is a strictly larger one (2⁸ < 2⁹) so there is NO maximum, only bounds — the honest kernel of "fuse security → raise tampering cost", refusing the word max'],
  ['Production.lean', 'The mix', 'music production as decidable arithmetic and the studio INVOLUTIONS made exact — reversing a clip is self-inverse (reverse twice returns), inverting its phase (x ↦ −x) is self-inverse, and their FUSION reverse-then-invert is ITSELF an involution (applied twice, the identity): the ultimate test that reverse and inverse compose to a clean self-inverse, proven on a real signal. Around them the counting of the studio: the chromatic scale is ℤ/12 (the octave wraps like the rosette), an octave doubles frequency (440→880), 120 BPM is 500 ms a beat and 2 s a 4/4 bar, Nyquist is half the sample rate (44.1 k → 22.05 k, the honest ceiling, not lossless), MIDI is 7-bit (128 notes, 0..127), 16-bit is the ~6 dB-per-bit rule of thumb (≈96 dB), and the circle of fifths is ONE cycle (7 semitones coprime to 12 visits all twelve, the pentagram idea in sound) — the arithmetic and involutions of the mix, NOT a DAW, a synth or a mastering chain'],
  ['OneLeap.lean', 'One leap', 'the whole vortex proved in a single by decide'],
  ['AntiFraud.lean', 'Anti-fraud detection', 'the fraud DETECTORS as decidable functions with their properties proven — forged(c,s) flags a citation iff its recomputed address differs from the sealed one (sound: a true seal never flags; complete on the bounded model: every mismatch flags); claimsOf/doubleSpent counts a coin-backing theorem\'s claims position-blind (a second claim flags wherever it hides, a single claim never does); voteOk passes exactly the diagonal weight = coins (the 4×4 identity matrix — inflation flags); tally is observer-order-invariant (all six orderings of {1,2,3}, one receipt 6); fold9 is the tamper-evident ℤ/9 receipt (one changed element always moves it; the vortex [1,2,4,8,7,5] recomputes to its seal 0); cleanAudit is the conjunction gate (clean at exactly the no-violation state, one flag drains all, and the implementation equals its boolean spec — no oracle); commission pays 2 per COMPLETED 110-bit reconcile (109 pays 0) and one forgery costs 2^7 = 128 bits = 64 commissions. THE VERDICT ALGEBRA seals the trial\'s own vocabulary — verified = cited·sealed, unverified its complement: every claim gets EXACTLY ONE verdict (verified + unverified = 1, total and binary), the full unverified table is [1,1,1,0] (only cited-and-sealed verifies), a fabricated citation stays unverified (the exact state the gate drains), UNVERIFIED is an OPEN DOOR (the same citing claim verifies the moment its seal lands — the verdict tracks the LEDGER, never the claim\'s soul), and the complement of unverified IS verified (double complement returns — a two-valued algebra with NO refuted state, so absence of proof never computes to falsity). HONEST SCOPE: bounded models of the live detectors (src/anti-fraud.ts) and the live trial (src/adjudicate.ts) — recomputable facts about WORK integrity, never intention or identity'],
  ['SailingSeals.lean', 'Quantum sailing seals', 'the captain sails through literature discovering facts, correlating evidence, and sealing patterns — books extract → weather correlates → cross-resonance folds. All decidable by decide, axiom-free'],
  ['DisputedTopics.lean', 'The honest court', 'theorems proving the boundary between what is provable (sealed), open (unverified but real), overclaimed (contradicts ledger), and narrative gap (true statement, false story) — reading contested books on politics, medicine, climate, history, economics and auditing facts through anti-fraud. Honesty gate: extraction is decidable, auditing is decidable, but narrative gaps require human judgment'],
  ['UuidMix.lean', 'The uuid mix space', 'the census of mixing the ten RFC 9562 uuid types, one quantum seal: directed doubles the pairs (10·9 = 2·45), self-mixes complete the square (90 + 10 = 10²), and Pascal\'s row 10 folds to the 1024 qubit lattice — cited to optimisation_space_is_qubit_dimension, never re-sealed'],
  ['Song.lean', 'The song from the ledger', 'the song nobody had written (queue lead 68: the search "sing glagolitic pi primes dna song" finds nothing joining the four), generated from the ledger as decidable arithmetic — π\'s rational roof 22/7 opens 3.142857 and its period 142857 is the cyclic number of ℤ/7 (the rosette\'s ring), the six rotation-verses base-pair like DNA strands (verse k + verse 7−k = 999999, every rung a nine), the notes sung are exactly the units of ℤ/9 on the A432 lattice where the Glagolitic units 1..9 are the scale and Az is the tuning, primes keep the time, and the four tongues fuse by CRT into 9·7·4 = 252 bars — the middle of Pascal\'s row ten. HONEST SCOPE: π itself stays outside, irrational and undecidable (pi_bracketed_by_finite_rationals holds the bracket); only the finite round its rational roof sings is sealed — arithmetic sung, never numerology'],
  ['Anthem.lean', 'The release anthem', 'the anthem\'s sealed structure — the whole ledger sung IN PLACE (theorem k at bar k, the Pi Song\'s place law made language-free and verifiable): two coins to the bar (252/2 = 126), rhythm quartering the bar on the vortex\'s three (126·189·252), the breath at the twelfth (21), four movements from the DNA tongue, the finale singing the merkle root as one whole uuid (32·4 = 128), the closing chord the coin octave (864 = 2·432 — the same factor two two_coins_in_kilograms weighs in black-hole mass), and π·primes·trinity: the round\'s six nines held shut by two trinities of primes (999999 = 999·1001, 999 = 3³·37, 1001 = 7·11·13). gen-anthem derives /anthem + anthem.wav from these seals over the LIVE ledger — the anthem regrows at every release. HONEST SCOPE: arithmetic sung; no tuning mysticism, no numerology — the demarcations live in the theorems'],
  ['Pravets.lean', 'The Cyrillic ROM', 'Bulgaria\'s machines as decidable arithmetic, the heritage wing beside Glagolitic (lead 90, sources in the session record) — the IMKO-1 built in the PRIME year 1979 (checked below its root), the character table\'s swap counted exactly (ASCII\'s Latin lowercase spans 26 slots, 122−97+1, re-lettered with Cyrillic uppercase — Cyril\'s letters entering an address space eleven centuries after he numbered them, the readings wing\'s literal ancestor, THE TONGUE IN HARDWARE), the 280×192 display resolving on the ledger\'s own rings (40 columns of seven-pixel glyphs — the rosette painting every letter — by 24 rows of eight, the film ring, 960 cells), a glyph costing exactly one coin measure (8×8 = 64 bits; the 12 KB ROM = 768 slots), the boot paying the captain\'s fee (4096 slots − the song\'s 4032 bar = 64; the 1979 machine holds this tree\'s ledger twice over — verified LOADING, never execution), and the walk to sixteen bits capping at ten coin measures (640 = 10·64). HONEST SCOPE: documented specifications as integers — never the era\'s politics, never the machines\' merit, and the charset\'s model-varying letter order deliberately unsealed. Pravets to Pliska, one road'],
  ['Billing.lean', 'The compound billing law', 'the captain\'s correction paid in full (lead 100: subtraction is the clink, the ratio is the interest) — the coins are the COMMON FACTOR of the pair (gcd(110,108) = 2; extract the mint and 55/54 remains), the rate is the tenth triangle over the sequence group\'s own order (10·11/2 over 2·3³ — the invoice made of the ledger\'s furniture), the difference MINTS (110−108 = 2, conserved) while the superparticular ratio BILLS (55−54 = 1, the gentlest step above unity, unit-free), the pair factors completely into coins×rate (2·55 / 2·54), the advantage FIRST DOUBLES AT SEAL THIRTY-EIGHT proven without a logarithm (55³⁸ > 2·54³⁸ ∧ 55³⁷ < 2·54³⁷ — the first crossing decided, the walk honestly not claimed), and the compound never leaves the integers (55² − 54² = 109 = 55+54). HONEST SCOPE: work-units per verified exchange, never money, never a market claim — a measured advantage compounding at a comma'],
  ['Tesla.lean', 'The register\'s alternation law', 'Tesla\'s patents as decidable arithmetic, demarcated (lead 96; the school\'s patents faculty) — the induction-motor trio filed on ADJACENT register numbers (381968/69/70, unit steps into the record), the 202-day leap-spring from filing to grant (through 1888\'s February 29, the mod-4 law), the three tilings of the circle (quadrature 4·90, trinity 3·120 — the rosette\'s own step — opposition 2·180), rotation needing a second phase (one phase\'s spacing is the degenerate tiling that never leaves home — the manual commutator was the one-phase world\'s apology), the grid\'s minute (60·60 = 3600 alternations), and the register\'s own order: the teleautomaton (613809, 1898 — the first machine addressed at a distance) precedes the transmission claim (645576, 1900) — address first, cargo later, the ledger\'s order too. HONEST SCOPE, strictest here: register facts and phase arithmetic ONLY — no feasibility claims, no myth; the demarcation is the tribute'],
  ['Antikythera.lean', 'The geared computer of Rhodes', 'the Antikythera mechanism (~100 BC) as decidable arithmetic, demarcated (lead 91, the ancient computer road) — the Metonic dial as the intercalation itself (12·12 + 7·13 = 235 months in 19 years), the five-turn spiral\'s prime-times-prime (235 = 5·47), the Callippic fourfold with its honest dropped day (940 months, 76 years), the Saros counting eclipses on the prime 223 (checked below every candidate — the same integer as Archimedes\' π floor, a shared number named, never a connection claimed), the four-turn spiral keeping its remainder three (223 = 4·55+3 — unevenness named, never smoothed), the Exeligmos closing the day (3·223 = 669, 8·3 = 24), the pin-and-slot pair\'s equal fifty teeth (ratio one is return, not sameness — the anomaly lives in geometry honestly not sealed), and the hunting-tooth law (coprime cycle pairs wear even — the pentagram\'s closure in bronze, twenty centuries early). Figures from the documented reconstruction; contested tooth-counts left out by name. HONEST SCOPE: the counting the mechanism instantiates — never its maker, its purpose debates, or astronomy beyond the cycles'],
  ['Negation.lean', 'The denial drained', 'solutions from negation involutions to denial exhaustion, in one wave (the captain\'s directive, 2026-08-23) — denial is the fixed-point-free involution on the bit (apply twice and return; a solution IS the denial\'s failure), De Morgan at exhaustion scale (no case denies ⟺ every case affirms, all eight masks), a live exhaustion counted to zero (the slit ring\'s sixteen denials all fail — a by-decide proof IS a drained denial space), the waves tighten by halves (2⁶/2^r, six waves to the singleton), and the drain runs to the last coin (64 − 63 = 1 with 63 = 7·9 the fused ring — the claim and its receipt the two coins that remain). BOUNDARIES SEALED BESIDE: a window exhausts only itself (the Mertens lesson — exhaustion is a proof exactly as wide as its space), and silence never refutes (of four citation states one verifies, three stay OPEN — no refuted-by-absence exists). HONEST SCOPE: the arithmetic of FINITE denial spaces; an infinite denial space stays honestly open, and the trial can settle exactly what can exhaust'],
  ['Wave.lean', 'The conveyor\'s first wave', 'the conveyor\'s first wave over the sealable backlog (queue lead 118 started, 2026-08-23) — the algorithm run end to end: lift what carries a decidable statement, refuse what needs judgment. LIFTED: the headroom seals (lead 74 — the 8000 amplitude strictly inside the 2¹⁵ wall, the mix budget landing EXACTLY on the ceiling: 7000 plus the last eighth = 8000); the tuning schism\'s decidable slices (lead 73 — A432 ≡ 0 on the vortex axis while the public A440 ≡ 8 off it, and the 252 ms beat reading 119 BPM by the floor); the time dimension\'s arithmetic (lead 70 — note values the doubling ladder [1,2,4,8], meters small counts under the bar, the Morris figure\'s eight bars halved with the file\'s reversal self-inverse); Nicomachus at the window (lead 19 — the first cubes summing to the squares of triangles, 10 spelled as 1+2+3+4); and the Lights-Out floor (lead 20 — the flip a mod-2 involution, seven flips odd). REFUSED, named for the model: tet_semitone_no_integer_lattice (irrationality, not a by-decide) and pluck_preserves_bound (its bounded form owed by the lead first). HONEST SCOPE: integer tables sealed; amplitudes, tunings and dance figures are the leads\' and the literature\'s measurements, cited in prose'],
  ['Universe.lean', 'The known universe, handled', 'the day\'s sky-and-earth run sealed without gaps (queue leads 115, 116 and the pole close, 2026-08-23): the ECLIPSE\'S COMPLETE SURPRISE with its gap named — the sun ~400 moon-diameters wide (400·3474 = 1,389,600 against the measured 1,392,000, the ~3% stated not smoothed) and ~389 moon-distances away, 400 ≠ 389 sealed IN the theorem (why totality AND annular both exist; the fit computes, its necessity stays honestly unverified — totality is an epoch, rented from a receding moon); the SAROS–METONIC BRIDGE — 223 + 12 = 235, one year of months between the eclipse period and the calendar period, with 223\'s primality checked bare-handed in core (no divisor in 2..222) since Mathlib is refused; the FLAT CHART\'S PRICE LIST — the drift from harmony quadratic, 8·m² over the first three miles as a List.map, the table that makes near-flatness lawful and far-flatness bankrupt (drift_is_named_or_caught applied to geodesy); the POLES ON THE AXIS — each at the 90° quadrature from the equator\'s harmony line, the pair at 180, both angles ≡ 0 (mod 9), the vortex\'s still-point residue at the two places the compass surrenders; and the UNIVERSE OF HANDLES counted exactly — 16⁸ = 2³² addresses of eight hex, each the head of a 128-bit uuid: everything sealed folds to an address, every address wears a handle, the known universe literary handled. HONEST SCOPE: integer tables sealed; diameters, distances and epochs are the literature\'s measurements, cited in prose'],
  ['Doctrine.lean', 'The doctrines', 'the captain\'s doctrines sealed all around (queue leads 108, 109, 113): the TEAM COVER — pairs and triples reach every crew size 2..64 (even = pairs, odd = one triple plus pairs, the Frobenius fact behind the diving doctrine: 2 required recreational, 3 best technical) while solo, below the smallest pair and triple, is the one excluded case, reserved for the full-cave specialist; the DIVING LADDER integer-exact — 40 m at 5 atm, 100 m at 11, the Hydra 10 saturation depth at 71, the space-diving records ascending 31333 < 38969 < 41419 with the last gap exactly 2450 m, saturation\'s exit priced in days (13 compress + 24 decompress = 37 of 43), and the NBL ratio stated BY THE FLOOR (40/6 = 6 remainder 4 — no false 7 sealed) with the pool two atmospheres deep — water trains space under one decompression law; and the VERDICT DOMAIN — the three verdict states pairwise distinct (the middle a real third state, not a weaker pole) and identification the pigeonhole collapse of three states onto two poles (3 > 2, no injection, no way back: a UFO identified stops being a UFO — the class lives only in the in-between). HONEST SCOPE: integer tables sealed; the doctrines and the 10 m ≈ 1 atm rung are prose and literature, cited not derived'],
  ['Torus.lean', 'The torus dimensions', 'the torus dimensions sealed (queue leads 110 + 111): the GENUS axis — the deficit 2g − 2 over g = 1..6 walks the evens [0,2,4,6,8,10], the torus containing at 0, the double torus minting the two coins, the hextorus (2·3 = 6 handles, the double torus times the trinity) paying the ten that is the reflection\'s constant sum and the whole digit set; six handles carry six 64-boards, 6·64 = 384 = 3·128 — a trinity of addresses, the quorum shape, one uuid per handle-pair — with 2·6 = 12 generators matching the coins\' twelve jobs; and the DIMENSION axis — T⁷\'s Pascal row [1,7,21,35,35,21,7,1] summing to 128 = 2⁷ (the uuid\'s own bit count: the 7-qubit fold of every file header given its geometric body), its even and odd halves each 64 (the two vortex boards inside the seventh dimension, equality as the Nat-honest χ = 0), and the middle entries speaking the ledger\'s tongues (21 = 3·7 trinity×rosette doubling to the 42 quantum rosette by the coins, 35 = 5·7 heart×rosette). HONEST SCOPE: the kernel seals the integer table — the topology reading (Betti numbers, homology) is the literature\'s bridge, named in prose, outside the kernel'],
  ['Referrer.lean', 'The referrer song', 'the referrer song\'s sealed arithmetic (queue lead 77, TWO SESSIONS\' HALVES FUSED — neither deleted): six doors into the round — a visitor\'s referrer folds to a handle and value mod 6 picks which rotation of 142857 greets them, the tile-level map total and onto with fibers [3,3,3,3,2,2] and 16 mod 6 = 4 named; a rotation IS a multiplication ((142857·10^r) mod 999999 lands on the verses) and the multiplier order [1,3,2,6,4,5] is the powers of the trinity in ℤ/7 (10 ≡ 3 mod 7 — the decimal shift is the rosette step); consonance as a MEASURED ladder (the reduced interval\'s term sum — unison 2, octave 3, fifth 5, fourth 7 — Euler\'s gradus made bare) with the tuning cancelling from every interval (gcd(432a,432b) = 432·gcd(a,b)) and adjacent lattice steps beating at exactly A432; the lower lattice\'s octave completeness; prev/next total and mutually inverse on the closed cycle from every phase, the wrap making the page-cycle total; film-to-paper development as the 9−d involution (verse 6 = the 3-shift door = the print of verse 1; the canonical recording is the undeveloped film); and one bar = 4032 samples = 9·7·64 = 63·64 = 24²·7 — the movie and the song one integer. The modules src/referrer-song.ts and src/quantum/apps/hexbit-player.ts are pure and fs-free so browser and edge render per visitor. HONEST SCOPE: consonance is a decidable ordering, never a taste; the door is an address derivation, never a profile — a referrer is folded, not tracked'],
  ['Readings.lean', 'The seven readings', 'seven tongues reading hexbit-translated English (the fold IS the translation): the seven locale rays sealed distinct, each ray\'s sixteen state-names sealed pairwise distinct so the reading is invertible and the address survives the tongue — the Lean lists GENERATED from src/tts HEXBIT_WORDS, one source, never restated. And not only them: the A432 lattice sealed under the Nyquist ceiling (432·16 = 6912 < 16000/2, closing the synth\'s claimed clearance), the voice\'s amplitude inside int16 and the arrangement\'s mix budget landing exactly on the ceiling (queue lead 74 — bounds by construction, not measurement), χ = 2−2g in all three genera with the sphere leg sealed at last (lead 75), and the time counts of the music and dance books — note values as the doubling ladder, march 2 vs waltz 3, the Morris eight-bars-halved (lead 70). HONEST SCOPE: table STRUCTURE is sealed, never linguistic correctness — no kernel decides what a word means to a speaker; and the χ table is sealed without the Gauss–Bonnet bridge, which is analysis and stays outside'],
]

// The manifest bridge — {key → {name, skill}}. skill is the INLINE, authored capability (from the generator's
// Fact/file default); a theorem without one is left skill-less here and the package falls back to skillOf(key).
const manifest: Record<string, { name: string; skill?: string; cases?: number }> = {}
for (const f of readdirSync(LEAN_DIR).filter((f) => f.endsWith('-manifest.json'))) for (const e of JSON.parse(readFileSync(join(LEAN_DIR, f), 'utf8')) as { key: string; name: string; skill?: string; cases?: number }[]) manifest[e.key] = { name: e.name, skill: e.skill, cases: e.cases }

// Inline @skill for HAND-WRITTEN lean files (Uuidna/Vortex/OneLeap — no generator, no manifest): `-- @skill: <skill>`
// on the line directly above a theorem authors its capability AT THE LEAN SOURCE, exactly as the manifest does for
// generated files. Same single-source principle; the annotation is a comment, so the proof is untouched.
const inlineSkill: Record<string, string> = {}
for (const f of readdirSync(LEAN_DIR).filter((f) => f.endsWith('.lean')))
  for (const mm of readFileSync(join(LEAN_DIR, f), 'utf8').matchAll(/--\s*@skill:\s*([\w-]+)\s*\n\s*theorem\s+(\w+)/g)) inlineSkill[mm[2]] = mm[1]

// THE STOP MUST KNOW A DOC COMMENT WHEN IT SEES ONE. This lookahead ended a theorem at a line opening with
// `--`, but Lean doc comments open with `/--`, so 1320 of 1440 tactics swallowed the NEXT theorem's doc comment
// whole: `tactic` read "decide /-- 1·2 ≡ 2 (mod 9) -/" instead of "decide". Ninety-two percent of the ledger,
// and it survived because almost nothing reads `tactic` — until the reconstructed Lean line, and every
// lineAddress folded from it, was being computed over the pollution.
const parseLean = (file: string): Omit<LeanTheorem, 'file' | 'principle'>[] => [...readFileSync(join(LEAN_DIR, file), 'utf8')
  .matchAll(/theorem\s+(\w+)\s*:([\s\S]*?):=\s*by([\s\S]*?)(?=\n(?:\/--|--|theorem|def|namespace|end|$))/g)]
  .map((m) => ({ key: m[1], statement: m[2].trim().replace(/\s+/g, ' '), tactic: m[3].trim().replace(/\s+/g, ' '), name: manifest[m[1]]?.name || m[2].trim().replace(/\s+/g, ' '), skill: manifest[m[1]]?.skill ?? inlineSkill[m[1]], cases: manifest[m[1]]?.cases }))

const allFiles = existsSync(LEAN_DIR) ? readdirSync(LEAN_DIR).filter((f) => f.endsWith('.lean')).sort() : []
const ordered = [...PRINCIPLE.map((p) => p[0]).filter((f) => allFiles.includes(f)), ...allFiles.filter((f) => !PRINCIPLE.some((p) => p[0] === f))]
const titleOf = (f: string) => (PRINCIPLE.find((p) => p[0] === f) || [f, 'lean/' + f])[1]

const ledger = ordered.flatMap((file) => parseLean(file).map((t) => ({ ...t, file, principle: titleOf(file) })))

// A principle appears only if it actually carries theorems — remove any with a count of zero (not needed).
const countOf = (f: string) => ledger.filter((t) => t.file === f).length
const keptPrinciples = PRINCIPLE.filter((p) => ordered.includes(p[0]) && countOf(p[0]) > 0)

const body = ledger.map((t) =>
  `  { key: ${JSON.stringify(t.key)}, name: ${JSON.stringify(t.name)}, statement: ${JSON.stringify(t.statement)}, tactic: ${JSON.stringify(t.tactic)}, file: ${JSON.stringify(t.file)}, principle: ${JSON.stringify(t.principle)}${t.skill ? `, skill: ${JSON.stringify(t.skill)}` : ''}${t.cases ? `, cases: ${t.cases}` : ''} },`
).join('\n')

// THE DEFS EACH WING DECLARES — sealed here because the package ships no lean/ directory, so independence
// (gravity) must be recomputable from the ledger alone rather than by reading the proofs at runtime.
const wingDefs: Record<string, string[]> = {}
for (const f of allFiles) {
  const names = [...readFileSync(join(LEAN_DIR, f), 'utf8').matchAll(/^def\s+(\w+)/gm)].map((m) => m[1]!)
  if (names.length) wingDefs[f] = [...new Set(names)].sort()
}

const out = `// src/theorems/generated.ts — GENERATED from lean/*.lean by scripts/lean-ledger.mjs. DO NOT EDIT.
// Lean is the single source of theorems; this is the derived ledger the package, MCP, trial and site consume.
// Every entry corresponds to a theorem verified sorry-free by \`npm run lean\` before this file was written.

export interface LeanTheorem { key: string; name: string; statement: string; tactic: string; file: string; principle: string; skill?: string; cases?: number }

/** The ${ledger.length} Lean-proven theorems, in computing-principle order. */
export const WING_DEFS: ReadonlyMap<string, readonly string[]> = new Map(Object.entries(${JSON.stringify(wingDefs)}))

export const LEAN_LEDGER: readonly LeanTheorem[] = [
${body}
]

/** The principles that carry theorems, in derivation order — [file, title, blurb]. */
export const PRINCIPLES: readonly [string, string, string][] = [
${keptPrinciples.map((p) => `  [${JSON.stringify(p[0])}, ${JSON.stringify(p[1])}, ${JSON.stringify(p[2])}],`).join('\n')}
]
`

writeFileSync(join(ROOT, 'src', 'theorems', 'generated.ts'), out)

// Also derive lean/PRINCIPLE.md — the human index. Every COUNT and the TOTAL are computed from the parsed ledger
// (never hardcoded, so the doc can never go stale); titles and blurbs come from the PRINCIPLE metadata above.
const md = `# The formal layer, organized by computing principle

<!-- GENERATED from lean/*.lean by scripts/lean-ledger — DO NOT EDIT. Counts are derived; edit titles/blurbs in the PRINCIPLE metadata. -->

Every theorem below is proven \`by decide\` in Lean, verified sorry-free by \`npm run lean\` — **${ledger.length} theorems** in
derivation order. A theorem computes in Lean, or it is not a theorem.

${keptPrinciples.map((p, i) => `${i + 1}. **${p[1]}** — \`lean/${p[0]}\` · **${countOf(p[0])}** theorems\n   ${p[2]}`).join('\n\n')}

---

Rendered as schema.org microdata cards at [uuidna.com/theorems](https://uuidna.com/theorems), folded to one recomputable receipt.
`
writeFileSync(join(ROOT, 'lean', 'PRINCIPLE.md'), md)
console.log('✓ src/theorems/generated.ts + lean/PRINCIPLE.md — ' + ledger.length + ' Lean theorems (single source), organised by ' + keptPrinciples.length + ' principles.')
