#!/usr/bin/env node
// @non-harmonic: one MCP call per piece to the named deposit door — NAMED boundary (like receipt-deposit).
//
// ledger-deposit — THE WHOLE LEDGER, DEPOSITED WHERE THE EDGE READS IT. Runs after lean-ledger. The ledger is split
// into pieces (src/edge-ledger.ts ledgerPiecesOf — one per wing, a pageless wing per hex digit, in ledger order), each
// deposited through the MCP door as uuidna_evidence {run: 'ledger', deposit: piece}; the door addresses it by its
// content and writes it to qpu storage at receipts/uuidna/ledger/<address>. A manifest naming every piece by address
// is deposited last; its address is the ROOT the bundle carries.
//
//   --bake   offline: write src/theorems/edge-root.ts (the root, and the sealed keys and addresses in ledger order).
//            Every address is computed here from the ledger, so the bake needs no network; build and ship after it.
//   (none)   deposit what storage does not already hold at its address, manifest last, then read the whole ledger
//            back from storage and compare it row for row. Refuses when the baked root lags the ledger.
//
// No token on any host: the MCP door writes over its QpuDeposit service binding. A door that declines is named, with
// its reason, and the run fails — a partial ledger is not a ledger.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'
import { LEAN_LEDGER } from '../theorems/generated.js'
import { THEOREMS } from '../theorems/index.js'
import type { EdgeRoot } from '../theorems/ledger-shape.js'
import { EDGE_ROOT } from '../theorems/edge-root.js'
import { ledgerPiecesOf, ledgerManifestOf, contentAddressOf, edgeRootOf, ledgerAt, storedAt, LEDGER_RUN, type LedgerPiece, type LedgerManifest } from '../edge-ledger.js'
import { depositEvidence } from './receipt-deposit.js'
import { GATE_THEOREMS } from '../gate-engine.js'

/** the ledger as it will be deposited: its pieces, their manifest, and the manifest's address — the root */
export const ledgerPlan = (): { pieces: LedgerPiece[]; manifest: LedgerManifest; root: string } => {
  const pieces = ledgerPiecesOf(LEAN_LEDGER, THEOREMS.map((t) => t.lineAddress))
  const manifest = ledgerManifestOf(pieces)
  return { pieces, manifest, root: contentAddressOf(manifest) }
}

/** the generated edge-root module for a root */
export const edgeRootSourceOf = (root: EdgeRoot): string =>
  `// src/theorems/edge-root.ts — GENERATED by scripts/ledger-deposit --bake from the ledger lean-ledger wrote. Do not edit.\n` +
  `// the sealed keys (EDGE_ROOT.count of them) and their addresses in ledger order; the rows live in qpu storage under the manifest at root.\n` +
  `import type { EdgeRoot } from './ledger-shape.js'\n\n` +
  `export const EDGE_ROOT: EdgeRoot | null = ${JSON.stringify(root)}\n`

/** bake() → write src/theorems/edge-root.ts for the current ledger; offline */
export const bake = (): { root: string; count: number; pieces: number } => {
  const { pieces, root } = ledgerPlan()
  writeFileSync(join(ROOT, 'src', 'theorems', 'edge-root.ts'), edgeRootSourceOf(edgeRootOf(THEOREMS, root, GATE_THEOREMS)))
  return { root, count: THEOREMS.length, pieces: pieces.length }
}

/** held(address) → true when storage already holds a deposit that recomputes this address */
const held = (address: string, fetchImpl: typeof fetch): Promise<boolean> => storedAt(address, fetchImpl).then(() => true, () => false)

/** depositLedger() → every missing piece, then the manifest, through the MCP door; then the whole ledger read back */
export const depositLedger = async (fetchImpl: typeof fetch = fetch): Promise<{ ok: boolean; root: string; deposited: number; held: number; why?: string }> => {
  const { pieces, manifest, root } = ledgerPlan()
  if (EDGE_ROOT?.root !== root)
    return { ok: false, root, deposited: 0, held: 0, why: `the baked root is ${EDGE_ROOT?.root ?? 'absent'} and this ledger's is ${root} — run ledger-deposit --bake, build and ship, then deposit` }
  let deposited = 0
  let already = 0
  const bodies: { address: string; body: Record<string, unknown>; name: string }[] = [
    ...pieces.map((p, i) => ({ address: manifest.wings[i]!.address, body: p as unknown as Record<string, unknown>, name: `${p.file}${p.part === null ? '' : ' ' + p.part}` })),
    { address: root, body: manifest as unknown as Record<string, unknown>, name: 'manifest' },
  ]
  // THE PIECES DO NOT WAIT ON EACH OTHER, AND THE MANIFEST WAITS ON ALL OF THEM. By construction the door derives each
  // key from the deposit's own content address, so a piece lands only at its own key and the order they finish in
  // leaves the same bytes at the same addresses — the concurrency is safe for that reason and no other.
  // What the order DID change was the wall-clock: one deposit is one store.put of the slot plus 2x7 RAID shares
  // across two layers, measured at about seventeen seconds, so 492 pieces in a row is over two hours of a run that
  // holds nothing between steps. Batching them into one call does not help — ten pieces in a call is ten of those
  // writes inside ONE request, which spends the Worker's budget instead of the clock's. Separate requests are
  // separate isolates, so a LANE is the thing to widen. The manifest is deposited last and alone, because it is the
  // root: it names the pieces, and a reader that finds it must find them.
  const LANES = 8
  const failures: string[] = []
  const lane = async (rows: typeof bodies): Promise<void> => {
    for (const { address, body, name } of rows) {
      if (failures.length) return
      if (await held(address, fetchImpl)) { already++; continue }
      const r = await depositEvidence(LEDGER_RUN, body, fetchImpl)
      if (!r.sent) { failures.push(`${name} (${address}) was not deposited: ${r.why ?? r.status}`); return }
      if (!r.href.endsWith('/' + address)) { failures.push(`${name} landed at ${r.href}, not at its address ${address}`); return }
      deposited++
    }
  }
  const wings = bodies.slice(0, bodies.length - 1)
  const lanes = Array.from({ length: LANES }, (_, i) => lane(wings.filter((_, j) => j % LANES === i)))
  await Promise.all(lanes)
  if (failures.length) return { ok: false, root, deposited, held: already, why: failures[0]! }
  const last = bodies[bodies.length - 1]!
  if (!(await held(last.address, fetchImpl))) {
    const r = await depositEvidence(LEDGER_RUN, last.body, fetchImpl)
    if (!r.sent) return { ok: false, root, deposited, held: already, why: `${last.name} (${last.address}) was not deposited: ${r.why ?? r.status}` }
    if (!r.href.endsWith('/' + last.address)) return { ok: false, root, deposited, held: already, why: `${last.name} landed at ${r.href}, not at its address ${last.address}` }
    deposited++
  } else already++
  // THE READ-BACK IS THE PROOF: the same reader the edge runs, over the public storage door, every address recomputed
  const read = await ledgerAt(root, fetchImpl)
  const drift = read.rows.findIndex((t, i) => t.key !== LEAN_LEDGER[i]?.key || read.lines[i] !== THEOREMS[i]?.lineAddress)
  if (read.rows.length !== LEAN_LEDGER.length || drift >= 0)
    return { ok: false, root, deposited, held: already, why: `storage reads back ${read.rows.length} rows; first difference at row ${drift}` }
  return { ok: true, root, deposited, held: already }
}

const IS_CLI = (process.argv[1] ?? '').endsWith('ledger-deposit.js')
if (IS_CLI) {
  if (process.argv.includes('--bake')) {
    const b = bake()
    console.log(`✓ ledger-deposit --bake — root ${b.root}: ${b.count} keys in ${b.pieces} pieces → src/theorems/edge-root.ts; build and ship, then deposit`)
  } else {
    depositLedger().then((r) => {
      console.log(r.ok
        ? `✓ ledger-deposit — root ${r.root}: ${r.deposited} deposited, ${r.held} already held; the whole ledger reads back from qpu storage`
        : `✗ ledger-deposit — ${r.why}`)
      process.exit(r.ok ? 0 : 1)
    }, (e: unknown) => { console.log(`✗ ledger-deposit — ${String((e as Error)?.message ?? e)}`); process.exit(1) })
  }
}
