#!/usr/bin/env node
// reconcile — regenerate the WHOLE derived layer to match the current Lean source, sync the heartbeats, then commit
// and push. The one command that gets a ledger change past the pre-push readiness gate: the gate git-diffs
// generated.ts, PRINCIPLE.md, CHANGELOG.md, lean/ (incl. lean/axioms.json), docs/mcp.md, audit-citations.json,
// support-audit.json and research-leads.json — so EVERY one must be regenerated here or the push is blocked. Each
// derived file must equal its own recomputation from the one audited ledger (a fixed point); a file left
// un-rotated is the "non-quantum" drift the gate hard-rejects. Add a domain (a lean-<x>.ts generator or a .lean), then:
//
//   npm run reconcile                       → default commit message
//   npm run reconcile "Add the nim domain"  → your own message
//
// Nothing is committed if the reconcile leaves the tree unchanged (the derived layer already matched). account.js
// fails loudly if the ledger does not reconcile, aborting before any commit/push. Integrity.
import { execSync } from 'node:child_process'
import { join } from 'node:path'
import { ROOT, stageDerived } from './api.js'
import { acquire, release } from './one-writer.js'

const run = (cmd: string): void => { console.log('  · ' + cmd); execSync(cmd, { stdio: 'inherit' }) }
const out = (cmd: string): string => execSync(cmd).toString().trim()
// --derive-only STOPS AFTER THE SEAL. The whole chain below is the re-derivation; the commit and push are a
// SEPARATE, OUTWARD act bolted onto the end of it. develop's cure for spin drift used to be plain `reconcile`,
// which meant a routine self-heal could publish to origin — so the pass that exists to make the gate green
// unattended could not be run unattended. This flag splits the two: re-derive and re-seal locally, publish never.
const deriveOnly = process.argv.includes('--derive-only')
const msg = process.argv.slice(2).filter((a) => a !== '--derive-only').join(' ') || 'Reconcile: regenerate the derived layer + sync heartbeats to the ledger, backed by theorem two_coins'

// GUARD FIRST, AND THE CHAIN OWNS IT. The standing law is "run the guard before every reconcile", and it was being
// obeyed by a human typing `guard && reconcile` — a manual step compensating for a missing precondition, which is
// the shape of every crack this tree folds into a finder. The gate DOES run later, inside the pre-push hook, but by
// then reconcile has already spent `npm run lean` and the whole regeneration; the guard costs 0.90s and fails on a
// forged ledger before any of that is paid. So the conjunction stops being something to remember.
// THE ONE-WRITER LAW, BEFORE ANYTHING IS PAID: two heavy chains regenerating the same derived layer at once is
// the interleaved-writers class the coherent self-heal below exists to cure after the fact — this refuses it
// BEFORE the fact. The lock is pid-liveness-stale (no clock): a crashed reconcile never wedges the tree, and a
// LIVE audit or peer reconcile is named with the cure (wait, or coordinate over messaging) instead of raced.
const gate = acquire('reconcile', process.pid)
if (!gate.ok) {
  console.error(`✗ reconcile — the tree is HELD by pid ${gate.holder.pid} (${gate.holder.purpose}); a second writer would interleave the derived layer. Wait, or coordinate — never race.`)
  process.exit(1)
}
process.on('exit', () => release(process.pid))   // the holder lets go however the chain ends; a crash is stale by pid

console.log('reconcile — the guard first, because a reconcile on an unforged ledger is the only kind worth paying for …')
run('node dist/scripts/guard.js')

console.log('reconcile — regenerating the derived layer to match the Lean source …')
run('npm run lean')                                   // generated.ts + PRINCIPLE.md + CHANGELOG — verifies every proof
run('node dist/scripts/one-receipt.js coherent || { rm -rf dist; npm run build; node dist/scripts/one-receipt.js coherent; }') // SELF-HEAL the mixed-dist class (interleaved writers on the shared tree): probe every dist import against dist/index.js; on drift, one clean emit — the known total cure — then re-probe. The wrapper no longer dies mid-chain on a stale export.
run('npm run build')                                  // REBUILD dist from the fresh generated.ts, so the downstream generators (gen-mcp/gen-readme/heartbeats/account) read the CURRENT ledger— else a new domain's theorems are missing from heartbeats and accounting fails at the pre-push gate
// ONE LIST, NOT TWO. reconcile listed nine generators by hand while generate.ts's manifest ran eighteen, so the
// eight it never named were regenerated by the audit and staged by nobody — git-diff then failed on a tree the gate
// itself had dirtied, and drainGaps could not see it because those generators were invoked by gate-all rather than
// by this chain. The manifest is now the single list: adding a generator there reaches the reconcile automatically,
// and drainGaps expands `generate` to the manifest so every one still declares what it writes.
run('node dist/scripts/generate.js')                  // every emitter, in manifest order, one process
run('node dist/scripts/sync-changelog.js')            // RE-STAMP CHANGELOG from the FRESH dist. `npm run lean` above stamps it during its OWN pre-lean-all build, so it reads the STALE (pre-new-theorem) count; without this re-stamp the committed CHANGELOG lags by the just-added theorems, and the pre-push gate (`npm run next`) recomputes the true count and BLOCKS on the drift — forcing a manual second reconcile. Re-stamping here makes reconcile ONE-SHOT (the measured cost of manual work, sealed as manipulation_never_faster / guard-before-reconcile).
run('node dist/scripts/lean-axioms.js')               // lean/axioms.json — re-derive the axiom-free audit from the CURRENT ledger (gated under lean/; the pre-push gate regenerates it, so reconcile must too or the git-diff blocks the push)
run('node dist/scripts/lean-heartbeats.js --sync')    // heartbeats.json — prune stale, measure the new, 100% coverage
run('node dist/scripts/support.js')                   // support-audit.json + research-leads.json — code reachability, dead → R&D
run('node dist/scripts/audit-citations.js')           // audit-citations.json — the publication citation audit
run('node dist/scripts/account.js')                   // ABORTS here (non-zero) if the ledger does NOT reconcile
run('node dist/scripts/spin.js --seal')               // spin-manifest.json — SEAL the coins of the freshly-rotated derived layer LAST (after every generator); once sealed, the gate re-spins them by itself (verify O(1))


// THE SPLIT. Everything above re-derives the layer from the ledger and re-seals it — local, reversible, and the
// only part a self-heal needs. Everything below publishes. A cure must never publish, so it stops here.
if (deriveOnly) {
  const dirty = out('git status --porcelain').length !== 0
  console.log(dirty
    ? '✓ reconcile --derive-only — the derived layer is re-derived and re-sealed; the tree is dirty and NOTHING was committed or pushed. Review it, then commit deliberately.'
    : '✓ reconcile --derive-only — nothing to reconcile; the derived layer already matches the source.')
  process.exit(0)
}

if (out('git status --porcelain').length === 0) {
  console.log('✓ nothing to reconcile — the derived layer already matches the source.')
} else {
  // SIGN the commit as TRUE before it is made — FAIL unless the message cites a real sealed theorem (none fabricated).
  // Loaded from the FRESH dist rebuilt above, so a message may cite a theorem sealed in THIS run. The signature folds
  // the message + its cited theorems to one gravity root through the abstract-0. A message that overclaims cannot commit.
  const { signCommit } = await import('../index.js')
  const sig = signCommit(msg)
  if (!sig.signed) {
    console.error('✗ reconcile — commit NOT signed true: ' + sig.reason)
    console.error('  A commit must cite a real sealed theorem — add `theorem <key>` or `/theorem/<key>` (see uuidna_theorems). Nothing committed.')
    process.exit(1)
  }
  console.log('  ✓ commit signed true — ' + sig.reason)
  // THE RECEIPT IS WRITTEN LAST, because it fingerprints what is about to be committed. It covers src/ and lean/,
  // and reconcile REGENERATES lean/ — so a receipt written any earlier (green wrote it after its arms passed) is
  // stale by the time this commit exists, and would have shipped a proof of a tree that no longer was. Written here
  // it addresses the tree as staged, which is the only tree the tag can ever check.
  run('node dist/scripts/gate-receipt.js')              // the push-time proof, fingerprinting the tree as it is about to be staged
  // explicit paths, never -A — the drain commits what IT regenerated; anything else belongs to whoever wrote it
  const staged = stageDerived(ROOT)
  if (staged.leftForHumans.length) console.log('· reconcile — left for a human (not staged' + staged.leftForHumans.join(', '))
  // NOTHING STAGED IS NOT NOTHING TO SAY. The tree is dirty (checked above) but the drain's paths matched none of
  // it — so every changed file belongs to a sibling, or to a generator whose output is missing from DRAIN_PATHS.
  // Committing anyway hands git an empty index and the run dies on `no changes added to commit`, an error about
  // git rather than about the repo. Name the files and the cure instead; `one-receipt drain` holds the
  // second case shut, and this holds the first honest.
  if (staged.staged === 0) {
    console.error('✗ reconcile — the tree is dirty but NOTHING the drain owns changed; nothing to commit.')
    console.error('  unstaged: ' + (staged.leftForHumans.join(', ') || '(none visible)'))
    console.error('  FIX if these are a sibling session\'s edits, let them land first. If a generator in the reconcile')
    console.error('      chain writes one of them, declare it in RECONCILE_OUTPUTS and add it to DRAIN_PATHS')
    console.error('      (src/scripts/api.ts) — run `node dist/scripts/one-receipt.js drain` for the exact list.')
    process.exit(1)
  }
  run('git commit -m ' + JSON.stringify(msg))
  console.log('  committed: ' + msg)
}
// RECONCILED-MEANS-SYNCED (gap 32, paid 2026-08-17): the old bare push could die with a raw Node trace — or
// worse, the wrapper exit 0 with the commit stranded local. Now the push failure is CAUGHT and named (the
// gate's verdict is already on screen above it), and success is not claimed but VERIFIED: after the push,
// origin is fetched and the ahead-count must be exactly 0 — reconciled means synced, or the run fails loudly.
try {
  run('git push origin HEAD')                          // the pre-push readiness gate re-verifies; passes if reconciled
} catch {
  console.error('✗ reconcile — push REJECTED (the gate\'s verdict is printed above). The commit is LOCAL; fix the denial, then push — nothing is synced.')
  process.exit(1)
}
run('git fetch origin')
const ahead = out('git rev-list --count origin/main..HEAD')
if (ahead !== '0') {
  console.error(`✗ reconcile — NOT SYNCED: ${ahead} commit(s) still ahead of origin/main after the push. Reconciled-means-synced; failing loudly instead of exiting 0 unsynced.`)
  process.exit(1)
}
console.log('✓ reconciled and pushed — verified synced with origin (0 ahead).')
