import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './api.js'

// ONE RECONCILE REACHES THE FIXED POINT (PATCHES §46, 2026-09-15). The court record (lean/refusal-trials.json) reads
// the ledger, the axiom receipts and the witness seals, and it is one of the files spin seals. So reconcile must
// compute it AFTER the full derivation and BEFORE the seal: a court refresh followed by a re-derivation that did not
// recompute it left the court stale and the heal alternated court ↔ spin for six rounds, twice.
// AND THE STAGING IS A STEP, not plumbing. It was invisible to this reader — which is why the order it
// constrains could invert unnoticed — so `stageDerived(` is read as the step `stage`, at column 0 like the rest.
const stepsOf = (src: string): string[] =>
  [...src.matchAll(/^(?:run\('node dist\/scripts\/([a-z-]+)\.js[^']*'\)|stageDerived\()/gm)].map((m) => m[1] ?? 'stage')

// AND THE SEAL COMES AFTER THE STAGING (2026-09-21). spin seals what git TRACKS; the commit carries what git
// has STAGED. A chunk generated by this run is neither until it is added, so a seal taken before the staging
// covers the PREVIOUS commit's file set — measured exactly that way when develop's cure for spin drift failed
// to cure it twice running. The two sets must be the same set, and only ordering makes them so.
const ordered = (steps: readonly string[]): boolean => {
  const derive = steps.indexOf('generate'), court = steps.indexOf('trial-refusals')
  const stage = steps.indexOf('stage'), seal = steps.lastIndexOf('spin')
  return derive >= 0 && court > derive && stage > court && seal > stage
}

test('reconcile derives everything, then computes the court record, then seals', () => {
  const steps = stepsOf(readFileSync(join(ROOT, 'src', 'scripts', 'reconcile.ts'), 'utf8'))
  assert.ok(ordered(steps), `reconcile's steps must be generate … trial-refusals … spin --seal, got ${steps.join(' → ')}`)
})

test('control: the order the heal alternated on is refused', () => {
  assert.equal(ordered(['generate', 'spin', 'trial-refusals']), false, 'a court record written after the seal drifts it')
  assert.equal(ordered(['trial-refusals', 'generate', 'spin']), false, 'a court record computed before the derivation goes stale')
  assert.equal(ordered(['generate', 'spin']), false, 'a reconcile with no court step leaves the sealed court record behind')
  assert.equal(ordered(['generate', 'trial-refusals', 'spin']), false,
    'a seal taken before the staging seals the set the LAST commit had, not the one this commit will carry')
  assert.equal(ordered(['generate', 'trial-refusals', 'spin', 'stage']), false,
    'staging after the seal is the same fault written the other way round')
  assert.equal(ordered(['stage', 'generate', 'trial-refusals', 'spin']), false,
    'staging before the derivation stages nothing the derivation is about to write')
})
