// quantum/models/mirror — GENERATED by scripts/lean-models.ts from openrouter.ai/api/v1/models (public, keyless). DO NOT EDIT.
// ALL PUBLIC LIVE MODEL DATA: every model the public feed routes, with its published context window and
// per-token prices (verbatim strings — labels, not numbers this tree computes on), so every deterministic
// surface (the /models page, the wing, the tests) reads the same census offline. Refreshed at the src/os
// boundary on every lean run; rewritten only when the feed moved. Data, never executed, never benchmarked.

export interface MirrorModel { id: string; name: string; contextTokens: number; promptPrice: string; completionPrice: string }
export interface ModelsMirror { source: string; endpoint: string; count: number; models: MirrorModel[] }

export const MODELS_MIRROR: ModelsMirror = {
 "source": "openrouter.ai/api/v1/models (public, keyless)",
 "endpoint": "https://openrouter.ai/api/v1/models",
 "count": 419,
 "models": [
  {
   "id": "aion-labs/aion-2.0",
   "name": "AionLabs: Aion-2.0",
   "contextTokens": 131072,
   "promptPrice": "0.0000008",
   "completionPrice": "0.0000016"
  },
  {
   "id": "aion-labs/aion-3.0",
   "name": "AionLabs: Aion-3.0",
   "contextTokens": 131072,
   "promptPrice": "0.000003",
   "completionPrice": "0.000006"
  },
  {
   "id": "aion-labs/aion-3.0-mini",
   "name": "AionLabs: Aion-3.0-Mini",
   "contextTokens": 131072,
   "promptPrice": "0.0000007",
   "completionPrice": "0.0000014"
  },
  {
   "id": "aion-labs/aion-rp-llama-3.1-8b",
   "name": "AionLabs: Aion-RP 1.0 (8B)",
   "contextTokens": 32768,
   "promptPrice": "0.0000008",
   "completionPrice": "0.0000016"
  },
  {
   "id": "amazon/nova-2-lite-v1",
   "name": "Amazon: Nova 2 Lite",
   "contextTokens": 1000000,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000025"
  },
  {
   "id": "amazon/nova-lite-v1",
   "name": "Amazon: Nova Lite 1.0",
   "contextTokens": 300000,
   "promptPrice": "0.00000006",
   "completionPrice": "0.00000024"
  },
  {
   "id": "amazon/nova-micro-v1",
   "name": "Amazon: Nova Micro 1.0",
   "contextTokens": 128000,
   "promptPrice": "0.000000035",
   "completionPrice": "0.00000014"
  },
  {
   "id": "amazon/nova-premier-v1",
   "name": "Amazon: Nova Premier 1.0",
   "contextTokens": 1000000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.0000125"
  },
  {
   "id": "amazon/nova-pro-v1",
   "name": "Amazon: Nova Pro 1.0",
   "contextTokens": 300000,
   "promptPrice": "0.0000008",
   "completionPrice": "0.0000032"
  },
  {
   "id": "anthracite-org/magnum-v4-72b",
   "name": "Magnum v4 72B",
   "contextTokens": 32768,
   "promptPrice": "0.0000025",
   "completionPrice": "0.000005"
  },
  {
   "id": "anthropic/claude-3-haiku",
   "name": "Anthropic: Claude 3 Haiku",
   "contextTokens": 200000,
   "promptPrice": "0.00000025",
   "completionPrice": "0.00000125"
  },
  {
   "id": "anthropic/claude-fable-5",
   "name": "Anthropic: Claude Fable 5",
   "contextTokens": 1000000,
   "promptPrice": "0.00001",
   "completionPrice": "0.00005"
  },
  {
   "id": "anthropic/claude-fable-5.1",
   "name": "Anthropic: Claude Fable 5.1",
   "contextTokens": 1000000,
   "promptPrice": "0.00001",
   "completionPrice": "0.00005"
  },
  {
   "id": "anthropic/claude-fable-5:batch",
   "name": "Anthropic: Claude Fable 5 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "anthropic/claude-haiku-4.5",
   "name": "Anthropic: Claude Haiku 4.5",
   "contextTokens": 200000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000005"
  },
  {
   "id": "anthropic/claude-haiku-4.5:batch",
   "name": "Anthropic: Claude Haiku 4.5 (batch)",
   "contextTokens": 200000,
   "promptPrice": "0.0000005",
   "completionPrice": "0.0000025"
  },
  {
   "id": "anthropic/claude-opus-4",
   "name": "Anthropic: Claude Opus 4",
   "contextTokens": 200000,
   "promptPrice": "0.000015",
   "completionPrice": "0.000075"
  },
  {
   "id": "anthropic/claude-opus-4.1",
   "name": "Anthropic: Claude Opus 4.1",
   "contextTokens": 200000,
   "promptPrice": "0.000015",
   "completionPrice": "0.000075"
  },
  {
   "id": "anthropic/claude-opus-4.1:batch",
   "name": "Anthropic: Claude Opus 4.1 (batch)",
   "contextTokens": 200000,
   "promptPrice": "0.0000075",
   "completionPrice": "0.0000375"
  },
  {
   "id": "anthropic/claude-opus-4.5",
   "name": "Anthropic: Claude Opus 4.5",
   "contextTokens": 200000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "anthropic/claude-opus-4.5:batch",
   "name": "Anthropic: Claude Opus 4.5 (batch)",
   "contextTokens": 200000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.0000125"
  },
  {
   "id": "anthropic/claude-opus-4.6",
   "name": "Anthropic: Claude Opus 4.6",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "anthropic/claude-opus-4.6:batch",
   "name": "Anthropic: Claude Opus 4.6 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.0000125"
  },
  {
   "id": "anthropic/claude-opus-4.7",
   "name": "Anthropic: Claude Opus 4.7",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "anthropic/claude-opus-4.7:batch",
   "name": "Anthropic: Claude Opus 4.7 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.0000125"
  },
  {
   "id": "anthropic/claude-opus-4.8",
   "name": "Anthropic: Claude Opus 4.8",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "anthropic/claude-opus-4.8:batch",
   "name": "Anthropic: Claude Opus 4.8 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.0000125"
  },
  {
   "id": "anthropic/claude-opus-5",
   "name": "Claude Opus 5",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "anthropic/claude-opus-5:batch",
   "name": "Claude Opus 5 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.0000125"
  },
  {
   "id": "anthropic/claude-sonnet-4",
   "name": "Anthropic: Claude Sonnet 4",
   "contextTokens": 1000000,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "anthropic/claude-sonnet-4.5",
   "name": "Anthropic: Claude Sonnet 4.5",
   "contextTokens": 1000000,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "anthropic/claude-sonnet-4.5:batch",
   "name": "Anthropic: Claude Sonnet 4.5 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.0000015",
   "completionPrice": "0.0000075"
  },
  {
   "id": "anthropic/claude-sonnet-4.6",
   "name": "Anthropic: Claude Sonnet 4.6",
   "contextTokens": 1000000,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "anthropic/claude-sonnet-4.6:batch",
   "name": "Anthropic: Claude Sonnet 4.6 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.0000015",
   "completionPrice": "0.0000075"
  },
  {
   "id": "anthropic/claude-sonnet-5",
   "name": "Anthropic: Claude Sonnet 5",
   "contextTokens": 1000000,
   "promptPrice": "0.000002",
   "completionPrice": "0.00001"
  },
  {
   "id": "anthropic/claude-sonnet-5:batch",
   "name": "Anthropic: Claude Sonnet 5 (batch)",
   "contextTokens": 1000000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000005"
  },
  {
   "id": "arcee-ai/trinity-large-thinking",
   "name": "Arcee AI: Trinity Large Thinking",
   "contextTokens": 262144,
   "promptPrice": "0.00000025",
   "completionPrice": "0.0000008"
  },
  {
   "id": "baidu/ernie-4.5-vl-424b-a47b",
   "name": "Baidu: ERNIE 4.5 VL 424B A47B ",
   "contextTokens": 123000,
   "promptPrice": "0.00000042",
   "completionPrice": "0.00000125"
  },
  {
   "id": "bytedance-seed/seed-1.6",
   "name": "ByteDance Seed: Seed 1.6",
   "contextTokens": 262144,
   "promptPrice": "0.00000025",
   "completionPrice": "0.000002"
  },
  {
   "id": "bytedance-seed/seed-1.6-flash",
   "name": "ByteDance Seed: Seed 1.6 Flash",
   "contextTokens": 262144,
   "promptPrice": "0.000000075",
   "completionPrice": "0.0000003"
  },
  {
   "id": "bytedance-seed/seed-2-1-turbo",
   "name": "ByteDance Seed: Seed 2.1 Turbo",
   "contextTokens": 262144,
   "promptPrice": "0.0000005",
   "completionPrice": "0.0000025"
  },
  {
   "id": "bytedance-seed/seed-2.0-code",
   "name": "ByteDance Seed: Seed-2.0-Code",
   "contextTokens": 262144,
   "promptPrice": "0.0000005",
   "completionPrice": "0.000003"
  },
  {
   "id": "bytedance-seed/seed-2.0-lite",
   "name": "ByteDance Seed: Seed-2.0-Lite",
   "contextTokens": 262144,
   "promptPrice": "0.00000025",
   "completionPrice": "0.000002"
  },
  {
   "id": "bytedance-seed/seed-2.0-mini",
   "name": "ByteDance Seed: Seed-2.0-Mini",
   "contextTokens": 262144,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000004"
  },
  {
   "id": "bytedance/ui-tars-1.5-7b",
   "name": "ByteDance: UI-TARS 7B ",
   "contextTokens": 128000,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000002"
  },
  {
   "id": "cognitivecomputations/dolphin-mistral-24b-venice-edition",
   "name": "Venice: Uncensored",
   "contextTokens": 128000,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000009"
  },
  {
   "id": "cohere/command-a",
   "name": "Cohere: Command A",
   "contextTokens": 256000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00001"
  },
  {
   "id": "cohere/command-r-08-2024",
   "name": "Cohere: Command R (08-2024)",
   "contextTokens": 128000,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "cohere/command-r-plus-08-2024",
   "name": "Cohere: Command R+ (08-2024)",
   "contextTokens": 128000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00001"
  },
  {
   "id": "cohere/command-r7b-12-2024",
   "name": "Cohere: Command R7B (12-2024)",
   "contextTokens": 128000,
   "promptPrice": "0.0000000375",
   "completionPrice": "0.00000015"
  },
  {
   "id": "cohere/north-mini-code:free",
   "name": "Cohere: North Mini Code (free)",
   "contextTokens": 256000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "deepseek/deepseek-chat",
   "name": "DeepSeek: DeepSeek V3",
   "contextTokens": 163840,
   "promptPrice": "0.0000002574",
   "completionPrice": "0.0000010287"
  },
  {
   "id": "deepseek/deepseek-chat-v3-0324",
   "name": "DeepSeek: DeepSeek V3 0324",
   "contextTokens": 163840,
   "promptPrice": "0.00000025",
   "completionPrice": "0.000001"
  },
  {
   "id": "deepseek/deepseek-chat-v3.1",
   "name": "DeepSeek: DeepSeek V3.1",
   "contextTokens": 163840,
   "promptPrice": "0.00000055",
   "completionPrice": "0.00000165"
  },
  {
   "id": "deepseek/deepseek-r1",
   "name": "DeepSeek: R1",
   "contextTokens": 64000,
   "promptPrice": "0.0000007",
   "completionPrice": "0.0000025"
  },
  {
   "id": "deepseek/deepseek-r1-0528",
   "name": "DeepSeek: R1 0528",
   "contextTokens": 163840,
   "promptPrice": "0.0000005",
   "completionPrice": "0.00000215"
  },
  {
   "id": "deepseek/deepseek-r1-distill-llama-70b",
   "name": "DeepSeek: R1 Distill Llama 70B",
   "contextTokens": 8192,
   "promptPrice": "0.0000008",
   "completionPrice": "0.0000008"
  },
  {
   "id": "deepseek/deepseek-v3.1-terminus",
   "name": "DeepSeek: DeepSeek V3.1 Terminus",
   "contextTokens": 163840,
   "promptPrice": "0.00000027",
   "completionPrice": "0.000001"
  },
  {
   "id": "deepseek/deepseek-v3.2",
   "name": "DeepSeek: DeepSeek V3.2",
   "contextTokens": 163840,
   "promptPrice": "0.000000269",
   "completionPrice": "0.0000004"
  },
  {
   "id": "deepseek/deepseek-v3.2-exp",
   "name": "DeepSeek: DeepSeek V3.2 Exp",
   "contextTokens": 163840,
   "promptPrice": "0.00000027",
   "completionPrice": "0.00000041"
  },
  {
   "id": "deepseek/deepseek-v4-flash",
   "name": "DeepSeek: DeepSeek V4 Flash 0423",
   "contextTokens": 1048576,
   "promptPrice": "0.00000007168",
   "completionPrice": "0.00000014336"
  },
  {
   "id": "deepseek/deepseek-v4-flash-0731",
   "name": "DeepSeek: DeepSeek V4 Flash 0731",
   "contextTokens": 1310720,
   "promptPrice": "0.000000065",
   "completionPrice": "0.00000018"
  },
  {
   "id": "deepseek/deepseek-v4-flash-0731:batch",
   "name": "DeepSeek: DeepSeek V4 Flash 0731 (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000014",
   "completionPrice": "0.00000028"
  },
  {
   "id": "deepseek/deepseek-v4-flash-vision-exp",
   "name": "DeepSeek: DeepSeek V4 Flash Vision Exp",
   "contextTokens": 1048576,
   "promptPrice": "0.00000022",
   "completionPrice": "0.00000066"
  },
  {
   "id": "deepseek/deepseek-v4-pro",
   "name": "DeepSeek: DeepSeek V4 Pro 0423",
   "contextTokens": 1048576,
   "promptPrice": "0.000001024164",
   "completionPrice": "0.000002048328"
  },
  {
   "id": "deepseek/deepseek-v4-pro-0813",
   "name": "DeepSeek: DeepSeek V4 Pro 0813",
   "contextTokens": 1048576,
   "promptPrice": "0.00000066",
   "completionPrice": "0.00000198"
  },
  {
   "id": "deepseek/deepseek-v4-pro-0813:batch",
   "name": "DeepSeek: DeepSeek V4 Pro 0813 (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000132",
   "completionPrice": "0.00000396"
  },
  {
   "id": "dots-studio/dots-3-note-preview:free",
   "name": "Dots Studio: Dots3-Note Preview (free)",
   "contextTokens": 512000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "google/gemini-2.5-flash",
   "name": "Google: Gemini 2.5 Flash",
   "contextTokens": 1048576,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000025"
  },
  {
   "id": "google/gemini-2.5-flash-image",
   "name": "Google: Nano Banana (Gemini 2.5 Flash Image)",
   "contextTokens": 32768,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000025"
  },
  {
   "id": "google/gemini-2.5-flash-lite",
   "name": "Google: Gemini 2.5 Flash Lite",
   "contextTokens": 1048576,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000004"
  },
  {
   "id": "google/gemini-2.5-flash-lite:batch",
   "name": "Google: Gemini 2.5 Flash Lite (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000002"
  },
  {
   "id": "google/gemini-2.5-flash:batch",
   "name": "Google: Gemini 2.5 Flash (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000015",
   "completionPrice": "0.00000125"
  },
  {
   "id": "google/gemini-2.5-pro",
   "name": "Google: Gemini 2.5 Pro",
   "contextTokens": 1048576,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "google/gemini-2.5-pro-preview",
   "name": "Google: Gemini 2.5 Pro Preview 06-05",
   "contextTokens": 1048576,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "google/gemini-2.5-pro-preview-05-06",
   "name": "Google: Gemini 2.5 Pro Preview 05-06",
   "contextTokens": 1048576,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "google/gemini-2.5-pro:batch",
   "name": "Google: Gemini 2.5 Pro (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.000000625",
   "completionPrice": "0.000005"
  },
  {
   "id": "google/gemini-3-flash-preview",
   "name": "Google: Gemini 3 Flash Preview",
   "contextTokens": 1048576,
   "promptPrice": "0.0000005",
   "completionPrice": "0.000003"
  },
  {
   "id": "google/gemini-3-flash-preview:batch",
   "name": "Google: Gemini 3 Flash Preview (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000025",
   "completionPrice": "0.0000015"
  },
  {
   "id": "google/gemini-3-pro-image",
   "name": "Google: Nano Banana Pro (Gemini 3 Pro Image)",
   "contextTokens": 131072,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "google/gemini-3-pro-image-preview",
   "name": "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
   "contextTokens": 65536,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "google/gemini-3.1-flash-image",
   "name": "Google: Nano Banana 2 (Gemini 3.1 Flash Image)",
   "contextTokens": 131072,
   "promptPrice": "0.0000005",
   "completionPrice": "0.000003"
  },
  {
   "id": "google/gemini-3.1-flash-image-preview",
   "name": "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
   "contextTokens": 65536,
   "promptPrice": "0.0000005",
   "completionPrice": "0.000003"
  },
  {
   "id": "google/gemini-3.1-flash-lite",
   "name": "Google: Gemini 3.1 Flash Lite",
   "contextTokens": 1048576,
   "promptPrice": "0.00000025",
   "completionPrice": "0.0000015"
  },
  {
   "id": "google/gemini-3.1-flash-lite-image",
   "name": "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
   "contextTokens": 65536,
   "promptPrice": "0.00000025",
   "completionPrice": "0.0000015"
  },
  {
   "id": "google/gemini-3.1-flash-lite-preview",
   "name": "Google: Gemini 3.1 Flash Lite Preview",
   "contextTokens": 1048576,
   "promptPrice": "0.00000025",
   "completionPrice": "0.0000015"
  },
  {
   "id": "google/gemini-3.1-flash-lite:batch",
   "name": "Google: Gemini 3.1 Flash Lite (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.000000125",
   "completionPrice": "0.00000075"
  },
  {
   "id": "google/gemini-3.1-pro-preview",
   "name": "Google: Gemini 3.1 Pro Preview",
   "contextTokens": 1048576,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "google/gemini-3.1-pro-preview-customtools",
   "name": "Google: Gemini 3.1 Pro Preview Custom Tools",
   "contextTokens": 1048576,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "google/gemini-3.1-pro-preview:batch",
   "name": "Google: Gemini 3.1 Pro Preview (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.000001",
   "completionPrice": "0.000006"
  },
  {
   "id": "google/gemini-3.5-flash",
   "name": "Google: Gemini 3.5 Flash",
   "contextTokens": 1048576,
   "promptPrice": "0.0000015",
   "completionPrice": "0.000009"
  },
  {
   "id": "google/gemini-3.5-flash-lite",
   "name": "Google: Gemini 3.5 Flash Lite",
   "contextTokens": 1048576,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000025"
  },
  {
   "id": "google/gemini-3.5-flash-lite:batch",
   "name": "Google: Gemini 3.5 Flash Lite (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000015",
   "completionPrice": "0.00000125"
  },
  {
   "id": "google/gemini-3.5-flash:batch",
   "name": "Google: Gemini 3.5 Flash (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.00000075",
   "completionPrice": "0.0000045"
  },
  {
   "id": "google/gemini-3.6-flash",
   "name": "Google: Gemini 3.6 Flash",
   "contextTokens": 1048576,
   "promptPrice": "0.00000075",
   "completionPrice": "0.00000375"
  },
  {
   "id": "google/gemini-3.6-flash:batch",
   "name": "Google: Gemini 3.6 Flash (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.000000375",
   "completionPrice": "0.000001875"
  },
  {
   "id": "google/gemini-3.7-flash",
   "name": "Google: Gemini 3.7 Flash",
   "contextTokens": 1048576,
   "promptPrice": "0.00000075",
   "completionPrice": "0.00000375"
  },
  {
   "id": "google/gemini-3.7-flash:batch",
   "name": "Google: Gemini 3.7 Flash (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.0000001875",
   "completionPrice": "0.0000009375"
  },
  {
   "id": "google/gemma-2-27b-it",
   "name": "Google: Gemma 2 27B",
   "contextTokens": 8192,
   "promptPrice": "0.00000065",
   "completionPrice": "0.00000065"
  },
  {
   "id": "google/gemma-3-12b-it",
   "name": "Google: Gemma 3 12B",
   "contextTokens": 131072,
   "promptPrice": "0.00000005",
   "completionPrice": "0.00000015"
  },
  {
   "id": "google/gemma-3-27b-it",
   "name": "Google: Gemma 3 27B",
   "contextTokens": 131072,
   "promptPrice": "0.00000008",
   "completionPrice": "0.00000045"
  },
  {
   "id": "google/gemma-3-4b-it",
   "name": "Google: Gemma 3 4B",
   "contextTokens": 131072,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000001"
  },
  {
   "id": "google/gemma-4-26b-a4b-it",
   "name": "Google: Gemma 4 26B A4B ",
   "contextTokens": 262144,
   "promptPrice": "0.00000007",
   "completionPrice": "0.00000034"
  },
  {
   "id": "google/gemma-4-26b-a4b-it:free",
   "name": "Google: Gemma 4 26B A4B  (free)",
   "contextTokens": 262144,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "google/gemma-4-31b-it",
   "name": "Google: Gemma 4 31B",
   "contextTokens": 262144,
   "promptPrice": "0.00000009",
   "completionPrice": "0.00000034"
  },
  {
   "id": "google/gemma-4-31b-it:batch",
   "name": "Google: Gemma 4 31B (batch)",
   "contextTokens": 262144,
   "promptPrice": "0.00000039",
   "completionPrice": "0.00000097"
  },
  {
   "id": "google/gemma-4-31b-it:free",
   "name": "Google: Gemma 4 31B (free)",
   "contextTokens": 262144,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "google/lyria-3-clip-preview",
   "name": "Google: Lyria 3 Clip Preview",
   "contextTokens": 1048576,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "google/lyria-3-pro-preview",
   "name": "Google: Lyria 3 Pro Preview",
   "contextTokens": 1048576,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "gryphe/mythomax-l2-13b",
   "name": "MythoMax 13B",
   "contextTokens": 8192,
   "promptPrice": "0.00000006",
   "completionPrice": "0.00000006"
  },
  {
   "id": "ibm-granite/granite-4.0-h-micro",
   "name": "IBM: Granite 4.0 Micro",
   "contextTokens": 131000,
   "promptPrice": "0.000000017",
   "completionPrice": "0.000000112"
  },
  {
   "id": "ibm-granite/granite-4.1-8b",
   "name": "IBM: Granite 4.1 8B",
   "contextTokens": 131072,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000001"
  },
  {
   "id": "ibm-granite/granite-4.2-8b",
   "name": "IBM: Granite 4.2 8B",
   "contextTokens": 131072,
   "promptPrice": "0.0000001",
   "completionPrice": "0.00000015"
  },
  {
   "id": "inception/mercury-2",
   "name": "Inception: Mercury 2",
   "contextTokens": 128000,
   "promptPrice": "0.00000025",
   "completionPrice": "0.00000075"
  },
  {
   "id": "inception/mercury-2.5-preview",
   "name": "Inception: Mercury 2.5 Preview",
   "contextTokens": 260000,
   "promptPrice": "0.00000004",
   "completionPrice": "0.00000015"
  },
  {
   "id": "inclusionai/ling-3.0-flash",
   "name": "Ling-3.0-flash",
   "contextTokens": 262144,
   "promptPrice": "0.000000021",
   "completionPrice": "0.000000063"
  },
  {
   "id": "inclusionai/ling-3.0-flash-fin:free",
   "name": "Ling 3.0 Flash Fin (free)",
   "contextTokens": 262144,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "kwaipilot/kat-coder-pro-v2",
   "name": "Kwaipilot: KAT-Coder-Pro V2",
   "contextTokens": 262144,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "kwaipilot/kat-coder-pro-v2.5",
   "name": "Kwaipilot: KAT-Coder-Pro V2.5",
   "contextTokens": 262144,
   "promptPrice": "0.00000074",
   "completionPrice": "0.00000296"
  },
  {
   "id": "liquid/lfm-2.5-2.6b:free",
   "name": "LiquidAI: LFM2.5-2.6B (free)",
   "contextTokens": 65536,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "mancer/weaver",
   "name": "Mancer: Weaver (alpha)",
   "contextTokens": 8000,
   "promptPrice": "0.0000004",
   "completionPrice": "0.00000075"
  },
  {
   "id": "meituan/longcat-2.0",
   "name": "Meituan: LongCat 2.0",
   "contextTokens": 1048756,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "meta-llama/llama-3.1-70b-instruct",
   "name": "Meta: Llama 3.1 70B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.0000004",
   "completionPrice": "0.0000004"
  },
  {
   "id": "meta-llama/llama-3.1-8b-instruct",
   "name": "Meta: Llama 3.1 8B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.00000005",
   "completionPrice": "0.00000008"
  },
  {
   "id": "meta-llama/llama-3.2-1b-instruct",
   "name": "Meta: Llama 3.2 1B Instruct",
   "contextTokens": 60000,
   "promptPrice": "0.000000027",
   "completionPrice": "0.000000201"
  },
  {
   "id": "meta-llama/llama-3.2-3b-instruct",
   "name": "Meta: Llama 3.2 3B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.00000005",
   "completionPrice": "0.00000033"
  },
  {
   "id": "meta-llama/llama-3.3-70b-instruct",
   "name": "Meta: Llama 3.3 70B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.00000071",
   "completionPrice": "0.00000071"
  },
  {
   "id": "meta-llama/llama-4-maverick",
   "name": "Meta: Llama 4 Maverick",
   "contextTokens": 1048576,
   "promptPrice": "0.0000002",
   "completionPrice": "0.000000696"
  },
  {
   "id": "meta-llama/llama-4-scout",
   "name": "Meta: Llama 4 Scout",
   "contextTokens": 1310720,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000003"
  },
  {
   "id": "meta-llama/llama-guard-4-12b",
   "name": "Meta: Llama Guard 4 12B",
   "contextTokens": 163840,
   "promptPrice": "0.00000018",
   "completionPrice": "0.00000018"
  },
  {
   "id": "meta/muse-glimmer-30b",
   "name": "Meta: Muse Glimmer 30B",
   "contextTokens": 131072,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "meta/muse-glimmer-30b:batch",
   "name": "Meta: Muse Glimmer 30B (batch)",
   "contextTokens": 131072,
   "promptPrice": "0.00000035",
   "completionPrice": "0.0000015"
  },
  {
   "id": "meta/muse-spark-1.1",
   "name": "Meta: Muse Spark 1.1",
   "contextTokens": 1048576,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00000425"
  },
  {
   "id": "meta/muse-spark-1.2",
   "name": "Meta: Muse Spark 1.2",
   "contextTokens": 1048576,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00000425"
  },
  {
   "id": "meta/muse-spark-1.2-contributor",
   "name": "Meta: Muse Spark 1.2 Contributor",
   "contextTokens": 1048576,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000002"
  },
  {
   "id": "microsoft/phi-4",
   "name": "Microsoft: Phi 4",
   "contextTokens": 16384,
   "promptPrice": "0.00000007",
   "completionPrice": "0.00000014"
  },
  {
   "id": "microsoft/wizardlm-2-8x22b",
   "name": "WizardLM-2 8x22B",
   "contextTokens": 65535,
   "promptPrice": "0.00000062",
   "completionPrice": "0.00000062"
  },
  {
   "id": "minimax/minimax-01",
   "name": "MiniMax: MiniMax-01",
   "contextTokens": 1000192,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000011"
  },
  {
   "id": "minimax/minimax-m1",
   "name": "MiniMax: MiniMax M1",
   "contextTokens": 1000000,
   "promptPrice": "0.00000055",
   "completionPrice": "0.0000022"
  },
  {
   "id": "minimax/minimax-m2",
   "name": "MiniMax: MiniMax M2",
   "contextTokens": 204800,
   "promptPrice": "0.000000255",
   "completionPrice": "0.00000102"
  },
  {
   "id": "minimax/minimax-m2-her",
   "name": "MiniMax: MiniMax M2-her",
   "contextTokens": 65536,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "minimax/minimax-m2.1",
   "name": "MiniMax: MiniMax M2.1",
   "contextTokens": 204800,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "minimax/minimax-m2.5",
   "name": "MiniMax: MiniMax M2.5",
   "contextTokens": 204800,
   "promptPrice": "0.00000027",
   "completionPrice": "0.00000108"
  },
  {
   "id": "minimax/minimax-m2.7",
   "name": "MiniMax: MiniMax M2.7",
   "contextTokens": 204800,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "minimax/minimax-m2.7:free",
   "name": "MiniMax: MiniMax M2.7 (free)",
   "contextTokens": 196608,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "minimax/minimax-m3",
   "name": "MiniMax: MiniMax M3",
   "contextTokens": 1048576,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "minimax/minimax-m3:batch",
   "name": "MiniMax: MiniMax M3 (batch)",
   "contextTokens": 524288,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000012"
  },
  {
   "id": "minimax/minimax-m3:free",
   "name": "MiniMax: MiniMax M3 (free)",
   "contextTokens": 1048576,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "mistralai/codestral-2508",
   "name": "Mistral: Codestral 2508",
   "contextTokens": 256000,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000009"
  },
  {
   "id": "mistralai/devstral-2512",
   "name": "Mistral: Devstral 2 2512",
   "contextTokens": 262144,
   "promptPrice": "0.0000004",
   "completionPrice": "0.000002"
  },
  {
   "id": "mistralai/ministral-14b-2512",
   "name": "Mistral: Ministral 3 14B 2512",
   "contextTokens": 262144,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000002"
  },
  {
   "id": "mistralai/ministral-3b-2512",
   "name": "Mistral: Ministral 3 3B 2512",
   "contextTokens": 131072,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000001"
  },
  {
   "id": "mistralai/ministral-8b-2512",
   "name": "Mistral: Ministral 3 8B 2512",
   "contextTokens": 262144,
   "promptPrice": "0.00000015",
   "completionPrice": "0.00000015"
  },
  {
   "id": "mistralai/mistral-large",
   "name": "Mistral Large",
   "contextTokens": 128000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "mistralai/mistral-large-2407",
   "name": "Mistral Large 2407",
   "contextTokens": 131072,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "mistralai/mistral-large-2512",
   "name": "Mistral: Mistral Large 3 2512",
   "contextTokens": 262144,
   "promptPrice": "0.0000005",
   "completionPrice": "0.0000015"
  },
  {
   "id": "mistralai/mistral-medium-3",
   "name": "Mistral: Mistral Medium 3",
   "contextTokens": 131072,
   "promptPrice": "0.0000004",
   "completionPrice": "0.000002"
  },
  {
   "id": "mistralai/mistral-medium-3-5",
   "name": "Mistral: Mistral Medium 3.5",
   "contextTokens": 262144,
   "promptPrice": "0.0000015",
   "completionPrice": "0.0000075"
  },
  {
   "id": "mistralai/mistral-medium-3-5:batch",
   "name": "Mistral: Mistral Medium 3.5 (batch)",
   "contextTokens": 262144,
   "promptPrice": "0.00000075",
   "completionPrice": "0.00000375"
  },
  {
   "id": "mistralai/mistral-medium-3.1",
   "name": "Mistral: Mistral Medium 3.1",
   "contextTokens": 131072,
   "promptPrice": "0.0000004",
   "completionPrice": "0.000002"
  },
  {
   "id": "mistralai/mistral-nemo",
   "name": "Mistral: Mistral Nemo",
   "contextTokens": 131072,
   "promptPrice": "0.000000019",
   "completionPrice": "0.00000003"
  },
  {
   "id": "mistralai/mistral-saba",
   "name": "Mistral: Saba",
   "contextTokens": 32768,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000006"
  },
  {
   "id": "mistralai/mistral-small-24b-instruct-2501",
   "name": "Mistral: Mistral Small 3",
   "contextTokens": 32768,
   "promptPrice": "0.00000005",
   "completionPrice": "0.00000008"
  },
  {
   "id": "mistralai/mistral-small-2603",
   "name": "Mistral: Mistral Small 4",
   "contextTokens": 262144,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "mistralai/mistral-small-3.1-24b-instruct",
   "name": "Mistral: Mistral Small 3.1 24B",
   "contextTokens": 128000,
   "promptPrice": "0.000000351",
   "completionPrice": "0.000000555"
  },
  {
   "id": "mistralai/mistral-small-3.2-24b-instruct",
   "name": "Mistral: Mistral Small 3.2 24B",
   "contextTokens": 131072,
   "promptPrice": "0.000000075",
   "completionPrice": "0.0000002"
  },
  {
   "id": "mistralai/mixtral-8x22b-instruct",
   "name": "Mistral: Mixtral 8x22B Instruct",
   "contextTokens": 65536,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "mistralai/voxtral-small-24b-2507",
   "name": "Mistral: Voxtral Small 24B 2507",
   "contextTokens": 32768,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000003"
  },
  {
   "id": "moonshotai/kimi-k2",
   "name": "MoonshotAI: Kimi K2 0711",
   "contextTokens": 131072,
   "promptPrice": "0.00000057",
   "completionPrice": "0.0000023"
  },
  {
   "id": "moonshotai/kimi-k2-0905",
   "name": "MoonshotAI: Kimi K2 0905",
   "contextTokens": 262144,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000025"
  },
  {
   "id": "moonshotai/kimi-k2-thinking",
   "name": "MoonshotAI: Kimi K2 Thinking",
   "contextTokens": 262144,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000025"
  },
  {
   "id": "moonshotai/kimi-k2.5",
   "name": "MoonshotAI: Kimi K2.5",
   "contextTokens": 262144,
   "promptPrice": "0.00000045",
   "completionPrice": "0.00000225"
  },
  {
   "id": "moonshotai/kimi-k2.6",
   "name": "MoonshotAI: Kimi K2.6",
   "contextTokens": 262144,
   "promptPrice": "0.00000095",
   "completionPrice": "0.000004"
  },
  {
   "id": "moonshotai/kimi-k2.7-code",
   "name": "MoonshotAI: Kimi K2.7 Code",
   "contextTokens": 262144,
   "promptPrice": "0.00000066",
   "completionPrice": "0.0000034"
  },
  {
   "id": "moonshotai/kimi-k3",
   "name": "MoonshotAI: Kimi K3",
   "contextTokens": 1048576,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "moonshotai/kimi-k3:batch",
   "name": "MoonshotAI: Kimi K3 (batch)",
   "contextTokens": 1048576,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "morph/morph-v3-fast",
   "name": "Morph: Morph V3 Fast",
   "contextTokens": 81920,
   "promptPrice": "0.0000008",
   "completionPrice": "0.0000012"
  },
  {
   "id": "morph/morph-v3-large",
   "name": "Morph: Morph V3 Large",
   "contextTokens": 262144,
   "promptPrice": "0.0000009",
   "completionPrice": "0.0000019"
  },
  {
   "id": "nex-agi/nex-n2-mini",
   "name": "Nex AGI: Nex-N2-Mini",
   "contextTokens": 262144,
   "promptPrice": "0.000000025",
   "completionPrice": "0.0000001"
  },
  {
   "id": "nex-agi/nex-n2-pro",
   "name": "Nex AGI: Nex-N2-Pro",
   "contextTokens": 262144,
   "promptPrice": "0.00000025",
   "completionPrice": "0.000001"
  },
  {
   "id": "nousresearch/hermes-3-llama-3.1-405b",
   "name": "Nous: Hermes 3 405B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.000001",
   "completionPrice": "0.000001"
  },
  {
   "id": "nousresearch/hermes-3-llama-3.1-70b",
   "name": "Nous: Hermes 3 70B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.0000007",
   "completionPrice": "0.0000007"
  },
  {
   "id": "nousresearch/hermes-4-405b",
   "name": "Nous: Hermes 4 405B",
   "contextTokens": 131072,
   "promptPrice": "0.000001",
   "completionPrice": "0.000003"
  },
  {
   "id": "nousresearch/hermes-4-70b",
   "name": "Nous: Hermes 4 70B",
   "contextTokens": 131072,
   "promptPrice": "0.00000013",
   "completionPrice": "0.0000004"
  },
  {
   "id": "nvidia/nemotron-3-nano-30b-a3b",
   "name": "NVIDIA: Nemotron 3 Nano 30B A3B",
   "contextTokens": 262144,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000002"
  },
  {
   "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
   "name": "NVIDIA: Nemotron 3 Nano Omni (free)",
   "contextTokens": 256000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "nvidia/nemotron-3-super-120b-a12b",
   "name": "NVIDIA: Nemotron 3 Super",
   "contextTokens": 1000000,
   "promptPrice": "0.000000085",
   "completionPrice": "0.0000004"
  },
  {
   "id": "nvidia/nemotron-3-super-120b-a12b:free",
   "name": "NVIDIA: Nemotron 3 Super (free)",
   "contextTokens": 262144,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "nvidia/nemotron-3-ultra-550b-a55b",
   "name": "NVIDIA: Nemotron 3 Ultra",
   "contextTokens": 262144,
   "promptPrice": "0.0000005",
   "completionPrice": "0.0000022"
  },
  {
   "id": "nvidia/nemotron-3-ultra-550b-a55b:batch",
   "name": "NVIDIA: Nemotron 3 Ultra (batch)",
   "contextTokens": 512288,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000036"
  },
  {
   "id": "nvidia/nemotron-3-ultra-550b-a55b:free",
   "name": "NVIDIA: Nemotron 3 Ultra (free)",
   "contextTokens": 1000000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "nvidia/nemotron-3.5-content-safety:free",
   "name": "NVIDIA: Nemotron 3.5 Content Safety (free)",
   "contextTokens": 128000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "nvidia/nemotron-3.5-lightning",
   "name": "NVIDIA: Nemotron 3.5 Lightning",
   "contextTokens": 262144,
   "promptPrice": "0.00000008",
   "completionPrice": "0.0000002"
  },
  {
   "id": "nvidia/nemotron-3.5-lightning:free",
   "name": "NVIDIA: Nemotron 3.5 Lightning (free)",
   "contextTokens": 1000000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "openai/gpt-3.5-turbo",
   "name": "OpenAI: GPT-3.5 Turbo",
   "contextTokens": 16385,
   "promptPrice": "0.0000005",
   "completionPrice": "0.0000015"
  },
  {
   "id": "openai/gpt-3.5-turbo-0613",
   "name": "OpenAI: GPT-3.5 Turbo (older v0613)",
   "contextTokens": 4095,
   "promptPrice": "0.000001",
   "completionPrice": "0.000002"
  },
  {
   "id": "openai/gpt-3.5-turbo-16k",
   "name": "OpenAI: GPT-3.5 Turbo 16k",
   "contextTokens": 16385,
   "promptPrice": "0.000003",
   "completionPrice": "0.000004"
  },
  {
   "id": "openai/gpt-3.5-turbo-instruct",
   "name": "OpenAI: GPT-3.5 Turbo Instruct",
   "contextTokens": 4095,
   "promptPrice": "0.0000015",
   "completionPrice": "0.000002"
  },
  {
   "id": "openai/gpt-3.5-turbo:batch",
   "name": "OpenAI: GPT-3.5 Turbo (batch)",
   "contextTokens": 16385,
   "promptPrice": "0.00000025",
   "completionPrice": "0.00000075"
  },
  {
   "id": "openai/gpt-4",
   "name": "OpenAI: GPT-4",
   "contextTokens": 8191,
   "promptPrice": "0.00003",
   "completionPrice": "0.00006"
  },
  {
   "id": "openai/gpt-4-turbo",
   "name": "OpenAI: GPT-4 Turbo",
   "contextTokens": 128000,
   "promptPrice": "0.00001",
   "completionPrice": "0.00003"
  },
  {
   "id": "openai/gpt-4-turbo-preview",
   "name": "OpenAI: GPT-4 Turbo Preview",
   "contextTokens": 128000,
   "promptPrice": "0.00001",
   "completionPrice": "0.00003"
  },
  {
   "id": "openai/gpt-4-turbo:batch",
   "name": "OpenAI: GPT-4 Turbo (batch)",
   "contextTokens": 128000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000015"
  },
  {
   "id": "openai/gpt-4.1",
   "name": "OpenAI: GPT-4.1",
   "contextTokens": 1047576,
   "promptPrice": "0.000002",
   "completionPrice": "0.000008"
  },
  {
   "id": "openai/gpt-4.1-mini",
   "name": "OpenAI: GPT-4.1 Mini",
   "contextTokens": 1047576,
   "promptPrice": "0.0000004",
   "completionPrice": "0.0000016"
  },
  {
   "id": "openai/gpt-4.1-mini:batch",
   "name": "OpenAI: GPT-4.1 Mini (batch)",
   "contextTokens": 1047576,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000008"
  },
  {
   "id": "openai/gpt-4.1-nano",
   "name": "OpenAI: GPT-4.1 Nano",
   "contextTokens": 1047576,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000004"
  },
  {
   "id": "openai/gpt-4.1-nano:batch",
   "name": "OpenAI: GPT-4.1 Nano (batch)",
   "contextTokens": 1047576,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000002"
  },
  {
   "id": "openai/gpt-4.1:batch",
   "name": "OpenAI: GPT-4.1 (batch)",
   "contextTokens": 1047576,
   "promptPrice": "0.000001",
   "completionPrice": "0.000004"
  },
  {
   "id": "openai/gpt-4o",
   "name": "OpenAI: GPT-4o",
   "contextTokens": 128000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-4o-2024-05-13",
   "name": "OpenAI: GPT-4o (2024-05-13)",
   "contextTokens": 128000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000015"
  },
  {
   "id": "openai/gpt-4o-2024-08-06",
   "name": "OpenAI: GPT-4o (2024-08-06)",
   "contextTokens": 128000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-4o-2024-11-20",
   "name": "OpenAI: GPT-4o (2024-11-20)",
   "contextTokens": 128000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-4o-mini",
   "name": "OpenAI: GPT-4o-mini",
   "contextTokens": 128000,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "openai/gpt-4o-mini-2024-07-18",
   "name": "OpenAI: GPT-4o-mini (2024-07-18)",
   "contextTokens": 128000,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "openai/gpt-4o-mini:batch",
   "name": "OpenAI: GPT-4o-mini (batch)",
   "contextTokens": 128000,
   "promptPrice": "0.000000075",
   "completionPrice": "0.0000003"
  },
  {
   "id": "openai/gpt-4o:batch",
   "name": "OpenAI: GPT-4o (batch)",
   "contextTokens": 128000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.000005"
  },
  {
   "id": "openai/gpt-5",
   "name": "OpenAI: GPT-5",
   "contextTokens": 400000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5-image",
   "name": "OpenAI: GPT-5 Image",
   "contextTokens": 400000,
   "promptPrice": "0.00001",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5-image-mini",
   "name": "OpenAI: GPT-5 Image Mini",
   "contextTokens": 400000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.000002"
  },
  {
   "id": "openai/gpt-5-mini",
   "name": "OpenAI: GPT-5 Mini",
   "contextTokens": 400000,
   "promptPrice": "0.00000025",
   "completionPrice": "0.000002"
  },
  {
   "id": "openai/gpt-5-mini:batch",
   "name": "OpenAI: GPT-5 Mini (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.000000125",
   "completionPrice": "0.000001"
  },
  {
   "id": "openai/gpt-5-nano",
   "name": "OpenAI: GPT-5 Nano",
   "contextTokens": 400000,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000004"
  },
  {
   "id": "openai/gpt-5-nano:batch",
   "name": "OpenAI: GPT-5 Nano (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.000000025",
   "completionPrice": "0.0000002"
  },
  {
   "id": "openai/gpt-5-pro",
   "name": "OpenAI: GPT-5 Pro",
   "contextTokens": 400000,
   "promptPrice": "0.000015",
   "completionPrice": "0.00012"
  },
  {
   "id": "openai/gpt-5-pro:batch",
   "name": "OpenAI: GPT-5 Pro (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.0000075",
   "completionPrice": "0.00006"
  },
  {
   "id": "openai/gpt-5.1",
   "name": "OpenAI: GPT-5.1",
   "contextTokens": 400000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5.1-codex",
   "name": "OpenAI: GPT-5.1-Codex",
   "contextTokens": 400000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5.1-codex-max",
   "name": "OpenAI: GPT-5.1-Codex-Max",
   "contextTokens": 400000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5.1-codex-mini",
   "name": "OpenAI: GPT-5.1-Codex-Mini",
   "contextTokens": 400000,
   "promptPrice": "0.00000025",
   "completionPrice": "0.000002"
  },
  {
   "id": "openai/gpt-5.1:batch",
   "name": "OpenAI: GPT-5.1 (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.000000625",
   "completionPrice": "0.000005"
  },
  {
   "id": "openai/gpt-5.2",
   "name": "OpenAI: GPT-5.2",
   "contextTokens": 400000,
   "promptPrice": "0.00000175",
   "completionPrice": "0.000014"
  },
  {
   "id": "openai/gpt-5.2-chat",
   "name": "OpenAI: GPT-5.2 Chat",
   "contextTokens": 128000,
   "promptPrice": "0.00000175",
   "completionPrice": "0.000014"
  },
  {
   "id": "openai/gpt-5.2-codex",
   "name": "OpenAI: GPT-5.2-Codex",
   "contextTokens": 400000,
   "promptPrice": "0.00000175",
   "completionPrice": "0.000014"
  },
  {
   "id": "openai/gpt-5.2-pro",
   "name": "OpenAI: GPT-5.2 Pro",
   "contextTokens": 400000,
   "promptPrice": "0.000021",
   "completionPrice": "0.000168"
  },
  {
   "id": "openai/gpt-5.2-pro:batch",
   "name": "OpenAI: GPT-5.2 Pro (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.0000105",
   "completionPrice": "0.000084"
  },
  {
   "id": "openai/gpt-5.2:batch",
   "name": "OpenAI: GPT-5.2 (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.000000875",
   "completionPrice": "0.000007"
  },
  {
   "id": "openai/gpt-5.3-codex",
   "name": "OpenAI: GPT-5.3-Codex",
   "contextTokens": 400000,
   "promptPrice": "0.00000175",
   "completionPrice": "0.000014"
  },
  {
   "id": "openai/gpt-5.4",
   "name": "OpenAI: GPT-5.4",
   "contextTokens": 1050000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.000015"
  },
  {
   "id": "openai/gpt-5.4-image-2",
   "name": "OpenAI: GPT-5.4 Image 2",
   "contextTokens": 272000,
   "promptPrice": "0.000008",
   "completionPrice": "0.000015"
  },
  {
   "id": "openai/gpt-5.4-mini",
   "name": "OpenAI: GPT-5.4 Mini",
   "contextTokens": 400000,
   "promptPrice": "0.00000075",
   "completionPrice": "0.0000045"
  },
  {
   "id": "openai/gpt-5.4-mini:batch",
   "name": "OpenAI: GPT-5.4 Mini (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.000000375",
   "completionPrice": "0.00000225"
  },
  {
   "id": "openai/gpt-5.4-nano",
   "name": "OpenAI: GPT-5.4 Nano",
   "contextTokens": 400000,
   "promptPrice": "0.0000002",
   "completionPrice": "0.00000125"
  },
  {
   "id": "openai/gpt-5.4-nano:batch",
   "name": "OpenAI: GPT-5.4 Nano (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.0000001",
   "completionPrice": "0.000000625"
  },
  {
   "id": "openai/gpt-5.4-pro",
   "name": "OpenAI: GPT-5.4 Pro",
   "contextTokens": 1050000,
   "promptPrice": "0.00003",
   "completionPrice": "0.00018"
  },
  {
   "id": "openai/gpt-5.4-pro:batch",
   "name": "OpenAI: GPT-5.4 Pro (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.000015",
   "completionPrice": "0.00009"
  },
  {
   "id": "openai/gpt-5.4:batch",
   "name": "OpenAI: GPT-5.4 (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.0000075"
  },
  {
   "id": "openai/gpt-5.5",
   "name": "OpenAI: GPT-5.5",
   "contextTokens": 1050000,
   "promptPrice": "0.000005",
   "completionPrice": "0.00003"
  },
  {
   "id": "openai/gpt-5.5-pro",
   "name": "OpenAI: GPT-5.5 Pro",
   "contextTokens": 1050000,
   "promptPrice": "0.00003",
   "completionPrice": "0.00018"
  },
  {
   "id": "openai/gpt-5.5-pro:batch",
   "name": "OpenAI: GPT-5.5 Pro (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.000015",
   "completionPrice": "0.00009"
  },
  {
   "id": "openai/gpt-5.5:batch",
   "name": "OpenAI: GPT-5.5 (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.000015"
  },
  {
   "id": "openai/gpt-5.6-luna",
   "name": "OpenAI: GPT-5.6 Luna",
   "contextTokens": 1050000,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000012"
  },
  {
   "id": "openai/gpt-5.6-luna-pro",
   "name": "OpenAI: GPT-5.6 Luna Pro",
   "contextTokens": 1050000,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000012"
  },
  {
   "id": "openai/gpt-5.6-luna-pro:batch",
   "name": "OpenAI: GPT-5.6 Luna Pro (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000006"
  },
  {
   "id": "openai/gpt-5.6-luna:batch",
   "name": "OpenAI: GPT-5.6 Luna (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000006"
  },
  {
   "id": "openai/gpt-5.6-sol",
   "name": "OpenAI: GPT-5.6 Sol",
   "contextTokens": 1050000,
   "promptPrice": "0.000002",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5.6-sol-pro",
   "name": "OpenAI: GPT-5.6 Sol Pro",
   "contextTokens": 1050000,
   "promptPrice": "0.000002",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-5.6-sol-pro:batch",
   "name": "OpenAI: GPT-5.6 Sol Pro (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000005"
  },
  {
   "id": "openai/gpt-5.6-sol:batch",
   "name": "OpenAI: GPT-5.6 Sol (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000005"
  },
  {
   "id": "openai/gpt-5.6-terra",
   "name": "OpenAI: GPT-5.6 Terra",
   "contextTokens": 1050000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "openai/gpt-5.6-terra-pro",
   "name": "OpenAI: GPT-5.6 Terra Pro",
   "contextTokens": 1050000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "openai/gpt-5.6-terra-pro:batch",
   "name": "OpenAI: GPT-5.6 Terra Pro (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000006"
  },
  {
   "id": "openai/gpt-5.6-terra:batch",
   "name": "OpenAI: GPT-5.6 Terra (batch)",
   "contextTokens": 1050000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000006"
  },
  {
   "id": "openai/gpt-5:batch",
   "name": "OpenAI: GPT-5 (batch)",
   "contextTokens": 400000,
   "promptPrice": "0.000000625",
   "completionPrice": "0.000005"
  },
  {
   "id": "openai/gpt-audio",
   "name": "OpenAI: GPT Audio",
   "contextTokens": 128000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00001"
  },
  {
   "id": "openai/gpt-audio-mini",
   "name": "OpenAI: GPT Audio Mini",
   "contextTokens": 128000,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000024"
  },
  {
   "id": "openai/gpt-chat-latest",
   "name": "OpenAI: GPT Chat Latest",
   "contextTokens": 400000,
   "promptPrice": "0.000005",
   "completionPrice": "0.00003"
  },
  {
   "id": "openai/gpt-oss-120b",
   "name": "OpenAI: gpt-oss-120b",
   "contextTokens": 131072,
   "promptPrice": "0.000000037",
   "completionPrice": "0.00000017"
  },
  {
   "id": "openai/gpt-oss-120b:batch",
   "name": "OpenAI: gpt-oss-120b (batch)",
   "contextTokens": 131072,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "openai/gpt-oss-20b",
   "name": "OpenAI: gpt-oss-20b",
   "contextTokens": 131072,
   "promptPrice": "0.00000003",
   "completionPrice": "0.00000013"
  },
  {
   "id": "openai/gpt-oss-20b:batch",
   "name": "OpenAI: gpt-oss-20b (batch)",
   "contextTokens": 131072,
   "promptPrice": "0.00000005",
   "completionPrice": "0.0000002"
  },
  {
   "id": "openai/gpt-oss-safeguard-20b",
   "name": "OpenAI: gpt-oss-safeguard-20b",
   "contextTokens": 131072,
   "promptPrice": "0.000000075",
   "completionPrice": "0.0000003"
  },
  {
   "id": "openai/o1",
   "name": "OpenAI: o1",
   "contextTokens": 200000,
   "promptPrice": "0.000015",
   "completionPrice": "0.00006"
  },
  {
   "id": "openai/o1-pro",
   "name": "OpenAI: o1-pro",
   "contextTokens": 200000,
   "promptPrice": "0.00015",
   "completionPrice": "0.0006"
  },
  {
   "id": "openai/o3",
   "name": "OpenAI: o3",
   "contextTokens": 200000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000008"
  },
  {
   "id": "openai/o3-mini",
   "name": "OpenAI: o3 Mini",
   "contextTokens": 200000,
   "promptPrice": "0.0000011",
   "completionPrice": "0.0000044"
  },
  {
   "id": "openai/o3-mini-high",
   "name": "OpenAI: o3 Mini High",
   "contextTokens": 200000,
   "promptPrice": "0.0000011",
   "completionPrice": "0.0000044"
  },
  {
   "id": "openai/o3-mini:batch",
   "name": "OpenAI: o3 Mini (batch)",
   "contextTokens": 200000,
   "promptPrice": "0.00000055",
   "completionPrice": "0.0000022"
  },
  {
   "id": "openai/o3-pro",
   "name": "OpenAI: o3 Pro",
   "contextTokens": 200000,
   "promptPrice": "0.00002",
   "completionPrice": "0.00008"
  },
  {
   "id": "openai/o3:batch",
   "name": "OpenAI: o3 (batch)",
   "contextTokens": 200000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000004"
  },
  {
   "id": "openai/o4-mini",
   "name": "OpenAI: o4 Mini",
   "contextTokens": 200000,
   "promptPrice": "0.0000011",
   "completionPrice": "0.0000044"
  },
  {
   "id": "openai/o4-mini-high",
   "name": "OpenAI: o4 Mini High",
   "contextTokens": 200000,
   "promptPrice": "0.0000011",
   "completionPrice": "0.0000044"
  },
  {
   "id": "openai/o4-mini:batch",
   "name": "OpenAI: o4 Mini (batch)",
   "contextTokens": 200000,
   "promptPrice": "0.00000055",
   "completionPrice": "0.0000022"
  },
  {
   "id": "openrouter/auto",
   "name": "Auto Router",
   "contextTokens": 2000000,
   "promptPrice": "-1",
   "completionPrice": "-1"
  },
  {
   "id": "openrouter/auto-beta",
   "name": "Auto Router (Beta)",
   "contextTokens": 2000000,
   "promptPrice": "-1",
   "completionPrice": "-1"
  },
  {
   "id": "openrouter/bodybuilder",
   "name": "Body Builder (beta)",
   "contextTokens": 128000,
   "promptPrice": "-1",
   "completionPrice": "-1"
  },
  {
   "id": "openrouter/free",
   "name": "Free Models Router",
   "contextTokens": 200000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "openrouter/fusion",
   "name": "OpenRouter: Fusion",
   "contextTokens": 1000000,
   "promptPrice": "-1",
   "completionPrice": "-1"
  },
  {
   "id": "openrouter/pareto-code",
   "name": "Pareto Code Router",
   "contextTokens": 2000000,
   "promptPrice": "-1",
   "completionPrice": "-1"
  },
  {
   "id": "perceptron/perceptron-mk1",
   "name": "Perceptron: Perceptron Mk1",
   "contextTokens": 32768,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000015"
  },
  {
   "id": "perplexity/sonar",
   "name": "Perplexity: Sonar",
   "contextTokens": 127072,
   "promptPrice": "0.000001",
   "completionPrice": "0.000001"
  },
  {
   "id": "perplexity/sonar-deep-research",
   "name": "Perplexity: Sonar Deep Research",
   "contextTokens": 128000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000008"
  },
  {
   "id": "perplexity/sonar-pro",
   "name": "Perplexity: Sonar Pro",
   "contextTokens": 200000,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "perplexity/sonar-pro-search",
   "name": "Perplexity: Sonar Pro Search",
   "contextTokens": 200000,
   "promptPrice": "0.000003",
   "completionPrice": "0.000015"
  },
  {
   "id": "perplexity/sonar-reasoning-pro",
   "name": "Perplexity: Sonar Reasoning Pro",
   "contextTokens": 128000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000008"
  },
  {
   "id": "poolside/laguna-s-2.1",
   "name": "Poolside: Laguna S 2.1",
   "contextTokens": 1048576,
   "promptPrice": "0.00000009",
   "completionPrice": "0.00000018"
  },
  {
   "id": "poolside/laguna-s-2.1:free",
   "name": "Poolside: Laguna S 2.1 (free)",
   "contextTokens": 262144,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "poolside/laguna-xs-2.1",
   "name": "Poolside: Laguna XS 2.1",
   "contextTokens": 262144,
   "promptPrice": "0.00000006",
   "completionPrice": "0.00000012"
  },
  {
   "id": "poolside/laguna-xs-2.1:free",
   "name": "Poolside: Laguna XS 2.1 (free)",
   "contextTokens": 262144,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "qwen/qwen-2.5-72b-instruct",
   "name": "Qwen2.5 72B Instruct",
   "contextTokens": 32768,
   "promptPrice": "0.00000036",
   "completionPrice": "0.0000004"
  },
  {
   "id": "qwen/qwen-2.5-7b-instruct",
   "name": "Qwen: Qwen2.5 7B Instruct",
   "contextTokens": 32768,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000002"
  },
  {
   "id": "qwen/qwen-2.5-coder-32b-instruct",
   "name": "Qwen2.5 Coder 32B Instruct",
   "contextTokens": 32768,
   "promptPrice": "0.00000066",
   "completionPrice": "0.000001"
  },
  {
   "id": "qwen/qwen-plus",
   "name": "Qwen: Qwen-Plus",
   "contextTokens": 1000000,
   "promptPrice": "0.00000026",
   "completionPrice": "0.00000078"
  },
  {
   "id": "qwen/qwen-plus-2025-07-28",
   "name": "Qwen: Qwen Plus 0728",
   "contextTokens": 1000000,
   "promptPrice": "0.00000026",
   "completionPrice": "0.00000078"
  },
  {
   "id": "qwen/qwen2.5-vl-72b-instruct",
   "name": "Qwen: Qwen2.5 VL 72B Instruct",
   "contextTokens": 128000,
   "promptPrice": "0.00000025",
   "completionPrice": "0.00000075"
  },
  {
   "id": "qwen/qwen3-14b",
   "name": "Qwen: Qwen3 14B",
   "contextTokens": 131072,
   "promptPrice": "0.00000012",
   "completionPrice": "0.00000024"
  },
  {
   "id": "qwen/qwen3-235b-a22b",
   "name": "Qwen: Qwen3 235B A22B",
   "contextTokens": 131072,
   "promptPrice": "0.000000455",
   "completionPrice": "0.00000182"
  },
  {
   "id": "qwen/qwen3-235b-a22b-2507",
   "name": "Qwen: Qwen3 235B A22B Instruct 2507",
   "contextTokens": 262144,
   "promptPrice": "0.0000000875",
   "completionPrice": "0.00000035"
  },
  {
   "id": "qwen/qwen3-235b-a22b-thinking-2507",
   "name": "Qwen: Qwen3 235B A22B Thinking 2507",
   "contextTokens": 131072,
   "promptPrice": "0.00000023",
   "completionPrice": "0.0000023"
  },
  {
   "id": "qwen/qwen3-30b-a3b",
   "name": "Qwen: Qwen3 30B A3B",
   "contextTokens": 131072,
   "promptPrice": "0.00000012",
   "completionPrice": "0.0000005"
  },
  {
   "id": "qwen/qwen3-30b-a3b-instruct-2507",
   "name": "Qwen: Qwen3 30B A3B Instruct 2507",
   "contextTokens": 262144,
   "promptPrice": "0.00000004815",
   "completionPrice": "0.00000019305"
  },
  {
   "id": "qwen/qwen3-30b-a3b-thinking-2507",
   "name": "Qwen: Qwen3 30B A3B Thinking 2507",
   "contextTokens": 81920,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000024"
  },
  {
   "id": "qwen/qwen3-32b",
   "name": "Qwen: Qwen3 32B",
   "contextTokens": 131072,
   "promptPrice": "0.00000008",
   "completionPrice": "0.00000028"
  },
  {
   "id": "qwen/qwen3-8b",
   "name": "Qwen: Qwen3 8B",
   "contextTokens": 131072,
   "promptPrice": "0.000000117",
   "completionPrice": "0.000000455"
  },
  {
   "id": "qwen/qwen3-coder",
   "name": "Qwen: Qwen3 Coder 480B A35B",
   "contextTokens": 262144,
   "promptPrice": "0.0000003",
   "completionPrice": "0.000001"
  },
  {
   "id": "qwen/qwen3-coder-30b-a3b-instruct",
   "name": "Qwen: Qwen3 Coder 30B A3B Instruct",
   "contextTokens": 262144,
   "promptPrice": "0.00000007",
   "completionPrice": "0.00000028"
  },
  {
   "id": "qwen/qwen3-coder-flash",
   "name": "Qwen: Qwen3 Coder Flash",
   "contextTokens": 1000000,
   "promptPrice": "0.000000195",
   "completionPrice": "0.000000975"
  },
  {
   "id": "qwen/qwen3-coder-next",
   "name": "Qwen: Qwen3 Coder Next",
   "contextTokens": 262144,
   "promptPrice": "0.00000012",
   "completionPrice": "0.0000008"
  },
  {
   "id": "qwen/qwen3-coder-plus",
   "name": "Qwen: Qwen3 Coder Plus",
   "contextTokens": 1000000,
   "promptPrice": "0.00000065",
   "completionPrice": "0.00000325"
  },
  {
   "id": "qwen/qwen3-max",
   "name": "Qwen: Qwen3 Max",
   "contextTokens": 262144,
   "promptPrice": "0.00000078",
   "completionPrice": "0.0000039"
  },
  {
   "id": "qwen/qwen3-max-thinking",
   "name": "Qwen: Qwen3 Max Thinking",
   "contextTokens": 262144,
   "promptPrice": "0.00000078",
   "completionPrice": "0.0000039"
  },
  {
   "id": "qwen/qwen3-next-80b-a3b-instruct",
   "name": "Qwen: Qwen3 Next 80B A3B Instruct",
   "contextTokens": 262144,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000011"
  },
  {
   "id": "qwen/qwen3-next-80b-a3b-thinking",
   "name": "Qwen: Qwen3 Next 80B A3B Thinking",
   "contextTokens": 262144,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000012"
  },
  {
   "id": "qwen/qwen3-vl-235b-a22b-instruct",
   "name": "Qwen: Qwen3 VL 235B A22B Instruct",
   "contextTokens": 262144,
   "promptPrice": "0.00000021",
   "completionPrice": "0.0000019"
  },
  {
   "id": "qwen/qwen3-vl-235b-a22b-thinking",
   "name": "Qwen: Qwen3 VL 235B A22B Thinking",
   "contextTokens": 131072,
   "promptPrice": "0.0000004",
   "completionPrice": "0.000004"
  },
  {
   "id": "qwen/qwen3-vl-30b-a3b-instruct",
   "name": "Qwen: Qwen3 VL 30B A3B Instruct",
   "contextTokens": 262144,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "qwen/qwen3-vl-30b-a3b-thinking",
   "name": "Qwen: Qwen3 VL 30B A3B Thinking",
   "contextTokens": 262144,
   "promptPrice": "0.0000002",
   "completionPrice": "0.0000024"
  },
  {
   "id": "qwen/qwen3-vl-32b-instruct",
   "name": "Qwen: Qwen3 VL 32B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.000000104",
   "completionPrice": "0.000000416"
  },
  {
   "id": "qwen/qwen3-vl-8b-instruct",
   "name": "Qwen: Qwen3 VL 8B Instruct",
   "contextTokens": 262144,
   "promptPrice": "0.000000117",
   "completionPrice": "0.000000455"
  },
  {
   "id": "qwen/qwen3-vl-8b-thinking",
   "name": "Qwen: Qwen3 VL 8B Thinking",
   "contextTokens": 131072,
   "promptPrice": "0.00000018",
   "completionPrice": "0.0000021"
  },
  {
   "id": "qwen/qwen3.5-122b-a10b",
   "name": "Qwen: Qwen3.5-122B-A10B",
   "contextTokens": 262144,
   "promptPrice": "0.00000029",
   "completionPrice": "0.0000024"
  },
  {
   "id": "qwen/qwen3.5-27b",
   "name": "Qwen: Qwen3.5-27B",
   "contextTokens": 262144,
   "promptPrice": "0.000000195",
   "completionPrice": "0.00000156"
  },
  {
   "id": "qwen/qwen3.5-35b-a3b",
   "name": "Qwen: Qwen3.5-35B-A3B",
   "contextTokens": 262144,
   "promptPrice": "0.00000025",
   "completionPrice": "0.00000125"
  },
  {
   "id": "qwen/qwen3.5-397b-a17b",
   "name": "Qwen: Qwen3.5 397B A17B",
   "contextTokens": 262144,
   "promptPrice": "0.00000039",
   "completionPrice": "0.00000234"
  },
  {
   "id": "qwen/qwen3.5-9b",
   "name": "Qwen: Qwen3.5-9B",
   "contextTokens": 262144,
   "promptPrice": "0.0000001",
   "completionPrice": "0.00000015"
  },
  {
   "id": "qwen/qwen3.5-9b:batch",
   "name": "Qwen: Qwen3.5-9B (batch)",
   "contextTokens": 262144,
   "promptPrice": "0.00000017",
   "completionPrice": "0.00000025"
  },
  {
   "id": "qwen/qwen3.5-flash-02-23",
   "name": "Qwen: Qwen3.5-Flash",
   "contextTokens": 1000000,
   "promptPrice": "0.000000065",
   "completionPrice": "0.00000026"
  },
  {
   "id": "qwen/qwen3.5-plus-02-15",
   "name": "Qwen: Qwen3.5 Plus 2026-02-15",
   "contextTokens": 1000000,
   "promptPrice": "0.00000026",
   "completionPrice": "0.00000156"
  },
  {
   "id": "qwen/qwen3.5-plus-20260420",
   "name": "Qwen: Qwen3.5 Plus 2026-04-20",
   "contextTokens": 1000000,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000018"
  },
  {
   "id": "qwen/qwen3.6-27b",
   "name": "Qwen: Qwen3.6 27B",
   "contextTokens": 262144,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000036"
  },
  {
   "id": "qwen/qwen3.6-35b-a3b",
   "name": "Qwen: Qwen3.6 35B A3B",
   "contextTokens": 262144,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000009"
  },
  {
   "id": "qwen/qwen3.6-flash",
   "name": "Qwen: Qwen3.6 Flash",
   "contextTokens": 1000000,
   "promptPrice": "0.0000001875",
   "completionPrice": "0.000001125"
  },
  {
   "id": "qwen/qwen3.6-max-preview",
   "name": "Qwen: Qwen3.6 Max Preview",
   "contextTokens": 262144,
   "promptPrice": "0.000001027",
   "completionPrice": "0.000006162"
  },
  {
   "id": "qwen/qwen3.6-plus",
   "name": "Qwen: Qwen3.6 Plus",
   "contextTokens": 1000000,
   "promptPrice": "0.000000325",
   "completionPrice": "0.00000195"
  },
  {
   "id": "qwen/qwen3.7-flash",
   "name": "Qwen: Qwen3.7 Flash",
   "contextTokens": 1000000,
   "promptPrice": "0.00000003",
   "completionPrice": "0.00000013"
  },
  {
   "id": "qwen/qwen3.7-max",
   "name": "Qwen: Qwen3.7 Max",
   "contextTokens": 1000000,
   "promptPrice": "0.000001475",
   "completionPrice": "0.000004425"
  },
  {
   "id": "qwen/qwen3.7-plus",
   "name": "Qwen: Qwen3.7 Plus",
   "contextTokens": 1000000,
   "promptPrice": "0.00000032",
   "completionPrice": "0.00000128"
  },
  {
   "id": "qwen/qwen3.8-2.4t-a95b",
   "name": "Qwen: Qwen3.8 2.4T A95B",
   "contextTokens": 1048576,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "qwen/qwen3.8-2.4t-a95b:batch",
   "name": "Qwen: Qwen3.8 2.4T A95B (batch)",
   "contextTokens": 1010000,
   "promptPrice": "0.0000025",
   "completionPrice": "0.00000625"
  },
  {
   "id": "qwen/qwen3.8-27b",
   "name": "Qwen: Qwen3.8 27B",
   "contextTokens": 1000000,
   "promptPrice": "0.000000425",
   "completionPrice": "0.00000255"
  },
  {
   "id": "qwen/qwen3.8-flash",
   "name": "Qwen: Qwen3.8 Flash",
   "contextTokens": 1000000,
   "promptPrice": "0.00000015",
   "completionPrice": "0.00000047"
  },
  {
   "id": "qwen/qwen3.8-max",
   "name": "Qwen: Qwen3.8 Max",
   "contextTokens": 1000000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "rekaai/reka-edge",
   "name": "Reka Edge",
   "contextTokens": 16384,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000001"
  },
  {
   "id": "rekaai/reka-flash-3",
   "name": "Reka Flash 3",
   "contextTokens": 65536,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000002"
  },
  {
   "id": "relace/relace-apply-3",
   "name": "Relace: Relace Apply 3",
   "contextTokens": 256000,
   "promptPrice": "0.00000085",
   "completionPrice": "0.00000125"
  },
  {
   "id": "relace/relace-search",
   "name": "Relace: Relace Search",
   "contextTokens": 256000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000003"
  },
  {
   "id": "sakana/fugu-ultra",
   "name": "Sakana: Fugu Ultra",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.00003"
  },
  {
   "id": "sakana/sakana-namazu",
   "name": "Sakana: Sakana Namazu",
   "contextTokens": 262144,
   "promptPrice": "0.00000095",
   "completionPrice": "0.000004"
  },
  {
   "id": "sao10k/l3-lunaris-8b",
   "name": "Sao10K: Llama 3 8B Lunaris",
   "contextTokens": 8192,
   "promptPrice": "0.00000004",
   "completionPrice": "0.00000005"
  },
  {
   "id": "sao10k/l3.1-euryale-70b",
   "name": "Sao10K: Llama 3.1 Euryale 70B v2.2",
   "contextTokens": 131072,
   "promptPrice": "0.00000085",
   "completionPrice": "0.00000085"
  },
  {
   "id": "sao10k/l3.3-euryale-70b",
   "name": "Sao10K: Llama 3.3 Euryale 70B",
   "contextTokens": 131072,
   "promptPrice": "0.00000065",
   "completionPrice": "0.00000075"
  },
  {
   "id": "stepfun/step-3.5-flash",
   "name": "StepFun: Step 3.5 Flash",
   "contextTokens": 262144,
   "promptPrice": "0.0000001",
   "completionPrice": "0.0000003"
  },
  {
   "id": "stepfun/step-3.7-flash",
   "name": "StepFun: Step 3.7 Flash",
   "contextTokens": 262144,
   "promptPrice": "0.0000002",
   "completionPrice": "0.00000115"
  },
  {
   "id": "tencent/hunyuan-a13b-instruct",
   "name": "Tencent: Hunyuan A13B Instruct",
   "contextTokens": 131072,
   "promptPrice": "0.00000014",
   "completionPrice": "0.00000057"
  },
  {
   "id": "tencent/hy-mt2-1.8b",
   "name": "Tencent: Hy-MT2-1.8B",
   "contextTokens": 8192,
   "promptPrice": "0.000000044",
   "completionPrice": "0.000000177"
  },
  {
   "id": "tencent/hy-mt2-30b-a3b",
   "name": "Tencent: Hy-MT2-30B-A3B",
   "contextTokens": 8192,
   "promptPrice": "0.000000074",
   "completionPrice": "0.000000295"
  },
  {
   "id": "tencent/hy-mt2-7b",
   "name": "Tencent: Hy-MT2-7B",
   "contextTokens": 8192,
   "promptPrice": "0.000000074",
   "completionPrice": "0.000000295"
  },
  {
   "id": "tencent/hy3",
   "name": "Tencent: Hy3",
   "contextTokens": 262144,
   "promptPrice": "0.0000000825",
   "completionPrice": "0.00000033"
  },
  {
   "id": "tencent/hy3-preview",
   "name": "Tencent: Hy3 preview",
   "contextTokens": 262144,
   "promptPrice": "0.00000018",
   "completionPrice": "0.0000006"
  },
  {
   "id": "tencent/hy4-preview",
   "name": "Tencent: Hy4 preview",
   "contextTokens": 1048576,
   "promptPrice": "0.000000834",
   "completionPrice": "0.000002501"
  },
  {
   "id": "thedrummer/cydonia-24b-v4.1",
   "name": "TheDrummer: Cydonia 24B V4.1",
   "contextTokens": 131072,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000005"
  },
  {
   "id": "thedrummer/skyfall-36b-v2",
   "name": "TheDrummer: Skyfall 36B V2",
   "contextTokens": 32768,
   "promptPrice": "0.00000055",
   "completionPrice": "0.0000008"
  },
  {
   "id": "thedrummer/unslopnemo-12b",
   "name": "TheDrummer: UnslopNemo 12B",
   "contextTokens": 1024000,
   "promptPrice": "0.0000004",
   "completionPrice": "0.0000004"
  },
  {
   "id": "thinkingmachines/inkling",
   "name": "Thinking Machines: Inkling",
   "contextTokens": 1048576,
   "promptPrice": "0.000001",
   "completionPrice": "0.00000405"
  },
  {
   "id": "thinkingmachines/inkling-small",
   "name": "Thinking Machines: Inkling Small",
   "contextTokens": 1048576,
   "promptPrice": "0.00000045",
   "completionPrice": "0.0000012"
  },
  {
   "id": "thinkingmachines/inkling-small:batch",
   "name": "Thinking Machines: Inkling Small (batch)",
   "contextTokens": 524288,
   "promptPrice": "0.0000005",
   "completionPrice": "0.0000012"
  },
  {
   "id": "thinkingmachines/inkling-small:free",
   "name": "Thinking Machines: Inkling Small (free)",
   "contextTokens": 1048576,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "thinkingmachines/inkling:batch",
   "name": "Thinking Machines: Inkling (batch)",
   "contextTokens": 524288,
   "promptPrice": "0.000001",
   "completionPrice": "0.00000405"
  },
  {
   "id": "thinkingmachines/inkling:free",
   "name": "Thinking Machines: Inkling (free)",
   "contextTokens": 1048576,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "undi95/remm-slerp-l2-13b",
   "name": "ReMM SLERP 13B",
   "contextTokens": 6144,
   "promptPrice": "0.00000045",
   "completionPrice": "0.00000065"
  },
  {
   "id": "upstage/solar-pro-3",
   "name": "Upstage: Solar Pro 3",
   "contextTokens": 131072,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000006"
  },
  {
   "id": "upstage/solar-pro4",
   "name": "Upstage: Solar Pro 4",
   "contextTokens": 524288,
   "promptPrice": "0.00000003",
   "completionPrice": "0.00000012"
  },
  {
   "id": "writer/palmyra-x5",
   "name": "Writer: Palmyra X5",
   "contextTokens": 1040000,
   "promptPrice": "0.0000006",
   "completionPrice": "0.000006"
  },
  {
   "id": "x-ai/grok-4.20",
   "name": "SpaceXAI: Grok 4.20",
   "contextTokens": 2000000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.0000025"
  },
  {
   "id": "x-ai/grok-4.20-multi-agent",
   "name": "SpaceXAI: Grok 4.20 Multi-Agent",
   "contextTokens": 2000000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.0000025"
  },
  {
   "id": "x-ai/grok-4.3",
   "name": "SpaceXAI: Grok 4.3",
   "contextTokens": 1000000,
   "promptPrice": "0.00000125",
   "completionPrice": "0.0000025"
  },
  {
   "id": "x-ai/grok-4.5",
   "name": "SpaceXAI: Grok 4.5",
   "contextTokens": 500000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "x-ai/grok-4.6",
   "name": "SpaceXAI: Grok 4.6",
   "contextTokens": 500000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "x-ai/grok-build-0.1",
   "name": "SpaceXAI: Grok Build 0.1",
   "contextTokens": 256000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000002"
  },
  {
   "id": "xiaomi/mimo-v2.5",
   "name": "Xiaomi: MiMo-V2.5",
   "contextTokens": 1050000,
   "promptPrice": "0.00000014",
   "completionPrice": "0.00000028"
  },
  {
   "id": "xiaomi/mimo-v2.5-pro",
   "name": "Xiaomi: MiMo-V2.5-Pro",
   "contextTokens": 1050000,
   "promptPrice": "0.000000435",
   "completionPrice": "0.00000087"
  },
  {
   "id": "z-ai/glm-4.5",
   "name": "Z.ai: GLM 4.5",
   "contextTokens": 131072,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000022"
  },
  {
   "id": "z-ai/glm-4.5-air",
   "name": "Z.ai: GLM 4.5 Air",
   "contextTokens": 131072,
   "promptPrice": "0.00000013",
   "completionPrice": "0.00000085"
  },
  {
   "id": "z-ai/glm-4.5v",
   "name": "Z.ai: GLM 4.5V",
   "contextTokens": 65536,
   "promptPrice": "0.0000006",
   "completionPrice": "0.0000018"
  },
  {
   "id": "z-ai/glm-4.6",
   "name": "Z.ai: GLM 4.6",
   "contextTokens": 204800,
   "promptPrice": "0.00000043",
   "completionPrice": "0.00000175"
  },
  {
   "id": "z-ai/glm-4.6v",
   "name": "Z.ai: GLM 4.6V",
   "contextTokens": 131072,
   "promptPrice": "0.0000003",
   "completionPrice": "0.0000009"
  },
  {
   "id": "z-ai/glm-4.7",
   "name": "Z.ai: GLM 4.7",
   "contextTokens": 204800,
   "promptPrice": "0.0000004",
   "completionPrice": "0.00000175"
  },
  {
   "id": "z-ai/glm-4.7-flash",
   "name": "Z.ai: GLM 4.7 Flash",
   "contextTokens": 202752,
   "promptPrice": "0.00000006",
   "completionPrice": "0.0000004"
  },
  {
   "id": "z-ai/glm-5",
   "name": "Z.ai: GLM 5",
   "contextTokens": 204800,
   "promptPrice": "0.0000006",
   "completionPrice": "0.00000192"
  },
  {
   "id": "z-ai/glm-5-turbo",
   "name": "Z.ai: GLM 5 Turbo",
   "contextTokens": 202752,
   "promptPrice": "0.0000012",
   "completionPrice": "0.000004"
  },
  {
   "id": "z-ai/glm-5.1",
   "name": "Z.ai: GLM 5.1",
   "contextTokens": 204800,
   "promptPrice": "0.000000966",
   "completionPrice": "0.000003036"
  },
  {
   "id": "z-ai/glm-5.2",
   "name": "Z.ai: GLM 5.2",
   "contextTokens": 1048576,
   "promptPrice": "0.00000119",
   "completionPrice": "0.00000374"
  },
  {
   "id": "z-ai/glm-5.2:free",
   "name": "Z.ai: GLM 5.2 (free)",
   "contextTokens": 256000,
   "promptPrice": "0",
   "completionPrice": "0"
  },
  {
   "id": "z-ai/glm-5.3",
   "name": "Z.ai: GLM 5.3",
   "contextTokens": 1310720,
   "promptPrice": "0.0000014",
   "completionPrice": "0.0000044"
  },
  {
   "id": "z-ai/glm-5.3-flash",
   "name": "Z.ai: GLM 5.3 Flash",
   "contextTokens": 1310720,
   "promptPrice": "0.000000075",
   "completionPrice": "0.00000025"
  },
  {
   "id": "z-ai/glm-5.3-flash:batch",
   "name": "Z.ai: GLM 5.3 Flash (batch)",
   "contextTokens": 1048575,
   "promptPrice": "0.00000015",
   "completionPrice": "0.0000005"
  },
  {
   "id": "z-ai/glm-5v-turbo",
   "name": "Z.ai: GLM 5V Turbo",
   "contextTokens": 202752,
   "promptPrice": "0.0000012",
   "completionPrice": "0.000004"
  },
  {
   "id": "~anthropic/claude-fable-latest",
   "name": "Anthropic: Claude Fable Latest",
   "contextTokens": 1000000,
   "promptPrice": "0.00001",
   "completionPrice": "0.00005"
  },
  {
   "id": "~anthropic/claude-haiku-latest",
   "name": "Anthropic Claude Haiku Latest",
   "contextTokens": 200000,
   "promptPrice": "0.000001",
   "completionPrice": "0.000005"
  },
  {
   "id": "~anthropic/claude-opus-latest",
   "name": "Anthropic: Claude Opus Latest",
   "contextTokens": 1000000,
   "promptPrice": "0.000005",
   "completionPrice": "0.000025"
  },
  {
   "id": "~anthropic/claude-sonnet-latest",
   "name": "Anthropic Claude Sonnet Latest",
   "contextTokens": 1000000,
   "promptPrice": "0.000002",
   "completionPrice": "0.00001"
  },
  {
   "id": "~deepseek/deepseek-v4-flash-latest",
   "name": "DeepSeek V4 Flash Latest",
   "contextTokens": 1310720,
   "promptPrice": "0.00000004998",
   "completionPrice": "0.00000009996"
  },
  {
   "id": "~google/gemini-flash-latest",
   "name": "Google Gemini Flash Latest",
   "contextTokens": 1048576,
   "promptPrice": "0.00000075",
   "completionPrice": "0.00000375"
  },
  {
   "id": "~google/gemini-pro-latest",
   "name": "Google Gemini Pro Latest",
   "contextTokens": 1048576,
   "promptPrice": "0.000002",
   "completionPrice": "0.000012"
  },
  {
   "id": "~moonshotai/kimi-latest",
   "name": "MoonshotAI Kimi Latest",
   "contextTokens": 1048576,
   "promptPrice": "0.00000255",
   "completionPrice": "0.00001275"
  },
  {
   "id": "~openai/gpt-latest",
   "name": "OpenAI GPT Latest",
   "contextTokens": 1050000,
   "promptPrice": "0.000002",
   "completionPrice": "0.00001"
  },
  {
   "id": "~openai/gpt-mini-latest",
   "name": "OpenAI GPT Mini Latest",
   "contextTokens": 400000,
   "promptPrice": "0.00000075",
   "completionPrice": "0.0000045"
  },
  {
   "id": "~x-ai/grok-latest",
   "name": "xAI: Grok Latest",
   "contextTokens": 500000,
   "promptPrice": "0.000002",
   "completionPrice": "0.000006"
  },
  {
   "id": "~z-ai/glm-latest",
   "name": "Z.ai: GLM Latest",
   "contextTokens": 1310720,
   "promptPrice": "0.00000117",
   "completionPrice": "0.00000396"
  }
 ]
}
