// os/installs — the ALWAYS-ALPINE-LATEST boundary for the default-install port. The pure, deterministic port
// (routes, specs, hexbit compiles, the build order) lives in src/quantum/os and reads only the committed
// mirror; THIS module is the one place the mirror is allowed to move: it re-reads Alpine's PUBLISHED
// latest-stable index over the network — a wall-clock-dependent act, honest HERE (src/os, the named
// non-determinism boundary) and nowhere else — recomputes alpine-base's dependency closure, and renders the
// exact mirror bytes for scripts/lean-installs to commit. Best-effort and honest: a down mirror yields null
// and the committed mirror stands; a closure is NEVER fabricated. The response is DATA: parsed, closed over,
// content-addressed — never installed, linked, booted, or executed. Integrity, not execution.
import { untarGzipMember } from '../packages/index.js'
import { fetchAlpineLatest } from '../alpine/index.js'
import { fetchDriverLatest } from '../../drivers/driver/index.js'
import { type InstallsMirror } from '../../quantum/os/mirror/index.js'

const CDN = 'https://dl-cdn.alpinelinux.org/alpine'
interface IndexRecord { name: string; version: string; checksum: string; desc: string; deps: string[]; provides: string[] }

const parseIndex = (apkindex: string): IndexRecord[] =>
  apkindex.split('\n\n').filter((r) => r.includes('P:')).map((r) => {
    const g = (k: string) => (r.match(new RegExp(`^${k}:(.+)$`, 'm')) || [])[1] ?? ''
    return { name: g('P'), version: g('V'), checksum: g('C'), desc: g('T'), deps: g('D').split(' ').filter(Boolean), provides: g('p').split(' ').filter(Boolean) }
  }).filter((p) => p.name)

/** fetchDefaultInstalls(branch, repo, arch) → recompute the default install from the PUBLISHED index, LIVE:
 *  read APKINDEX, resolve alpine-base's dependency closure (plain names, versioned constraints, and the
 *  so:/cmd:/file forms via each package's published providers), and return the mirror-shaped data — or null
 *  if the mirror is down or alpine-base is missing. Always Alpine latest, never a hand-frozen set. */
export async function fetchDefaultInstalls(branch = 'latest-stable', repo = 'main', arch = 'x86_64'): Promise<InstallsMirror | null> {
  try {
    const gz = new Uint8Array(await (await fetch(`${CDN}/${branch}/${repo}/${arch}/APKINDEX.tar.gz`)).arrayBuffer())
    // the member SEARCH, never the whole-buffer decode. Until 2026-08-25 this read the first gzip member — the
    // signature — and so returned null for every live index, which the caller could not tell from "Alpine has no
    // default install set". See untarGzipMember in os/packages for the format and the measurement.
    const recs = parseIndex(await untarGzipMember(gz, 'APKINDEX'))
    const byName = new Map(recs.map((r) => [r.name, r]))
    const providers = new Map<string, string>()
    for (const r of recs) for (const pv of r.provides) { const key = pv.split('=')[0]!; if (!providers.has(key)) providers.set(key, r.name) }
    const resolve = (dep: string): string | null => {
      if (dep.startsWith('!')) return null                        // a conflict marker excludes, it never adds
      const bare = dep.split(/[<>=~]/)[0]!
      return byName.has(bare) ? bare : providers.get(bare) ?? null
    }
    const seed = 'alpine-base'
    if (!byName.has(seed)) return null
    const inSet = new Set<string>([seed])
    const queue = [seed]
    while (queue.length) {
      const r = byName.get(queue.shift()!)!
      for (const d of r.deps) {
        const t = resolve(d)
        if (t && !inSet.has(t)) { inSet.add(t); queue.push(t) }
      }
    }
    const release = await fetchAlpineLatest(arch, branch)
    if (!release) return null                                     // the set without its release pin is half a port
    const driverPin = await fetchDriverLatest(arch, branch)
    if (!driverPin) return null                                   // drivers/modloop pin moves with the release or nothing
    const names = [...inSet].sort()
    return {
      branch, repo, arch,
      release: { version: release.version, rootfsSha256: release.rootfsSha256 },
      driver: { flavor: driverPin.flavor, file: driverPin.file, sha256: driverPin.sha256 },
      count: names.length,
      packages: names.map((n) => {
        const r = byName.get(n)!
        return { name: n, version: r.version, checksum: r.checksum, desc: r.desc, deps: [...new Set(r.deps.map(resolve).filter((x): x is string => x !== null))].sort() }
      }),
    }
  } catch {
    return null  // a down mirror yields null — the committed mirror stands; nothing is ever fabricated
  }
}

/** renderMirror(data) → the EXACT bytes of src/quantum/os/mirror/index.ts for this data — the one serialisation
 *  the generator writes and the bootstrap wrote, so an unchanged upstream is a byte-identical mirror. */
export function renderMirror(m: InstallsMirror): string {
  return `// quantum/os/mirror — GENERATED by scripts/lean-installs.ts from Alpine ${m.branch} (${m.repo}/${m.arch}). DO NOT EDIT.
// The DEFAULT INSTALL: alpine-base's dependency closure in the PUBLISHED index, pinned with the release it is
// the world of, so every deterministic surface (site, MCP, tests, the Lean wing) reads the same set offline.
// Always Alpine latest: scripts/lean-installs re-reads latest-stable at the os/ boundary on every lean run and
// rewrites this file only when upstream moved. Data, never executed.

export interface MirrorPackage { name: string; version: string; checksum: string; desc: string; deps: string[] }
export interface InstallsMirror {
  branch: string; repo: string; arch: string
  release: { version: string; rootfsSha256: string }
  driver: { flavor: string; file: string; sha256: string }
  count: number
  packages: MirrorPackage[]
}

export const INSTALLS_MIRROR: InstallsMirror = ${JSON.stringify(m, null, 1)}
`
}
