// GENERATED by src/scripts/gen-packages.ts — DO NOT EDIT: the split is computed from src/index.ts
// (the one export surface). Regenerate with `npm run gen:packages`; the guard hard-rejects drift.
// @uuidna/quantum — the CLASSICAL, EXACT quantum surface: the Gaussian-integer state-vector simulator
// (honestly bounded, no quantum advantage), quantum messages / voting / receipts, the sailing fleet, the news
// portals, gravity contractions, the diamond involution, holofractal and pentagram folds, the A432 aura,
// quantum analytics, and the uuidnaOS provenance boundary (provenance and integrity, NEVER an OS port or
// execution). Integrity, not truth.
export { merkleGravity, doubleTorusGravity, doubleTorusField, fall, fixedPoints, seats } from '@uuidna/uuidna'
export { diamond, DIAMOND_FIXED, involute, involutionFixed } from '@uuidna/uuidna'
export { domainWave, type DomainWave } from '@uuidna/uuidna'
export {
  ket0, hadamard, cnot, cz, swap, toffoli, ccz, pauliX, pauliY, pauliZ, phaseS, phaseSdg,
  distribution, probability, marginal, amplitude, equalState, isInvolution, bellState, ghzState, receiptOf, quantumReceipt,
  runCircuit, isClassical, classicalMap, truthTable,
  report, fraction, label, type QState, type Prob, type Cx, type GateOp,
} from '@uuidna/uuidna'
export { gcdInt, coprime, starPolygon, fibonacciCycle, rotate, crt } from '@uuidna/uuidna'
export { pentagramHologramFractal, holofractalHook, type HoloFractal } from '@uuidna/uuidna'
export { pentagramStream, type PentagramStream, type PentagramStreamCell } from '@uuidna/uuidna'
export { pentagramMonographs, type Pentagram, type PentagramPoint, type PentagramMonographs } from '@uuidna/uuidna'
export { quantumAnalytics, type QuantumAnalytics, type Distribution, type LayerMeasure } from '@uuidna/uuidna'
export { quantumAura, auraDecode, type Aura } from '@uuidna/uuidna'
export { encodeMessage, measureMessage, verifyMessage, serializeMessage, deserializeMessage, sealMessage, openMessage, type QuantumMessage, type QuantumState, type SealedQuantumMessage } from '@uuidna/uuidna'
export { agentContribute, encodeVote, tallyVotes, signCommitWithVoting, serializeCommitWithVoting, type AgentContribution, type Vote, type QuantumVote, type CommitWithVoting } from '@uuidna/uuidna'
export { buildQuantumSailingLibrary, serializeQuantumSailingLibrary, getQuantumSailingLibrary, type SailingBook, type QuantumSailingLibrary } from '@uuidna/uuidna'
export { extractFactsFromArticle, auditFactAgainstLedger, buildNewsPortal, renderPortalSummary, tallyJudgmentVotes, shouldSealFact, type NewsArticle, type NewsExtractedFact, type FactJudgment, type NewsPortal, type JudgmentVote } from '@uuidna/uuidna'
export { buildPoliticsPortal, extractPoliticsFacts, buildMedicinePortal, extractMedicineFacts, buildClimatePortal, extractClimateFacts, buildHistoryPortal, extractHistoryFacts, buildEconomicsPortal, extractEconomicsFacts, processMultiDomainJudgment, type PoliticsArticle, type MedicineArticle, type ClimateArticle, type HistoryArticle, type EconomicsArticle } from '@uuidna/uuidna'
export { discoverQuantumSailingAPIs, correlateWeatherToTheorems, simulateQuantumSailingWeather, serializeWeatherCorrelation, type WeatherFact, type QuantumSailingWeatherCorrelation } from '@uuidna/uuidna'
export { correlateAcrossBooks, clusterByTheorem, serializeCrossBookCorrelation, serializeClusters, type BookPair, type CrossBookResonance, type CrossBookCluster } from '@uuidna/uuidna'
export { automateQuantumSailing, serializeQuantumSailingComplete, type BookWithLinkage, type QuantumSailingComplete } from '@uuidna/uuidna'
export { alpineRelease, verifyAlpineRootfs, fetchAlpineLatest, type AlpineRelease, type RootfsCheck } from '@uuidna/uuidna'
export { driverBundle, verifyDriverBundle, fetchDriverLatest, type DriverBundle, type DriverCheck } from '@uuidna/uuidna'
