// src/edge-slices/generated.ts — GENERATED by scripts/gen-edge-slices from package.json, wrangler.toml, packages/ and
// the minted receipts. Do not edit. Regenerate with `npm run x -- gen-edge-slices`; the generate chain runs it after gen-receipts.
import type { EdgeSlices } from './index.js'

export const EDGE_SLICES: EdgeSlices = {
 "package": {
  "dependencies": [],
  "devDependencies": [
   "@eslint/js",
   "@types/node",
   "eslint",
   "typescript",
   "typescript-eslint",
   "vitepress",
   "wrangler"
  ]
 },
 "wrangler": {
  "assetsBindingPresent": true,
  "kvIdCommitted": false,
  "trialKeyValueCommitted": false
 },
 "workspaces": [
  {
   "dir": "crypto",
   "name": "@uuidna/crypto"
  },
  {
   "dir": "edge",
   "name": "@uuidna/edge"
  },
  {
   "dir": "ledger",
   "name": "@uuidna/ledger"
  },
  {
   "dir": "mcp",
   "name": "@uuidna/mcp"
  },
  {
   "dir": "quantum",
   "name": "@uuidna/quantum"
  },
  {
   "dir": "research",
   "name": "@uuidna/research"
  }
 ],
 "receipts": {
  "decode": {
   "key": "a5e94242-cb8b-840a-9065-267675cb8074",
   "value": {
    "polarities": {
     "minus": 28470,
     "neutral": 14094,
     "plus": 28346,
     "capacity": {
      "minus": 4,
      "neutral": 2,
      "plus": 4
     },
     "byRay": [
      {
       "ray": 0,
       "minus": 4094,
       "neutral": 1998,
       "plus": 4044
      },
      {
       "ray": 1,
       "minus": 4133,
       "neutral": 1993,
       "plus": 4025
      },
      {
       "ray": 2,
       "minus": 4156,
       "neutral": 1937,
       "plus": 3943
      },
      {
       "ray": 3,
       "minus": 3994,
       "neutral": 2039,
       "plus": 4025
      },
      {
       "ray": 4,
       "minus": 4025,
       "neutral": 2070,
       "plus": 4126
      },
      {
       "ray": 5,
       "minus": 3996,
       "neutral": 2088,
       "plus": 4140
      },
      {
       "ray": 6,
       "minus": 4072,
       "neutral": 1969,
       "plus": 4043
      }
     ],
     "bySeed": [
      {
       "seed": 0,
       "theorems": 7014
      },
      {
       "seed": 1,
       "theorems": 7048
      },
      {
       "seed": 2,
       "theorems": 7148
      },
      {
       "seed": 3,
       "theorems": 7104
      },
      {
       "seed": 4,
       "theorems": 7170
      },
      {
       "seed": 5,
       "theorems": 7080
      },
      {
       "seed": 6,
       "theorems": 7137
      },
      {
       "seed": 7,
       "theorems": 7107
      },
      {
       "seed": 8,
       "theorems": 7001
      },
      {
       "seed": 9,
       "theorems": 7101
      }
     ],
     "ratios": [
      {
       "id": "polarity.minus-plus",
       "labelA": "minus theorems",
       "labelB": "plus theorems",
       "a": 28470,
       "b": 28346,
       "forward": 1.004,
       "reverse": 0.996,
       "balanced": false
      },
      {
       "id": "polarity.neutral-rest",
       "labelA": "neutral",
       "labelB": "non-neutral",
       "a": 14094,
       "b": 56816,
       "forward": 0.248,
       "reverse": 4.031,
       "balanced": false
      },
      {
       "id": "polarity.capacity.minus",
       "labelA": "minus load",
       "labelB": "minus digits",
       "a": 28470,
       "b": 4,
       "forward": 7117.5,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "polarity.capacity.plus",
       "labelA": "plus load",
       "labelB": "plus digits",
       "a": 28346,
       "b": 4,
       "forward": 7086.5,
       "reverse": 0,
       "balanced": false
      }
     ],
     "receipt": "4ff01a77-3578-88b1-ab9e-664a74a35ad7"
    },
    "angles": {
     "dashStepDegrees": 60,
     "weightedBearing": 0,
     "closes": true,
     "steps": 11,
     "rosettaRayStep": 51,
     "ratios": [
      {
       "id": "angles.dash-rosetta",
       "labelA": "dash step °",
       "labelB": "ray step °",
       "a": 60,
       "b": 51,
       "forward": 1.176,
       "reverse": 0.85,
       "balanced": false
      },
      {
       "id": "angles.steps-rays",
       "labelA": "dash steps",
       "labelB": "rosetta rays",
       "a": 11,
       "b": 7,
       "forward": 1.571,
       "reverse": 0.636,
       "balanced": false
      },
      {
       "id": "angles.full-circle",
       "labelA": "bearing",
       "labelB": "complement",
       "a": 0,
       "b": 360,
       "forward": 0,
       "reverse": null,
       "balanced": false
      }
     ],
     "receipt": "b326044e-1b4c-84b4-ae84-48c369437530"
    },
    "sequence": {
     "bySeed": [
      {
       "seed": 0,
       "theorems": 7014
      },
      {
       "seed": 1,
       "theorems": 7048
      },
      {
       "seed": 2,
       "theorems": 7148
      },
      {
       "seed": 3,
       "theorems": 7104
      },
      {
       "seed": 4,
       "theorems": 7170
      },
      {
       "seed": 5,
       "theorems": 7080
      },
      {
       "seed": 6,
       "theorems": 7137
      },
      {
       "seed": 7,
       "theorems": 7107
      },
      {
       "seed": 8,
       "theorems": 7001
      },
      {
       "seed": 9,
       "theorems": 7101
      }
     ],
     "fixed": 14094,
     "nonFixed": 56816,
     "canonical": [
      {
       "seed": 0,
       "period": 2,
       "visited": 1
      },
      {
       "seed": 1,
       "period": 0,
       "visited": 3
      },
      {
       "seed": 2,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 3,
       "period": 0,
       "visited": 6
      },
      {
       "seed": 4,
       "period": 0,
       "visited": 8
      },
      {
       "seed": 5,
       "period": 0,
       "visited": 4
      },
      {
       "seed": 6,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 7,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 8,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 9,
       "period": 0,
       "visited": 10
      }
     ],
     "receipt": "c13eda17-3949-8f02-b526-f3a94f81d545"
    },
    "rosetta": {
     "rays": [
      {
       "ray": 0,
       "degrees": 0,
       "theorems": 10136
      },
      {
       "ray": 1,
       "degrees": 51,
       "theorems": 10151
      },
      {
       "ray": 2,
       "degrees": 102,
       "theorems": 10036
      },
      {
       "ray": 3,
       "degrees": 154,
       "theorems": 10058
      },
      {
       "ray": 4,
       "degrees": 205,
       "theorems": 10221
      },
      {
       "ray": 5,
       "degrees": 257,
       "theorems": 10224
      },
      {
       "ray": 6,
       "degrees": 308,
       "theorems": 10084
      }
     ],
     "census": {
      "total": 70910,
      "perLeg": [
       {
        "leg": "symbol",
        "theorems": 1229,
        "share": "1229 of 70910"
       },
       {
        "leg": "proof",
        "theorems": 70910,
        "share": "70910 of 70910"
       },
       {
        "leg": "witness",
        "theorems": 17,
        "share": "17 of 70910"
       },
       {
        "leg": "falsifier",
        "theorems": 70910,
        "share": "70910 of 70910"
       },
       {
        "leg": "address",
        "theorems": 70910,
        "share": "70910 of 70910"
       }
      ],
      "scarcest": "witness",
      "byLegCount": [
       {
        "legs": 5,
        "theorems": 16,
        "verdict": "can locate a fault"
       },
       {
        "legs": 4,
        "theorems": 1214,
        "verdict": "can locate a fault"
       },
       {
        "legs": 3,
        "theorems": 69680,
        "verdict": "can locate a fault"
       }
      ],
      "detectOnly": 0,
      "fullyAnchored": [
       "abo_klein_four",
       "blood_types_eight",
       "bulge_exceeds_relief",
       "codons_sixty_four",
       "dna_base_pairing_involution",
       "eratosthenes_fiftieth_circle",
       "hardware_above_landauer",
       "landauer_bound_derived",
       "landauer_floor_falls_with_temperature",
       "light_speed_rounds_to_300000",
       "reversible_erases_nothing",
       "the_defining_constants_are_exact_integers",
       "the_metre_is_defined_by_the_second",
       "two_coins_in_kilograms",
       "van_de_graaf_margins",
       "wgs84_polar_shorter"
      ],
      "claimedBy": [
       {
        "who": "captain",
        "theorems": 70893
       },
       {
        "who": "SI",
        "theorems": 5
       },
       {
        "who": "Landauer",
        "theorems": 3
       },
       {
        "who": "WGS 84",
        "theorems": 2
       },
       {
        "who": "10.1038/171737a0",
        "theorems": 1
       },
       {
        "who": "10.1038/345229a0",
        "theorems": 1
       },
       {
        "who": "10.1073/pnas.47.10.1588",
        "theorems": 1
       },
       {
        "who": "10.3181/00379727-43-11151",
        "theorems": 1
       },
       {
        "who": "CODATA",
        "theorems": 1
       },
       {
        "who": "Eratosthenes",
        "theorems": 1
       },
       {
        "who": "Gutenberg",
        "theorems": 1
       }
      ],
      "floor": {
       "witness": 17,
       "falsifier": 63
      },
      "floorGaps": [],
      "receipt": "79ff537d-440b-82b4-a94c-e219fe1377c7",
      "honest": "The leg census MEASURES how many INDEPENDENT witnesses each sealed theorem carries; it does not certify any of them. PROOF is the kernel verdict and ADDRESS is the content fold, so both are near-universal by construction and neither is evidence about the world. SYMBOL is the js mirror the emitter cross-checks. WITNESS (a source outside this repository) and FALSIFIER (a test that must fail on a deliberate mutation) are the scarce ones, and a low count is reported as it stands rather than smoothed: two legs can DETECT a disagreement and never locate it. A missing leg is never a claim that the theorem is false. Integrity, not truth."
     },
     "maskCoins": 160,
     "ratios": [
      {
       "id": "rosetta.rays.spread",
       "labelA": "sparsest ray",
       "labelB": "densest ray",
       "a": 10036,
       "b": 10224,
       "forward": 0.982,
       "reverse": 1.019,
       "balanced": false
      },
      {
       "id": "rosetta.legs.witness-falsifier",
       "labelA": "witness",
       "labelB": "falsifier",
       "a": 17,
       "b": 70910,
       "forward": 0,
       "reverse": 4171.176,
       "balanced": false
      },
      {
       "id": "rosetta.coins.walk",
       "labelA": "coin sum",
       "labelB": "masks",
       "a": 160,
       "b": 32,
       "forward": 5,
       "reverse": 0.2,
       "balanced": false
      }
     ],
     "receipt": "64b8e1c1-ff0f-8a6f-9c0f-d834e9ddeba1"
    },
    "life": {
     "os": {
      "receipt": "5b11d9e6-5229-8bcc-b79f-497b10df1cd3",
      "bootStates": 832,
      "packages": 25,
      "floor": "uuidna/alpine-baselayout-data",
      "fourWidths": [
       4,
       8,
       16,
       32
      ]
     },
     "living": {
      "count": 70910,
      "target": 131072,
      "toGo": 60162,
      "monotone": true
     },
     "latent": {
      "count": 112,
      "sample": [
       {
        "file": "Affine.lean",
        "def": "av",
        "principle": "The affine"
       },
       {
        "file": "Affine.lean",
        "def": "bv",
        "principle": "The affine"
       },
       {
        "file": "BioPhysics.lean",
        "def": "lxorAux",
        "principle": "Applied structure — the science pairs"
       },
       {
        "file": "Boolean.lean",
        "def": "bitOf",
        "principle": "The boolean"
       },
       {
        "file": "Cipher.lean",
        "def": "lxorAux",
        "principle": "The cipher & the strand"
       },
       {
        "file": "Codes.lean",
        "def": "lxorAux",
        "principle": "The error-correcting codes"
       },
       {
        "file": "Command.lean",
        "def": "lxorAux",
        "principle": "Command authentication"
       },
       {
        "file": "Equilibrium.lean",
        "def": "lxorAux",
        "principle": "The six-cube and its polarity double"
       },
       {
        "file": "EquilibriumXor1.lean",
        "def": "lxorAux",
        "principle": "The six-cube translations, file 1 of 8"
       },
       {
        "file": "EquilibriumXor2.lean",
        "def": "lxorAux",
        "principle": "The six-cube translations, file 2 of 8"
       },
       {
        "file": "EquilibriumXor3.lean",
        "def": "lxorAux",
        "principle": "The six-cube translations, file 3 of 8"
       },
       {
        "file": "EquilibriumXor4.lean",
        "def": "lxorAux",
        "principle": "The six-cube translations, file 4 of 8"
       }
      ]
     },
     "balance": {
      "active": 221,
      "balanced": 20,
      "open": 201,
      "revealGap": 32864,
      "worst": [
       {
        "dimension": "wing",
        "id": "HexSpan1.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan10.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan11.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan12.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan13.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan14.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan15.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan16.lean",
        "delta": 4094,
        "balanced": false
       }
      ]
     },
     "ratios": [
      {
       "id": "life.os-living",
       "labelA": "boot states",
       "labelB": "living theorems",
       "a": 832,
       "b": 70910,
       "forward": 0.012,
       "reverse": 85.228,
       "balanced": false
      },
      {
       "id": "life.latent-cited",
       "labelA": "latent axioms",
       "labelB": "cited axioms",
       "a": 112,
       "b": 174,
       "forward": 0.644,
       "reverse": 1.554,
       "balanced": false
      },
      {
       "id": "life.milestone",
       "labelA": "to next 2^n",
       "labelB": "living now",
       "a": 60162,
       "b": 70910,
       "forward": 0.848,
       "reverse": 1.179,
       "balanced": false
      },
      {
       "id": "life.balance",
       "labelA": "balanced slices",
       "labelB": "open slices",
       "a": 20,
       "b": 201,
       "forward": 0.1,
       "reverse": 10.05,
       "balanced": false
      },
      {
       "id": "life.wing-ledger",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 70910,
       "b": 70910,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      }
     ],
     "receipt": "f6cfabda-4db4-89ac-945d-39429023a25b"
    },
    "genesis": {
     "deposits": 35,
     "tip": "ef82bb3ec7874a7e",
     "chainIntact": true
    },
    "audit": {
     "polarities": {
      "minus": 28470,
      "neutral": 14094,
      "plus": 28346,
      "capacity": {
       "minus": 4,
       "neutral": 2,
       "plus": 4
      },
      "byRay": [
       {
        "ray": 0,
        "minus": 4094,
        "neutral": 1998,
        "plus": 4044
       },
       {
        "ray": 1,
        "minus": 4133,
        "neutral": 1993,
        "plus": 4025
       },
       {
        "ray": 2,
        "minus": 4156,
        "neutral": 1937,
        "plus": 3943
       },
       {
        "ray": 3,
        "minus": 3994,
        "neutral": 2039,
        "plus": 4025
       },
       {
        "ray": 4,
        "minus": 4025,
        "neutral": 2070,
        "plus": 4126
       },
       {
        "ray": 5,
        "minus": 3996,
        "neutral": 2088,
        "plus": 4140
       },
       {
        "ray": 6,
        "minus": 4072,
        "neutral": 1969,
        "plus": 4043
       }
      ],
      "bySeed": [
       {
        "seed": 0,
        "theorems": 7014
       },
       {
        "seed": 1,
        "theorems": 7048
       },
       {
        "seed": 2,
        "theorems": 7148
       },
       {
        "seed": 3,
        "theorems": 7104
       },
       {
        "seed": 4,
        "theorems": 7170
       },
       {
        "seed": 5,
        "theorems": 7080
       },
       {
        "seed": 6,
        "theorems": 7137
       },
       {
        "seed": 7,
        "theorems": 7107
       },
       {
        "seed": 8,
        "theorems": 7001
       },
       {
        "seed": 9,
        "theorems": 7101
       }
      ],
      "ratios": [
       {
        "id": "polarity.minus-plus",
        "labelA": "minus theorems",
        "labelB": "plus theorems",
        "a": 28470,
        "b": 28346,
        "forward": 1.004,
        "reverse": 0.996,
        "balanced": false
       },
       {
        "id": "polarity.neutral-rest",
        "labelA": "neutral",
        "labelB": "non-neutral",
        "a": 14094,
        "b": 56816,
        "forward": 0.248,
        "reverse": 4.031,
        "balanced": false
       },
       {
        "id": "polarity.capacity.minus",
        "labelA": "minus load",
        "labelB": "minus digits",
        "a": 28470,
        "b": 4,
        "forward": 7117.5,
        "reverse": 0,
        "balanced": false
       },
       {
        "id": "polarity.capacity.plus",
        "labelA": "plus load",
        "labelB": "plus digits",
        "a": 28346,
        "b": 4,
        "forward": 7086.5,
        "reverse": 0,
        "balanced": false
       }
      ],
      "receipt": "4ff01a77-3578-88b1-ab9e-664a74a35ad7"
     },
     "angles": {
      "dashStepDegrees": 60,
      "weightedBearing": 0,
      "closes": true,
      "steps": 11,
      "rosettaRayStep": 51,
      "ratios": [
       {
        "id": "angles.dash-rosetta",
        "labelA": "dash step °",
        "labelB": "ray step °",
        "a": 60,
        "b": 51,
        "forward": 1.176,
        "reverse": 0.85,
        "balanced": false
       },
       {
        "id": "angles.steps-rays",
        "labelA": "dash steps",
        "labelB": "rosetta rays",
        "a": 11,
        "b": 7,
        "forward": 1.571,
        "reverse": 0.636,
        "balanced": false
       },
       {
        "id": "angles.full-circle",
        "labelA": "bearing",
        "labelB": "complement",
        "a": 0,
        "b": 360,
        "forward": 0,
        "reverse": null,
        "balanced": false
       }
      ],
      "receipt": "b326044e-1b4c-84b4-ae84-48c369437530"
     },
     "sequence": {
      "bySeed": [
       {
        "seed": 0,
        "theorems": 7014
       },
       {
        "seed": 1,
        "theorems": 7048
       },
       {
        "seed": 2,
        "theorems": 7148
       },
       {
        "seed": 3,
        "theorems": 7104
       },
       {
        "seed": 4,
        "theorems": 7170
       },
       {
        "seed": 5,
        "theorems": 7080
       },
       {
        "seed": 6,
        "theorems": 7137
       },
       {
        "seed": 7,
        "theorems": 7107
       },
       {
        "seed": 8,
        "theorems": 7001
       },
       {
        "seed": 9,
        "theorems": 7101
       }
      ],
      "fixed": 14094,
      "nonFixed": 56816,
      "canonical": [
       {
        "seed": 0,
        "period": 2,
        "visited": 1
       },
       {
        "seed": 1,
        "period": 0,
        "visited": 3
       },
       {
        "seed": 2,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 3,
        "period": 0,
        "visited": 6
       },
       {
        "seed": 4,
        "period": 0,
        "visited": 8
       },
       {
        "seed": 5,
        "period": 0,
        "visited": 4
       },
       {
        "seed": 6,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 7,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 8,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 9,
        "period": 0,
        "visited": 10
       }
      ],
      "receipt": "c13eda17-3949-8f02-b526-f3a94f81d545"
     },
     "rosetta": {
      "rays": [
       {
        "ray": 0,
        "degrees": 0,
        "theorems": 10136
       },
       {
        "ray": 1,
        "degrees": 51,
        "theorems": 10151
       },
       {
        "ray": 2,
        "degrees": 102,
        "theorems": 10036
       },
       {
        "ray": 3,
        "degrees": 154,
        "theorems": 10058
       },
       {
        "ray": 4,
        "degrees": 205,
        "theorems": 10221
       },
       {
        "ray": 5,
        "degrees": 257,
        "theorems": 10224
       },
       {
        "ray": 6,
        "degrees": 308,
        "theorems": 10084
       }
      ],
      "census": {
       "total": 70910,
       "perLeg": [
        {
         "leg": "symbol",
         "theorems": 1229,
         "share": "1229 of 70910"
        },
        {
         "leg": "proof",
         "theorems": 70910,
         "share": "70910 of 70910"
        },
        {
         "leg": "witness",
         "theorems": 17,
         "share": "17 of 70910"
        },
        {
         "leg": "falsifier",
         "theorems": 70910,
         "share": "70910 of 70910"
        },
        {
         "leg": "address",
         "theorems": 70910,
         "share": "70910 of 70910"
        }
       ],
       "scarcest": "witness",
       "byLegCount": [
        {
         "legs": 5,
         "theorems": 16,
         "verdict": "can locate a fault"
        },
        {
         "legs": 4,
         "theorems": 1214,
         "verdict": "can locate a fault"
        },
        {
         "legs": 3,
         "theorems": 69680,
         "verdict": "can locate a fault"
        }
       ],
       "detectOnly": 0,
       "fullyAnchored": [
        "abo_klein_four",
        "blood_types_eight",
        "bulge_exceeds_relief",
        "codons_sixty_four",
        "dna_base_pairing_involution",
        "eratosthenes_fiftieth_circle",
        "hardware_above_landauer",
        "landauer_bound_derived",
        "landauer_floor_falls_with_temperature",
        "light_speed_rounds_to_300000",
        "reversible_erases_nothing",
        "the_defining_constants_are_exact_integers",
        "the_metre_is_defined_by_the_second",
        "two_coins_in_kilograms",
        "van_de_graaf_margins",
        "wgs84_polar_shorter"
       ],
       "claimedBy": [
        {
         "who": "captain",
         "theorems": 70893
        },
        {
         "who": "SI",
         "theorems": 5
        },
        {
         "who": "Landauer",
         "theorems": 3
        },
        {
         "who": "WGS 84",
         "theorems": 2
        },
        {
         "who": "10.1038/171737a0",
         "theorems": 1
        },
        {
         "who": "10.1038/345229a0",
         "theorems": 1
        },
        {
         "who": "10.1073/pnas.47.10.1588",
         "theorems": 1
        },
        {
         "who": "10.3181/00379727-43-11151",
         "theorems": 1
        },
        {
         "who": "CODATA",
         "theorems": 1
        },
        {
         "who": "Eratosthenes",
         "theorems": 1
        },
        {
         "who": "Gutenberg",
         "theorems": 1
        }
       ],
       "floor": {
        "witness": 17,
        "falsifier": 63
       },
       "floorGaps": [],
       "receipt": "79ff537d-440b-82b4-a94c-e219fe1377c7",
       "honest": "The leg census MEASURES how many INDEPENDENT witnesses each sealed theorem carries; it does not certify any of them. PROOF is the kernel verdict and ADDRESS is the content fold, so both are near-universal by construction and neither is evidence about the world. SYMBOL is the js mirror the emitter cross-checks. WITNESS (a source outside this repository) and FALSIFIER (a test that must fail on a deliberate mutation) are the scarce ones, and a low count is reported as it stands rather than smoothed: two legs can DETECT a disagreement and never locate it. A missing leg is never a claim that the theorem is false. Integrity, not truth."
      },
      "maskCoins": 160,
      "ratios": [
       {
        "id": "rosetta.rays.spread",
        "labelA": "sparsest ray",
        "labelB": "densest ray",
        "a": 10036,
        "b": 10224,
        "forward": 0.982,
        "reverse": 1.019,
        "balanced": false
       },
       {
        "id": "rosetta.legs.witness-falsifier",
        "labelA": "witness",
        "labelB": "falsifier",
        "a": 17,
        "b": 70910,
        "forward": 0,
        "reverse": 4171.176,
        "balanced": false
       },
       {
        "id": "rosetta.coins.walk",
        "labelA": "coin sum",
        "labelB": "masks",
        "a": 160,
        "b": 32,
        "forward": 5,
        "reverse": 0.2,
        "balanced": false
       }
      ],
      "receipt": "64b8e1c1-ff0f-8a6f-9c0f-d834e9ddeba1"
     },
     "life": {
      "os": {
       "receipt": "5b11d9e6-5229-8bcc-b79f-497b10df1cd3",
       "bootStates": 832,
       "packages": 25,
       "floor": "uuidna/alpine-baselayout-data",
       "fourWidths": [
        4,
        8,
        16,
        32
       ]
      },
      "living": {
       "count": 70910,
       "target": 131072,
       "toGo": 60162,
       "monotone": true
      },
      "latent": {
       "count": 112,
       "sample": [
        {
         "file": "Affine.lean",
         "def": "av",
         "principle": "The affine"
        },
        {
         "file": "Affine.lean",
         "def": "bv",
         "principle": "The affine"
        },
        {
         "file": "BioPhysics.lean",
         "def": "lxorAux",
         "principle": "Applied structure — the science pairs"
        },
        {
         "file": "Boolean.lean",
         "def": "bitOf",
         "principle": "The boolean"
        },
        {
         "file": "Cipher.lean",
         "def": "lxorAux",
         "principle": "The cipher & the strand"
        },
        {
         "file": "Codes.lean",
         "def": "lxorAux",
         "principle": "The error-correcting codes"
        },
        {
         "file": "Command.lean",
         "def": "lxorAux",
         "principle": "Command authentication"
        },
        {
         "file": "Equilibrium.lean",
         "def": "lxorAux",
         "principle": "The six-cube and its polarity double"
        },
        {
         "file": "EquilibriumXor1.lean",
         "def": "lxorAux",
         "principle": "The six-cube translations, file 1 of 8"
        },
        {
         "file": "EquilibriumXor2.lean",
         "def": "lxorAux",
         "principle": "The six-cube translations, file 2 of 8"
        },
        {
         "file": "EquilibriumXor3.lean",
         "def": "lxorAux",
         "principle": "The six-cube translations, file 3 of 8"
        },
        {
         "file": "EquilibriumXor4.lean",
         "def": "lxorAux",
         "principle": "The six-cube translations, file 4 of 8"
        }
       ]
      },
      "balance": {
       "active": 221,
       "balanced": 20,
       "open": 201,
       "revealGap": 32864,
       "worst": [
        {
         "dimension": "wing",
         "id": "HexSpan1.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan10.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan11.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan12.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan13.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan14.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan15.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan16.lean",
         "delta": 4094,
         "balanced": false
        }
       ]
      },
      "ratios": [
       {
        "id": "life.os-living",
        "labelA": "boot states",
        "labelB": "living theorems",
        "a": 832,
        "b": 70910,
        "forward": 0.012,
        "reverse": 85.228,
        "balanced": false
       },
       {
        "id": "life.latent-cited",
        "labelA": "latent axioms",
        "labelB": "cited axioms",
        "a": 112,
        "b": 174,
        "forward": 0.644,
        "reverse": 1.554,
        "balanced": false
       },
       {
        "id": "life.milestone",
        "labelA": "to next 2^n",
        "labelB": "living now",
        "a": 60162,
        "b": 70910,
        "forward": 0.848,
        "reverse": 1.179,
        "balanced": false
       },
       {
        "id": "life.balance",
        "labelA": "balanced slices",
        "labelB": "open slices",
        "a": 20,
        "b": 201,
        "forward": 0.1,
        "reverse": 10.05,
        "balanced": false
       },
       {
        "id": "life.wing-ledger",
        "labelA": "wing theorems",
        "labelB": "ledger keys",
        "a": 70910,
        "b": 70910,
        "forward": 1,
        "reverse": 1,
        "balanced": true
       }
      ],
      "receipt": "f6cfabda-4db4-89ac-945d-39429023a25b"
     },
     "axiom": {
      "global": {
       "dimension": "ledger",
       "id": "ledger",
       "theorems": 70910,
       "citedDefs": 174,
       "bound": 68285,
       "citeEdges": 134193,
       "theoremsPerDef": 771.224,
       "defsPerBound": 1.965,
       "delta": 769.259,
       "balanced": false
      },
      "active": 221,
      "balanced": 20,
      "fused": "253a21d9-f880-8659-9e63-c6d761b7660c"
     },
     "kernel": {
      "id": "kernel.axiom",
      "labelA": "audited",
      "labelB": "ledger",
      "a": 70910,
      "b": 70910,
      "forward": 1,
      "reverse": 1,
      "balanced": true
     },
     "wing": {
      "id": "wing.parity",
      "labelA": "wing theorems",
      "labelB": "ledger keys",
      "a": 70910,
      "b": 70910,
      "forward": 1,
      "reverse": 1,
      "balanced": true
     },
     "genesis": {
      "deposits": 35,
      "tip": "ef82bb3ec7874a7e",
      "chainIntact": true
     },
     "ratios": [
      {
       "id": "polarity.minus-plus",
       "labelA": "minus theorems",
       "labelB": "plus theorems",
       "a": 28470,
       "b": 28346,
       "forward": 1.004,
       "reverse": 0.996,
       "balanced": false
      },
      {
       "id": "polarity.neutral-rest",
       "labelA": "neutral",
       "labelB": "non-neutral",
       "a": 14094,
       "b": 56816,
       "forward": 0.248,
       "reverse": 4.031,
       "balanced": false
      },
      {
       "id": "polarity.capacity.minus",
       "labelA": "minus load",
       "labelB": "minus digits",
       "a": 28470,
       "b": 4,
       "forward": 7117.5,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "polarity.capacity.plus",
       "labelA": "plus load",
       "labelB": "plus digits",
       "a": 28346,
       "b": 4,
       "forward": 7086.5,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "angles.dash-rosetta",
       "labelA": "dash step °",
       "labelB": "ray step °",
       "a": 60,
       "b": 51,
       "forward": 1.176,
       "reverse": 0.85,
       "balanced": false
      },
      {
       "id": "angles.steps-rays",
       "labelA": "dash steps",
       "labelB": "rosetta rays",
       "a": 11,
       "b": 7,
       "forward": 1.571,
       "reverse": 0.636,
       "balanced": false
      },
      {
       "id": "angles.full-circle",
       "labelA": "bearing",
       "labelB": "complement",
       "a": 0,
       "b": 360,
       "forward": 0,
       "reverse": null,
       "balanced": false
      },
      {
       "id": "rosetta.rays.spread",
       "labelA": "sparsest ray",
       "labelB": "densest ray",
       "a": 10036,
       "b": 10224,
       "forward": 0.982,
       "reverse": 1.019,
       "balanced": false
      },
      {
       "id": "rosetta.legs.witness-falsifier",
       "labelA": "witness",
       "labelB": "falsifier",
       "a": 17,
       "b": 70910,
       "forward": 0,
       "reverse": 4171.176,
       "balanced": false
      },
      {
       "id": "rosetta.coins.walk",
       "labelA": "coin sum",
       "labelB": "masks",
       "a": 160,
       "b": 32,
       "forward": 5,
       "reverse": 0.2,
       "balanced": false
      },
      {
       "id": "life.os-living",
       "labelA": "boot states",
       "labelB": "living theorems",
       "a": 832,
       "b": 70910,
       "forward": 0.012,
       "reverse": 85.228,
       "balanced": false
      },
      {
       "id": "life.latent-cited",
       "labelA": "latent axioms",
       "labelB": "cited axioms",
       "a": 112,
       "b": 174,
       "forward": 0.644,
       "reverse": 1.554,
       "balanced": false
      },
      {
       "id": "life.milestone",
       "labelA": "to next 2^n",
       "labelB": "living now",
       "a": 60162,
       "b": 70910,
       "forward": 0.848,
       "reverse": 1.179,
       "balanced": false
      },
      {
       "id": "life.balance",
       "labelA": "balanced slices",
       "labelB": "open slices",
       "a": 20,
       "b": 201,
       "forward": 0.1,
       "reverse": 10.05,
       "balanced": false
      },
      {
       "id": "life.wing-ledger",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 70910,
       "b": 70910,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "kernel.axiom",
       "labelA": "audited",
       "labelB": "ledger",
       "a": 70910,
       "b": 70910,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "wing.parity",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 70910,
       "b": 70910,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "axiom.vocabulary",
       "labelA": "cited defs",
       "labelB": "bound theorems",
       "a": 174,
       "b": 68285,
       "forward": 0.003,
       "reverse": 392.443,
       "balanced": false
      },
      {
       "id": "sequence.fixed",
       "labelA": "fixed",
       "labelB": "non-fixed",
       "a": 14094,
       "b": 56816,
       "forward": 0.248,
       "reverse": 4.031,
       "balanced": false
      },
      {
       "id": "genesis.deposits-theorems",
       "labelA": "deposits",
       "labelB": "theorems",
       "a": 35,
       "b": 70910,
       "forward": 0,
       "reverse": 2026,
       "balanced": false
      }
     ],
     "fused": "fe2b7ccc-b016-8dc2-9de4-0d3993280650",
     "honest": "Ratios, angles, polarities, and life DECODED — runSequence on every address, ±60° dash, 360/7° rosetta rays, uuidnaOS boot ground, living ledger, latent axioms, genesis chain. Folded order-invariant. Descriptive only."
    },
    "fused": "8bf56894-fada-840d-8832-9ea9b7d68a03"
   }
  }
 }
}
