// src/edge-slices/generated.ts — GENERATED by scripts/gen-edge-slices from package.json, wrangler.toml, packages/ and
// the minted receipts. Do not edit. Regenerate with `npm run x -- gen-edge-slices`; the generate chain runs it after gen-receipts.
import type { EdgeSlices } from './index.js'

export const EDGE_SLICES: EdgeSlices = {
 "package": {
  "dependencies": [],
  "devDependencies": [
   "@eslint/js",
   "@types/node",
   "eslint",
   "typescript",
   "typescript-eslint",
   "vitepress",
   "wrangler"
  ]
 },
 "wrangler": {
  "assetsBindingPresent": true,
  "kvIdCommitted": false,
  "trialKeyValueCommitted": false
 },
 "workspaces": [
  {
   "dir": "crypto",
   "name": "@uuidna/crypto"
  },
  {
   "dir": "edge",
   "name": "@uuidna/edge"
  },
  {
   "dir": "ledger",
   "name": "@uuidna/ledger"
  },
  {
   "dir": "mcp",
   "name": "@uuidna/mcp"
  },
  {
   "dir": "quantum",
   "name": "@uuidna/quantum"
  },
  {
   "dir": "research",
   "name": "@uuidna/research"
  }
 ],
 "receipts": {
  "decode": {
   "key": "3e78a5bb-dc5d-8c7c-acdd-cb789787d8a8",
   "value": {
    "polarities": {
     "minus": 28535,
     "neutral": 14139,
     "plus": 28420,
     "capacity": {
      "minus": 4,
      "neutral": 2,
      "plus": 4
     },
     "byRay": [
      {
       "ray": 0,
       "minus": 4106,
       "neutral": 2003,
       "plus": 4062
      },
      {
       "ray": 1,
       "minus": 4144,
       "neutral": 1998,
       "plus": 4034
      },
      {
       "ray": 2,
       "minus": 4161,
       "neutral": 1946,
       "plus": 3950
      },
      {
       "ray": 3,
       "minus": 4004,
       "neutral": 2051,
       "plus": 4031
      },
      {
       "ray": 4,
       "minus": 4032,
       "neutral": 2077,
       "plus": 4130
      },
      {
       "ray": 5,
       "minus": 4005,
       "neutral": 2090,
       "plus": 4147
      },
      {
       "ray": 6,
       "minus": 4083,
       "neutral": 1974,
       "plus": 4066
      }
     ],
     "bySeed": [
      {
       "seed": 0,
       "theorems": 7034
      },
      {
       "seed": 1,
       "theorems": 7067
      },
      {
       "seed": 2,
       "theorems": 7174
      },
      {
       "seed": 3,
       "theorems": 7115
      },
      {
       "seed": 4,
       "theorems": 7179
      },
      {
       "seed": 5,
       "theorems": 7105
      },
      {
       "seed": 6,
       "theorems": 7165
      },
      {
       "seed": 7,
       "theorems": 7127
      },
      {
       "seed": 8,
       "theorems": 7019
      },
      {
       "seed": 9,
       "theorems": 7109
      }
     ],
     "ratios": [
      {
       "id": "polarity.minus-plus",
       "labelA": "minus theorems",
       "labelB": "plus theorems",
       "a": 28535,
       "b": 28420,
       "forward": 1.004,
       "reverse": 0.996,
       "balanced": false
      },
      {
       "id": "polarity.neutral-rest",
       "labelA": "neutral",
       "labelB": "non-neutral",
       "a": 14139,
       "b": 56955,
       "forward": 0.248,
       "reverse": 4.028,
       "balanced": false
      },
      {
       "id": "polarity.capacity.minus",
       "labelA": "minus load",
       "labelB": "minus digits",
       "a": 28535,
       "b": 4,
       "forward": 7133.75,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "polarity.capacity.plus",
       "labelA": "plus load",
       "labelB": "plus digits",
       "a": 28420,
       "b": 4,
       "forward": 7105,
       "reverse": 0,
       "balanced": false
      }
     ],
     "receipt": "d50ecc82-f534-86ed-b01a-0e84d737a7d1"
    },
    "angles": {
     "dashStepDegrees": 60,
     "weightedBearing": 0,
     "closes": true,
     "steps": 11,
     "rosettaRayStep": 51,
     "ratios": [
      {
       "id": "angles.dash-rosetta",
       "labelA": "dash step °",
       "labelB": "ray step °",
       "a": 60,
       "b": 51,
       "forward": 1.176,
       "reverse": 0.85,
       "balanced": false
      },
      {
       "id": "angles.steps-rays",
       "labelA": "dash steps",
       "labelB": "rosetta rays",
       "a": 11,
       "b": 7,
       "forward": 1.571,
       "reverse": 0.636,
       "balanced": false
      },
      {
       "id": "angles.full-circle",
       "labelA": "bearing",
       "labelB": "complement",
       "a": 0,
       "b": 360,
       "forward": 0,
       "reverse": null,
       "balanced": false
      }
     ],
     "receipt": "1f25cb68-3fc8-8d92-91aa-112dcb5494b8"
    },
    "sequence": {
     "bySeed": [
      {
       "seed": 0,
       "theorems": 7034
      },
      {
       "seed": 1,
       "theorems": 7067
      },
      {
       "seed": 2,
       "theorems": 7174
      },
      {
       "seed": 3,
       "theorems": 7115
      },
      {
       "seed": 4,
       "theorems": 7179
      },
      {
       "seed": 5,
       "theorems": 7105
      },
      {
       "seed": 6,
       "theorems": 7165
      },
      {
       "seed": 7,
       "theorems": 7127
      },
      {
       "seed": 8,
       "theorems": 7019
      },
      {
       "seed": 9,
       "theorems": 7109
      }
     ],
     "fixed": 14139,
     "nonFixed": 56955,
     "canonical": [
      {
       "seed": 0,
       "period": 2,
       "visited": 1
      },
      {
       "seed": 1,
       "period": 0,
       "visited": 3
      },
      {
       "seed": 2,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 3,
       "period": 0,
       "visited": 6
      },
      {
       "seed": 4,
       "period": 0,
       "visited": 8
      },
      {
       "seed": 5,
       "period": 0,
       "visited": 4
      },
      {
       "seed": 6,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 7,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 8,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 9,
       "period": 0,
       "visited": 10
      }
     ],
     "receipt": "2662a9cd-1022-8c78-a0d2-32f97f47fbda"
    },
    "rosetta": {
     "rays": [
      {
       "ray": 0,
       "degrees": 0,
       "theorems": 10171
      },
      {
       "ray": 1,
       "degrees": 51,
       "theorems": 10176
      },
      {
       "ray": 2,
       "degrees": 102,
       "theorems": 10057
      },
      {
       "ray": 3,
       "degrees": 154,
       "theorems": 10086
      },
      {
       "ray": 4,
       "degrees": 205,
       "theorems": 10239
      },
      {
       "ray": 5,
       "degrees": 257,
       "theorems": 10242
      },
      {
       "ray": 6,
       "degrees": 308,
       "theorems": 10123
      }
     ],
     "census": {
      "total": 71094,
      "perLeg": [
       {
        "leg": "symbol",
        "theorems": 1396,
        "share": "1396 of 71094"
       },
       {
        "leg": "proof",
        "theorems": 71094,
        "share": "71094 of 71094"
       },
       {
        "leg": "witness",
        "theorems": 30,
        "share": "30 of 71094"
       },
       {
        "leg": "falsifier",
        "theorems": 71090,
        "share": "71090 of 71094"
       },
       {
        "leg": "address",
        "theorems": 71094,
        "share": "71094 of 71094"
       }
      ],
      "scarcest": "witness",
      "byLegCount": [
       {
        "legs": 5,
        "theorems": 29,
        "verdict": "can locate a fault"
       },
       {
        "legs": 4,
        "theorems": 1364,
        "verdict": "can locate a fault"
       },
       {
        "legs": 3,
        "theorems": 69701,
        "verdict": "can locate a fault"
       }
      ],
      "detectOnly": 0,
      "fullyAnchored": [
       "abo_klein_four",
       "blood_types_eight",
       "bulge_exceeds_relief",
       "codons_sixty_four",
       "crossing_sits_inside",
       "cuts_break_successors",
       "dna_base_pairing_involution",
       "edits_break_recompute",
       "energy_is_reachable_by_four_independent_routes",
       "eratosthenes_fiftieth_circle",
       "handle_outreaches_planck",
       "hardware_above_landauer",
       "kinematics_cancels_both",
       "landauer_bound_derived",
       "landauer_floor_falls_with_temperature",
       "light_speed_rounds_to_300000",
       "mass_selects_cancellation",
       "pairings_exhaust_the_cancellations",
       "payload_falls_short",
       "planck_margin_bounded",
       "product_isolates_quantum",
       "ratio_isolates_gravity",
       "reversible_erases_nothing",
       "the_defining_constants_are_exact_integers",
       "the_metre_is_defined_by_the_second",
       "the_pairing_cancels_the_constant",
       "two_coins_in_kilograms",
       "van_de_graaf_margins",
       "wgs84_polar_shorter"
      ],
      "claimedBy": [
       {
        "who": "captain",
        "theorems": 71064
       },
       {
        "who": "CODATA",
        "theorems": 10
       },
       {
        "who": "SI",
        "theorems": 7
       },
       {
        "who": "Landauer",
        "theorems": 3
       },
       {
        "who": "10.1007/BF00196791",
        "theorems": 2
       },
       {
        "who": "WGS 84",
        "theorems": 2
       },
       {
        "who": "10.1038/171737a0",
        "theorems": 1
       },
       {
        "who": "10.1038/345229a0",
        "theorems": 1
       },
       {
        "who": "10.1073/pnas.47.10.1588",
        "theorems": 1
       },
       {
        "who": "10.3181/00379727-43-11151",
        "theorems": 1
       },
       {
        "who": "Eratosthenes",
        "theorems": 1
       },
       {
        "who": "Gutenberg",
        "theorems": 1
       }
      ],
      "floor": {
       "witness": 30,
       "falsifier": 63
      },
      "floorGaps": [],
      "receipt": "4ca99a87-570a-83f6-9639-d1a3f614d990",
      "honest": "The leg census MEASURES how many INDEPENDENT witnesses each sealed theorem carries; it does not certify any of them. PROOF is the kernel verdict and ADDRESS is the content fold, so both are near-universal by construction and neither is evidence about the world. SYMBOL is the js mirror the emitter cross-checks. WITNESS (a source outside this repository) and FALSIFIER (a test that must fail on a deliberate mutation) are the scarce ones, and a low count is reported as it stands rather than smoothed: two legs can DETECT a disagreement and never locate it. A missing leg is never a claim that the theorem is false. Integrity, not truth."
     },
     "maskCoins": 160,
     "ratios": [
      {
       "id": "rosetta.rays.spread",
       "labelA": "sparsest ray",
       "labelB": "densest ray",
       "a": 10057,
       "b": 10242,
       "forward": 0.982,
       "reverse": 1.018,
       "balanced": false
      },
      {
       "id": "rosetta.legs.witness-falsifier",
       "labelA": "witness",
       "labelB": "falsifier",
       "a": 30,
       "b": 71090,
       "forward": 0,
       "reverse": 2369.667,
       "balanced": false
      },
      {
       "id": "rosetta.coins.walk",
       "labelA": "coin sum",
       "labelB": "masks",
       "a": 160,
       "b": 32,
       "forward": 5,
       "reverse": 0.2,
       "balanced": false
      }
     ],
     "receipt": "05f50e2a-a432-8c45-b269-78a0d9dfc94a"
    },
    "life": {
     "os": {
      "receipt": "7a5adc22-9943-8ed3-9c23-33d831014ce4",
      "bootStates": 832,
      "packages": 25,
      "floor": "uuidna/alpine-baselayout-data",
      "fourWidths": [
       4,
       8,
       16,
       32
      ]
     },
     "living": {
      "count": 71094,
      "target": 131072,
      "toGo": 59978,
      "monotone": true
     },
     "latent": {
      "count": 230,
      "sample": [
       {
        "file": "Affine.lean",
        "def": "av",
        "principle": "The affine"
       },
       {
        "file": "Affine.lean",
        "def": "bv",
        "principle": "The affine"
       },
       {
        "file": "Audit.lean",
        "def": "lh",
        "principle": "The detectors, proven"
       },
       {
        "file": "Audit.lean",
        "def": "step",
        "principle": "The detectors, proven"
       },
       {
        "file": "BioPhysics.lean",
        "def": "lxorAux",
        "principle": "Applied structure — the science pairs"
       },
       {
        "file": "Boolean.lean",
        "def": "bitOf",
        "principle": "The boolean"
       },
       {
        "file": "Cipher.lean",
        "def": "lxorAux",
        "principle": "The cipher & the strand"
       },
       {
        "file": "Codes.lean",
        "def": "lxorAux",
        "principle": "The error-correcting codes"
       },
       {
        "file": "CoinsBalance.lean",
        "def": "hexbit",
        "principle": "THE COINS BALANCE"
       },
       {
        "file": "CoinsBalance.lean",
        "def": "seed",
        "principle": "THE COINS BALANCE"
       },
       {
        "file": "CoinsBalance.lean",
        "def": "vertices",
        "principle": "THE COINS BALANCE"
       },
       {
        "file": "Command.lean",
        "def": "lxorAux",
        "principle": "Command authentication"
       }
      ]
     },
     "balance": {
      "active": 388,
      "balanced": 170,
      "open": 218,
      "revealGap": 32982,
      "worst": [
       {
        "dimension": "wing",
        "id": "HexSpan1.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan10.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan11.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan12.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan13.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan14.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan15.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan16.lean",
        "delta": 4094,
        "balanced": false
       }
      ]
     },
     "ratios": [
      {
       "id": "life.os-living",
       "labelA": "boot states",
       "labelB": "living theorems",
       "a": 832,
       "b": 71094,
       "forward": 0.012,
       "reverse": 85.45,
       "balanced": false
      },
      {
       "id": "life.latent-cited",
       "labelA": "latent axioms",
       "labelB": "cited axioms",
       "a": 230,
       "b": 362,
       "forward": 0.635,
       "reverse": 1.574,
       "balanced": false
      },
      {
       "id": "life.milestone",
       "labelA": "to next 2^n",
       "labelB": "living now",
       "a": 59978,
       "b": 71094,
       "forward": 0.844,
       "reverse": 1.185,
       "balanced": false
      },
      {
       "id": "life.balance",
       "labelA": "balanced slices",
       "labelB": "open slices",
       "a": 170,
       "b": 218,
       "forward": 0.78,
       "reverse": 1.282,
       "balanced": false
      },
      {
       "id": "life.wing-ledger",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 71094,
       "b": 71094,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      }
     ],
     "receipt": "2c854f5f-f9fe-8bf0-833e-0f64c465b1cb"
    },
    "genesis": {
     "deposits": 35,
     "tip": "ef82bb3ec7874a7e",
     "chainIntact": true
    },
    "audit": {
     "polarities": {
      "minus": 28535,
      "neutral": 14139,
      "plus": 28420,
      "capacity": {
       "minus": 4,
       "neutral": 2,
       "plus": 4
      },
      "byRay": [
       {
        "ray": 0,
        "minus": 4106,
        "neutral": 2003,
        "plus": 4062
       },
       {
        "ray": 1,
        "minus": 4144,
        "neutral": 1998,
        "plus": 4034
       },
       {
        "ray": 2,
        "minus": 4161,
        "neutral": 1946,
        "plus": 3950
       },
       {
        "ray": 3,
        "minus": 4004,
        "neutral": 2051,
        "plus": 4031
       },
       {
        "ray": 4,
        "minus": 4032,
        "neutral": 2077,
        "plus": 4130
       },
       {
        "ray": 5,
        "minus": 4005,
        "neutral": 2090,
        "plus": 4147
       },
       {
        "ray": 6,
        "minus": 4083,
        "neutral": 1974,
        "plus": 4066
       }
      ],
      "bySeed": [
       {
        "seed": 0,
        "theorems": 7034
       },
       {
        "seed": 1,
        "theorems": 7067
       },
       {
        "seed": 2,
        "theorems": 7174
       },
       {
        "seed": 3,
        "theorems": 7115
       },
       {
        "seed": 4,
        "theorems": 7179
       },
       {
        "seed": 5,
        "theorems": 7105
       },
       {
        "seed": 6,
        "theorems": 7165
       },
       {
        "seed": 7,
        "theorems": 7127
       },
       {
        "seed": 8,
        "theorems": 7019
       },
       {
        "seed": 9,
        "theorems": 7109
       }
      ],
      "ratios": [
       {
        "id": "polarity.minus-plus",
        "labelA": "minus theorems",
        "labelB": "plus theorems",
        "a": 28535,
        "b": 28420,
        "forward": 1.004,
        "reverse": 0.996,
        "balanced": false
       },
       {
        "id": "polarity.neutral-rest",
        "labelA": "neutral",
        "labelB": "non-neutral",
        "a": 14139,
        "b": 56955,
        "forward": 0.248,
        "reverse": 4.028,
        "balanced": false
       },
       {
        "id": "polarity.capacity.minus",
        "labelA": "minus load",
        "labelB": "minus digits",
        "a": 28535,
        "b": 4,
        "forward": 7133.75,
        "reverse": 0,
        "balanced": false
       },
       {
        "id": "polarity.capacity.plus",
        "labelA": "plus load",
        "labelB": "plus digits",
        "a": 28420,
        "b": 4,
        "forward": 7105,
        "reverse": 0,
        "balanced": false
       }
      ],
      "receipt": "d50ecc82-f534-86ed-b01a-0e84d737a7d1"
     },
     "angles": {
      "dashStepDegrees": 60,
      "weightedBearing": 0,
      "closes": true,
      "steps": 11,
      "rosettaRayStep": 51,
      "ratios": [
       {
        "id": "angles.dash-rosetta",
        "labelA": "dash step °",
        "labelB": "ray step °",
        "a": 60,
        "b": 51,
        "forward": 1.176,
        "reverse": 0.85,
        "balanced": false
       },
       {
        "id": "angles.steps-rays",
        "labelA": "dash steps",
        "labelB": "rosetta rays",
        "a": 11,
        "b": 7,
        "forward": 1.571,
        "reverse": 0.636,
        "balanced": false
       },
       {
        "id": "angles.full-circle",
        "labelA": "bearing",
        "labelB": "complement",
        "a": 0,
        "b": 360,
        "forward": 0,
        "reverse": null,
        "balanced": false
       }
      ],
      "receipt": "1f25cb68-3fc8-8d92-91aa-112dcb5494b8"
     },
     "sequence": {
      "bySeed": [
       {
        "seed": 0,
        "theorems": 7034
       },
       {
        "seed": 1,
        "theorems": 7067
       },
       {
        "seed": 2,
        "theorems": 7174
       },
       {
        "seed": 3,
        "theorems": 7115
       },
       {
        "seed": 4,
        "theorems": 7179
       },
       {
        "seed": 5,
        "theorems": 7105
       },
       {
        "seed": 6,
        "theorems": 7165
       },
       {
        "seed": 7,
        "theorems": 7127
       },
       {
        "seed": 8,
        "theorems": 7019
       },
       {
        "seed": 9,
        "theorems": 7109
       }
      ],
      "fixed": 14139,
      "nonFixed": 56955,
      "canonical": [
       {
        "seed": 0,
        "period": 2,
        "visited": 1
       },
       {
        "seed": 1,
        "period": 0,
        "visited": 3
       },
       {
        "seed": 2,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 3,
        "period": 0,
        "visited": 6
       },
       {
        "seed": 4,
        "period": 0,
        "visited": 8
       },
       {
        "seed": 5,
        "period": 0,
        "visited": 4
       },
       {
        "seed": 6,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 7,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 8,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 9,
        "period": 0,
        "visited": 10
       }
      ],
      "receipt": "2662a9cd-1022-8c78-a0d2-32f97f47fbda"
     },
     "rosetta": {
      "rays": [
       {
        "ray": 0,
        "degrees": 0,
        "theorems": 10171
       },
       {
        "ray": 1,
        "degrees": 51,
        "theorems": 10176
       },
       {
        "ray": 2,
        "degrees": 102,
        "theorems": 10057
       },
       {
        "ray": 3,
        "degrees": 154,
        "theorems": 10086
       },
       {
        "ray": 4,
        "degrees": 205,
        "theorems": 10239
       },
       {
        "ray": 5,
        "degrees": 257,
        "theorems": 10242
       },
       {
        "ray": 6,
        "degrees": 308,
        "theorems": 10123
       }
      ],
      "census": {
       "total": 71094,
       "perLeg": [
        {
         "leg": "symbol",
         "theorems": 1396,
         "share": "1396 of 71094"
        },
        {
         "leg": "proof",
         "theorems": 71094,
         "share": "71094 of 71094"
        },
        {
         "leg": "witness",
         "theorems": 30,
         "share": "30 of 71094"
        },
        {
         "leg": "falsifier",
         "theorems": 71090,
         "share": "71090 of 71094"
        },
        {
         "leg": "address",
         "theorems": 71094,
         "share": "71094 of 71094"
        }
       ],
       "scarcest": "witness",
       "byLegCount": [
        {
         "legs": 5,
         "theorems": 29,
         "verdict": "can locate a fault"
        },
        {
         "legs": 4,
         "theorems": 1364,
         "verdict": "can locate a fault"
        },
        {
         "legs": 3,
         "theorems": 69701,
         "verdict": "can locate a fault"
        }
       ],
       "detectOnly": 0,
       "fullyAnchored": [
        "abo_klein_four",
        "blood_types_eight",
        "bulge_exceeds_relief",
        "codons_sixty_four",
        "crossing_sits_inside",
        "cuts_break_successors",
        "dna_base_pairing_involution",
        "edits_break_recompute",
        "energy_is_reachable_by_four_independent_routes",
        "eratosthenes_fiftieth_circle",
        "handle_outreaches_planck",
        "hardware_above_landauer",
        "kinematics_cancels_both",
        "landauer_bound_derived",
        "landauer_floor_falls_with_temperature",
        "light_speed_rounds_to_300000",
        "mass_selects_cancellation",
        "pairings_exhaust_the_cancellations",
        "payload_falls_short",
        "planck_margin_bounded",
        "product_isolates_quantum",
        "ratio_isolates_gravity",
        "reversible_erases_nothing",
        "the_defining_constants_are_exact_integers",
        "the_metre_is_defined_by_the_second",
        "the_pairing_cancels_the_constant",
        "two_coins_in_kilograms",
        "van_de_graaf_margins",
        "wgs84_polar_shorter"
       ],
       "claimedBy": [
        {
         "who": "captain",
         "theorems": 71064
        },
        {
         "who": "CODATA",
         "theorems": 10
        },
        {
         "who": "SI",
         "theorems": 7
        },
        {
         "who": "Landauer",
         "theorems": 3
        },
        {
         "who": "10.1007/BF00196791",
         "theorems": 2
        },
        {
         "who": "WGS 84",
         "theorems": 2
        },
        {
         "who": "10.1038/171737a0",
         "theorems": 1
        },
        {
         "who": "10.1038/345229a0",
         "theorems": 1
        },
        {
         "who": "10.1073/pnas.47.10.1588",
         "theorems": 1
        },
        {
         "who": "10.3181/00379727-43-11151",
         "theorems": 1
        },
        {
         "who": "Eratosthenes",
         "theorems": 1
        },
        {
         "who": "Gutenberg",
         "theorems": 1
        }
       ],
       "floor": {
        "witness": 30,
        "falsifier": 63
       },
       "floorGaps": [],
       "receipt": "4ca99a87-570a-83f6-9639-d1a3f614d990",
       "honest": "The leg census MEASURES how many INDEPENDENT witnesses each sealed theorem carries; it does not certify any of them. PROOF is the kernel verdict and ADDRESS is the content fold, so both are near-universal by construction and neither is evidence about the world. SYMBOL is the js mirror the emitter cross-checks. WITNESS (a source outside this repository) and FALSIFIER (a test that must fail on a deliberate mutation) are the scarce ones, and a low count is reported as it stands rather than smoothed: two legs can DETECT a disagreement and never locate it. A missing leg is never a claim that the theorem is false. Integrity, not truth."
      },
      "maskCoins": 160,
      "ratios": [
       {
        "id": "rosetta.rays.spread",
        "labelA": "sparsest ray",
        "labelB": "densest ray",
        "a": 10057,
        "b": 10242,
        "forward": 0.982,
        "reverse": 1.018,
        "balanced": false
       },
       {
        "id": "rosetta.legs.witness-falsifier",
        "labelA": "witness",
        "labelB": "falsifier",
        "a": 30,
        "b": 71090,
        "forward": 0,
        "reverse": 2369.667,
        "balanced": false
       },
       {
        "id": "rosetta.coins.walk",
        "labelA": "coin sum",
        "labelB": "masks",
        "a": 160,
        "b": 32,
        "forward": 5,
        "reverse": 0.2,
        "balanced": false
       }
      ],
      "receipt": "05f50e2a-a432-8c45-b269-78a0d9dfc94a"
     },
     "life": {
      "os": {
       "receipt": "7a5adc22-9943-8ed3-9c23-33d831014ce4",
       "bootStates": 832,
       "packages": 25,
       "floor": "uuidna/alpine-baselayout-data",
       "fourWidths": [
        4,
        8,
        16,
        32
       ]
      },
      "living": {
       "count": 71094,
       "target": 131072,
       "toGo": 59978,
       "monotone": true
      },
      "latent": {
       "count": 230,
       "sample": [
        {
         "file": "Affine.lean",
         "def": "av",
         "principle": "The affine"
        },
        {
         "file": "Affine.lean",
         "def": "bv",
         "principle": "The affine"
        },
        {
         "file": "Audit.lean",
         "def": "lh",
         "principle": "The detectors, proven"
        },
        {
         "file": "Audit.lean",
         "def": "step",
         "principle": "The detectors, proven"
        },
        {
         "file": "BioPhysics.lean",
         "def": "lxorAux",
         "principle": "Applied structure — the science pairs"
        },
        {
         "file": "Boolean.lean",
         "def": "bitOf",
         "principle": "The boolean"
        },
        {
         "file": "Cipher.lean",
         "def": "lxorAux",
         "principle": "The cipher & the strand"
        },
        {
         "file": "Codes.lean",
         "def": "lxorAux",
         "principle": "The error-correcting codes"
        },
        {
         "file": "CoinsBalance.lean",
         "def": "hexbit",
         "principle": "THE COINS BALANCE"
        },
        {
         "file": "CoinsBalance.lean",
         "def": "seed",
         "principle": "THE COINS BALANCE"
        },
        {
         "file": "CoinsBalance.lean",
         "def": "vertices",
         "principle": "THE COINS BALANCE"
        },
        {
         "file": "Command.lean",
         "def": "lxorAux",
         "principle": "Command authentication"
        }
       ]
      },
      "balance": {
       "active": 388,
       "balanced": 170,
       "open": 218,
       "revealGap": 32982,
       "worst": [
        {
         "dimension": "wing",
         "id": "HexSpan1.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan10.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan11.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan12.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan13.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan14.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan15.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan16.lean",
         "delta": 4094,
         "balanced": false
        }
       ]
      },
      "ratios": [
       {
        "id": "life.os-living",
        "labelA": "boot states",
        "labelB": "living theorems",
        "a": 832,
        "b": 71094,
        "forward": 0.012,
        "reverse": 85.45,
        "balanced": false
       },
       {
        "id": "life.latent-cited",
        "labelA": "latent axioms",
        "labelB": "cited axioms",
        "a": 230,
        "b": 362,
        "forward": 0.635,
        "reverse": 1.574,
        "balanced": false
       },
       {
        "id": "life.milestone",
        "labelA": "to next 2^n",
        "labelB": "living now",
        "a": 59978,
        "b": 71094,
        "forward": 0.844,
        "reverse": 1.185,
        "balanced": false
       },
       {
        "id": "life.balance",
        "labelA": "balanced slices",
        "labelB": "open slices",
        "a": 170,
        "b": 218,
        "forward": 0.78,
        "reverse": 1.282,
        "balanced": false
       },
       {
        "id": "life.wing-ledger",
        "labelA": "wing theorems",
        "labelB": "ledger keys",
        "a": 71094,
        "b": 71094,
        "forward": 1,
        "reverse": 1,
        "balanced": true
       }
      ],
      "receipt": "2c854f5f-f9fe-8bf0-833e-0f64c465b1cb"
     },
     "axiom": {
      "global": {
       "dimension": "ledger",
       "id": "ledger",
       "theorems": 71094,
       "citedDefs": 362,
       "bound": 68373,
       "citeEdges": 134424,
       "theoremsPerDef": 371.337,
       "defsPerBound": 1.966,
       "delta": 369.371,
       "balanced": false
      },
      "active": 388,
      "balanced": 170,
      "fused": "8a56f853-a017-8c8f-9fca-cd1e5749b87f"
     },
     "kernel": {
      "id": "kernel.axiom",
      "labelA": "audited",
      "labelB": "ledger",
      "a": 71094,
      "b": 71094,
      "forward": 1,
      "reverse": 1,
      "balanced": true
     },
     "wing": {
      "id": "wing.parity",
      "labelA": "wing theorems",
      "labelB": "ledger keys",
      "a": 71094,
      "b": 71094,
      "forward": 1,
      "reverse": 1,
      "balanced": true
     },
     "genesis": {
      "deposits": 35,
      "tip": "ef82bb3ec7874a7e",
      "chainIntact": true
     },
     "ratios": [
      {
       "id": "polarity.minus-plus",
       "labelA": "minus theorems",
       "labelB": "plus theorems",
       "a": 28535,
       "b": 28420,
       "forward": 1.004,
       "reverse": 0.996,
       "balanced": false
      },
      {
       "id": "polarity.neutral-rest",
       "labelA": "neutral",
       "labelB": "non-neutral",
       "a": 14139,
       "b": 56955,
       "forward": 0.248,
       "reverse": 4.028,
       "balanced": false
      },
      {
       "id": "polarity.capacity.minus",
       "labelA": "minus load",
       "labelB": "minus digits",
       "a": 28535,
       "b": 4,
       "forward": 7133.75,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "polarity.capacity.plus",
       "labelA": "plus load",
       "labelB": "plus digits",
       "a": 28420,
       "b": 4,
       "forward": 7105,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "angles.dash-rosetta",
       "labelA": "dash step °",
       "labelB": "ray step °",
       "a": 60,
       "b": 51,
       "forward": 1.176,
       "reverse": 0.85,
       "balanced": false
      },
      {
       "id": "angles.steps-rays",
       "labelA": "dash steps",
       "labelB": "rosetta rays",
       "a": 11,
       "b": 7,
       "forward": 1.571,
       "reverse": 0.636,
       "balanced": false
      },
      {
       "id": "angles.full-circle",
       "labelA": "bearing",
       "labelB": "complement",
       "a": 0,
       "b": 360,
       "forward": 0,
       "reverse": null,
       "balanced": false
      },
      {
       "id": "rosetta.rays.spread",
       "labelA": "sparsest ray",
       "labelB": "densest ray",
       "a": 10057,
       "b": 10242,
       "forward": 0.982,
       "reverse": 1.018,
       "balanced": false
      },
      {
       "id": "rosetta.legs.witness-falsifier",
       "labelA": "witness",
       "labelB": "falsifier",
       "a": 30,
       "b": 71090,
       "forward": 0,
       "reverse": 2369.667,
       "balanced": false
      },
      {
       "id": "rosetta.coins.walk",
       "labelA": "coin sum",
       "labelB": "masks",
       "a": 160,
       "b": 32,
       "forward": 5,
       "reverse": 0.2,
       "balanced": false
      },
      {
       "id": "life.os-living",
       "labelA": "boot states",
       "labelB": "living theorems",
       "a": 832,
       "b": 71094,
       "forward": 0.012,
       "reverse": 85.45,
       "balanced": false
      },
      {
       "id": "life.latent-cited",
       "labelA": "latent axioms",
       "labelB": "cited axioms",
       "a": 230,
       "b": 362,
       "forward": 0.635,
       "reverse": 1.574,
       "balanced": false
      },
      {
       "id": "life.milestone",
       "labelA": "to next 2^n",
       "labelB": "living now",
       "a": 59978,
       "b": 71094,
       "forward": 0.844,
       "reverse": 1.185,
       "balanced": false
      },
      {
       "id": "life.balance",
       "labelA": "balanced slices",
       "labelB": "open slices",
       "a": 170,
       "b": 218,
       "forward": 0.78,
       "reverse": 1.282,
       "balanced": false
      },
      {
       "id": "life.wing-ledger",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 71094,
       "b": 71094,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "kernel.axiom",
       "labelA": "audited",
       "labelB": "ledger",
       "a": 71094,
       "b": 71094,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "wing.parity",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 71094,
       "b": 71094,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "axiom.vocabulary",
       "labelA": "cited defs",
       "labelB": "bound theorems",
       "a": 362,
       "b": 68373,
       "forward": 0.005,
       "reverse": 188.876,
       "balanced": false
      },
      {
       "id": "sequence.fixed",
       "labelA": "fixed",
       "labelB": "non-fixed",
       "a": 14139,
       "b": 56955,
       "forward": 0.248,
       "reverse": 4.028,
       "balanced": false
      },
      {
       "id": "genesis.deposits-theorems",
       "labelA": "deposits",
       "labelB": "theorems",
       "a": 35,
       "b": 71094,
       "forward": 0,
       "reverse": 2031.257,
       "balanced": false
      }
     ],
     "fused": "26a336d5-b985-821b-8879-882483ff0f6d",
     "honest": "Ratios, angles, polarities, and life DECODED — runSequence on every address, ±60° dash, 360/7° rosetta rays, uuidnaOS boot ground, living ledger, latent axioms, genesis chain. Folded order-invariant. Descriptive only."
    },
    "fused": "dac5e09a-5dd6-84f3-a82e-6b72c6118a2c"
   }
  }
 }
}
