// src/edge-slices/generated.ts — GENERATED by scripts/gen-edge-slices from package.json, wrangler.toml, packages/ and
// the minted receipts. Do not edit. Regenerate with `npm run x -- gen-edge-slices`; the generate chain runs it after gen-receipts.
import type { EdgeSlices } from './index.js'

export const EDGE_SLICES: EdgeSlices = {
 "package": {
  "dependencies": [],
  "devDependencies": [
   "@eslint/js",
   "@types/node",
   "eslint",
   "typescript",
   "typescript-eslint",
   "vitepress",
   "wrangler"
  ]
 },
 "wrangler": {
  "assetsBindingPresent": true,
  "kvIdCommitted": false,
  "trialKeyValueCommitted": false
 },
 "workspaces": [
  {
   "dir": "crypto",
   "name": "@uuidna/crypto"
  },
  {
   "dir": "edge",
   "name": "@uuidna/edge"
  },
  {
   "dir": "ledger",
   "name": "@uuidna/ledger"
  },
  {
   "dir": "mcp",
   "name": "@uuidna/mcp"
  },
  {
   "dir": "quantum",
   "name": "@uuidna/quantum"
  },
  {
   "dir": "research",
   "name": "@uuidna/research"
  }
 ],
 "receipts": {
  "decode": {
   "key": "f85a257e-c7c7-8479-8e82-1134e213f9d0",
   "value": {
    "polarities": {
     "minus": 28534,
     "neutral": 14132,
     "plus": 28414,
     "capacity": {
      "minus": 4,
      "neutral": 2,
      "plus": 4
     },
     "byRay": [
      {
       "ray": 0,
       "minus": 4105,
       "neutral": 2002,
       "plus": 4059
      },
      {
       "ray": 1,
       "minus": 4144,
       "neutral": 1999,
       "plus": 4034
      },
      {
       "ray": 2,
       "minus": 4162,
       "neutral": 1946,
       "plus": 3948
      },
      {
       "ray": 3,
       "minus": 4004,
       "neutral": 2045,
       "plus": 4032
      },
      {
       "ray": 4,
       "minus": 4034,
       "neutral": 2077,
       "plus": 4131
      },
      {
       "ray": 5,
       "minus": 4007,
       "neutral": 2091,
       "plus": 4149
      },
      {
       "ray": 6,
       "minus": 4078,
       "neutral": 1972,
       "plus": 4061
      }
     ],
     "bySeed": [
      {
       "seed": 0,
       "theorems": 7030
      },
      {
       "seed": 1,
       "theorems": 7068
      },
      {
       "seed": 2,
       "theorems": 7174
      },
      {
       "seed": 3,
       "theorems": 7112
      },
      {
       "seed": 4,
       "theorems": 7180
      },
      {
       "seed": 5,
       "theorems": 7102
      },
      {
       "seed": 6,
       "theorems": 7163
      },
      {
       "seed": 7,
       "theorems": 7125
      },
      {
       "seed": 8,
       "theorems": 7018
      },
      {
       "seed": 9,
       "theorems": 7108
      }
     ],
     "ratios": [
      {
       "id": "polarity.minus-plus",
       "labelA": "minus theorems",
       "labelB": "plus theorems",
       "a": 28534,
       "b": 28414,
       "forward": 1.004,
       "reverse": 0.996,
       "balanced": false
      },
      {
       "id": "polarity.neutral-rest",
       "labelA": "neutral",
       "labelB": "non-neutral",
       "a": 14132,
       "b": 56948,
       "forward": 0.248,
       "reverse": 4.03,
       "balanced": false
      },
      {
       "id": "polarity.capacity.minus",
       "labelA": "minus load",
       "labelB": "minus digits",
       "a": 28534,
       "b": 4,
       "forward": 7133.5,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "polarity.capacity.plus",
       "labelA": "plus load",
       "labelB": "plus digits",
       "a": 28414,
       "b": 4,
       "forward": 7103.5,
       "reverse": 0,
       "balanced": false
      }
     ],
     "receipt": "15ef6510-d7f0-8cac-b5db-7d56cc4d4037"
    },
    "angles": {
     "dashStepDegrees": 60,
     "weightedBearing": 0,
     "closes": true,
     "steps": 11,
     "rosettaRayStep": 51,
     "ratios": [
      {
       "id": "angles.dash-rosetta",
       "labelA": "dash step °",
       "labelB": "ray step °",
       "a": 60,
       "b": 51,
       "forward": 1.176,
       "reverse": 0.85,
       "balanced": false
      },
      {
       "id": "angles.steps-rays",
       "labelA": "dash steps",
       "labelB": "rosetta rays",
       "a": 11,
       "b": 7,
       "forward": 1.571,
       "reverse": 0.636,
       "balanced": false
      },
      {
       "id": "angles.full-circle",
       "labelA": "bearing",
       "labelB": "complement",
       "a": 0,
       "b": 360,
       "forward": 0,
       "reverse": null,
       "balanced": false
      }
     ],
     "receipt": "1f25cb68-3fc8-8d92-91aa-112dcb5494b8"
    },
    "sequence": {
     "bySeed": [
      {
       "seed": 0,
       "theorems": 7030
      },
      {
       "seed": 1,
       "theorems": 7068
      },
      {
       "seed": 2,
       "theorems": 7174
      },
      {
       "seed": 3,
       "theorems": 7112
      },
      {
       "seed": 4,
       "theorems": 7180
      },
      {
       "seed": 5,
       "theorems": 7102
      },
      {
       "seed": 6,
       "theorems": 7163
      },
      {
       "seed": 7,
       "theorems": 7125
      },
      {
       "seed": 8,
       "theorems": 7018
      },
      {
       "seed": 9,
       "theorems": 7108
      }
     ],
     "fixed": 14132,
     "nonFixed": 56948,
     "canonical": [
      {
       "seed": 0,
       "period": 2,
       "visited": 1
      },
      {
       "seed": 1,
       "period": 0,
       "visited": 3
      },
      {
       "seed": 2,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 3,
       "period": 0,
       "visited": 6
      },
      {
       "seed": 4,
       "period": 0,
       "visited": 8
      },
      {
       "seed": 5,
       "period": 0,
       "visited": 4
      },
      {
       "seed": 6,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 7,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 8,
       "period": 0,
       "visited": 10
      },
      {
       "seed": 9,
       "period": 0,
       "visited": 10
      }
     ],
     "receipt": "45687141-de0a-848e-acb2-2e5349e85dae"
    },
    "rosetta": {
     "rays": [
      {
       "ray": 0,
       "degrees": 0,
       "theorems": 10166
      },
      {
       "ray": 1,
       "degrees": 51,
       "theorems": 10177
      },
      {
       "ray": 2,
       "degrees": 102,
       "theorems": 10056
      },
      {
       "ray": 3,
       "degrees": 154,
       "theorems": 10081
      },
      {
       "ray": 4,
       "degrees": 205,
       "theorems": 10242
      },
      {
       "ray": 5,
       "degrees": 257,
       "theorems": 10247
      },
      {
       "ray": 6,
       "degrees": 308,
       "theorems": 10111
      }
     ],
     "census": {
      "total": 71071,
      "perLeg": [
       {
        "leg": "symbol",
        "theorems": 1375,
        "share": "1375 of 71071"
       },
       {
        "leg": "proof",
        "theorems": 71071,
        "share": "71071 of 71071"
       },
       {
        "leg": "witness",
        "theorems": 30,
        "share": "30 of 71071"
       },
       {
        "leg": "falsifier",
        "theorems": 71051,
        "share": "71051 of 71071"
       },
       {
        "leg": "address",
        "theorems": 71071,
        "share": "71071 of 71071"
       }
      ],
      "scarcest": "witness",
      "byLegCount": [
       {
        "legs": 5,
        "theorems": 28,
        "verdict": "can locate a fault"
       },
       {
        "legs": 4,
        "theorems": 1329,
        "verdict": "can locate a fault"
       },
       {
        "legs": 3,
        "theorems": 69714,
        "verdict": "can locate a fault"
       }
      ],
      "detectOnly": 0,
      "fullyAnchored": [
       "abo_klein_four",
       "blood_types_eight",
       "bulge_exceeds_relief",
       "codons_sixty_four",
       "crossing_sits_inside",
       "cuts_break_successors",
       "dna_base_pairing_involution",
       "edits_break_recompute",
       "eratosthenes_fiftieth_circle",
       "handle_outreaches_planck",
       "hardware_above_landauer",
       "kinematics_cancels_both",
       "landauer_bound_derived",
       "landauer_floor_falls_with_temperature",
       "light_speed_rounds_to_300000",
       "mass_selects_cancellation",
       "pairings_exhaust_the_cancellations",
       "payload_falls_short",
       "planck_margin_bounded",
       "product_isolates_quantum",
       "ratio_isolates_gravity",
       "reversible_erases_nothing",
       "the_defining_constants_are_exact_integers",
       "the_metre_is_defined_by_the_second",
       "the_pairing_cancels_the_constant",
       "two_coins_in_kilograms",
       "van_de_graaf_margins",
       "wgs84_polar_shorter"
      ],
      "claimedBy": [
       {
        "who": "captain",
        "theorems": 71041
       },
       {
        "who": "CODATA",
        "theorems": 10
       },
       {
        "who": "SI",
        "theorems": 7
       },
       {
        "who": "Landauer",
        "theorems": 3
       },
       {
        "who": "10.1007/BF00196791",
        "theorems": 2
       },
       {
        "who": "WGS 84",
        "theorems": 2
       },
       {
        "who": "10.1038/171737a0",
        "theorems": 1
       },
       {
        "who": "10.1038/345229a0",
        "theorems": 1
       },
       {
        "who": "10.1073/pnas.47.10.1588",
        "theorems": 1
       },
       {
        "who": "10.3181/00379727-43-11151",
        "theorems": 1
       },
       {
        "who": "Eratosthenes",
        "theorems": 1
       },
       {
        "who": "Gutenberg",
        "theorems": 1
       }
      ],
      "floor": {
       "witness": 30,
       "falsifier": 63
      },
      "floorGaps": [],
      "receipt": "cdaa83b5-2f12-86a9-9208-d77436e3e272",
      "honest": "The leg census MEASURES how many INDEPENDENT witnesses each sealed theorem carries; it does not certify any of them. PROOF is the kernel verdict and ADDRESS is the content fold, so both are near-universal by construction and neither is evidence about the world. SYMBOL is the js mirror the emitter cross-checks. WITNESS (a source outside this repository) and FALSIFIER (a test that must fail on a deliberate mutation) are the scarce ones, and a low count is reported as it stands rather than smoothed: two legs can DETECT a disagreement and never locate it. A missing leg is never a claim that the theorem is false. Integrity, not truth."
     },
     "maskCoins": 160,
     "ratios": [
      {
       "id": "rosetta.rays.spread",
       "labelA": "sparsest ray",
       "labelB": "densest ray",
       "a": 10056,
       "b": 10247,
       "forward": 0.981,
       "reverse": 1.019,
       "balanced": false
      },
      {
       "id": "rosetta.legs.witness-falsifier",
       "labelA": "witness",
       "labelB": "falsifier",
       "a": 30,
       "b": 71051,
       "forward": 0,
       "reverse": 2368.367,
       "balanced": false
      },
      {
       "id": "rosetta.coins.walk",
       "labelA": "coin sum",
       "labelB": "masks",
       "a": 160,
       "b": 32,
       "forward": 5,
       "reverse": 0.2,
       "balanced": false
      }
     ],
     "receipt": "09cc5522-d646-8fb9-98ee-cbd813bf92d6"
    },
    "life": {
     "os": {
      "receipt": "7a5adc22-9943-8ed3-9c23-33d831014ce4",
      "bootStates": 832,
      "packages": 25,
      "floor": "uuidna/alpine-baselayout-data",
      "fourWidths": [
       4,
       8,
       16,
       32
      ]
     },
     "living": {
      "count": 71080,
      "target": 131072,
      "toGo": 59992,
      "monotone": true
     },
     "latent": {
      "count": 221,
      "sample": [
       {
        "file": "Affine.lean",
        "def": "av",
        "principle": "The affine"
       },
       {
        "file": "Affine.lean",
        "def": "bv",
        "principle": "The affine"
       },
       {
        "file": "Audit.lean",
        "def": "lh",
        "principle": "The detectors, proven"
       },
       {
        "file": "Audit.lean",
        "def": "step",
        "principle": "The detectors, proven"
       },
       {
        "file": "BioPhysics.lean",
        "def": "lxorAux",
        "principle": "Applied structure — the science pairs"
       },
       {
        "file": "Boolean.lean",
        "def": "bitOf",
        "principle": "The boolean"
       },
       {
        "file": "Cipher.lean",
        "def": "lxorAux",
        "principle": "The cipher & the strand"
       },
       {
        "file": "Codes.lean",
        "def": "lxorAux",
        "principle": "The error-correcting codes"
       },
       {
        "file": "Command.lean",
        "def": "lxorAux",
        "principle": "Command authentication"
       },
       {
        "file": "CrossProof.lean",
        "def": "rng",
        "principle": "THE SYMMETRIC AND THE ASYMMETRIC CROSS. One proportion between four quantities has two spellings"
       },
       {
        "file": "Equilibrium.lean",
        "def": "lxorAux",
        "principle": "The six-cube and its polarity double"
       },
       {
        "file": "EquilibriumXor1.lean",
        "def": "lxorAux",
        "principle": "The six-cube translation by 0"
       }
      ]
     },
     "balance": {
      "active": 373,
      "balanced": 163,
      "open": 210,
      "revealGap": 32973,
      "worst": [
       {
        "dimension": "wing",
        "id": "HexSpan1.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan10.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan11.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan12.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan13.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan14.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan15.lean",
        "delta": 4094,
        "balanced": false
       },
       {
        "dimension": "wing",
        "id": "HexSpan16.lean",
        "delta": 4094,
        "balanced": false
       }
      ]
     },
     "ratios": [
      {
       "id": "life.os-living",
       "labelA": "boot states",
       "labelB": "living theorems",
       "a": 832,
       "b": 71080,
       "forward": 0.012,
       "reverse": 85.433,
       "balanced": false
      },
      {
       "id": "life.latent-cited",
       "labelA": "latent axioms",
       "labelB": "cited axioms",
       "a": 221,
       "b": 336,
       "forward": 0.658,
       "reverse": 1.52,
       "balanced": false
      },
      {
       "id": "life.milestone",
       "labelA": "to next 2^n",
       "labelB": "living now",
       "a": 59992,
       "b": 71080,
       "forward": 0.844,
       "reverse": 1.185,
       "balanced": false
      },
      {
       "id": "life.balance",
       "labelA": "balanced slices",
       "labelB": "open slices",
       "a": 163,
       "b": 210,
       "forward": 0.776,
       "reverse": 1.288,
       "balanced": false
      },
      {
       "id": "life.wing-ledger",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 71080,
       "b": 71080,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      }
     ],
     "receipt": "0bbe917c-19fb-8867-9621-9ecaf7f9671f"
    },
    "genesis": {
     "deposits": 35,
     "tip": "ef82bb3ec7874a7e",
     "chainIntact": true
    },
    "audit": {
     "polarities": {
      "minus": 28534,
      "neutral": 14132,
      "plus": 28414,
      "capacity": {
       "minus": 4,
       "neutral": 2,
       "plus": 4
      },
      "byRay": [
       {
        "ray": 0,
        "minus": 4105,
        "neutral": 2002,
        "plus": 4059
       },
       {
        "ray": 1,
        "minus": 4144,
        "neutral": 1999,
        "plus": 4034
       },
       {
        "ray": 2,
        "minus": 4162,
        "neutral": 1946,
        "plus": 3948
       },
       {
        "ray": 3,
        "minus": 4004,
        "neutral": 2045,
        "plus": 4032
       },
       {
        "ray": 4,
        "minus": 4034,
        "neutral": 2077,
        "plus": 4131
       },
       {
        "ray": 5,
        "minus": 4007,
        "neutral": 2091,
        "plus": 4149
       },
       {
        "ray": 6,
        "minus": 4078,
        "neutral": 1972,
        "plus": 4061
       }
      ],
      "bySeed": [
       {
        "seed": 0,
        "theorems": 7030
       },
       {
        "seed": 1,
        "theorems": 7068
       },
       {
        "seed": 2,
        "theorems": 7174
       },
       {
        "seed": 3,
        "theorems": 7112
       },
       {
        "seed": 4,
        "theorems": 7180
       },
       {
        "seed": 5,
        "theorems": 7102
       },
       {
        "seed": 6,
        "theorems": 7163
       },
       {
        "seed": 7,
        "theorems": 7125
       },
       {
        "seed": 8,
        "theorems": 7018
       },
       {
        "seed": 9,
        "theorems": 7108
       }
      ],
      "ratios": [
       {
        "id": "polarity.minus-plus",
        "labelA": "minus theorems",
        "labelB": "plus theorems",
        "a": 28534,
        "b": 28414,
        "forward": 1.004,
        "reverse": 0.996,
        "balanced": false
       },
       {
        "id": "polarity.neutral-rest",
        "labelA": "neutral",
        "labelB": "non-neutral",
        "a": 14132,
        "b": 56948,
        "forward": 0.248,
        "reverse": 4.03,
        "balanced": false
       },
       {
        "id": "polarity.capacity.minus",
        "labelA": "minus load",
        "labelB": "minus digits",
        "a": 28534,
        "b": 4,
        "forward": 7133.5,
        "reverse": 0,
        "balanced": false
       },
       {
        "id": "polarity.capacity.plus",
        "labelA": "plus load",
        "labelB": "plus digits",
        "a": 28414,
        "b": 4,
        "forward": 7103.5,
        "reverse": 0,
        "balanced": false
       }
      ],
      "receipt": "15ef6510-d7f0-8cac-b5db-7d56cc4d4037"
     },
     "angles": {
      "dashStepDegrees": 60,
      "weightedBearing": 0,
      "closes": true,
      "steps": 11,
      "rosettaRayStep": 51,
      "ratios": [
       {
        "id": "angles.dash-rosetta",
        "labelA": "dash step °",
        "labelB": "ray step °",
        "a": 60,
        "b": 51,
        "forward": 1.176,
        "reverse": 0.85,
        "balanced": false
       },
       {
        "id": "angles.steps-rays",
        "labelA": "dash steps",
        "labelB": "rosetta rays",
        "a": 11,
        "b": 7,
        "forward": 1.571,
        "reverse": 0.636,
        "balanced": false
       },
       {
        "id": "angles.full-circle",
        "labelA": "bearing",
        "labelB": "complement",
        "a": 0,
        "b": 360,
        "forward": 0,
        "reverse": null,
        "balanced": false
       }
      ],
      "receipt": "1f25cb68-3fc8-8d92-91aa-112dcb5494b8"
     },
     "sequence": {
      "bySeed": [
       {
        "seed": 0,
        "theorems": 7030
       },
       {
        "seed": 1,
        "theorems": 7068
       },
       {
        "seed": 2,
        "theorems": 7174
       },
       {
        "seed": 3,
        "theorems": 7112
       },
       {
        "seed": 4,
        "theorems": 7180
       },
       {
        "seed": 5,
        "theorems": 7102
       },
       {
        "seed": 6,
        "theorems": 7163
       },
       {
        "seed": 7,
        "theorems": 7125
       },
       {
        "seed": 8,
        "theorems": 7018
       },
       {
        "seed": 9,
        "theorems": 7108
       }
      ],
      "fixed": 14132,
      "nonFixed": 56948,
      "canonical": [
       {
        "seed": 0,
        "period": 2,
        "visited": 1
       },
       {
        "seed": 1,
        "period": 0,
        "visited": 3
       },
       {
        "seed": 2,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 3,
        "period": 0,
        "visited": 6
       },
       {
        "seed": 4,
        "period": 0,
        "visited": 8
       },
       {
        "seed": 5,
        "period": 0,
        "visited": 4
       },
       {
        "seed": 6,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 7,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 8,
        "period": 0,
        "visited": 10
       },
       {
        "seed": 9,
        "period": 0,
        "visited": 10
       }
      ],
      "receipt": "45687141-de0a-848e-acb2-2e5349e85dae"
     },
     "rosetta": {
      "rays": [
       {
        "ray": 0,
        "degrees": 0,
        "theorems": 10166
       },
       {
        "ray": 1,
        "degrees": 51,
        "theorems": 10177
       },
       {
        "ray": 2,
        "degrees": 102,
        "theorems": 10056
       },
       {
        "ray": 3,
        "degrees": 154,
        "theorems": 10081
       },
       {
        "ray": 4,
        "degrees": 205,
        "theorems": 10242
       },
       {
        "ray": 5,
        "degrees": 257,
        "theorems": 10247
       },
       {
        "ray": 6,
        "degrees": 308,
        "theorems": 10111
       }
      ],
      "census": {
       "total": 71071,
       "perLeg": [
        {
         "leg": "symbol",
         "theorems": 1375,
         "share": "1375 of 71071"
        },
        {
         "leg": "proof",
         "theorems": 71071,
         "share": "71071 of 71071"
        },
        {
         "leg": "witness",
         "theorems": 30,
         "share": "30 of 71071"
        },
        {
         "leg": "falsifier",
         "theorems": 71051,
         "share": "71051 of 71071"
        },
        {
         "leg": "address",
         "theorems": 71071,
         "share": "71071 of 71071"
        }
       ],
       "scarcest": "witness",
       "byLegCount": [
        {
         "legs": 5,
         "theorems": 28,
         "verdict": "can locate a fault"
        },
        {
         "legs": 4,
         "theorems": 1329,
         "verdict": "can locate a fault"
        },
        {
         "legs": 3,
         "theorems": 69714,
         "verdict": "can locate a fault"
        }
       ],
       "detectOnly": 0,
       "fullyAnchored": [
        "abo_klein_four",
        "blood_types_eight",
        "bulge_exceeds_relief",
        "codons_sixty_four",
        "crossing_sits_inside",
        "cuts_break_successors",
        "dna_base_pairing_involution",
        "edits_break_recompute",
        "eratosthenes_fiftieth_circle",
        "handle_outreaches_planck",
        "hardware_above_landauer",
        "kinematics_cancels_both",
        "landauer_bound_derived",
        "landauer_floor_falls_with_temperature",
        "light_speed_rounds_to_300000",
        "mass_selects_cancellation",
        "pairings_exhaust_the_cancellations",
        "payload_falls_short",
        "planck_margin_bounded",
        "product_isolates_quantum",
        "ratio_isolates_gravity",
        "reversible_erases_nothing",
        "the_defining_constants_are_exact_integers",
        "the_metre_is_defined_by_the_second",
        "the_pairing_cancels_the_constant",
        "two_coins_in_kilograms",
        "van_de_graaf_margins",
        "wgs84_polar_shorter"
       ],
       "claimedBy": [
        {
         "who": "captain",
         "theorems": 71041
        },
        {
         "who": "CODATA",
         "theorems": 10
        },
        {
         "who": "SI",
         "theorems": 7
        },
        {
         "who": "Landauer",
         "theorems": 3
        },
        {
         "who": "10.1007/BF00196791",
         "theorems": 2
        },
        {
         "who": "WGS 84",
         "theorems": 2
        },
        {
         "who": "10.1038/171737a0",
         "theorems": 1
        },
        {
         "who": "10.1038/345229a0",
         "theorems": 1
        },
        {
         "who": "10.1073/pnas.47.10.1588",
         "theorems": 1
        },
        {
         "who": "10.3181/00379727-43-11151",
         "theorems": 1
        },
        {
         "who": "Eratosthenes",
         "theorems": 1
        },
        {
         "who": "Gutenberg",
         "theorems": 1
        }
       ],
       "floor": {
        "witness": 30,
        "falsifier": 63
       },
       "floorGaps": [],
       "receipt": "cdaa83b5-2f12-86a9-9208-d77436e3e272",
       "honest": "The leg census MEASURES how many INDEPENDENT witnesses each sealed theorem carries; it does not certify any of them. PROOF is the kernel verdict and ADDRESS is the content fold, so both are near-universal by construction and neither is evidence about the world. SYMBOL is the js mirror the emitter cross-checks. WITNESS (a source outside this repository) and FALSIFIER (a test that must fail on a deliberate mutation) are the scarce ones, and a low count is reported as it stands rather than smoothed: two legs can DETECT a disagreement and never locate it. A missing leg is never a claim that the theorem is false. Integrity, not truth."
      },
      "maskCoins": 160,
      "ratios": [
       {
        "id": "rosetta.rays.spread",
        "labelA": "sparsest ray",
        "labelB": "densest ray",
        "a": 10056,
        "b": 10247,
        "forward": 0.981,
        "reverse": 1.019,
        "balanced": false
       },
       {
        "id": "rosetta.legs.witness-falsifier",
        "labelA": "witness",
        "labelB": "falsifier",
        "a": 30,
        "b": 71051,
        "forward": 0,
        "reverse": 2368.367,
        "balanced": false
       },
       {
        "id": "rosetta.coins.walk",
        "labelA": "coin sum",
        "labelB": "masks",
        "a": 160,
        "b": 32,
        "forward": 5,
        "reverse": 0.2,
        "balanced": false
       }
      ],
      "receipt": "09cc5522-d646-8fb9-98ee-cbd813bf92d6"
     },
     "life": {
      "os": {
       "receipt": "7a5adc22-9943-8ed3-9c23-33d831014ce4",
       "bootStates": 832,
       "packages": 25,
       "floor": "uuidna/alpine-baselayout-data",
       "fourWidths": [
        4,
        8,
        16,
        32
       ]
      },
      "living": {
       "count": 71080,
       "target": 131072,
       "toGo": 59992,
       "monotone": true
      },
      "latent": {
       "count": 221,
       "sample": [
        {
         "file": "Affine.lean",
         "def": "av",
         "principle": "The affine"
        },
        {
         "file": "Affine.lean",
         "def": "bv",
         "principle": "The affine"
        },
        {
         "file": "Audit.lean",
         "def": "lh",
         "principle": "The detectors, proven"
        },
        {
         "file": "Audit.lean",
         "def": "step",
         "principle": "The detectors, proven"
        },
        {
         "file": "BioPhysics.lean",
         "def": "lxorAux",
         "principle": "Applied structure — the science pairs"
        },
        {
         "file": "Boolean.lean",
         "def": "bitOf",
         "principle": "The boolean"
        },
        {
         "file": "Cipher.lean",
         "def": "lxorAux",
         "principle": "The cipher & the strand"
        },
        {
         "file": "Codes.lean",
         "def": "lxorAux",
         "principle": "The error-correcting codes"
        },
        {
         "file": "Command.lean",
         "def": "lxorAux",
         "principle": "Command authentication"
        },
        {
         "file": "CrossProof.lean",
         "def": "rng",
         "principle": "THE SYMMETRIC AND THE ASYMMETRIC CROSS. One proportion between four quantities has two spellings"
        },
        {
         "file": "Equilibrium.lean",
         "def": "lxorAux",
         "principle": "The six-cube and its polarity double"
        },
        {
         "file": "EquilibriumXor1.lean",
         "def": "lxorAux",
         "principle": "The six-cube translation by 0"
        }
       ]
      },
      "balance": {
       "active": 373,
       "balanced": 163,
       "open": 210,
       "revealGap": 32973,
       "worst": [
        {
         "dimension": "wing",
         "id": "HexSpan1.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan10.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan11.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan12.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan13.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan14.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan15.lean",
         "delta": 4094,
         "balanced": false
        },
        {
         "dimension": "wing",
         "id": "HexSpan16.lean",
         "delta": 4094,
         "balanced": false
        }
       ]
      },
      "ratios": [
       {
        "id": "life.os-living",
        "labelA": "boot states",
        "labelB": "living theorems",
        "a": 832,
        "b": 71080,
        "forward": 0.012,
        "reverse": 85.433,
        "balanced": false
       },
       {
        "id": "life.latent-cited",
        "labelA": "latent axioms",
        "labelB": "cited axioms",
        "a": 221,
        "b": 336,
        "forward": 0.658,
        "reverse": 1.52,
        "balanced": false
       },
       {
        "id": "life.milestone",
        "labelA": "to next 2^n",
        "labelB": "living now",
        "a": 59992,
        "b": 71080,
        "forward": 0.844,
        "reverse": 1.185,
        "balanced": false
       },
       {
        "id": "life.balance",
        "labelA": "balanced slices",
        "labelB": "open slices",
        "a": 163,
        "b": 210,
        "forward": 0.776,
        "reverse": 1.288,
        "balanced": false
       },
       {
        "id": "life.wing-ledger",
        "labelA": "wing theorems",
        "labelB": "ledger keys",
        "a": 71080,
        "b": 71080,
        "forward": 1,
        "reverse": 1,
        "balanced": true
       }
      ],
      "receipt": "0bbe917c-19fb-8867-9621-9ecaf7f9671f"
     },
     "axiom": {
      "global": {
       "dimension": "ledger",
       "id": "ledger",
       "theorems": 71080,
       "citedDefs": 336,
       "bound": 68360,
       "citeEdges": 134388,
       "theoremsPerDef": 399.964,
       "defsPerBound": 1.966,
       "delta": 397.998,
       "balanced": false
      },
      "active": 373,
      "balanced": 163,
      "fused": "24083186-c1a6-85d5-8415-79ea752acba3"
     },
     "kernel": {
      "id": "kernel.axiom",
      "labelA": "audited",
      "labelB": "ledger",
      "a": 71080,
      "b": 71080,
      "forward": 1,
      "reverse": 1,
      "balanced": true
     },
     "wing": {
      "id": "wing.parity",
      "labelA": "wing theorems",
      "labelB": "ledger keys",
      "a": 71080,
      "b": 71080,
      "forward": 1,
      "reverse": 1,
      "balanced": true
     },
     "genesis": {
      "deposits": 35,
      "tip": "ef82bb3ec7874a7e",
      "chainIntact": true
     },
     "ratios": [
      {
       "id": "polarity.minus-plus",
       "labelA": "minus theorems",
       "labelB": "plus theorems",
       "a": 28534,
       "b": 28414,
       "forward": 1.004,
       "reverse": 0.996,
       "balanced": false
      },
      {
       "id": "polarity.neutral-rest",
       "labelA": "neutral",
       "labelB": "non-neutral",
       "a": 14132,
       "b": 56948,
       "forward": 0.248,
       "reverse": 4.03,
       "balanced": false
      },
      {
       "id": "polarity.capacity.minus",
       "labelA": "minus load",
       "labelB": "minus digits",
       "a": 28534,
       "b": 4,
       "forward": 7133.5,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "polarity.capacity.plus",
       "labelA": "plus load",
       "labelB": "plus digits",
       "a": 28414,
       "b": 4,
       "forward": 7103.5,
       "reverse": 0,
       "balanced": false
      },
      {
       "id": "angles.dash-rosetta",
       "labelA": "dash step °",
       "labelB": "ray step °",
       "a": 60,
       "b": 51,
       "forward": 1.176,
       "reverse": 0.85,
       "balanced": false
      },
      {
       "id": "angles.steps-rays",
       "labelA": "dash steps",
       "labelB": "rosetta rays",
       "a": 11,
       "b": 7,
       "forward": 1.571,
       "reverse": 0.636,
       "balanced": false
      },
      {
       "id": "angles.full-circle",
       "labelA": "bearing",
       "labelB": "complement",
       "a": 0,
       "b": 360,
       "forward": 0,
       "reverse": null,
       "balanced": false
      },
      {
       "id": "rosetta.rays.spread",
       "labelA": "sparsest ray",
       "labelB": "densest ray",
       "a": 10056,
       "b": 10247,
       "forward": 0.981,
       "reverse": 1.019,
       "balanced": false
      },
      {
       "id": "rosetta.legs.witness-falsifier",
       "labelA": "witness",
       "labelB": "falsifier",
       "a": 30,
       "b": 71051,
       "forward": 0,
       "reverse": 2368.367,
       "balanced": false
      },
      {
       "id": "rosetta.coins.walk",
       "labelA": "coin sum",
       "labelB": "masks",
       "a": 160,
       "b": 32,
       "forward": 5,
       "reverse": 0.2,
       "balanced": false
      },
      {
       "id": "life.os-living",
       "labelA": "boot states",
       "labelB": "living theorems",
       "a": 832,
       "b": 71080,
       "forward": 0.012,
       "reverse": 85.433,
       "balanced": false
      },
      {
       "id": "life.latent-cited",
       "labelA": "latent axioms",
       "labelB": "cited axioms",
       "a": 221,
       "b": 336,
       "forward": 0.658,
       "reverse": 1.52,
       "balanced": false
      },
      {
       "id": "life.milestone",
       "labelA": "to next 2^n",
       "labelB": "living now",
       "a": 59992,
       "b": 71080,
       "forward": 0.844,
       "reverse": 1.185,
       "balanced": false
      },
      {
       "id": "life.balance",
       "labelA": "balanced slices",
       "labelB": "open slices",
       "a": 163,
       "b": 210,
       "forward": 0.776,
       "reverse": 1.288,
       "balanced": false
      },
      {
       "id": "life.wing-ledger",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 71080,
       "b": 71080,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "kernel.axiom",
       "labelA": "audited",
       "labelB": "ledger",
       "a": 71080,
       "b": 71080,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "wing.parity",
       "labelA": "wing theorems",
       "labelB": "ledger keys",
       "a": 71080,
       "b": 71080,
       "forward": 1,
       "reverse": 1,
       "balanced": true
      },
      {
       "id": "axiom.vocabulary",
       "labelA": "cited defs",
       "labelB": "bound theorems",
       "a": 336,
       "b": 68360,
       "forward": 0.005,
       "reverse": 203.452,
       "balanced": false
      },
      {
       "id": "sequence.fixed",
       "labelA": "fixed",
       "labelB": "non-fixed",
       "a": 14132,
       "b": 56948,
       "forward": 0.248,
       "reverse": 4.03,
       "balanced": false
      },
      {
       "id": "genesis.deposits-theorems",
       "labelA": "deposits",
       "labelB": "theorems",
       "a": 35,
       "b": 71080,
       "forward": 0,
       "reverse": 2030.857,
       "balanced": false
      }
     ],
     "fused": "0e7bd8ce-a100-8ccb-8ef5-cb15c60eed3c",
     "honest": "Ratios, angles, polarities, and life DECODED — runSequence on every address, ±60° dash, 360/7° rosetta rays, uuidnaOS boot ground, living ledger, latent axioms, genesis chain. Folded order-invariant. Descriptive only."
    },
    "fused": "52dcd844-ac9a-8176-aac0-dc3536ef85e0"
   }
  }
 }
}
