// GENERATED by src/scripts/gen-packages.ts — DO NOT EDIT: the split is computed from src/index.ts
// (the one export surface). Regenerate with `npm run gen:packages`; the guard hard-rejects drift.
// @uuidna/edge — the DEPLOYMENT SURFACE: the Cloudflare bindings audit (committed config. Integrity.
export { auditCloudflareBindings, type CloudflareAudit, type BindingAudit } from '@uuidna/uuidna'
export { heroAnimation, readHero, type HeroAnimation, renderTheorem, renderList, renderHero, type TheoremView, type RenderOpts } from '@uuidna/uuidna'
export { serialize, documentAddress, documentHandle, reAddress, payloadFoldHook, type DocNode, type EditorState, type DocFold, type PayloadHookArgs } from '@uuidna/uuidna'
export { seedUuid, readSeed, filterSeeds, belongsTo, buildLeanPageSeed, verifySeed, toPayloadDocs, type SeedStatus, type SeedIdentity, type LeanPageSeed, type PayloadDoc } from '@uuidna/uuidna'
export { canonicalOrder, nextOf, gaps, discoverStaticPages, computeSidebar, SIDEBAR_CATEGORIES, type PageNode, type SidebarGroup } from '@uuidna/uuidna'
export { quantumProfile, type QuantumProfile } from '@uuidna/uuidna'
export { socialProfile, type SocialProfile } from '@uuidna/uuidna'
export { quantumSeo, type Seo, type HeadTuple } from '@uuidna/uuidna'
export { oeapiProfile, oeapiOrganisations, oeapiProgrammes, oeapiCourses, oeapiLearningOutcomes, OEAPI_SPEC, OEAPI_VERSION,
  type OeapiProfile, type OeapiOrganisation, type OeapiProgramme, type OeapiCourse, type OeapiLearningOutcome,
  type OeapiLangString, type OeapiCode } from '@uuidna/uuidna'
