// quantum/os/mirror — GENERATED by scripts/lean-installs.ts from Alpine latest-stable (main/x86_64). DO NOT EDIT.
// The DEFAULT INSTALL: alpine-base's dependency closure in the PUBLISHED index, pinned with the release it is
// the world of, so every deterministic surface (site, MCP, tests, the Lean wing) reads the same set offline.
// Always Alpine latest: scripts/lean-installs re-reads latest-stable at the os/ boundary on every lean run and
// rewrites this file only when upstream moved. Data, never executed.

export interface MirrorPackage { name: string; version: string; checksum: string; desc: string; deps: string[] }
export interface InstallsMirror {
  branch: string; repo: string; arch: string
  release: { version: string; rootfsSha256: string }
  count: number
  packages: MirrorPackage[]
}

export const INSTALLS_MIRROR: InstallsMirror = {
 "branch": "latest-stable",
 "repo": "main",
 "arch": "x86_64",
 "release": {
  "version": "3.24.1",
  "rootfsSha256": "41f73e3cf5fa919b8aa5ca6b30dc48f0da2720776d7423e2a7748211456fe081"
 },
 "count": 25,
 "packages": [
  {
   "name": "alpine-base",
   "version": "3.24.1-r0",
   "checksum": "Q1FVD1ypez9RDWd52MokUzPbtTaj8=",
   "desc": "Meta package for minimal alpine base",
   "deps": [
    "alpine-baselayout",
    "alpine-conf",
    "alpine-release",
    "apk-tools",
    "busybox",
    "busybox-mdev-openrc",
    "busybox-openrc",
    "busybox-suid",
    "musl-utils",
    "openrc"
   ]
  },
  {
   "name": "alpine-baselayout",
   "version": "3.7.2-r1",
   "checksum": "Q18Pz9wvTaBYr2RzvEXE6rYpFiJbI=",
   "desc": "Alpine base dir structure and init scripts",
   "deps": [
    "alpine-baselayout-data",
    "busybox-binsh"
   ]
  },
  {
   "name": "alpine-baselayout-data",
   "version": "3.7.2-r1",
   "checksum": "Q1xvm97RfYRLbxsLtXZtLDXA1chQg=",
   "desc": "Alpine base dir structure and init scripts",
   "deps": []
  },
  {
   "name": "alpine-conf",
   "version": "3.22.0-r0",
   "checksum": "Q16CliiBBKgwsiM/O3ucF5orx3JuQ=",
   "desc": "Alpine configuration management scripts",
   "deps": [
    "busybox",
    "musl",
    "openrc"
   ]
  },
  {
   "name": "alpine-keys",
   "version": "2.6-r0",
   "checksum": "Q12Na4DlPAWad+SRXaeLqWTz/+okA=",
   "desc": "Public keys for Alpine Linux packages",
   "deps": []
  },
  {
   "name": "alpine-release",
   "version": "3.24.1-r0",
   "checksum": "Q1vGkSolzcdzPgA17VCezqpAJpRuM=",
   "desc": "Alpine release data",
   "deps": [
    "alpine-keys"
   ]
  },
  {
   "name": "apk-tools",
   "version": "3.0.7-r0",
   "checksum": "Q1dLXHOFXPYF6O8puceaa15gWGTDU=",
   "desc": "Alpine Package Keeper - package manager for alpine",
   "deps": [
    "ca-certificates-bundle",
    "libapk",
    "libcrypto3",
    "musl",
    "zlib"
   ]
  },
  {
   "name": "busybox",
   "version": "1.37.0-r31",
   "checksum": "Q1tUBevAL33YvpW2JlxUskPVRWq48=",
   "desc": "Size optimized toolbox of many common UNIX utilities",
   "deps": [
    "musl"
   ]
  },
  {
   "name": "busybox-binsh",
   "version": "1.37.0-r31",
   "checksum": "Q1XL0UrMbxgExbrGx33CxJLwELD8c=",
   "desc": "busybox ash /bin/sh",
   "deps": [
    "busybox"
   ]
  },
  {
   "name": "busybox-ifupdown",
   "version": "1.37.0-r31",
   "checksum": "Q1ez4d3LobV4sLYM2DnkQ0wW3TE/A=",
   "desc": "placeholder package for busybox ifupdown",
   "deps": []
  },
  {
   "name": "busybox-mdev-openrc",
   "version": "1.37.0-r31",
   "checksum": "Q17911Y5QO/WM6kH50Da7ruRLw+Ck=",
   "desc": "Size optimized toolbox of many common UNIX utilities",
   "deps": [
    "mdev-conf",
    "openrc"
   ]
  },
  {
   "name": "busybox-openrc",
   "version": "1.37.0-r31",
   "checksum": "Q14JOLaJA0Bdxr4Kx2WFKWIHwCsgw=",
   "desc": "Size optimized toolbox of many common UNIX utilities",
   "deps": [
    "openrc"
   ]
  },
  {
   "name": "busybox-suid",
   "version": "1.37.0-r31",
   "checksum": "Q10I131aeOncNTjS9OZyso/feLg6w=",
   "desc": "suid binaries of Busybox",
   "deps": [
    "busybox",
    "musl"
   ]
  },
  {
   "name": "ca-certificates-bundle",
   "version": "20260611-r0",
   "checksum": "Q1yVNKA3UL3640HxCWkBYJD8Ef670=",
   "desc": "Pre generated bundle of Mozilla certificates",
   "deps": []
  },
  {
   "name": "libapk",
   "version": "3.0.7-r0",
   "checksum": "Q1PvZp8Y+OXreXo6B9LCOkRTE2NTo=",
   "desc": "Alpine Package Keeper - package manager for alpine",
   "deps": [
    "libcrypto3",
    "libssl3",
    "musl",
    "zlib"
   ]
  },
  {
   "name": "libcap2",
   "version": "2.78-r0",
   "checksum": "Q1Vi3y8KkXpS2XsFrXvtM0FK2izUs=",
   "desc": "POSIX 1003.1e capabilities (libraries)",
   "deps": [
    "musl"
   ]
  },
  {
   "name": "libcrypto3",
   "version": "3.5.8-r0",
   "checksum": "Q1GzufwME29JNpMryy7CFJnwrl39M=",
   "desc": "Crypto library from openssl",
   "deps": [
    "musl"
   ]
  },
  {
   "name": "libssl3",
   "version": "3.5.8-r0",
   "checksum": "Q1X5seVdghlT0uKx2zItrXCjtQQeo=",
   "desc": "SSL shared libraries",
   "deps": [
    "libcrypto3",
    "musl"
   ]
  },
  {
   "name": "mdev-conf",
   "version": "4.10-r0",
   "checksum": "Q1KLmZv7/kWrWBUERvJrmnJvxXnRk=",
   "desc": "Configuration files for mdev and mdevd",
   "deps": []
  },
  {
   "name": "musl",
   "version": "1.2.6-r2",
   "checksum": "Q1D35YJ+ThpzYxvtont4QxqLokDgU=",
   "desc": "the musl c library (libc) implementation",
   "deps": []
  },
  {
   "name": "musl-utils",
   "version": "1.2.6-r2",
   "checksum": "Q1da2jxI1j7F2HxC/fk0o/3REpjcU=",
   "desc": "the musl c library (libc) implementation",
   "deps": [
    "musl",
    "scanelf"
   ]
  },
  {
   "name": "openrc",
   "version": "0.63.2-r0",
   "checksum": "Q1sbrKI+PLDCITuRsoERGsT/DcUuo=",
   "desc": "OpenRC manages the services, startup and shutdown of a host",
   "deps": [
    "busybox-binsh",
    "busybox-ifupdown",
    "libcap2",
    "musl",
    "openrc-user"
   ]
  },
  {
   "name": "openrc-user",
   "version": "0.63.2-r0",
   "checksum": "Q1pNbfg2vFC2aIXpxZNbF/zlSZeG8=",
   "desc": "OpenRC user services without PAM support",
   "deps": [
    "musl",
    "openrc"
   ]
  },
  {
   "name": "scanelf",
   "version": "1.3.9-r1",
   "checksum": "Q1AT+QPQuiGWc6673QT3S7XtgrAfA=",
   "desc": "Scan ELF binaries for stuff",
   "deps": [
    "musl"
   ]
  },
  {
   "name": "zlib",
   "version": "1.3.2-r0",
   "checksum": "Q13Uw9ECrK7ypxoUlZUdVfq8hoBhM=",
   "desc": "A compression/decompression Library",
   "deps": [
    "musl"
   ]
  }
 ]
}
