export {
  ADVANTAGE_MCP_ORIGIN,
  ADVANTAGE_OVERCLAIM,
  atPath,
  expectHolds,
  hookAdvantageMcp,
  renderAdvantageMcpMarkdown,
  advantageCurriculum,
  schoolAdvantageMcpExamples,
  type AdvantageMcpCurriculum,
  type AdvantageMcpExample,
  type AdvantageMcpHook,
  type McpExpect,
  type McpHookHop,
} from './mcp/examples/index.js'
