<!-- The hero, animated — and every number in it is SEALED, not chosen. The path is the doubling orbit imported from
     the ledger (vortexOrbit: 1→2→4→8→7→5→1, the unit group of ℤ/9 generated by 2), so the walk closes because the
     orbit closes. The rays are the seven reading DIMENSIONS, and `dimension` selects which one leads: it turns to
     the top, burns bright, and the other six dim behind it. Colours read the --seq-* custom properties that
     applySequence() already puts on the root from the ℤ/9 sequence, and the tempi are the units of ℤ/9 written three
     times (111 … 888ms), so the motion carries the same arithmetic as the figure. Self-contained inline SVG + CSS —
     no external calls, CSP-safe, like FoldAnimation beside it.

     The proof link goes through withBase, because routing is VitePress's job: a component does not invent a URL
     prefix. HONEST SCOPE: this VISUALISES arithmetic already proven; it demonstrates nothing further. -->
<script setup>
import { computed } from 'vue'
import { withBase } from 'vitepress'
import { vortexOrbit, DIMENSIONS } from '../../../dist/index.js'

const props = defineProps({
  dimension: { type: String, default: 'en' },      // which of the seven rays leads
  rung: { type: Number, default: 1 },              // where the sequence colour starts
  theorem: { type: String, default: 'vortex_orbit' }, // the proof this hero announces
  size: { type: Number, default: 240 },
})

const orbit = vortexOrbit()                        // [1,2,4,8,7,5] — sealed, never typed here
const dims = DIMENSIONS                            // the seven reading dimensions — sealed
const TEMPI = ['111ms', '222ms', '444ms', '555ms', '777ms', '888ms']  // the units of ℤ/9, tripled

// an unrecognised dimension leads with the first AND is reported below, never silently swapped
const found = computed(() => dims.indexOf(props.dimension))
const lead = computed(() => (found.value < 0 ? 0 : found.value))
const leadName = computed(() => dims[lead.value])
const proof = computed(() => withBase(`/theorem/${props.theorem}`))
const hue = (n) => `var(--seq-${((n + props.rung - 1) % 9) + 1}, var(--vp-c-brand-1))`
const beat = (i) => TEMPI[i % TEMPI.length]
// every ray turns by its distance FROM the lead, so selecting a dimension rotates the whole figure
const rayTurn = (i) => ((i - lead.value + dims.length) % dims.length) * (360 / dims.length)
const nodeTurn = (i) => i * (360 / orbit.length)
</script>

<template>
  <figure class="heroanim">
    <a :href="proof" :aria-label="`the proof of ${theorem}`">
      <svg :width="size" :height="size" viewBox="0 0 200 200" role="img"
           :aria-label="`the doubling orbit ${orbit.join('→')} across ${dims.length} dimensions, ${leadName} leading`">
        <!-- the seven dimensions; the lead one points up, long and bright -->
        <g class="rays">
          <g v-for="(d, i) in dims" :key="d" :transform="`rotate(${rayTurn(i)} 100 100)`">
            <line x1="100" y1="100" :x2="100" :y2="i === lead ? 54 : 64" :stroke="hue(i + 1)"
                  :stroke-width="i === lead ? 3 : 1" :class="i === lead ? 'lead' : 'dim'"
                  :style="{ '--beat': beat(i) }" />
            <text v-if="i === lead" x="100" y="50" text-anchor="middle" font-size="8" :fill="hue(i + 1)">{{ d }}</text>
          </g>
        </g>
        <!-- the doubling orbit: six rungs, each pulsing on its sealed tempo -->
        <g class="orbit">
          <g v-for="(v, i) in orbit" :key="v" :transform="`rotate(${nodeTurn(i)} 100 100)`">
            <circle cx="100" cy="30" r="9" :fill="hue(v)" class="rung" :style="{ '--beat': beat(i) }" />
            <text x="100" y="34" text-anchor="middle" font-size="10" class="num"
                  :transform="`rotate(${-nodeTurn(i)} 100 30)`">{{ v }}</text>
          </g>
        </g>
        <!-- 5 — the fixed point of the diamond involution r(d) = 10 − d -->
        <circle cx="100" cy="100" r="4" :fill="hue(5)" />
      </svg>
    </a>
    <figcaption>
      the doubling orbit {{ orbit.join(' → ') }} → {{ orbit[0] }}, {{ dims.length }} dimensions,
      <strong>{{ leadName }}</strong> leading<span v-if="found < 0"> (asked for “{{ dimension }}”, which is not one of the seven)</span>
    </figcaption>
  </figure>
</template>

<style scoped>
.heroanim { margin: 1.5rem auto; text-align: center }
.heroanim a { display: inline-block; text-decoration: none }
figcaption { font-size: .78rem; color: var(--vp-c-text-2); margin-top: .4rem }
.rung { animation: pulse var(--beat) infinite ease-in-out }
.lead { animation: burn var(--beat) infinite ease-in-out }
.dim { opacity: .12; animation: fade var(--beat) infinite ease-in-out }
.num { fill: var(--vp-c-bg); font-weight: 600 }
@keyframes pulse { 0%, 100% { r: 9 } 50% { r: 13 } }
@keyframes burn { 0%, 100% { opacity: .7 } 50% { opacity: 1 } }
@keyframes fade { 0%, 100% { opacity: .08 } 50% { opacity: .18 } }
@media (prefers-reduced-motion: reduce) {
  .rung, .lead, .dim { animation: none }
}
</style>
