// school/laws — EVERY STANDING LAW ENROLLS AT SCHOOL (the captain, 2026-09-14: "the school legal training need to be
// complete so agents be aware!"). The laws live in src/laws.ts, the same source uuidna_laws serves; this renders all of
// them for /school, each with its own words, the captain's words and date where given, the gate that enforces it, and
// whether it holds at this generation — recomputed, never asserted. A law that does not hold is shown as not holding,
// never left out, so an agent that studies here meets every law it will be held to.
//
// PURE over the laws the caller hands in; gen-school computes them and the test holds the page to them exactly.
import type { Laws } from '../../laws.js'
import { pageSafe } from '../../quantum/advantage/page/safe/index.js'

export const LAWS_START = '<!-- laws: GENERATED by scripts/gen-school from src/laws.ts — every standing law, so no agent studies here without meeting it -->'
export const LAWS_END = '<!-- /laws -->'

/** renderSchoolLaws(laws) → the /school block: every law, in the order src/laws.ts states them */
export function renderSchoolLaws(l: Laws): string {
  const holding = l.laws.filter((x) => x.holds).length
  const rows = l.laws.map((x) =>
    `- **${x.holds ? 'holds' : 'does not hold'}** · ${pageSafe(x.law)}` +
    (x.said ? `\n  <br><small>said: ${pageSafe(x.said)}</small>` : '') +
    `\n  <br><small>enforced by: ${pageSafe(x.enforcedBy)} — ${pageSafe(x.detail)}</small>`)
  return [
    LAWS_START,
    '## The laws {#laws}',
    '',
    'Every law this ledger holds itself to, from the same source an agent reads through `uuidna_laws`, each beside the',
    'gate that enforces it and its state recomputed at this generation. A law is only as true as its computed check:',
    'one that does not hold is shown here as not holding, never left out. Only a Lean proof settles a claim',
    '([`legal_only_the_proven_is_admitted`](/theorem/legal_only_the_proven_is_admitted)).',
    '',
    `**${l.laws.length} laws** — ${holding} hold · ${l.laws.length - holding} do not hold · receipt \`${l.receipt}\``,
    '',
    ...rows,
    LAWS_END,
  ].join('\n')
}
