// GENERATED by src/scripts/gen-packages.ts — DO NOT EDIT: the split is computed from src/index.ts
// (the one export surface). Regenerate with `npm run gen:packages`; the guard hard-rejects drift.
// @uuidna/research — RECOMPUTABLE RESEARCH: deep research through the imprint codec, corroboration and
// publication scans, book/movie/record/standard audits, gated publications, the reporter’s method, prior art,
// the NIST beacon anchor, CODATA constants, CVE fingerprints, the vocabulary, transform-until-verified, the
// reasoner, and reflections. Provenance and structure. Integrity.
export { RESEARCH_SOURCE_NAMES, corroborate, approve, firewall, entangle, researchEvidence, corroborateWithResearch, scanPublications, type ResearchEvidence, type Corroboration, type FirewallResult, type Entanglement, type PublicationScan, type PublicationFinding } from '@uuidna/uuidna'
export { deepResearch, type DeepResearch } from '@uuidna/uuidna'
export { auditText, auditTranslation, fetchGutenberg, auditBook, auditMovie, auditZenodo, auditStandard, extractDecidable, linkBookFacts, composeBookArticle, bookArticle, bookContents, readChapter, readBook, type BookAudit, type TranslationAudit, type FetchedBook, type MovieAudit, type RecordAudit, type StandardAudit, type ExtractedFact, type BookTheoremLink, type BookLedgerLinkage, type ChapterRead } from '@uuidna/uuidna'
export { transformUntilVerified, transformOne, type TransformCell, type TransformRun } from '@uuidna/uuidna'
export { composePublication, publications, coverage, auditPublication, revisePublication, comparePublications, type Publication, type PubFinding, type Revision, type Comparison, type Coverage } from '@uuidna/uuidna'
export { fileReport, type FiledReport } from '@uuidna/uuidna'
export { reason, type Rule, type Derivation, type Reasoning } from '@uuidna/uuidna'
export { reflects, type Reflection, type Reflected } from '@uuidna/uuidna'
export { priorArt, type PriorArt, type PriorArtExhibit } from '@uuidna/uuidna'
export { beaconAnchor, type Anchor } from '@uuidna/uuidna'
export { nistConstant, type NistConstant } from '@uuidna/uuidna'
export { auditCve, type CveAudit } from '@uuidna/uuidna'
export { vocabulary, type Term, type Vocabulary } from '@uuidna/uuidna'
export { schoolApiRegistry, schoolApiFetch, escoSearch, eurostatEducation, giscoSchools,
  dataEuropaSearch, cordisSearch, tedNotices, pickLang, probeSchoolApis, immutableReads, CPV_EDUCATION,
  escoOccupationsForSkill, eurostatVacancies, pairEducationToJobs, splitCsvLine, SCHOOL_APIS, GISCO_VINTAGE,
  EUROSTAT_VACANCIES, type SchoolApi, type SchoolApiRegistry, type SchoolApiAnswer, type SchoolApiEvidence,
  type SchoolApiQuery, type EscoConcept, type EurostatObservation, type EuDataset, type CordisRecord, type TedNotice, type SourceProbe, type Heartbeat,
  type GiscoSchool, type OccupationLink, type SkillJobPair, type EducationJobsPairing } from '@uuidna/uuidna'
