// GENERATED by src/scripts/gen-packages.ts — DO NOT EDIT: the split is computed from src/index.ts
// (the one export surface). Regenerate with `npm run gen:packages`; the guard hard-rejects drift.
// @uuidna/mcp — the MCP SERVER package: the `uuidna-mcp` stdio bin (re-served from the root dist) plus the
// I/O boundary the server stands on — the sanitizers and the reeducating harness. Integrity.
export {
  type Harnessed, DIMENSIONS,
  harness, opaque, harnessGain, harness7, reeducate,
} from '@uuidna/uuidna'
export { sanitizeValue, sanitizeInput, scrubString, MAX_DEPTH, MAX_STRING, MAX_ARRAY, MAX_KEYS } from '@uuidna/uuidna'
