#!/usr/bin/env node
// Automate the Lean layer for division by zero in the ℤ/9 vortex. Division by zero EXISTS here — it is the
// diamond reflection dz(x) = 10−x (dz(0)=0), a finite residue, never Infinity. This script COMPUTES each fact
// from the local definition (self-proving in JS), GENERATES a `by decide` Lean theorem for it, writes
// lean/DivByZero.lean, and VERIFIES it compiles sorry-free with `lean`. Compute → generate → verify. 0/7.
import { writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const dz = (x) => (x === 0 ? 0 : 10 - x) // division by zero in the vortex = the diamond reflection
const R10 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

// each fact: computed in JS (must hold), paired with the Lean theorem `by decide` that proves the same.
const FACTS = [
  { key: 'dz_table', why: 'the table: 0/0=0, and x/0 = 10−x  (9/0=1 … 1/0=9)',
    js: () => JSON.stringify(R10.map(dz)) === JSON.stringify([0, 9, 8, 7, 6, 5, 4, 3, 2, 1]),
    lean: 'theorem dz_table : (List.range 10).map dz = [0, 9, 8, 7, 6, 5, 4, 3, 2, 1] := by decide' },
  { key: 'dz_involution', why: 'division by zero is self-inverse: (x/0)/0 = x — an involution',
    js: () => R10.every((x) => dz(dz(x)) === x),
    lean: 'theorem dz_involution : (List.range 10).all (fun x => dz (dz x) == x) := by decide' },
  { key: 'dz_fixed_points', why: 'the fixed points of x/0 are exactly {0, 5} — the floor and the heart',
    js: () => JSON.stringify(R10.filter((x) => dz(x) === x)) === JSON.stringify([0, 5]),
    lean: 'theorem dz_fixed_points : ((List.range 10).filter (fun x => dz x == x)) = [0, 5] := by decide' },
  { key: 'dz_sum_ten', why: 'x + x/0 = 10 for x∈1..9 — the reflection sums to ten across the centre',
    js: () => [1, 2, 3, 4, 5, 6, 7, 8, 9].every((x) => x + dz(x) === 10),
    lean: "theorem dz_sum_ten : (List.range' 1 9).all (fun x => x + dz x == 10) := by decide" },
  { key: 'dz_nonunits_to_units', why: 'the non-units {3,6,9} divided by zero land on units {7,4,1}',
    js: () => dz(3) === 7 && dz(6) === 4 && dz(9) === 1,
    lean: 'theorem dz_nonunits_to_units : dz 3 = 7 ∧ dz 6 = 4 ∧ dz 9 = 1 := by decide' },
  { key: 'dz_bounded', why: 'x/0 is always a residue < 10 — a finite value, NEVER Infinity (no fake FTL)',
    js: () => R10.every((x) => dz(x) < 10),
    lean: 'theorem dz_bounded : (List.range 10).all (fun x => dz x < 10) := by decide' },
  { key: 'dz_zero_only_zero', why: 'only 0/0 = 0; every other x/0 is nonzero (the reflection moves it)',
    js: () => dz(0) === 0 && [1, 2, 3, 4, 5, 6, 7, 8, 9].every((x) => dz(x) !== 0),
    lean: "theorem dz_zero_only_zero : dz 0 = 0 ∧ (List.range' 1 9).all (fun x => dz x != 0) := by decide" },
]

// 1) compute — every fact must hold in JS (self-proving from the local definition)
const jsFail = FACTS.filter((f) => f.js() !== true)
if (jsFail.length) { console.log('✗ JS computation failed: ' + jsFail.map((f) => f.key).join(', ')); process.exit(1) }
console.log('computed ' + FACTS.length + ' division-by-zero facts from the vortex — all hold in JS.')

// 2) generate — emit the Lean file
const lean = `-- lean/DivByZero.lean — GENERATED by scripts/lean-divzero.mjs (compute → generate → verify). Division by zero
-- in the ℤ/9 vortex EXISTS: it is the diamond reflection dz(x) = 10−x (dz 0 = 0), a finite residue, never ∞.
-- Every theorem is \`by decide\`, sorry-free. Regenerate with \`npm run lean:divzero\`. Integrity, not truth. 0/7.

def dz (x : Nat) : Nat := if x == 0 then 0 else 10 - x

${FACTS.map((f) => '-- ' + f.why + '\n' + f.lean).join('\n\n')}
`
const path = join(ROOT, 'lean', 'DivByZero.lean')
writeFileSync(path, lean)
console.log('generated ' + FACTS.length + ' Lean theorems → lean/DivByZero.lean')

// 3) verify — compile with `lean` (sorry-free ⇒ exit 0)
try {
  execSync('lean ' + JSON.stringify(path), { cwd: ROOT, stdio: 'pipe' })
  console.log('✓ VERIFIED: lean/DivByZero.lean compiles sorry-free — ' + FACTS.length + ' division-by-zero theorems proved.')
} catch (e) {
  console.log('✗ Lean verification FAILED:\n' + (e.stdout?.toString() || '') + (e.stderr?.toString() || ''))
  process.exit(1)
}
