#!/usr/bin/env node
// The 8×8 CORE — the multiplication table of ℤ/9's eight non-zero residues {1..8}. These 64 theorems are the
// generating core: from this one table the rest COMPUTES — the units (a has an inverse iff a row contains 1),
// the self-inverses (a·a=1: {1,8}), the nilpotents (a·a=0: {3,6}), the vortex orbit and the reflection all read
// off the table. Each `by decide`, sorry-free. Also emits the microdata manifest for the UI. 8×8 → the rest. 0/7.
import { writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const T = []
for (let a = 1; a <= 8; a++) for (let b = 1; b <= 8; b++) T.push({ key: `mul9_${a}_${b}`, stmt: `(${a} * ${b}) % 9 = ${(a * b) % 9}`, name: `${a}·${b} ≡ ${(a * b) % 9} (mod 9)` })
console.log('the 8×8 core: ' + T.length + ' non-zero ℤ/9 multiplication theorems (from these the rest computes).')

const lean = `-- lean/Core.lean — GENERATED by scripts/lean-core.mjs. The 8×8 CORE: the multiplication table of ℤ/9's eight
-- non-zero residues {1..8}. From these 64 theorems the rest COMPUTES — units, inverses, self-inverses {1,8},
-- nilpotents {3,6}, the vortex orbit and the reflection all read off this table. Every proof \`by decide\`,
-- sorry-free, no Mathlib. Regenerate with \`npm run lean:core\`. Integrity, not truth. 0/7.

${T.map((t) => `theorem ${t.key} : ${t.stmt} := by decide`).join('\n')}
`
writeFileSync(join(ROOT, 'lean', 'Core.lean'), lean)
writeFileSync(join(ROOT, 'lean', 'core-manifest.json'), JSON.stringify(T.map((t) => ({ key: t.key, name: t.name })), null, 0) + '\n')
console.log('generated lean/Core.lean (' + T.length + ') + lean/core-manifest.json')
try { execSync('lean ' + JSON.stringify(join(ROOT, 'lean', 'Core.lean')), { cwd: ROOT, stdio: 'pipe' }); console.log('✓ VERIFIED: lean/Core.lean compiles sorry-free — ' + T.length + ' theorems.') }
catch (e) { console.log('✗ FAILED:\n' + (e.stdout?.toString() || '').slice(0, 1500)); process.exit(1) }
