-- lean/CoinsBalance.lean — GENERATED. THE COINS BALANCE — seven rows MOVED from qpu (src/quantum/processing/unit/index.lean), where they sat beside a processing unit's efficiency while measuring something else: the string ratios over 27, the same fractions as a separate published row, the pentagram as three words plus two coins, the schema combinatorics that reach 432, theory and practice as one coin each, the two coins following every application, and the coil as the fourteen faces. THE CAPTAIN RULED MOVE, NOT DELETE (2026-09-27), and that ruling is the design: a sealed theorem is a published record and no one withdraws a settlement, so qpu's defs are carried verbatim and every claim is the claim it was, re-proven here. Measured before the move: nothing in qpu cites any of these seven, so removing them there breaks no kernel proof — while two_coins_make_a_coil and design were LEFT because coil_efficiency and neuro cite them. CLAIMED: this arithmetic, decided by the kernel over its own finite domain, axiom-free, with the universal row carrying its quantifier rather than a sample. NOT CLAIMED: that 432 is a correct tuning, that any framework must be built on these integers, or that an aphorism becomes true by being decidable — each row proves its arithmetic and the reading beside it stays a reading. Every proof `by decide`, sorry-free, no Mathlib, and axiom-free — depends on NO axiom beyond the leanprover/lean4 kernel (verified by scripts/lean-axioms; not even propext).

/-- FOUR HUNDRED AND THIRTY-TWO IS REACHED TWICE, BY ROUTES THAT SHARE NO STEP — and the agreement is the claim.
    From the string side it is sixteen twenty-sevens: the integer multiples of 27 that a monochord divides. From
    the combinatorial side it is 2 × 3 × 8 × 9 — two coins, the three words of "quantum processing unit", the
    eight doublings of those three, and the nine of three squared. Neither route mentions the other, and both
    land on 432. Then the just fractions of it — 3/2, 4/3, 5/4, 5/3 — fall on 648, 576, 540 and 720 in exact Nat
    division with no remainder, which is why the number carries the ratios at all. NOT CLAIMED: that 432 is a
    correct or preferable tuning, nor that any framework must be built on these integers. What is claimed is
    that two unrelated countings meet on one integer and that its fifths, fourths and thirds are exact there. -/
theorem two_routes_reach_four_hundred_and_thirty_two : ([16 * 27, (1 + 1) * 3 * 8 * (3 * 3)] : List Nat).all (fun r => r == 432) = true ∧ ([16 * 27, (1 + 1) * 3 * 8 * (3 * 3)] : List Nat).length = 2 ∧ 432 * 3 / 2 = 648 ∧ 432 * 4 / 3 = 576 ∧ 432 * 5 / 4 = 540 ∧ 432 * 5 / 3 = 720 := by decide
