-- lean/Sequence.lean — GENERATED by scripts/lean-sequence.mjs (compute → generate → verify). The ℤ/9 vortex
-- sequence and its reflection group: the mirror m(d)=10−d, doubling σ and the mirror generating AGL(1,ℤ/9) of
-- order 54 in ONE orbit, with commutator [σ,μ] = the unit shift. Every theorem is `by decide`, sorry-free.
-- Regenerate with `npm run lean:sequence`. Integrity, not truth. 0/7.

def ap (a b x : Nat) : Nat := (a * x + b) % 9          -- an affine map on ℤ/9: x ↦ a·x + b
def tour : List Nat := [1, 2, 4, 8, 7, 5, 3, 6, 0]     -- the vortex tour in ℤ/9 (9 ≡ 0)
def units9 : List Nat := [1, 2, 4, 5, 7, 8]
def carries9 (d nx : Nat) : Bool :=                    -- ×2 on units, +3 on {3,6}; neither elsewhere
  if units9.contains d then nx == (2 * d) % 9
  else if d == 3 || d == 6 then nx == (d + 3) % 9
  else false

-- the mirror m(d)=10−d equals 1−d (mod 9) — a reflection through the origin+1
theorem mirror_congruence : (List.range' 1 9).all (fun d => ((10 - d : Int)) % 9 = (1 - d) % 9) := by decide

-- the mirror fixes exactly one digit in 1..9 — the heart, 5
theorem mirror_fixed_five : ((List.range' 1 9).filter (fun d => 10 - d == d)) = [5] := by decide

-- AGL(1,ℤ/9) = { x ↦ a·x+b : a a unit, b ∈ ℤ/9 } has |units|·9 = 6·9 = 54 elements
theorem agl_order_54 : ((List.range 9).filter (fun a => (List.range 9).any (fun e => a*e % 9 == 1))).length * 9 = 54 := by decide

-- the commutator [σ,μ] of doubling with the mirror is the unit shift x ↦ x+1
theorem commutator_is_shift : (List.range 9).all (fun x => ap 2 0 (ap 8 1 (ap 5 0 (ap 8 1 x))) == (x + 1) % 9) := by decide

-- the shifts alone act transitively — every digit is in ONE orbit of ℤ/9
theorem one_orbit : (List.range 9).all (fun y => (List.range 9).any (fun b => (0 + b) % 9 == y)) := by decide

-- the reflection equilibrium: d + m(d) = 10 for every d in 1..9
theorem ten_pairs : (List.range' 1 9).all (fun d => d + (10 - d) == 10) := by decide

-- the polar equilibrium: d + (9−d) = 9 across the negation of ℤ/9
theorem polar_nine_pairs : (List.range' 1 8).all (fun d => d + (9 - d) == 9) := by decide

-- the 6+3 partition: 6 units {1,2,4,5,7,8} and 3 non-units {3,6,9}
theorem partition_six_three : ((List.range' 1 9).filter (fun a => (List.range 9).any (fun e => a*e % 9 == 1))).length = 6 ∧ ((List.range' 1 9).filter (fun a => ¬ (List.range 9).any (fun e => a*e % 9 == 1))).length = 3 := by decide

-- the ring closes: ten slots × 36° = 360°, and the ⟨2⟩ flow is 60° per doubling
theorem angles_close : 10 * 36 = 360 ∧ 6 * 60 = 360 := by decide

-- exactly 2 seams (5→3 and 0→1) where neither ×2 nor +3 carries — the two involution centers, −χ = 2
theorem seams_two : ((tour.zip (tour.drop 1 ++ tour.take 1)).filter (fun p => ! carries9 p.1 p.2)).length = 2 := by decide
