// os/models — the PUBLIC-LIVE-DATA boundary for the model comparison (the captain's order: widen the
// comparison to ALL public live data). Exactly the os/installs pattern one shelf over: the pure page
// (src/quantum/models) reads only the committed mirror; THIS module is the one place the mirror may move —
// it reads a PUBLIC, keyless model feed (OpenRouter's /api/v1/models: every routed model's id, published
// context window, and published per-token prices) at the named non-determinism boundary, and renders the
// exact mirror bytes for scripts/lean-models to commit. The response is DATA: parsed, sorted, carried with
// its source — never a benchmark of ours, never executed, and PRICES STAY VERBATIM STRINGS (this tree runs
// no floats; a price is a published label, not a number we compute on). Best-effort: a down feed yields null
// and the committed mirror stands; a model list is NEVER fabricated.
import { type ModelsMirror } from '../../quantum/models/mirror.js'

const FEED = 'https://openrouter.ai/api/v1/models'

/** fetchPublicModels() → the WHOLE public feed, mirror-shaped: every model's id, name, published context
 *  window (integer tokens), and published prices (verbatim strings) — sorted by id, source-stamped. Null on
 *  any failure or shape drift; nothing is guessed. */
export async function fetchPublicModels(): Promise<ModelsMirror | null> {
  try {
    const body = await (await fetch(FEED)).json() as { data?: { id?: string; name?: string; context_length?: number; pricing?: { prompt?: string; completion?: string } }[] }
    if (!Array.isArray(body.data) || body.data.length === 0) return null
    const models = body.data
      .filter((m) => typeof m.id === 'string' && Number.isInteger(m.context_length) && m.context_length! > 0)
      .map((m) => ({
        id: m.id!,
        name: m.name ?? m.id!,
        contextTokens: m.context_length!,
        promptPrice: String(m.pricing?.prompt ?? ''),
        completionPrice: String(m.pricing?.completion ?? ''),
      }))
      .sort((a, b) => (a.id < b.id ? -1 : 1))
    if (!models.length) return null
    return { source: 'openrouter.ai/api/v1/models (public, keyless)', endpoint: FEED, count: models.length, models }
  } catch {
    return null  // a down feed yields null — the committed mirror stands; a list is never fabricated
  }
}

/** renderModelsMirror(data) → the EXACT bytes of src/quantum/models/mirror.ts for this data — one
 *  serialisation, so an unchanged feed is a byte-identical mirror. */
export function renderModelsMirror(m: ModelsMirror): string {
  return `// quantum/models/mirror — GENERATED by scripts/lean-models.ts from ${m.source}. DO NOT EDIT.
// ALL PUBLIC LIVE MODEL DATA: every model the public feed routes, with its published context window and
// per-token prices (verbatim strings — labels, not numbers this tree computes on), so every deterministic
// surface (the /models page, the wing, the tests) reads the same census offline. Refreshed at the src/os
// boundary on every lean run; rewritten only when the feed moved. Data, never executed, never benchmarked.

export interface MirrorModel { id: string; name: string; contextTokens: number; promptPrice: string; completionPrice: string }
export interface ModelsMirror { source: string; endpoint: string; count: number; models: MirrorModel[] }

export const MODELS_MIRROR: ModelsMirror = ${JSON.stringify(m, null, 1)}
`
}
