import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './boundary.js'
import { disagreements, crossSurfaceCensus, type Probe } from './cross-surface.js'
import { MIRROR } from './rosetta-mirror.js'
import { theorems } from './index.js'
import { claimsFrom } from './claim-attribution.js'

// THE PROBES ARE THE POINT. cross-surface.ts is arithmetic over pairs; this file is where the pairs are named,
// and naming them is the whole instrument. Each pair below is two censuses of the SAME quantity reached by
// different mechanisms — the Lean source read directly, a generated mirror, a generated claims ledger. Any one
// of them can be wrong while reading clean. What they cannot do is be wrong TOGETHER and still agree — cannot,
// because agreement here is on a number neither surface takes from the other: the mirror is rendered from the
// wings, the claims ledger is indexed from the parsed lines, and this file counts the .lean text itself. Two
// derivations that never read each other have no channel to make the same mistake through.

/** The ledger, counted from the Lean source itself — the one reading that no generator produced. */
function leanSourceKeys(): Set<string> {
  const keys = new Set<string>()
  const dir = join(ROOT, 'lean')
  for (const f of readdirSync(dir).filter((x) => x.endsWith('.lean'))) {
    for (const line of readFileSync(join(dir, f), 'utf8').split('\n')) {
      const m = /^(theorem|lemma)\s+([A-Za-z0-9_']+)/.exec(line)
      if (m) keys.add(m[2]!)
    }
  }
  return keys
}

/** The ledger as the shipped rosetta mirror records it. */
function mirrorKeys(): Set<string> {
  return new Set(
    MIRROR.split('\n')
      .filter((l) => l.trim() && !l.startsWith('#'))
      .map((l) => l.trim().split(/\s+/)[0]!),
  )
}

// RECOMPUTED, NEVER READ. docs/captain-claims.json is a cache of exactly this call, and reading it here raced
// the generator that writes it — intermittently, which is the worst way for a probe to be wrong: three passes,
// then a failure on an unchanged tree, and no diff capturable because reproducing the race reran the suite.
test('cross-surface — the probe pairs agree, or each disagreement is a lead', () => {
  const lean = leanSourceKeys(), mirror = mirrorKeys()
  const list = claimsFrom(theorems())
  const claims = {
    claims_list: list,
    total_claimed: list.length,
    novelty_claimed: list.filter((c) => c.held === 'discovery+formalisation').length,
    formalisation_only: list.filter((c) => c.held === 'formalisation').length,
    attributed_facts: list.filter((c) => c.factAttributedTo),
  }
  const claimed = new Set(claims.claims_list.map((c) => c.key))
  const probes: Probe[] = [
    {
      what: 'ledger size',
      a: { surface: 'lean/*.lean (source, ungenerated)', value: lean.size },
      b: { surface: 'src/rosetta-mirror.ts MIRROR', value: mirror.size },
      why: 'the mirror is shipped to an edge with no filesystem; if it drifts from the source, the edge answers a ledger that does not exist',
    },
    {
      what: 'ledger size',
      a: { surface: 'lean/*.lean (source, ungenerated)', value: lean.size },
      b: { surface: 'claimsFrom(theorems()) — the rule the claims ledger is generated by', value: claimed.size },
      why: 'a claim for a theorem not in the source is a claim on nothing; a theorem absent from the claims is unclaimed work',
    },
    {
      what: 'claims partition into discovery and formalisation',
      a: { surface: 'total_claimed', value: claims.total_claimed },
      b: { surface: 'novelty_claimed + formalisation_only', value: claims.novelty_claimed + claims.formalisation_only },
      why: 'the two parts must exhaust the whole, or a row is claimed twice or not at all',
    },
    {
      what: 'attributed facts recorded',
      a: { surface: 'captain-claims.attributed_facts', value: claims.attributed_facts.length },
      b: { surface: 'captain-claims.formalisation_only', value: claims.formalisation_only },
      why: 'the count and the list are written by one generator from one census; if they part, one of them is stale',
    },
  ]

  // A DISAGREEMENT MUST NAME ITS CURE, or it gets read as flakiness and waved through. The first pair has a
  // LEGITIMATE window in which to part — between sealing a theorem and regenerating the derived layer the
  // mirror is honestly behind the source — and a reader who hits that mid-reconcile and sees a bare number
  // learns nothing except that this test is noisy. The other three are written by one generator from one census
  // and have no such window: if they part, something is stale or a row is counted twice.
  const found = disagreements(probes)
  const cure = (what: string): string =>
    what === 'ledger size'
      ? 'the derived layer is behind the source — run the reconcile (generate → heartbeats --sync → messaging → rosetta → spin --seal); if it persists AFTER a reconcile, a generator is dropping rows'
      : 'no reconcile can fix this — these are written by ONE generator from ONE census, so a row is counted twice, or not at all, or a count and its list have parted'
  assert.deepEqual(
    found.map((d) => `${d.what}: ${d.a.surface}=${d.a.value} vs ${d.b.surface}=${d.b.value} (delta ${d.delta}) — ${d.why}. FIX: ${cure(d.what)}`),
    [],
  )
  assert.equal(crossSurfaceCensus(probes).asked, 4)
})

// THE CONTROL. Every assertion above passes if disagreements() simply never reports — which is also what a
// broken comparator looks like. Handed a pair that differs by one it must say so, and it must say so about the
// LARGER gap first, because a planner reads the top of the list.
// THE SHIPPED ARTEFACT AGAINST THE LIVE SOURCE — the probe removed to cure a race, restored without it.
//
// Reading docs/captain-claims.json for the probe VALUES raced the generator that writes it, so those values are
// recomputed above and the file is no longer their source. That cured the race and BLINDED the probe: the
// shipped artefact went stale by three rows — 2659 claims over a ledger of 2656, five claimed keys absent from
// the source — and every test here passed, because both of the artefact's own numbers came from the same stale
// run and agreed with each other perfectly. Internal consistency cannot detect staleness; only a second surface
// can, which is this file's whole thesis arriving at its own blind spot.
//
// RACE-TOLERANT BY CONSTRUCTION: the file is read inside a try, and an unparseable read is reported as NOT
// ASKED rather than as a disagreement. A half-written JSON does not parse, so the failure mode that caused the
// original race becomes a skipped probe instead of a false alarm — the same "an absent instrument voids"
// discipline the prior-art sweep uses for a 429.
test('cross-surface — the shipped claims artefact agrees with the live ledger', () => {
  let shipped: { total_theorems?: number; total_claimed?: number; claims_list?: { key: string }[] } | null = null
  try {
    shipped = JSON.parse(readFileSync(join(ROOT, 'docs', 'captain-claims.json'), 'utf8'))
  } catch {
    return  // UNASKED: mid-write or absent. Not evidence of agreement, and never reported as such.
  }
  const live = new Set(claimsFrom(theorems()).map((c) => c.key))
  assert.equal(shipped!.total_theorems, theorems().length, 'the artefact reports a ledger size the source does not have — regenerate the derived layer')
  const orphans = (shipped!.claims_list ?? []).map((c) => c.key).filter((k) => !live.has(k))
  assert.deepEqual(orphans.slice(0, 8), [], 'the artefact claims keys the ledger no longer contains — a renamed or removed theorem left a claim behind')
})

test('cross-surface — the comparator REPORTS a difference when one exists', () => {
  const probes: Probe[] = [
    { what: 'small', a: { surface: 'a', value: 10 }, b: { surface: 'b', value: 11 }, why: 'w' },
    { what: 'large', a: { surface: 'a', value: 10 }, b: { surface: 'b', value: 4 }, why: 'w' },
    { what: 'none', a: { surface: 'a', value: 7 }, b: { surface: 'b', value: 7 }, why: 'w' },
  ]
  const d = disagreements(probes)
  assert.equal(d.length, 2, 'the comparator missed a differing pair, or reported an agreeing one')
  assert.equal(d[0]!.what, 'large', 'the widest gap must be reported first — a negative delta is still a big gap')
  assert.equal(d[0]!.delta, -6)
  assert.deepEqual(crossSurfaceCensus(probes), { asked: 3, disagreed: 2, agreed: 1 })
})
