// hex-line-css — THE 768 LINE ATTRIBUTES ARE POSITION, AND CSS ALREADY KNOWS POSITION.
//
// MEASURED ON THE BUILT SITE. Every theorem page shipped 768 `<span class="hex-line" data-yang="0|1">`
// elements — 46,080 bytes, 28 percent of the page, against 11,746 bytes of visible text. Across 5,606 pages that
// is about 246 MEGABYTES. And the bits carry NO page-specific information whatsoever: the component computed
// them as `(i >> b) & 1`, the LSB-first binary expansion of each gate's own index, so the same 768 values appear
// on every page of the site. Verified directly rather than reasoned about — the bit string extracted from two
// different theorem pages in the built dist is byte-identical.
//
// A span whose only attribute is the binary expansion of its own position is a span describing where it already
// is. CSS reads position with `:nth-child`, so the attribute can go and the styling can be derived instead.
//
// THE ARITHMETIC. Line b (zero-based) of gate i is YANG iff bit b of i is set. A gate is the (i+1)-th child of
// the board and a line the (b+1)-th child of its gate, so with n = i + 1 the condition is on (n-1) mod 2^(b+1):
// set iff that residue is at least 2^b. Each bit therefore needs 2^b `:nth-child(2^(b+1) n + k)` clauses, and
// 1 + 2 + 4 + 8 + 16 + 32 = 63 clauses cover all six lines — about 3 KB of stylesheet, shipped ONCE, replacing
// 46 KB of markup on every page. The generator below emits them and the test checks every one of the 128 x 6
// cases against `(i >> b) & 1`, because a selector that is subtly wrong changes the face silently.

/** How many lines a hexagram has. Mirrored as a plain number so this module stays free of a cycle. */
export const HEX_LINES = 6

/** yangAt(gate, line) → is that line solid? The ONE definition, and the component's own former expression. */
export const yangAt = (gate: number, line: number): boolean => ((gate >> line) & 1) === 1

/** nthClausesForBit(b) → the `An+B` pairs selecting every gate position whose bit b is SET.
 *
 *  With n one-based, gate i = n - 1, and bit b of i is set exactly when (n-1) mod 2^(b+1) >= 2^b. Enumerating
 *  those residues gives 2^b arithmetic progressions of stride 2^(b+1). */
export function nthClausesForBit(b: number): { stride: number; offset: number }[] {
  const stride = 1 << (b + 1)
  const half = 1 << b
  const out: { stride: number; offset: number }[] = []
  for (let r = half; r < stride; r++) {
    // residue r of (n-1) means n ≡ r+1 (mod stride); nth-child(An+B) uses B in 1..A
    const offset = ((r + 1) % stride) === 0 ? stride : (r + 1) % stride
    out.push({ stride, offset })
  }
  return out
}

/** matchesNth(n, stride, offset) → does `:nth-child(stride n + offset)` select the n-th child?
 *  CSS counts n from 0 upward, so the clause selects positions offset, offset+stride, offset+2*stride, … */
export const matchesNth = (n: number, stride: number, offset: number): boolean =>
  n >= offset && (n - offset) % stride === 0

/** selectedByBit(gate, b) → does the generated clause set for bit b select this gate's position? */
export function selectedByBit(gate: number, b: number): boolean {
  const n = gate + 1
  return nthClausesForBit(b).some((c) => matchesNth(n, c.stride, c.offset))
}

/** hexLineCss(gates) → the stylesheet block: default yin, with the derived YANG overrides.
 *
 *  Default-yin and override-yang is the inverse of what the component had (default solid, `[data-yang="0"]`
 *  broken). It is inverted deliberately: the override set is what the generator can prove correct, so the
 *  proven half is the half that paints, and a missing clause shows as a visibly broken line rather than a
 *  silently solid one. A wrong selector must be visible. */
export function hexLineCss(gates = 128): string {
  const lines: string[] = []
  lines.push('/* GENERATED by src/hex-line-css.ts — do not hand-edit.')
  lines.push(' * The line values are the binary expansion of each gate\'s own position, so they are derived from')
  lines.push(' * :nth-child rather than shipped as 768 per-line attributes on every page (about 246 MB across the')
  lines.push(' * site). Default is YIN (broken); the clauses below paint the YANG lines. */')
  lines.push('.hex-gate > span {')
  lines.push('  display: block;')
  lines.push('  height: 2px;')
  lines.push('  background: linear-gradient(90deg, var(--face-aura) 38%, transparent 38%, transparent 62%, var(--face-aura) 62%);')
  lines.push('}')
  for (let b = 0; b < HEX_LINES; b++) {
    const sel = nthClausesForBit(b)
      .filter((c) => c.offset <= gates)
      .map((c) => `.hex-board > :nth-child(${c.stride}n + ${c.offset}) > :nth-child(${b + 1})`)
      .join(',\n')
    if (!sel) continue
    lines.push(`/* line ${b + 1}: yang where bit ${b} of the gate index is set */`)
    lines.push(`${sel} {`)
    lines.push('  background: var(--face-aura);')
    lines.push('}')
  }
  return lines.join('\n')
}
