import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { yangAt, nthClausesForBit, runsForBit, coverForBit, coverSelectors, matchesNth, selectedByBit, hexLineCss, HEX_LINES } from './hex-line-css.js'
import { ROOT } from './boundary.js'

// A SELECTOR THAT IS SUBTLY WRONG CHANGES THE FACE SILENTLY, so the generated clause set is checked against the
// component's own former expression — `(i >> b) & 1` — for EVERY one of the 128 x 6 cases, not a sample.

test('the generated clauses select exactly the gates whose bit is set — all 128 gates, all 6 lines', () => {
  const wrong: string[] = []
  for (let gate = 0; gate < 128; gate++)
    for (let b = 0; b < HEX_LINES; b++)
      if (selectedByBit(gate, b) !== yangAt(gate, b))
        wrong.push(`gate ${gate} line ${b}: selector says ${selectedByBit(gate, b)}, arithmetic says ${yangAt(gate, b)}`)
  assert.deepEqual(wrong, [], 'a mismatch here paints the wrong line on every page of the site')
})

test('the STRIDE cover costs 2^b per bit, 63 across the six lines — the price the generator used to pay for all of them', () => {
  let total = 0
  for (let b = 0; b < HEX_LINES; b++) {
    const c = nthClausesForBit(b)
    assert.equal(c.length, 1 << b, `bit ${b} needs 2^${b} progressions`)
    for (const x of c) {
      assert.equal(x.stride, 1 << (b + 1))
      assert.ok(x.offset >= 1 && x.offset <= x.stride, `offset ${x.offset} outside 1..${x.stride}`)
    }
    total += c.length
  }
  assert.equal(total, 63, '1+2+4+8+16+32')
})

test('matchesNth is CSS nth-child semantics, counting n from zero', () => {
  // :nth-child(2n + 2) selects 2, 4, 6 …
  assert.equal(matchesNth(2, 2, 2), true)
  assert.equal(matchesNth(4, 2, 2), true)
  assert.equal(matchesNth(1, 2, 2), false)
  assert.equal(matchesNth(3, 2, 2), false)
  // an offset larger than the position selects nothing
  assert.equal(matchesNth(1, 4, 3), false)
  assert.equal(matchesNth(3, 4, 3), true)
})

test('bit 0 is every second gate — the simplest case, checked by hand', () => {
  // gates 1, 3, 5 … have bit 0 set; those are one-based positions 2, 4, 6 …
  for (const gate of [1, 3, 5, 7, 127]) assert.equal(yangAt(gate, 0), true)
  for (const gate of [0, 2, 4, 6, 126]) assert.equal(yangAt(gate, 0), false)
  const c = nthClausesForBit(0)
  assert.deepEqual(c, [{ stride: 2, offset: 2 }], 'bit 0 set means an even one-based position')
})

test('the stylesheet declares a yin default and a yang override for each line', () => {
  const css = hexLineCss(128)
  assert.match(css, /GENERATED by src\/hex-line-css\.ts/)
  assert.match(css, /\.hex-gate > span \{/, 'the default must apply to every line')
  for (let b = 0; b < HEX_LINES; b++)
    assert.match(css, new RegExp(`> :nth-child\\(${b + 1}\\)`), `line ${b + 1} has no override`)
  // AND NO ATTRIBUTE SELECTOR SURVIVES — checked as `[data-yang`, not as the bare word, because the generated
  // comment legitimately explains which attribute was removed. The first version of this assertion matched its
  // own explanation and failed: a check whose subject includes its own documentation.
  assert.ok(!/\[data-yang/.test(css), 'no rule may select on the removed attribute; position is the source')
})

test('the stylesheet is deterministic and small — it ships once, unlike the markup it replaces', () => {
  assert.equal(hexLineCss(128), hexLineCss(128))
  assert.ok(hexLineCss(128).length < 8000, 'a few kilobytes once, against 46 KB on each of 5606 pages')
})

// ── THE FOLD. "Bit b of the position is set" has two exact descriptions — 2^b strides, or 2^(6-b) contiguous
// runs — dual under bit-reversal of the index. Painting every line by stride costs 63 selectors; taking the
// cheaper dual per line costs 21, and paints identically. These check the duality itself, not just the count,
// because a cover that is cheaper and WRONG is the only way this change can hurt.

test('the two covers describe the SAME set, for every line and every one of the 128 positions', () => {
  for (let b = 0; b < HEX_LINES; b++) {
    const runs = runsForBit(b, 128)
    const clauses = nthClausesForBit(b).filter((c) => c.offset <= 128)
    for (let n = 1; n <= 128; n++) {
      const byRun = runs.some((r) => n >= r.from && n <= r.to)
      const byStride = clauses.some((c) => matchesNth(n, c.stride, c.offset))
      assert.equal(byRun, byStride, `line ${b + 1} position ${n}: the duals disagree`)
      assert.equal(byRun, yangAt(n - 1, b), `line ${b + 1} position ${n}: neither cover is the arithmetic`)
    }
  }
})

test('each line ships the cheaper dual, and the six together cost 21 selectors instead of 63', () => {
  const kinds = Array.from({ length: HEX_LINES }, (_, b) => coverForBit(b, 128).kind)
  assert.deepEqual(kinds, ['stride', 'stride', 'stride', 'stride', 'runs', 'runs'],
    'the crossover is between line 4 and line 5; a tie at line 4 keeps the stride, which is the form the arithmetic already speaks')
  const counts = Array.from({ length: HEX_LINES }, (_, b) => coverSelectors(coverForBit(b, 128)))
  assert.deepEqual(counts, [1, 2, 4, 8, 4, 2])
  assert.equal(counts.reduce((a, c) => a + c, 0), 21, '1+2+4+8+4+2 — where paying stride for all six is 63')
})

test('line 6 is two ranges and line 1 is one stride — the emitted stylesheet, not the plan', () => {
  const css = hexLineCss(128)
  assert.match(css, /:nth-child\(n \+ 33\):nth-child\(-n \+ 64\) > :nth-child\(6\)/, 'first half of line 6 as a range')
  assert.match(css, /:nth-child\(n \+ 97\):nth-child\(-n \+ 128\) > :nth-child\(6\)/, 'second half of line 6 as a range')
  assert.match(css, /:nth-child\(2n \+ 2\) > :nth-child\(1\)/, 'line 1 stays a single stride — 64 ranges would be worse')
  assert.equal((css.match(/> :nth-child\(6\)/g) ?? []).length, 2, 'line 6 shipped 32 selectors before the fold')
})

test('a board shorter than a full block clips the last run rather than overrunning it', () => {
  assert.deepEqual(runsForBit(5, 40), [{ from: 33, to: 40 }], 'the run stops at the board, not at 64')
  for (let n = 1; n <= 40; n++)
    assert.equal(selectedByBit(n - 1, 5, 40), yangAt(n - 1, 5), `clipped board, position ${n}`)
})

// ── THE COMPONENT MUST CARRY EXACTLY WHAT THE GENERATOR PRODUCES. The clauses live inside a .vue style block, so
// no generator writes that file — which would normally make it hand-authored prose that drifts. This assertion
// IS the generator gate: edit the generator without pasting the result, or edit the pasted result by hand, and
// it fails. Same discipline as the stamped-surface finder, applied to a stylesheet.
test('HexFace.vue carries the generated clauses verbatim, and no longer selects on the removed attribute', () => {
  const vue = readFileSync(join(ROOT, 'docs', '.vitepress', 'theme', 'HexFace.vue'), 'utf8')
  assert.ok(vue.includes(hexLineCss(128)), 'the .vue style block has drifted from src/hex-line-css.ts — paste the generator output')
  assert.ok(!/\[data-yang/.test(vue), 'no rule may select on data-yang')
  assert.ok(!/:data-yang=/.test(vue), 'the template must not emit the attribute')
  assert.ok(!/class="hex-line"/.test(vue), 'the per-line class is gone; the lines are selected by position')
})

test('the template no longer computes the line bits — only `lit` is data', () => {
  const vue = readFileSync(join(ROOT, 'docs', '.vitepress', 'theme', 'HexFace.vue'), 'utf8')
  assert.ok(!/lines\.push\(\(i >> b\) & 1\)/.test(vue), 'the binary expansion of the position is not data')
  assert.match(vue, /out\.push\(\{ i, lit: row\[i\] === 1 \}\)/, 'the cell carries its index and whether it is lit')
})
