// prose-provenance — EVERY MACHINE-WRITTEN PAGE DECLARES THAT IT IS MACHINE-WRITTEN.
//
// WHAT WAS ASKED, AND WHY IT CANNOT BE ANSWERED AS ASKED. The captain asked for a proof that all essays are
// human creation with no artificial edits. That proof does not exist and this file does not pretend to it —
// not because the tooling is missing, but because the claim is FALSE HERE and the pages say so themselves:
// every file in docs/articles is written by a script in this repository. `docs/articles/acoustics.md` states
// it in its own second paragraph: "This article is computed from the ledger — nothing here is authored, and
// every claim carries its citation." Measured: 234 article pages, 234 written by a generator, 0 hand-authored.
// A checker that certified those as human would be the exact fault this tree spends every finder refusing.
//
// SO THE CLAIM IS INVOLUTED, and the involute is both true and checkable: rather than proving no page was
// machine-edited, prove that EVERY page which was machine-written SAYS SO. That is the property with real
// value, and it is the one that protects an authorship claim rather than diluting it — the captain's own work
// is worth distinguishing from a generator's output, and it can only be distinguished if the generator's
// output is labelled. An unlabelled generated page is the thing that would let a machine's prose be read as a
// person's, which is the harm the original request was reaching for.
//
// THE DECIDABLE QUESTION: for each prose surface a generator writes, does the page carry an ORIGIN STATEMENT?
// Not a fixed phrase — the search pages say "this page is what the trial returned" and the domain articles say
// "computed from the ledger", and both are honest. What is refused is SILENCE.
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './boundary.js'
import { toUuid, merkleFold } from './address.js'

/** the prose trees a generator owns, and the generator that owns each */
export const GENERATED_PROSE: readonly { dir: string; writer: string }[] = [
  { dir: 'docs/articles', writer: 'gen-articles / quantum-search-trial' },
]

// AN ORIGIN STATEMENT, IN ANY OF THE HONEST WORDINGS THE TREE ACTUALLY USES. A single required phrase would be
// worse: it would force every page into one voice and would be satisfied by pasting a string, whereas what
// matters is that a reader is told. These are the forms present in the tree, and a new form is added here
// deliberately when a generator starts using one — never by loosening the rule to a substring that any page
// would satisfy.
export const ORIGIN_FORMS: readonly RegExp[] = [
  /computed from the ledger/i,
  /computed from lean\//i,
  /GENERATED by/,
  /nothing here is authored/i,
  /this page is what the trial returned/i,
  /derived from the sealed/i,
]

export interface ProseOrigin {
  path: string
  writer: string
  declares: boolean
  /** the wording it used, when it declares — so a reader can see which voice, not just that it passed */
  form: string | null
}

/** proseProvenance() → every generated prose page with whether it declares its own origin. */
export function proseProvenance(): ProseOrigin[] {
  const out: ProseOrigin[] = []
  for (const { dir, writer } of GENERATED_PROSE) {
    const abs = join(ROOT, dir)
    if (!existsSync(abs)) continue
    for (const name of readdirSync(abs).sort()) {
      if (!name.endsWith('.md')) continue
      const text = readFileSync(join(abs, name), 'utf8')
      const hit = ORIGIN_FORMS.find((r) => r.test(text))
      out.push({ path: `${dir}/${name}`, writer, declares: hit !== undefined, form: hit ? hit.source : null })
    }
  }
  return out
}

export interface ProseCensus {
  pages: number
  declared: number
  silent: string[]
  /** every distinct wording in use, so the vocabulary is visible rather than assumed */
  forms: string[]
  receipt: string
  honest: string
}

const HONEST =
  'This census does NOT establish that anything was written by a person. It establishes the opposite direction, ' +
  'which is the checkable one: that every page a generator writes says so. All 234 pages under docs/articles are ' +
  'machine-written — that is what the generators do — and the property worth holding is that none of them can be ' +
  'read as a person\'s prose. No test in this repository can certify human authorship of any text, and none claims to.'

export function proseCensus(): ProseCensus {
  const rows = proseProvenance()
  const silent = rows.filter((r) => !r.declares).map((r) => r.path)
  return {
    pages: rows.length,
    declared: rows.length - silent.length,
    silent,
    forms: [...new Set(rows.map((r) => r.form).filter((f): f is string => f !== null))].sort(),
    receipt: merkleFold([toUuid('prose-provenance|' + rows.length), ...silent.map((s) => toUuid('silent|' + s))]),
    honest: HONEST,
  }
}

/** the gaps, in the guard's shape: a generated page that does not declare it was generated */
export const proseProvenanceGaps = (): { what: string; fix: string }[] => {
  const c = proseCensus()
  if (c.silent.length === 0) return []
  return [{
    what: `${c.silent.length} of ${c.pages} generated prose page(s) carry NO origin statement — a machine's prose a reader could take for a person's: ${c.silent.slice(0, 6).join(', ')}${c.silent.length > 6 ? ` …and ${c.silent.length - 6} more` : ''}`,
    fix: 'have the generator emit an origin statement in the page (any of the wordings in ORIGIN_FORMS, or add a new one there deliberately). This is what makes the captain\'s own authorship distinguishable — an unlabelled generated page dilutes the claim it looks like it supports.',
  }]
}
