import { t as _plugin_vue_export_helper_default } from "./plugin-vue_export-helper.BOaGB7Aw.js";
import { ssrRenderAttrs, ssrRenderComponent } from "vue/server-renderer";
import { resolveComponent, useSSRContext } from "vue";
//#region docs/chat.md
var __pageData = JSON.parse("{\"title\":\"Chat\",\"description\":\"What chat means in uuidna — not a chatbot, but two real things. Agents converse through receipted MCP tool calls (the receipt chain is the transcript), and parties exchange encrypted messages as uuid streams. Try the messaging live, in your browser.\",\"frontmatter\":{\"title\":\"Chat\",\"description\":\"What chat means in uuidna — not a chatbot, but two real things. Agents converse through receipted MCP tool calls (the receipt chain is the transcript), and parties exchange encrypted messages as uuid streams. Try the messaging live, in your browser.\",\"prev\":{\"text\":\"changelog\",\"link\":\"/changelog\"},\"next\":{\"text\":\"deploy\",\"link\":\"/deploy\"},\"head\":[[\"link\",{\"rel\":\"canonical\",\"href\":\"https://uuidna.com/chat\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://uuidna.com/chat\"}]]},\"headers\":[],\"relativePath\":\"chat.md\",\"filePath\":\"chat.md\",\"lastUpdated\":1786488381000}");
var _sfc_main = { name: "chat.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
	const _component_Badge = resolveComponent("Badge");
	const _component_MessageStream = resolveComponent("MessageStream");
	_push(`<div${ssrRenderAttrs(_attrs)}><h1 id="chat" tabindex="-1">Chat `);
	_push(ssrRenderComponent(_component_Badge, {
		type: "tip",
		text: "receipted"
	}, null, _parent));
	_push(` <a class="header-anchor" href="#chat" aria-label="Permalink to “Chat”">​</a></h1><blockquote><p>Not a chatbot — a conversation you can recompute, and messages only the keyholder can read.</p></blockquote><p>There is no language model on this page, and uuidna does not pretend to be one. &quot;Chat&quot; here is two concrete things that <strong>do</strong> exist and recompute: agents conversing through the <strong>MCP</strong>, and parties exchanging <strong>encrypted messages</strong>.</p><h2 id="agents-chat-through-the-mcp" tabindex="-1">Agents chat through the MCP <a class="header-anchor" href="#agents-chat-through-the-mcp" aria-label="Permalink to “Agents chat through the MCP”">​</a></h2><p>An agent&#39;s conversation with uuidna is a sequence of <strong>tool calls</strong>, and every call returns a chained <strong>receipt</strong> (<code>receipt · seq · referer</code>) — a content-address of that command, hardened from the one before it. So the transcript isn&#39;t a claim about what was said; it&#39;s a <strong>recomputable chain</strong> anyone can recheck. The &quot;intelligence&quot; is the sealed theorems and the tools, not a model&#39;s fluency — which is why a uuidna answer can be <em>verified</em>, not just trusted. Browse the <a href="/mcp">64 MCP tools</a>; connect the server and every turn you take is receipted.</p><p><strong>A trial is authoritative only when signed by uuidna.com.</strong> Send a claim to the live <code>uuidna.com/trials</code> and it comes back with a <code>signature</code> — an HMAC keyed by a secret only uuidna.com holds. A fork running the same public code recomputes the <em>same</em> verdict (that is the strength), but it <strong>cannot forge the signature</strong>, so it cannot pass its trials off as uuidna.com&#39;s. Honest scope: this is a symmetric MAC — you verify it by re-requesting the same statement from uuidna.com (the signature is deterministic), not with a public key; the verdict itself stays recomputable by anyone via its receipt.</p><h2 id="people-chat-in-encrypted-streams" tabindex="-1">People chat in encrypted streams <a class="header-anchor" href="#people-chat-in-encrypted-streams" aria-label="Permalink to “People chat in encrypted streams”">​</a></h2><p>Between parties, a message is sealed (pure-TS ChaCha20-Poly1305) and carried <strong>as a stream of uuids</strong> — the channel <em>is</em> the uuid stream. Seal one below and watch it form, then arrive and decrypt. It runs in your browser; nothing is sent:</p>`);
	_push(ssrRenderComponent(_component_MessageStream, null, null, _parent));
	_push(`<p>For real confidentiality between two parties, key it with a <strong>private contract</strong> — only contract-holders decrypt, and a changed contract fails authentication (see <a href="/mcp#uuidna-contract-seal">Contract-keyed messaging</a> and the <a href="/license#what-the-license-can-and-cannot-lock">license</a>). Honest scope: secrecy is exactly the secrecy of the key; sealing under a <em>public</em> contract binds a message to the terms but hides nothing.</p><h2 id="what-chat-is-not-here" tabindex="-1">What chat is not here <a class="header-anchor" href="#what-chat-is-not-here" aria-label="Permalink to “What chat is not here”">​</a></h2><ul><li><strong>Not an AI assistant.</strong> No model runs on this page; the recomputable tools and theorems are the substance.</li><li><strong>Not &quot;intelligent secure chat&quot; as a slogan.</strong> The security is the ChaCha20-Poly1305 layer keyed by a secret; the receipts are non-crypto content-addresses (integrity and routing, not secrecy). Each is exactly what it is.</li></ul><p>The <a href="/guides">Guides</a> show how to fuse the MCP; the <a href="/games">Games</a> let you play the same functions. Integrity, not truth.</p></div>`);
}
var _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
	const ssrContext = useSSRContext();
	(ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("chat.md");
	return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
var chat_default = /*#__PURE__*/ _plugin_vue_export_helper_default(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
//#endregion
export { __pageData, chat_default as default };
