import { t as _plugin_vue_export_helper_default } from "./plugin-vue_export-helper.BOaGB7Aw.js";
import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
//#region docs/publications/one-leap.md
var __pageData = JSON.parse("{\"title\":\"One leap\",\"description\":\"undefined — proven by undefined in Lean 4, sorry-free (no Mathlib); part of undefined.\",\"frontmatter\":{\"prev\":{\"text\":\"The mix\",\"link\":\"/publications/production\"},\"next\":{\"text\":\"home\",\"link\":\"/\"},\"head\":[[\"link\",{\"rel\":\"canonical\",\"href\":\"https://uuidna.com/publications/one-leap\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://uuidna.com/publications/one-leap\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:title\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"undefined — proven by undefined in Lean 4.\"}],[\"meta\",{\"property\":\"uuidna:address\",\"content\":\"18f6e3e1-8daa-8059-9b56-cb2ad401582d\"}]]},\"headers\":[],\"params\":{\"slug\":\"one-leap\",\"address\":\"18f6e3e1-8daa-8059-9b56-cb2ad401582d\",\"receipt\":\"d45cb19c-8964-8e4a-9b73-d2e8aa654605\"},\"relativePath\":\"publications/one-leap.md\",\"filePath\":\"publications/[slug].md\",\"lastUpdated\":1786504329000}");
var _sfc_main = { name: "publications/one-leap.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
	_push(`<div${ssrRenderAttrs(_attrs)}><h1 id="one-leap" tabindex="-1">One leap <a class="header-anchor" href="#one-leap" aria-label="Permalink to “One leap”">​</a></h1><blockquote><p>the whole vortex proved in a single by decide</p></blockquote><p>These 1 facts hold by decision. Each was proven in Lean 4 — no Mathlib, checked sorry-free — and every sentence below links the proof that seals it. This note claims nothing beyond what its theorems settle: not that the domain is complete, only that the prose says nothing the proofs do not. It was written by reading the sealed ledger; read the proofs, not the prose.</p><h2 id="the-facts-each-backed-by-its-proof" tabindex="-1">The facts, each backed by its proof <a class="header-anchor" href="#the-facts-each-backed-by-its-proof" aria-label="Permalink to “The facts, each backed by its proof”">​</a></h2><ul><li>one by-decide from division-by-zero=the reflection: the doubling orbit, the involution {0,5}, ℤ/9 arithmetic, AGL(1,ℤ/9)=54 with commutator=the unit shift, and the equilibriums — the whole vortex at once — <a href="/theorem/vortex_one_leap">proof</a>.</li></ul><h2 id="provenance" tabindex="-1">Provenance <a class="header-anchor" href="#provenance" aria-label="Permalink to “Provenance”">​</a></h2><p>These 1 proofs fold, order-invariant, to the receipt <code>d45cb19c-8964-8e4a-9b73-d2e8aa654605</code> — recompute it from the same ledger and it returns. The note itself content-addresses to a uuid, so any edit is visible. Writing descends from reading: this note holds only what the proofs it links already sealed, and it was audited by uuidna&#39;s own honesty gate before it was published — a sentence that overreached a proof would have been refused, not shipped.</p><p>Source · <a href="https://github.com/uuidna/uuidna/blob/main/lean/OneLeap.lean" target="_blank" rel="noreferrer">lean/OneLeap.lean</a> · <a href="/theorems">all theorems</a></p><hr><p><strong>Audited before published</strong> · this note passed uuidna&#39;s honesty gate at build time — every claim above links the proof that seals it. Content-address <code>18f6e3e1-8daa-8059-9b56-cb2ad401582d</code> · proofs fold to receipt <code>d45cb19c-8964-8e4a-9b73-d2e8aa654605</code> · 1 sealed theorems.</p><p><a href="/publications">All publications</a> · <a href="/theorems">All theorems</a> · <a href="/trials">How auditing works</a></p></div>`);
}
var _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
	const ssrContext = useSSRContext();
	(ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/one-leap.md");
	return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
var one_leap_default = /*#__PURE__*/ _plugin_vue_export_helper_default(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
//#endregion
export { __pageData, one_leap_default as default };
